# Generated by Django 5.2.6 on 2026-01-29 12:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("admin_operativa", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PeriodoContable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                ("nombre", models.CharField(max_length=100)),
                ("fecha_inicio", models.DateField()),
                ("fecha_fin", models.DateField()),
                ("cerrado", models.BooleanField(default=False)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_records",
                        to="admin_operativa.providerprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AsientoContable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                ("fecha", models.DateField()),
                ("descripcion", models.CharField(max_length=255)),
                (
                    "creado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="admin_asientos_creados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_records",
                        to="admin_operativa.providerprofile",
                    ),
                ),
                (
                    "periodo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="admin_asientos",
                        to="admin_contabilidad.periodocontable",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PlanDeCuentas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                ("nombre", models.CharField(max_length=255)),
                ("descripcion", models.TextField(blank=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_records",
                        to="admin_operativa.providerprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Plan de Cuentas (Admin)",
            },
        ),
        migrations.CreateModel(
            name="Cuenta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                ("nombre", models.CharField(max_length=255)),
                ("codigo", models.CharField(max_length=20)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("ACTIVO", "Activo"),
                            ("PASIVO", "Pasivo"),
                            ("PATRIMONIO", "Patrimonio"),
                            ("INGRESOS", "Ingresos"),
                            ("GASTOS", "Gastos"),
                            ("COSTOS", "Costos"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "saldo_inicial",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=18),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_records",
                        to="admin_operativa.providerprofile",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admin_children",
                        to="admin_contabilidad.cuenta",
                    ),
                ),
                (
                    "plan_de_cuentas",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admin_cuentas",
                        to="admin_contabilidad.plandecuentas",
                    ),
                ),
            ],
            options={
                "unique_together": {("plan_de_cuentas", "codigo")},
            },
        ),
        migrations.CreateModel(
            name="Transaccion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "debito",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=18),
                ),
                (
                    "credito",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=18),
                ),
                (
                    "asiento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admin_transacciones",
                        to="admin_contabilidad.asientocontable",
                    ),
                ),
                (
                    "cuenta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="admin_transacciones",
                        to="admin_contabilidad.cuenta",
                    ),
                ),
            ],
        ),
    ]
