# Generated by Django 5.2.12 on 2026-03-15 13:07

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core_erp", "0001_initial_base"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminAccount",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("core_erp.account",),
        ),
        migrations.CreateModel(
            name="AdminAccountingTransaction",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("core_erp.ledgerentry",),
        ),
        migrations.CreateModel(
            name="AdminChartOfAccounts",
            fields=[],
            options={
                "verbose_name": "Admin Chart of Accounts",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("core_erp.chartofaccounts",),
        ),
        migrations.CreateModel(
            name="AdminFiscalPeriod",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("core_erp.fiscalperiod",),
        ),
        migrations.CreateModel(
            name="AdminJournalEntry",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("core_erp.journalentry",),
        ),
    ]
