# Generated by Django 5.2.6 on 2026-02-06 11:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LegacyCustodian",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("entity_represented", models.CharField(max_length=255)),
                ("role", models.CharField(default="GARANTE", max_length=100)),
                ("appointed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "public_key",
                    models.TextField(
                        help_text="Clave pública para validación de ratificaciones multicanal."
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="LegacyMilestone",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "justification",
                    models.TextField(help_text="Por qué ocurrió este cambio."),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "governance_hash",
                    models.CharField(
                        help_text="Hash del estado del sistema al momento del hito.",
                        max_length=64,
                    ),
                ),
            ],
        ),
    ]
