# Generated by Django 5.2.12 on 2026-03-15 13:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core_erp", "0001_initial_base"),
    ]

    operations = [
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("INFO", "Informational"),
                            ("PREVENTIVE", "Preventive"),
                            ("CRITICAL", "Critical"),
                            ("BLOCKING", "Blocking"),
                        ],
                        default="INFO",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("ACKNOWLEDGED", "Acknowledged"),
                            ("RESOLVED", "Resolved"),
                            ("ESCALATED", "Escalated"),
                        ],
                        default="OPEN",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("entity_scope", models.CharField(default="TENANT", max_length=50)),
                (
                    "source_event",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("correlation_id", models.UUIDField(blank=True, null=True)),
                (
                    "impact_score",
                    models.FloatField(default=0.0, help_text="Estimated impact 0-100"),
                ),
                (
                    "domain_affected",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "financial_exposure",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=18),
                ),
                ("confidence_score", models.FloatField(default=0.95)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_records",
                        to="core_erp.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="KPI",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("FINANCIAL", "Financial"),
                            ("OPERATIONAL", "Operational"),
                            ("STRATEGIC", "Strategic"),
                            ("TECHNICAL", "Technical"),
                        ],
                        max_length=50,
                    ),
                ),
                ("value", models.DecimalField(decimal_places=2, max_digits=20)),
                ("unit", models.CharField(default="USD", max_length=20)),
                ("legal_entity_id", models.UUIDField(blank=True, null=True)),
                ("country_code", models.CharField(blank=True, max_length=3, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("meta_data", models.JSONField(blank=True, default=dict)),
                (
                    "methodology_version",
                    models.CharField(default="v1.0", max_length=50),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_records",
                        to="core_erp.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "KPI Snapshot",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="Threshold",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("kpi_name", models.CharField(max_length=100)),
                (
                    "operator",
                    models.CharField(
                        choices=[
                            ("GT", "Greater Than"),
                            ("LT", "Less Than"),
                            ("EQ", "Equal"),
                            ("DROP", "Percentage Drop"),
                            ("SPIKE", "Percentage Spike"),
                        ],
                        max_length=10,
                    ),
                ),
                ("value", models.DecimalField(decimal_places=2, max_digits=20)),
                ("severity", models.CharField(default="CRITICAL", max_length=20)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_records",
                        to="core_erp.tenant",
                    ),
                ),
            ],
        ),
    ]
