# Generated by Django 5.2.6 on 2026-02-06 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="agent_domain",
            field=models.CharField(
                blank=True,
                help_text="Dominio institucional asignado al agente.",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="is_agent",
            field=models.BooleanField(
                default=False,
                help_text="Indica si este usuario es un Funcionario Digital (Agente IA).",
            ),
        ),
    ]
