# Generated by Django 5.2.6 on 2025-10-29 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
        ("prestadores", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="plantillaverificacion",
            name="categoria_prestador",
            field=models.ForeignKey(
                blank=True,
                help_text="Asocia esta plantilla a una categoría de prestador específica (opcional).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="plantillas_verificacion",
                to="prestadores.categoriaprestador",
            ),
        ),
    ]
