# Generated by Django 5.2.6 on 2025-11-01 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_plantillaverificacion_categoria_prestador"),
        ("mi_negocio", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plantillaverificacion",
            name="categoria_prestador",
            field=models.ForeignKey(
                blank=True,
                help_text="Asocia esta plantilla a una categoría de prestador específica (opcional).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="plantillas_verificacion",
                to="mi_negocio.categoriaprestador",
            ),
        ),
    ]
