# Generated by Django 5.2.6 on 2025-11-09 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_plantillaverificacion_categoria_prestador"),
        ("prestadores", "0002_cancellationpolicy_kitchenstation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentoverificacion",
            name="prestador",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documentos_verificacion",
                to="prestadores.providerprofile",
            ),
        ),
        migrations.AddField(
            model_name="imagengaleria",
            name="prestador",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="galeria_imagenes",
                to="prestadores.providerprofile",
            ),
        ),
        migrations.AddField(
            model_name="rutaturistica",
            name="prestadores",
            field=models.ManyToManyField(
                blank=True,
                related_name="rutas",
                to="prestadores.providerprofile",
                verbose_name="Prestadores en la Ruta",
            ),
        ),
        migrations.AddField(
            model_name="verificacion",
            name="prestador",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="verificaciones_recibidas",
                to="prestadores.providerprofile",
            ),
        ),
    ]
