# Generated by Django 6.0.3 on 2026-03-24 03:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_initial_base"),
        ("turismo", "0002_department_municipality"),
    ]

    operations = [
        migrations.AlterField(
            model_name="atractivoturistico",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="api_atractivos",
                to="turismo.department",
                verbose_name="Departamento",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="api_profiles",
                to="turismo.department",
            ),
        ),
        migrations.RemoveField(
            model_name="municipality",
            name="department",
        ),
        migrations.AlterField(
            model_name="artesano",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="api_artesanos",
                to="turismo.department",
                verbose_name="Departamento",
            ),
        ),
        migrations.AlterField(
            model_name="atractivoturistico",
            name="municipality",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="api_atractivos",
                to="turismo.municipality",
                verbose_name="Municipio",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="municipality",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="api_profiles",
                to="turismo.municipality",
            ),
        ),
        migrations.AlterField(
            model_name="artesano",
            name="municipality",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="api_artesanos",
                to="turismo.municipality",
                verbose_name="Municipio",
            ),
        ),
        migrations.AlterField(
            model_name="rutaturistica",
            name="municipalities",
            field=models.ManyToManyField(
                blank=True,
                related_name="rutas_turisticas",
                to="turismo.municipality",
                verbose_name="Municipios que abarca la Ruta",
            ),
        ),
        migrations.DeleteModel(
            name="Department",
        ),
        migrations.DeleteModel(
            name="Municipality",
        ),
    ]
