# Generated by Django 6.0.3 on 2026-03-24 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_atractivoturistico_department_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="birthdate",
            field=models.DateField(
                blank=True,
                help_text="Requerido para verificación de edad en servicios sociales/citas.",
                null=True,
                verbose_name="Fecha de Nacimiento",
            ),
        ),
    ]
