# Generated by Django 6.0.3 on 2026-03-25 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_customuser_birthdate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Super Administrador"),
                    ("ADMIN_ENTIDAD", "Admin de Entidad"),
                    ("ADMIN_NACIONAL", "Admin Entidad Nacional"),
                    ("ADMIN_DEPARTAMENTAL", "Admin Entidad Departamental"),
                    ("ADMIN_MUNICIPAL", "Admin Entidad Municipal"),
                    ("DIRECTIVO_NACIONAL", "Directivo Nacional"),
                    ("DIRECTIVO_DEPARTAMENTAL", "Directivo Departamental"),
                    ("DIRECTIVO_MUNICIPAL", "Directivo Municipal"),
                    ("FUNCIONARIO_DIRECTIVO", "Funcionario Directivo"),
                    ("FUNCIONARIO_PROFESIONAL", "Funcionario Profesional"),
                    ("FUNCIONARIO_TECNICO", "Funcionario Técnico"),
                    ("FUNCIONARIO_ASISTENCIAL", "Funcionario Asistencial"),
                    ("PRESTADOR", "Prestador de Servicio (Genérico)"),
                    ("BUSINESS_OWNER", "Propietario de Negocio"),
                    ("BUSINESS_ADMIN", "Administrador de Negocio"),
                    ("BUSINESS_OPERATOR", "Operador de Negocio"),
                    ("BUSINESS_EMPLOYEE", "Empleado de Negocio"),
                    ("ARTESANO", "Artesano"),
                    ("EVENT_MANAGER", "Organizador de Eventos"),
                    ("DELIVERY", "Delivery / Logística (Genérico)"),
                    ("DELIVERY_ADMIN", "Administrador de Delivery"),
                    ("DELIVERY_DRIVER", "Repartidor / Mensajero"),
                    ("DELIVERY_OPERATOR", "Operador Logístico"),
                    ("TURISTA", "Turista"),
                    ("CONSEJO_CONSULTIVO_TURISMO", "Consejo Consultivo de Turismo"),
                ],
                max_length=50,
                verbose_name="Rol",
            ),
        ),
    ]
