# Generated by Django 5.2.12 on 2026-03-27 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_alter_customuser_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="publicacion",
            name="direccion",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Dirección"
            ),
        ),
        migrations.AddField(
            model_name="publicacion",
            name="latitud",
            field=models.FloatField(blank=True, null=True, verbose_name="Latitud"),
        ),
        migrations.AddField(
            model_name="publicacion",
            name="longitud",
            field=models.FloatField(blank=True, null=True, verbose_name="Longitud"),
        ),
    ]
