# Generated by Django 5.2.12 on 2026-03-27 11:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_publicacion_direccion_publicacion_latitud_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="face_verified",
            field=models.BooleanField(
                default=False,
                help_text="Indica si el rostro ha sido validado mediante biometría.",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="phone_verified",
            field=models.BooleanField(
                default=False,
                help_text="Indica si el número telefónico ha sido validado vía OTP.",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="verification_status",
            field=models.CharField(
                choices=[
                    ("UNVERIFIED", "No Verificado"),
                    ("PENDING", "Pendiente de Revisión"),
                    ("VERIFIED", "Verificado"),
                    ("REJECTED", "Rechazado"),
                ],
                default="UNVERIFIED",
                help_text="Estado general de la protección de identidad del usuario.",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="IdentityVerification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone_number", models.CharField(blank=True, max_length=20)),
                (
                    "face_hash",
                    models.CharField(
                        blank=True,
                        help_text="Hash seguro del rostro verificado para auditoría.",
                        max_length=255,
                    ),
                ),
                ("verification_date", models.DateTimeField(blank=True, null=True)),
                (
                    "provider_reference",
                    models.CharField(
                        blank=True,
                        help_text="ID de referencia del proveedor externo de KYC.",
                        max_length=255,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="identity_audit",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
