version: '3.8'
services:
  prometheus:
    image: prom/prometheus:v2.45.0
    ports: ["9090:9090"]
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:10.0.0
    ports: ["3000:3000"]
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=sarita_master

  tempo:
    image: grafana/tempo:2.2.0
    command: [ "-config.file=/etc/tempo.yaml" ]
    ports: ["3200:3200", "4317:4317"]

  loki:
    image: grafana/loki:2.8.0
    ports: ["3100:3100"]
