global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'sarita_workers'
    static_configs:
      - targets: ['financial-worker:8000', 'ai-worker:8001']
  - job_name: 'kafka_brokers'
    static_configs:
      - targets: ['kafka-exporter:9308']
