-- 00_init/schemas.sql
-- NORMALIZACIÓN TOTAL SARITA

CREATE SCHEMA IF NOT EXISTS core;
CREATE SCHEMA IF NOT EXISTS identity;
CREATE SCHEMA IF NOT EXISTS governance;
CREATE SCHEMA IF NOT EXISTS tourism;
CREATE SCHEMA IF NOT EXISTS erp;
CREATE SCHEMA IF NOT EXISTS ai_core;
CREATE SCHEMA IF NOT EXISTS finance; -- Incluye ledger y payments
CREATE SCHEMA IF NOT EXISTS infrastructure;
