# Generated by Django 5.2.6 on 2025-11-02 18:56

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("mi_negocio", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChartOfAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=20)),
                ("nombre", models.CharField(max_length=255)),
                (
                    "naturaleza",
                    models.CharField(
                        choices=[("DEBITO", "Debito"), ("CREDITO", "Credito")],
                        max_length=10,
                    ),
                ),
                (
                    "permite_transacciones",
                    models.BooleanField(
                        default=True,
                        help_text="Si es 'False', es una cuenta de control.",
                    ),
                ),
                (
                    "perfil",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plan_de_cuentas",
                        to="mi_negocio.perfil",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cuenta Contable",
                "verbose_name_plural": "Plan de Cuentas (PUC)",
                "ordering": ["codigo"],
                "unique_together": {("perfil", "codigo")},
            },
        ),
        migrations.CreateModel(
            name="JournalEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("entry_date", models.DateField(db_index=True)),
                ("description", models.TextField()),
                ("entry_type", models.CharField(max_length=100)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "perfil",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asientos_contables",
                        to="mi_negocio.perfil",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="asientos_creados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Asiento Contable",
                "verbose_name_plural": "Asientos Contables (Libro Diario)",
                "ordering": ["-entry_date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "debit",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=18
                    ),
                ),
                (
                    "credit",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=18
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="contabilidad.chartofaccount",
                    ),
                ),
                (
                    "journal_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="contabilidad.journalentry",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transacción Contable",
                "verbose_name_plural": "Transacciones Contables",
                "ordering": ["id"],
            },
        ),
    ]
