# Generated by Django 5.2.12 on 2026-03-15 12:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TourismFlowAnalytics",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("origen_visitante", models.CharField(max_length=255)),
                ("destino", models.CharField(max_length=255)),
                ("fecha", models.DateField()),
                ("volumen_visitantes", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TourismSeasonality",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("destino", models.CharField(max_length=255)),
                (
                    "mes",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "1"),
                            (2, "2"),
                            (3, "3"),
                            (4, "4"),
                            (5, "5"),
                            (6, "6"),
                            (7, "7"),
                            (8, "8"),
                            (9, "9"),
                            (10, "10"),
                            (11, "11"),
                            (12, "12"),
                        ]
                    ),
                ),
                (
                    "nivel_demanda",
                    models.CharField(
                        choices=[
                            ("LOW", "Temporada Baja"),
                            ("MEDIUM", "Temporada Media"),
                            ("HIGH", "Temporada Alta"),
                        ],
                        max_length=10,
                    ),
                ),
                ("categoria_destacada", models.CharField(blank=True, max_length=100)),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TourismDemandForecast",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("destino", models.CharField(max_length=255)),
                ("categoria_servicio", models.CharField(max_length=100)),
                ("fecha", models.DateField()),
                ("demanda_estimada", models.PositiveIntegerField()),
                ("demanda_real", models.PositiveIntegerField(blank=True, null=True)),
                ("precision_modelo", models.FloatField(default=0.0)),
            ],
            options={
                "unique_together": {("destino", "categoria_servicio", "fecha")},
            },
        ),
        migrations.CreateModel(
            name="TourismEconomicImpact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("destino", models.CharField(max_length=255)),
                ("periodo", models.CharField(max_length=50)),
                (
                    "ventas_totales",
                    models.DecimalField(decimal_places=2, max_digits=18),
                ),
                (
                    "ingresos_turisticos_netos",
                    models.DecimalField(decimal_places=2, max_digits=18),
                ),
                ("empleo_generado_estimado", models.PositiveIntegerField(default=0)),
            ],
            options={
                "unique_together": {("destino", "periodo")},
            },
        ),
        migrations.CreateModel(
            name="TouristBehaviorProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("destinos_visitados", models.JSONField(default=list)),
                ("categorias_preferidas", models.JSONField(default=list)),
                (
                    "ticket_promedio",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                ("frecuencia_viajes_anual", models.PositiveIntegerField(default=0)),
                (
                    "segmento_asignado",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ADVENTURER", "Turista Aventurero"),
                            ("GASTRONOMIC", "Turista Gastronómico"),
                            ("CULTURAL", "Turista Cultural"),
                            ("ECOLOGICAL", "Turista Ecológico"),
                            ("FAMILY", "Turista Familiar"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="behavior_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
    ]
