# Generated by Django 6.0.3 on 2026-03-23 22:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tourism_intelligence", "0001_full_reset"),
        ("turismo", "0002_department_municipality"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConversationalIntent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("conversation_id", models.UUIDField(db_index=True)),
                ("message_id", models.UUIDField(db_index=True)),
                (
                    "intent",
                    models.CharField(
                        choices=[
                            ("SEARCH_HOTEL", "Búsqueda de Alojamiento"),
                            ("SEARCH_FOOD", "Búsqueda de Restaurante"),
                            ("BOOKING_REQUEST", "Solicitud de Reserva"),
                            ("PRICING_QUERY", "Consulta de Precios"),
                            ("HOW_TO_ARRIVE", "Consulta de Ubicación/GPS"),
                            ("SERVICE_COMPLAINT", "Queja o Reclamo"),
                            ("POSITIVE_FEEDBACK", "Comentario Positivo"),
                        ],
                        max_length=50,
                    ),
                ),
                ("confidence_score", models.FloatField(default=0.0)),
                ("sentiment_score", models.FloatField(default=0.0)),
                ("detected_entities", models.JSONField(default=dict)),
                (
                    "tourist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ConversationalKPI",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("avg_response_time_seconds", models.FloatField(default=0.0)),
                ("response_rate", models.FloatField(default=0.0)),
                ("total_chats", models.PositiveIntegerField(default=0)),
                ("missed_chats", models.PositiveIntegerField(default=0)),
                ("period", models.CharField(max_length=20)),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_kpis",
                        to="turismo.tourismprovider",
                    ),
                ),
            ],
            options={
                "unique_together": {("provider", "period")},
            },
        ),
    ]
