# Generated by Django 5.2.6 on 2026-01-22 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contabilidad", "0001_initial"),
        ("prestadores", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="asientocontable",
            name="provider",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_items",
                to="prestadores.providerprofile",
            ),
        ),
        migrations.AddField(
            model_name="cuenta",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="contabilidad.cuenta",
            ),
        ),
        migrations.AddField(
            model_name="cuenta",
            name="provider",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_items",
                to="prestadores.providerprofile",
            ),
        ),
        migrations.AddField(
            model_name="periodocontable",
            name="provider",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_items",
                to="prestadores.providerprofile",
            ),
        ),
        migrations.AddField(
            model_name="asientocontable",
            name="periodo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="asientos",
                to="contabilidad.periodocontable",
            ),
        ),
        migrations.AddField(
            model_name="plandecuentas",
            name="provider",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_items",
                to="prestadores.providerprofile",
            ),
        ),
        migrations.AddField(
            model_name="cuenta",
            name="plan_de_cuentas",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cuentas",
                to="contabilidad.plandecuentas",
            ),
        ),
        migrations.AddField(
            model_name="transaccion",
            name="asiento",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transacciones",
                to="contabilidad.asientocontable",
            ),
        ),
        migrations.AddField(
            model_name="transaccion",
            name="cuenta",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="transacciones",
                to="contabilidad.cuenta",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="periodocontable",
            unique_together={("provider", "fecha_inicio", "fecha_fin")},
        ),
        migrations.AlterUniqueTogether(
            name="plandecuentas",
            unique_together={("provider", "nombre")},
        ),
        migrations.AlterUniqueTogether(
            name="cuenta",
            unique_together={("plan_de_cuentas", "codigo")},
        ),
    ]
