# Generated by Django 5.2.6 on 2025-12-11 15:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contabilidad", "0001_initial"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("prestadores", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="costcenter",
            name="perfil",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cost_centers",
                to="prestadores.providerprofile",
            ),
        ),
        migrations.AddField(
            model_name="exchangerate",
            name="from_currency",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rates_from",
                to="contabilidad.currency",
            ),
        ),
        migrations.AddField(
            model_name="exchangerate",
            name="to_currency",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rates_to",
                to="contabilidad.currency",
            ),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="content_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="perfil",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="journal_entries",
                to="prestadores.providerprofile",
            ),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="journal_entries",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="contabilidad.chartofaccount",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="cost_center",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="contabilidad.costcenter",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="journal_entry",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to="contabilidad.journalentry",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="exchangerate",
            unique_together={("from_currency", "to_currency", "date")},
        ),
    ]
