# Generated by Django 5.2.11 on 2026-02-15 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contabilidad", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cuenta",
            name="codigo",
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="cuenta",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("ACTIVO", "Activo"),
                    ("PASIVO", "Pasivo"),
                    ("PATRIMONIO", "Patrimonio"),
                    ("INGRESOS", "Ingresos"),
                    ("GASTOS", "Gastos"),
                    ("COSTOS", "Costos"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="plandecuentas",
            name="nombre",
            field=models.CharField(max_length=255),
        ),
    ]
