# Generated by Django 5.2.12 on 2026-03-15 13:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("commercial_engine", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UsageMetric",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Ej: API_CALL, STORAGE_GB, AI_TOKEN",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "unit",
                    models.CharField(
                        help_text="Ej: calls, gb, tokens, users", max_length=20
                    ),
                ),
                (
                    "aggregation_type",
                    models.CharField(
                        choices=[
                            ("sum", "Sum"),
                            ("max", "Maximum"),
                            ("avg", "Average"),
                            ("count", "Count"),
                        ],
                        default="sum",
                        max_length=10,
                    ),
                ),
                ("billable", models.BooleanField(default=True)),
                (
                    "price_model",
                    models.CharField(
                        choices=[
                            ("flat", "Flat Fee"),
                            ("tiered", "Tiered"),
                            ("volume", "Volume Based"),
                            ("dynamic", "Dynamic"),
                        ],
                        default="flat",
                        max_length=10,
                    ),
                ),
                ("pricing_config", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Métrica de Uso",
                "verbose_name_plural": "Métricas de Uso",
            },
        ),
        migrations.CreateModel(
            name="UsageEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=6, max_digits=20)),
                ("timestamp", models.DateTimeField(db_index=True)),
                (
                    "source",
                    models.CharField(
                        help_text="Origin of the event (API, AI_SERVICE, etc.)",
                        max_length=100,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "idempotency_key",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                ("processed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_events",
                        to="commercial_engine.saassubscription",
                    ),
                ),
                (
                    "metric",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="usage_billing.usagemetric",
                    ),
                ),
            ],
            options={
                "verbose_name": "Evento de Uso",
                "verbose_name_plural": "Eventos de Uso",
            },
        ),
        migrations.CreateModel(
            name="UsageAggregation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                (
                    "total_quantity",
                    models.DecimalField(decimal_places=6, default=0, max_digits=20),
                ),
                ("is_billed", models.BooleanField(default=False)),
                ("billed_at", models.DateTimeField(blank=True, null=True)),
                ("last_recalculated_at", models.DateTimeField(auto_now=True)),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_aggregations",
                        to="commercial_engine.saassubscription",
                    ),
                ),
                (
                    "metric",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="usage_billing.usagemetric",
                    ),
                ),
            ],
            options={
                "verbose_name": "Agregación de Uso",
                "verbose_name_plural": "Agregaciones de Uso",
                "unique_together": {
                    ("subscription", "metric", "period_start", "period_end")
                },
            },
        ),
    ]
