# Generated by Django 6.0.3 on 2026-03-23 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("prestadores", "0001_full_reset"),
    ]

    operations = [
        migrations.CreateModel(
            name="VehiculoDeAlquiler",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        help_text="Ej: Toyota Corolla 2023", max_length=100
                    ),
                ),
                ("placa", models.CharField(max_length=10, unique=True)),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("economico", "Económico"),
                            ("compacto", "Compacto"),
                            ("intermedio", "Intermedio"),
                            ("suv", "SUV"),
                            ("lujo", "Lujo"),
                            ("van", "Van/Minivan"),
                            ("moto", "Motocicleta"),
                        ],
                        default="compacto",
                        max_length=20,
                    ),
                ),
                (
                    "transmision",
                    models.CharField(
                        choices=[("automatica", "Automática"), ("manual", "Manual")],
                        default="automatica",
                        max_length=10,
                    ),
                ),
                ("numero_pasajeros", models.PositiveIntegerField(default=5)),
                (
                    "precio_por_dia",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("disponible", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "perfil",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vehiculos_de_alquiler",
                        to="prestadores.providerprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Alquiler",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_cliente_temporal", models.CharField(max_length=150)),
                ("email_cliente", models.EmailField(max_length=254)),
                ("fecha_recogida", models.DateTimeField()),
                ("fecha_devolucion", models.DateTimeField()),
                (
                    "costo_total_calculado",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("reservado", "Reservado"),
                            ("activo", "Activo"),
                            ("finalizado", "Finalizado"),
                            ("cancelado", "Cancelado"),
                        ],
                        default="reservado",
                        max_length=15,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "vehiculo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="alquileres",
                        to="arrendadoras_vehiculos.vehiculodealquiler",
                    ),
                ),
            ],
        ),
    ]
