# Generated by Django 5.2.6 on 2026-01-29 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("admin_operativa", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivoFijo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("fecha_adquisicion", models.DateField()),
                (
                    "valor_adquisicion",
                    models.DecimalField(decimal_places=2, max_digits=18),
                ),
                (
                    "perfil",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admin_activos_fijos",
                        to="admin_operativa.providerprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CalculoDepreciacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField()),
                ("valor", models.DecimalField(decimal_places=2, max_digits=18)),
                (
                    "activo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admin_depreciaciones",
                        to="admin_activos_fijos.activofijo",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CategoriaActivo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("vida_util_meses", models.IntegerField()),
                (
                    "perfil",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admin_categorias_activos",
                        to="admin_operativa.providerprofile",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="activofijo",
            name="categoria",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="admin_activos_fijos.categoriaactivo",
            ),
        ),
    ]
