# Generated by Django 6.0.3 on 2026-03-23 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("prestadores", "0001_full_reset"),
    ]

    operations = [
        migrations.CreateModel(
            name="TipoAlojamiento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, unique=True)),
                ("descripcion", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Alojamiento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("descripcion", models.TextField()),
                ("direccion", models.CharField(max_length=255)),
                (
                    "perfil",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alojamiento",
                        to="prestadores.providerprofile",
                    ),
                ),
                (
                    "tipo",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="alojamientos.tipoalojamiento",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Habitacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("capacidad_maxima", models.PositiveIntegerField()),
                (
                    "alojamiento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="habitaciones",
                        to="alojamientos.alojamiento",
                    ),
                ),
                (
                    "producto",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="habitacion",
                        to="prestadores.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tarifa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("fecha_inicio", models.DateField()),
                ("fecha_fin", models.DateField()),
                (
                    "precio_adicional",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Valor a sumar (o restar si es negativo) al precio base de la habitación.",
                        max_digits=10,
                    ),
                ),
                (
                    "habitacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tarifas",
                        to="alojamientos.habitacion",
                    ),
                ),
            ],
        ),
    ]
