# Generated by Django 6.0.3 on 2026-03-24 13:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="socialconversation",
            name="entry_fee",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Tarifa de entrada para salas privadas.",
                max_digits=12,
            ),
        ),
        migrations.AddField(
            model_name="socialconversation",
            name="is_adult_only",
            field=models.BooleanField(
                default=False, help_text="Restricción para mayores de 18 años."
            ),
        ),
        migrations.AddField(
            model_name="socialprofilepreference",
            name="is_dating_active",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="socialprofilepreference",
            name="presentation_photo",
            field=models.URLField(
                blank=True, help_text="Foto principal de presentación.", null=True
            ),
        ),
        migrations.AddField(
            model_name="socialprofilepreference",
            name="presentation_video",
            field=models.URLField(
                blank=True, help_text="Video de presentación.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="socialconversation",
            name="conversation_type",
            field=models.CharField(
                choices=[
                    ("direct", "Directo"),
                    ("group", "Grupo"),
                    ("public_room", "Sala Pública (Video Cita)"),
                    ("private_room", "Sala Privada (Video Cita)"),
                ],
                default="direct",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="socialmessage",
            name="message_type",
            field=models.CharField(
                choices=[
                    ("text", "Texto"),
                    ("emoji", "Emoji"),
                    ("file", "Archivo"),
                    ("voice", "Voz"),
                    ("gift", "Regalo Económico"),
                ],
                default="text",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="SocialProfileMedia",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "media_type",
                    models.CharField(
                        choices=[("image", "Imagen"), ("video", "Video")], max_length=20
                    ),
                ),
                ("media_url", models.URLField()),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media_gallery",
                        to="social.socialprofilepreference",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "created_at"],
            },
        ),
    ]
