# Generated by Django 6.0.3 on 2026-03-23 20:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("event_type", models.CharField(db_index=True, max_length=100)),
                ("domain", models.CharField(max_length=50)),
                ("payload", models.JSONField()),
                ("timestamp", models.DateTimeField(db_index=True)),
                ("entity_id", models.UUIDField(blank=True, null=True)),
                ("tenant_id", models.CharField(blank=True, max_length=100, null=True)),
                ("version", models.IntegerField(default=1)),
            ],
            options={
                "verbose_name": "Evento Histórico",
                "verbose_name_plural": "Data Lake - Eventos",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="ValuationRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField(auto_now_add=True, db_index=True)),
                (
                    "valuation_base",
                    models.DecimalField(decimal_places=2, max_digits=20),
                ),
                (
                    "valuation_conservative",
                    models.DecimalField(decimal_places=2, max_digits=20),
                ),
                (
                    "valuation_aggressive",
                    models.DecimalField(decimal_places=2, max_digits=20),
                ),
                (
                    "methodology",
                    models.CharField(default="SaaS Multiples + DCF", max_length=100),
                ),
                ("key_metrics", models.JSONField()),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="BoardDecision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "committee",
                    models.CharField(
                        choices=[
                            ("BOARD", "Junta Directiva"),
                            ("FINANCE", "Comité Financiero"),
                            ("RISK", "Comité de Riesgo"),
                            ("EXPANSION", "Comité de Expansión"),
                        ],
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PROPOSED", "Propuesta"),
                            ("IN_VOTING", "En Votación"),
                            ("APPROVED", "Aprobada"),
                            ("REJECTED", "Rechazada"),
                            ("EXECUTED", "Ejecutada"),
                        ],
                        default="PROPOSED",
                        max_length=20,
                    ),
                ),
                ("impact_simulation", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("finalized_at", models.DateTimeField(blank=True, null=True)),
                (
                    "proposed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="proposed_decisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DataRoomAccess",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("requester_name", models.CharField(max_length=255)),
                ("organization", models.CharField(max_length=255)),
                ("purpose", models.TextField()),
                ("token", models.CharField(max_length=100, unique=True)),
                ("expires_at", models.DateTimeField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "authorized_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InstitutionalAuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("action", models.CharField(max_length=255)),
                (
                    "impact_financial",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                ("change_details", models.JSONField()),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("digital_signature", models.TextField(blank=True, null=True)),
                (
                    "previous_hash",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("integrity_hash", models.CharField(db_index=True, max_length=64)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Log de Auditoría Institucional",
                "ordering": ["-timestamp"],
            },
        ),
    ]
