# Generated by Django 6.0 on 2025-12-18 01:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("automation", "0001_initial"),
        ("infrastructure", "0006_alter_user_options_alter_user_managers_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="executionlog",
            name="instance",
        ),
        migrations.RemoveField(
            model_name="executionlog",
            name="node",
        ),
        migrations.RemoveField(
            model_name="edge",
            name="condition_path",
        ),
        migrations.RemoveField(
            model_name="node",
            name="position_x",
        ),
        migrations.RemoveField(
            model_name="node",
            name="position_y",
        ),
        migrations.RemoveField(
            model_name="workflow",
            name="updated_at",
        ),
        migrations.AlterField(
            model_name="node",
            name="node_type",
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name="AgentPersona",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "role_description",
                    models.TextField(
                        help_text="Descripción del rol, ej. 'Asistente de ventas experto en moda'"
                    ),
                ),
                (
                    "tone",
                    models.CharField(
                        help_text="Ej. 'Amigable y servicial', 'Profesional y directo'",
                        max_length=100,
                    ),
                ),
                (
                    "base_prompt",
                    models.TextField(
                        help_text="El prompt de sistema que guía a la IA."
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_personas",
                        to="infrastructure.tenant",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="ExecutionInstance",
        ),
        migrations.DeleteModel(
            name="ExecutionLog",
        ),
    ]
