# Generated by Django 5.2.6 on 2026-01-29 12:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FacturaVenta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("perfil_ref_id", models.UUIDField()),
                ("number", models.CharField(max_length=50)),
                ("issue_date", models.DateField()),
            ],
            options={
                "verbose_name": "Factura de Venta (Admin)",
            },
        ),
        migrations.CreateModel(
            name="ItemFactura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descripcion", models.CharField(max_length=255)),
                ("cantidad", models.PositiveIntegerField()),
                (
                    "precio_unitario",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("subtotal", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "factura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admin_items",
                        to="admin_comercial.facturaventa",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OperacionComercial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("perfil_ref_id", models.UUIDField()),
                ("cliente_ref_id", models.UUIDField()),
                (
                    "tipo_operacion",
                    models.CharField(
                        choices=[
                            ("VENTA", "Venta de Productos/Servicios"),
                            ("CONTRATO", "Contrato"),
                        ],
                        default="VENTA",
                        max_length=20,
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("BORRADOR", "Borrador"),
                            ("CONFIRMADA", "Confirmada"),
                            ("FACTURADA", "Facturada"),
                            ("ANULADA", "Anulada"),
                        ],
                        default="BORRADOR",
                        max_length=20,
                    ),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                (
                    "creado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="admin_operaciones_creadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Operación Comercial (Admin)",
            },
        ),
        migrations.CreateModel(
            name="ItemOperacionComercial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("producto_ref_id", models.UUIDField()),
                ("descripcion", models.CharField(max_length=255)),
                ("cantidad", models.PositiveIntegerField()),
                (
                    "precio_unitario",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("subtotal", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "operacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admin_items",
                        to="admin_comercial.operacioncomercial",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="facturaventa",
            name="operacion",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="admin_factura",
                to="admin_comercial.operacioncomercial",
            ),
        ),
        migrations.CreateModel(
            name="ReciboCaja",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("perfil_ref_id", models.UUIDField()),
                ("fecha_pago", models.DateField()),
                ("monto", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "factura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admin_recibos_caja",
                        to="admin_comercial.facturaventa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Recibo de Caja (Admin)",
            },
        ),
    ]
