# Generated by Django 5.2.6 on 2025-12-22 18:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("api", "0001_initial"),
        ("contabilidad", "__first__"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CuentaBancaria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("banco", models.CharField(max_length=100)),
                ("numero_cuenta", models.CharField(max_length=50)),
                (
                    "tipo_cuenta",
                    models.CharField(
                        choices=[("AHORROS", "Ahorros"), ("CORRIENTE", "Corriente")],
                        max_length=20,
                    ),
                ),
                (
                    "saldo_actual",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=18),
                ),
                ("titular", models.CharField(max_length=255)),
                (
                    "cuenta_contable",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"allows_transactions": True},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cuentas_bancarias_asociadas",
                        to="contabilidad.chartofaccount",
                    ),
                ),
                (
                    "perfil",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cuentas_bancarias",
                        to="api.providerprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TransaccionBancaria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField()),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("INGRESO", "Ingreso"),
                            ("EGRESO", "Egreso"),
                            ("TRANSFERENCIA", "Transferencia"),
                        ],
                        max_length=20,
                    ),
                ),
                ("monto", models.DecimalField(decimal_places=2, max_digits=18)),
                ("descripcion", models.CharField(max_length=255)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "creado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "cuenta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transacciones",
                        to="gestion_financiera.cuentabancaria",
                    ),
                ),
            ],
        ),
    ]
