# Generated by Django 5.2.6 on 2026-01-06 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("api", "0001_initial"),
        ("contabilidad", "0001_initial"),
        ("empresa", "0001_initial"),
        ("nomina", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CuentaBancaria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("banco", models.CharField(max_length=100)),
                ("numero_cuenta", models.CharField(max_length=50, unique=True)),
                ("tipo_cuenta", models.CharField(max_length=50)),
                (
                    "saldo_inicial",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=18),
                ),
                (
                    "saldo_actual",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=18),
                ),
                ("activa", models.BooleanField(default=True)),
                (
                    "cuenta_contable",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cuenta_bancaria_asociada",
                        to="contabilidad.chartofaccount",
                    ),
                ),
                (
                    "perfil",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cuentas_bancarias",
                        to="api.providerprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrdenPago",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_pago", models.DateField()),
                ("monto", models.DecimalField(decimal_places=2, max_digits=18)),
                ("concepto", models.CharField(max_length=255)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente"),
                            ("PAGADA", "Pagada"),
                            ("CANCELADA", "Cancelada"),
                        ],
                        default="PENDIENTE",
                        max_length=20,
                    ),
                ),
                ("referencia_pago", models.CharField(blank=True, max_length=100)),
                (
                    "beneficiario_empleado",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pagos_recibidos",
                        to="nomina.empleado",
                    ),
                ),
                (
                    "beneficiario_tercero",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pagos_recibidos",
                        to="empresa.tercero",
                    ),
                ),
                (
                    "cuenta_bancaria_origen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pagos_realizados",
                        to="gestion_financiera.cuentabancaria",
                    ),
                ),
                (
                    "perfil",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ordenes_pago",
                        to="api.providerprofile",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("beneficiario_empleado__isnull", False),
                                ("beneficiario_tercero__isnull", True),
                            ),
                            models.Q(
                                ("beneficiario_empleado__isnull", True),
                                ("beneficiario_tercero__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="un_solo_beneficiario_por_pago",
                    )
                ],
            },
        ),
    ]
