# Generated by Django 5.2.12 on 2026-03-15 12:35

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core_erp", "0001_initial_base"),
        ("prestadores", "0001_full_reset"),
    ]

    operations = [
        migrations.CreateModel(
            name="AlertaFinanciera",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("DESVIACION_PRESUPUESTAL", "Desviación Presupuestal"),
                            ("BAJA_LIQUIDEZ", "Baja Liquidez"),
                            ("VENCIMIENTO_CREDITO", "Vencimiento de Crédito"),
                            ("INCONSISTENCIA_AUDITORIA", "Inconsistencia de Auditoría"),
                        ],
                        max_length=50,
                    ),
                ),
                ("titulo", models.CharField(max_length=255)),
                ("descripcion", models.TextField()),
                ("nivel_prioridad", models.CharField(default="ALTA", max_length=20)),
                ("resuelta", models.BooleanField(default=False)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                (
                    "provider",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_items",
                        to="prestadores.providerprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BalanceGeneral",
            fields=[
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("fecha_corte", models.DateField()),
                (
                    "total_activos",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "total_pasivos",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "total_patrimonio",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                ("metadata_detalle", models.JSONField(default=dict)),
                ("fecha_generacion", models.DateTimeField(auto_now_add=True)),
                (
                    "provider",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_items",
                        to="prestadores.providerprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CambiosPatrimonio",
            fields=[
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("periodo_contable_ref_id", models.UUIDField()),
                (
                    "saldo_inicial",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "aumentos",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "disminuciones",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "saldo_final",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                ("metadata_detalle", models.JSONField(default=dict)),
                (
                    "provider",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_items",
                        to="prestadores.providerprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CreditoFinanciero",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("entidad_financiera", models.CharField(max_length=255)),
                (
                    "monto_principal",
                    models.DecimalField(decimal_places=2, max_digits=18),
                ),
                (
                    "tasa_interes_anual",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("plazo_meses", models.PositiveIntegerField()),
                ("fecha_desembolso", models.DateField()),
                (
                    "saldo_pendiente",
                    models.DecimalField(decimal_places=2, max_digits=18),
                ),
                ("estado", models.CharField(default="ACTIVO", max_length=50)),
                (
                    "provider",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_items",
                        to="prestadores.providerprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CuentaBancaria",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("bank_name", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "account_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "account_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "balance",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=18),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("perfil_ref_id", models.UUIDField()),
                (
                    "saldo_inicial",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=18),
                ),
                ("cuenta_contable_ref_id", models.UUIDField(null=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_records",
                        to="core_erp.tenant",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CuotaCredito",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_cuota", models.PositiveIntegerField()),
                ("fecha_vencimiento", models.DateField()),
                ("monto_capital", models.DecimalField(decimal_places=2, max_digits=18)),
                ("monto_interes", models.DecimalField(decimal_places=2, max_digits=18)),
                ("esta_pagada", models.BooleanField(default=False)),
                ("fecha_pago", models.DateField(blank=True, null=True)),
                (
                    "credito",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cuotas",
                        to="gestion_financiera.creditofinanciero",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EstadoResultados",
            fields=[
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("periodo_contable_ref_id", models.UUIDField()),
                (
                    "ingresos_totales",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "costos_totales",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "gastos_totales",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "utilidad_neta",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                ("metadata_detalle", models.JSONField(default=dict)),
                ("fecha_generacion", models.DateTimeField(auto_now_add=True)),
                (
                    "provider",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_items",
                        to="prestadores.providerprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Estado de Resultados",
                "verbose_name_plural": "Estados de Resultados",
            },
        ),
        migrations.CreateModel(
            name="FlujoEfectivo",
            fields=[
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("periodo_contable_ref_id", models.UUIDField()),
                (
                    "actividades_operacion",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "actividades_inversion",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "actividades_financiacion",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "efectivo_final",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                ("metadata_detalle", models.JSONField(default=dict)),
                (
                    "provider",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_items",
                        to="prestadores.providerprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="IndicadorFinancieroHistorico",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("nombre", models.CharField(max_length=100)),
                ("valor", models.DecimalField(decimal_places=2, max_digits=18)),
                ("fecha_calculo", models.DateTimeField(auto_now_add=True)),
                ("metadata_calculo", models.JSONField(default=dict)),
                (
                    "provider",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_items",
                        to="prestadores.providerprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="LogFinancieroInmutable",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("entidad_afectada", models.CharField(max_length=100)),
                ("registro_id", models.UUIDField()),
                ("accion", models.CharField(max_length=100)),
                ("datos_anteriores", models.JSONField(null=True)),
                ("datos_nuevos", models.JSONField()),
                ("usuario_id", models.IntegerField()),
                ("hash_integridad", models.CharField(max_length=64, unique=True)),
                ("fecha_registro", models.DateTimeField(auto_now_add=True)),
                (
                    "provider",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_items",
                        to="prestadores.providerprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OrdenPago",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("payment_date", models.DateField(default=django.utils.timezone.now)),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=18),
                ),
                ("concept", models.CharField(blank=True, max_length=255, null=True)),
                ("status", models.CharField(default="PENDING", max_length=20)),
                ("perfil_ref_id", models.UUIDField()),
                ("cuenta_bancaria_ref_id", models.UUIDField()),
                (
                    "beneficiario_id",
                    models.UUIDField(
                        help_text="ID del beneficiario (Cliente, Proveedor, Empleado, etc.)",
                        null=True,
                    ),
                ),
                (
                    "tipo_beneficiario",
                    models.CharField(
                        help_text="Tipo de beneficiario para resolución por servicio.",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("referencia_pago", models.CharField(blank=True, max_length=100)),
                (
                    "documento_archivistico_ref_id",
                    models.UUIDField(blank=True, null=True),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_records",
                        to="core_erp.tenant",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Presupuesto",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("nombre", models.CharField(max_length=255)),
                ("año", models.PositiveIntegerField()),
                (
                    "centro_costo",
                    models.CharField(
                        blank=True,
                        help_text="Ej: Operaciones, Marketing, Administración",
                        max_length=100,
                    ),
                ),
                (
                    "total_estimado",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "total_ejecutado",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                ("activo", models.BooleanField(default=True)),
                (
                    "provider",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_items",
                        to="prestadores.providerprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="LineaPresupuesto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cuenta_contable_ref_id",
                    models.UUIDField(
                        help_text="Referencia a la cuenta de gastos/ingresos"
                    ),
                ),
                ("nombre_item", models.CharField(max_length=255)),
                (
                    "monto_presupuestado",
                    models.DecimalField(decimal_places=2, max_digits=18),
                ),
                (
                    "monto_ejecutado",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "presupuesto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lineas",
                        to="gestion_financiera.presupuesto",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProyeccionFinanciera",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("nombre_escenario", models.CharField(max_length=255)),
                ("fecha_inicio", models.DateField()),
                ("fecha_fin", models.DateField()),
                (
                    "ingresos_proyectados",
                    models.DecimalField(decimal_places=2, max_digits=18),
                ),
                (
                    "gastos_proyectados",
                    models.DecimalField(decimal_places=2, max_digits=18),
                ),
                ("nivel_probabilidad", models.FloatField(help_text="0.0 a 1.0")),
                (
                    "provider",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_items",
                        to="prestadores.providerprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ReservaFinanciera",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("nombre", models.CharField(max_length=255)),
                (
                    "monto_objetivo",
                    models.DecimalField(decimal_places=2, max_digits=18),
                ),
                (
                    "monto_actual",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                ("proposito", models.TextField()),
                (
                    "provider",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_items",
                        to="prestadores.providerprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RiesgoFinanciero",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("tipo_riesgo", models.CharField(max_length=100)),
                ("descripcion", models.TextField()),
                (
                    "impacto_estimado",
                    models.DecimalField(decimal_places=2, max_digits=18),
                ),
                (
                    "nivel",
                    models.CharField(
                        choices=[
                            ("BAJO", "Bajo"),
                            ("MEDIO", "Medio"),
                            ("ALTO", "Alto"),
                            ("CRITICO", "Crítico"),
                        ],
                        max_length=20,
                    ),
                ),
                ("mitigacion_sugerida", models.TextField()),
                ("activo", models.BooleanField(default=True)),
                (
                    "provider",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_items",
                        to="prestadores.providerprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TesoreriaCentral",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "saldo_total_custodia",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "reservas_totales",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "liquidez_disponible",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                ("ultima_conciliacion", models.DateTimeField(blank=True, null=True)),
                (
                    "provider",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_items",
                        to="prestadores.providerprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tesorería Central",
                "verbose_name_plural": "Tesorerías Centrales",
            },
        ),
    ]
