# Generated by Django 5.2.6 on 2026-02-08 14:27

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion_financiera", "0001_initial"),
        ("prestadores", "0002_procesooperativo_tareaoperativa"),
    ]

    operations = [
        migrations.CreateModel(
            name="BalanceGeneral",
            fields=[
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("fecha_corte", models.DateField()),
                (
                    "total_activos",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "total_pasivos",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "total_patrimonio",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                ("metadata_detalle", models.JSONField(default=dict)),
                ("fecha_generacion", models.DateTimeField(auto_now_add=True)),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_items",
                        to="prestadores.providerprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CambiosPatrimonio",
            fields=[
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("periodo_contable_ref_id", models.UUIDField()),
                (
                    "saldo_inicial",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "aumentos",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "disminuciones",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "saldo_final",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                ("metadata_detalle", models.JSONField(default=dict)),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_items",
                        to="prestadores.providerprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EstadoResultados",
            fields=[
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("periodo_contable_ref_id", models.UUIDField()),
                (
                    "ingresos_totales",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "costos_totales",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "gastos_totales",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "utilidad_neta",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                ("metadata_detalle", models.JSONField(default=dict)),
                ("fecha_generacion", models.DateTimeField(auto_now_add=True)),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_items",
                        to="prestadores.providerprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Estado de Resultados",
                "verbose_name_plural": "Estados de Resultados",
            },
        ),
        migrations.CreateModel(
            name="FlujoEfectivo",
            fields=[
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("periodo_contable_ref_id", models.UUIDField()),
                (
                    "actividades_operacion",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "actividades_inversion",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "actividades_financiacion",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "efectivo_final",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                ("metadata_detalle", models.JSONField(default=dict)),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_items",
                        to="prestadores.providerprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProyeccionFinanciera",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("nombre_escenario", models.CharField(max_length=255)),
                ("fecha_inicio", models.DateField()),
                ("fecha_fin", models.DateField()),
                (
                    "ingresos_proyectados",
                    models.DecimalField(decimal_places=2, max_digits=18),
                ),
                (
                    "gastos_proyectados",
                    models.DecimalField(decimal_places=2, max_digits=18),
                ),
                ("nivel_probabilidad", models.FloatField(help_text="0.0 a 1.0")),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_items",
                        to="prestadores.providerprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ReservaFinanciera",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("nombre", models.CharField(max_length=255)),
                (
                    "monto_objetivo",
                    models.DecimalField(decimal_places=2, max_digits=18),
                ),
                (
                    "monto_actual",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                ("proposito", models.TextField()),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_items",
                        to="prestadores.providerprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RiesgoFinanciero",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("tipo_riesgo", models.CharField(max_length=100)),
                ("descripcion", models.TextField()),
                (
                    "impacto_estimado",
                    models.DecimalField(decimal_places=2, max_digits=18),
                ),
                (
                    "nivel",
                    models.CharField(
                        choices=[
                            ("BAJO", "Bajo"),
                            ("MEDIO", "Medio"),
                            ("ALTO", "Alto"),
                            ("CRITICO", "Crítico"),
                        ],
                        max_length=20,
                    ),
                ),
                ("mitigacion_sugerida", models.TextField()),
                ("activo", models.BooleanField(default=True)),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_items",
                        to="prestadores.providerprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TesoreriaCentral",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "saldo_total_custodia",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "reservas_totales",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "liquidez_disponible",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                ("ultima_conciliacion", models.DateTimeField(blank=True, null=True)),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_items",
                        to="prestadores.providerprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tesorería Central",
                "verbose_name_plural": "Tesorerías Centrales",
            },
        ),
    ]
