# Generated by Django 5.2.6 on 2026-01-07 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("api", "0001_initial"),
        ("empresa", "0001_initial"),
        ("gestion_financiera", "0001_initial"),
        ("nomina", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ordenpago",
            name="beneficiario_empleado",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="pagos_recibidos",
                to="nomina.empleado",
            ),
        ),
        migrations.AddField(
            model_name="ordenpago",
            name="beneficiario_tercero",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="pagos_recibidos",
                to="empresa.tercero",
            ),
        ),
        migrations.AddField(
            model_name="ordenpago",
            name="cuenta_bancaria_origen",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="pagos_realizados",
                to="gestion_financiera.cuentabancaria",
            ),
        ),
        migrations.AddField(
            model_name="ordenpago",
            name="perfil",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ordenes_pago",
                to="api.providerprofile",
            ),
        ),
        migrations.AddConstraint(
            model_name="ordenpago",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("beneficiario_empleado__isnull", False),
                        ("beneficiario_tercero__isnull", True),
                    ),
                    models.Q(
                        ("beneficiario_empleado__isnull", True),
                        ("beneficiario_tercero__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="un_solo_beneficiario_por_pago",
            ),
        ),
    ]
