# Generated by Django 5.2.6 on 2026-01-09 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion_financiera", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ordenpago",
            name="beneficiario_content_type",
        ),
        migrations.RemoveField(
            model_name="ordenpago",
            name="beneficiario_object_id",
        ),
        migrations.AddField(
            model_name="ordenpago",
            name="beneficiario_id",
            field=models.UUIDField(
                help_text="ID del beneficiario (Cliente, Proveedor, Empleado, etc.)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="ordenpago",
            name="tipo_beneficiario",
            field=models.CharField(
                help_text="Tipo de beneficiario para resolución por servicio.",
                max_length=100,
                null=True,
            ),
        ),
    ]
