# Generated by Django 5.2.6 on 2025-12-11 15:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("gestion_financiera", "0001_initial"),
        ("prestadores", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="cuentabancaria",
            name="perfil",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cuentas_bancarias",
                to="prestadores.providerprofile",
            ),
        ),
        migrations.AddField(
            model_name="transaccionbancaria",
            name="creado_por",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="transaccionbancaria",
            name="cuenta",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transacciones",
                to="gestion_financiera.cuentabancaria",
            ),
        ),
    ]
