# Generated by Django 5.2.11 on 2026-02-15 15:25

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "gestion_financiera",
            "0002_balancegeneral_cambiospatrimonio_estadoresultados_and_more",
        ),
        (
            "prestadores",
            "0004_remove_alojamiento_perfil_remove_alojamiento_tipo_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="CreditoFinanciero",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("entidad_financiera", models.CharField(max_length=255)),
                (
                    "monto_principal",
                    models.DecimalField(decimal_places=2, max_digits=18),
                ),
                (
                    "tasa_interes_anual",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("plazo_meses", models.PositiveIntegerField()),
                ("fecha_desembolso", models.DateField()),
                (
                    "saldo_pendiente",
                    models.DecimalField(decimal_places=2, max_digits=18),
                ),
                ("estado", models.CharField(default="ACTIVO", max_length=50)),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_items",
                        to="prestadores.providerprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CuotaCredito",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_cuota", models.PositiveIntegerField()),
                ("fecha_vencimiento", models.DateField()),
                ("monto_capital", models.DecimalField(decimal_places=2, max_digits=18)),
                ("monto_interes", models.DecimalField(decimal_places=2, max_digits=18)),
                ("esta_pagada", models.BooleanField(default=False)),
                ("fecha_pago", models.DateField(blank=True, null=True)),
                (
                    "credito",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cuotas",
                        to="gestion_financiera.creditofinanciero",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IndicadorFinancieroHistorico",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("nombre", models.CharField(max_length=100)),
                ("valor", models.DecimalField(decimal_places=2, max_digits=18)),
                ("fecha_calculo", models.DateTimeField(auto_now_add=True)),
                ("metadata_calculo", models.JSONField(default=dict)),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_items",
                        to="prestadores.providerprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Presupuesto",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("nombre", models.CharField(max_length=255)),
                ("año", models.PositiveIntegerField()),
                (
                    "total_estimado",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "total_ejecutado",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                ("activo", models.BooleanField(default=True)),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_items",
                        to="prestadores.providerprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="LineaPresupuesto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cuenta_contable_ref_id",
                    models.UUIDField(
                        help_text="Referencia a la cuenta de gastos/ingresos"
                    ),
                ),
                ("nombre_item", models.CharField(max_length=255)),
                (
                    "monto_presupuestado",
                    models.DecimalField(decimal_places=2, max_digits=18),
                ),
                (
                    "monto_ejecutado",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "presupuesto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lineas",
                        to="gestion_financiera.presupuesto",
                    ),
                ),
            ],
        ),
    ]
