# Generated by Django 5.2.11 on 2026-02-15 15:58

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion_financiera", "0003_creditofinanciero_cuotacredito_and_more"),
        (
            "prestadores",
            "0004_remove_alojamiento_perfil_remove_alojamiento_tipo_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="presupuesto",
            name="centro_costo",
            field=models.CharField(
                blank=True,
                help_text="Ej: Operaciones, Marketing, Administración",
                max_length=100,
            ),
        ),
        migrations.CreateModel(
            name="AlertaFinanciera",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("DESVIACION_PRESUPUESTAL", "Desviación Presupuestal"),
                            ("BAJA_LIQUIDEZ", "Baja Liquidez"),
                            ("VENCIMIENTO_CREDITO", "Vencimiento de Crédito"),
                            ("INCONSISTENCIA_AUDITORIA", "Inconsistencia de Auditoría"),
                        ],
                        max_length=50,
                    ),
                ),
                ("titulo", models.CharField(max_length=255)),
                ("descripcion", models.TextField()),
                ("nivel_prioridad", models.CharField(default="ALTA", max_length=20)),
                ("resuelta", models.BooleanField(default=False)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_items",
                        to="prestadores.providerprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="LogFinancieroInmutable",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("entidad_afectada", models.CharField(max_length=100)),
                ("registro_id", models.UUIDField()),
                ("accion", models.CharField(max_length=100)),
                ("datos_anteriores", models.JSONField(null=True)),
                ("datos_nuevos", models.JSONField()),
                ("usuario_id", models.IntegerField()),
                ("hash_integridad", models.CharField(max_length=64, unique=True)),
                ("fecha_registro", models.DateTimeField(auto_now_add=True)),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_items",
                        to="prestadores.providerprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
    ]
