# Generated by Django 5.2.6 on 2026-01-20 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("prestadores", "0003_categoriaprestador_providerprofile_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, unique=True)),
                ("descripcion", models.TextField()),
                ("precio", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "frecuencia",
                    models.CharField(
                        choices=[
                            ("MENSUAL", "Mensual"),
                            ("SEMESTRAL", "Semestral"),
                            ("ANUAL", "Anual"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "tipo_usuario_objetivo",
                    models.CharField(
                        choices=[("GOBIERNO", "Gobierno"), ("PRESTADOR", "Prestador")],
                        max_length=20,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indica si el plan está disponible para nuevas suscripciones.",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Suscripcion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_inicio", models.DateField()),
                ("fecha_fin", models.DateField()),
                ("is_active", models.BooleanField(default=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suscripciones_como_cliente",
                        to="prestadores.providerprofile",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="suscripciones",
                        to="admin_plataforma.plan",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Suscripciones",
                "ordering": ["-fecha_inicio"],
            },
        ),
    ]
