# Generated by Django 5.2.12 on 2026-03-15 13:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentInteraction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("correlation_id", models.UUIDField(db_index=True)),
                ("sender_id", models.CharField(max_length=100)),
                ("interaction_type", models.CharField(max_length=50)),
                ("payload", models.JSONField()),
                ("intelligence", models.JSONField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="AgentPerformance",
            fields=[
                (
                    "agent_id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("total_votes", models.IntegerField(default=0)),
                (
                    "votes_in_consensus",
                    models.IntegerField(
                        default=0,
                        help_text="Veces que votó con la decisión final exitosa.",
                    ),
                ),
                ("avg_confidence", models.FloatField(default=0.0)),
                ("current_weight_multiplier", models.FloatField(default=1.0)),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="DecisionHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("intention", models.CharField(db_index=True, max_length=255)),
                ("input_params", models.JSONField()),
                ("risk_score", models.FloatField()),
                ("consensus_score", models.FloatField()),
                ("final_status", models.CharField(db_index=True, max_length=50)),
                ("execution_time_ms", models.IntegerField(blank=True, null=True)),
                ("was_compensated", models.BooleanField(default=False)),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "embedding",
                    models.BinaryField(
                        blank=True,
                        help_text="Representación vectorial de la decisión.",
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GovernanceIntention",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("origin_domain", models.CharField(max_length=100)),
                ("trigger_event", models.CharField(max_length=100)),
                ("requested_action", models.JSONField()),
                ("risk_score", models.FloatField(default=0.0)),
                (
                    "validation_status",
                    models.CharField(
                        choices=[
                            ("RECEIVED", "Received"),
                            ("VALIDATING", "Validating"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("EXECUTING", "Executing"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        default="RECEIVED",
                        max_length=20,
                    ),
                ),
                ("execution_result", models.JSONField(blank=True, null=True)),
                (
                    "hash_chain",
                    models.CharField(
                        blank=True, db_index=True, max_length=64, null=True
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="GovernancePolicy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("BLOCK", "Bloqueo Total"),
                            ("THRESHOLD", "Umbral de Alerta/Bloqueo"),
                            ("REQUIRE_VERIFICATION", "Requiere Verificación Manual"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "domain",
                    models.CharField(
                        default="global",
                        help_text="Dominio afectado (global, comercial, etc.)",
                        max_length=100,
                    ),
                ),
                (
                    "affected_intentions",
                    models.JSONField(
                        default=list,
                        help_text="Lista de intenciones que responden a esta política.",
                    ),
                ),
                (
                    "config",
                    models.JSONField(
                        default=dict,
                        help_text="Configuración dinámica (ej: {'limit': 1000})",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Política de Gobernanza",
                "verbose_name_plural": "Políticas de Gobernanza",
            },
        ),
        migrations.CreateModel(
            name="AdaptiveProposal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("WEIGHT_ADJUST", "Ajuste de Pesos PCA"),
                            ("WORKFLOW_OPT", "Optimización de Workflow"),
                            ("RISK_THRESHOLD", "Ajuste de Umbral de Riesgo"),
                        ],
                        max_length=50,
                    ),
                ),
                ("proposal_data", models.JSONField()),
                ("reasoning", models.TextField()),
                ("is_applied", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GovernanceAuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("intencion", models.CharField(db_index=True, max_length=255)),
                ("parametros", models.JSONField(default=dict)),
                ("resultado", models.JSONField(default=dict)),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("success", models.BooleanField(default=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("es_intervencion_soberana", models.BooleanField(default=False)),
                (
                    "integrity_hash",
                    models.CharField(
                        blank=True, db_index=True, max_length=64, null=True
                    ),
                ),
                (
                    "previous_hash",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="governance_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="WorkflowDefinition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("version", models.IntegerField(default=1)),
                (
                    "definition",
                    models.JSONField(
                        help_text="Esquema JSON con pasos, dependencias y compensaciones."
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "unique_together": {("name", "version")},
            },
        ),
        migrations.CreateModel(
            name="WorkflowInstance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "correlation_id",
                    models.UUIDField(
                        db_index=True, help_text="ID del comando MCP que disparó esto."
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("CREATED", "Created"),
                            ("RUNNING", "Running"),
                            ("WAITING", "Waiting"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                            ("COMPENSATING", "Compensating"),
                            ("ROLLED_BACK", "Rolled Back"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="CREATED",
                        max_length=20,
                    ),
                ),
                ("input_data", models.JSONField(default=dict)),
                ("output_data", models.JSONField(blank=True, default=dict, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("current_step_index", models.IntegerField(default=0)),
                (
                    "definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="admin_plataforma.workflowdefinition",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StepExecution",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("step_name", models.CharField(max_length=255)),
                ("status", models.CharField(default="PENDING", max_length=20)),
                ("attempts", models.IntegerField(default=0)),
                ("last_error", models.TextField(blank=True, null=True)),
                ("executed_at", models.DateTimeField(auto_now_add=True)),
                ("is_compensated", models.BooleanField(default=False)),
                (
                    "instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="admin_plataforma.workflowinstance",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GovernancePolicyVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version_number", models.IntegerField()),
                ("config_snapshot", models.JSONField()),
                ("reason_for_change", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="admin_plataforma.governancepolicy",
                    ),
                ),
            ],
            options={
                "unique_together": {("policy", "version_number")},
            },
        ),
    ]
