# Generated by Django 5.2.6 on 2026-01-29 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_operativa", "0001_initial"),
        ("admin_plataforma", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="descripcion",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="plan",
            name="frecuencia",
            field=models.CharField(
                choices=[
                    ("MENSUAL", "Mensual"),
                    ("SEMESTRAL", "Semestral"),
                    ("ANUAL", "Anual"),
                ],
                default="MENSUAL",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="plan",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Indica si el plan está disponible para nuevas suscripciones.",
            ),
        ),
        migrations.AddField(
            model_name="plan",
            name="precio",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="plan",
            name="tipo_usuario_objetivo",
            field=models.CharField(
                choices=[("GOBIERNO", "Gobierno"), ("PRESTADOR", "Prestador")],
                default="PRESTADOR",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Suscripcion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_inicio", models.DateField()),
                ("fecha_fin", models.DateField()),
                ("is_active", models.BooleanField(default=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admin_suscripciones",
                        to="admin_operativa.providerprofile",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="admin_suscripciones",
                        to="admin_plataforma.plan",
                    ),
                ),
            ],
        ),
    ]
