# Generated by Django 5.2.6 on 2026-01-22 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("admin_plataforma", "0001_initial"),
        ("prestadores", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="suscripcion",
            name="cliente",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="suscripciones_como_cliente",
                to="prestadores.providerprofile",
            ),
        ),
        migrations.AddField(
            model_name="suscripcion",
            name="plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="suscripciones",
                to="admin_plataforma.plan",
            ),
        ),
    ]
