# Generated by Django 6.0.3 on 2026-03-24 23:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_plataforma", "0001_full_reset"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlatformGlobalSettings",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "social_gift_commission_pct",
                    models.DecimalField(
                        decimal_places=2,
                        default=2.0,
                        help_text="Porcentaje de comisión por regalos sociales.",
                        max_digits=5,
                    ),
                ),
                (
                    "room_entry_commission_pct",
                    models.DecimalField(
                        decimal_places=2,
                        default=10.0,
                        help_text="Porcentaje de comisión por entrada a salas privadas.",
                        max_digits=5,
                    ),
                ),
                (
                    "max_gift_amount",
                    models.DecimalField(
                        decimal_places=2, default=100000.0, max_digits=12
                    ),
                ),
                ("maintenance_mode", models.BooleanField(default=False)),
                ("registration_open", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Configuración Global de Plataforma",
            },
        ),
    ]
