# Generated by Django 5.2.10 on 2026-01-29 20:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_plataforma", "0003_governanceauditlog"),
    ]

    operations = [
        migrations.CreateModel(
            name="GovernancePolicy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("BLOCK", "Bloqueo Total"),
                            ("THRESHOLD", "Umbral de Alerta/Bloqueo"),
                            ("REQUIRE_VERIFICATION", "Requiere Verificación Manual"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "domain",
                    models.CharField(
                        default="global",
                        help_text="Dominio afectado (global, comercial, etc.)",
                        max_length=100,
                    ),
                ),
                (
                    "affected_intentions",
                    models.JSONField(
                        default=list,
                        help_text="Lista de intenciones que responden a esta política.",
                    ),
                ),
                (
                    "config",
                    models.JSONField(
                        default=dict,
                        help_text="Configuración dinámica (ej: {'limit': 1000})",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Política de Gobernanza",
                "verbose_name_plural": "Políticas de Gobernanza",
            },
        ),
    ]
