# Generated by Django 5.2.10 on 2026-01-29 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_plataforma", "0004_governancepolicy"),
    ]

    operations = [
        migrations.AddField(
            model_name="governanceauditlog",
            name="es_intervencion_soberana",
            field=models.BooleanField(default=False),
        ),
    ]
