# Generated by Django 5.2.6 on 2026-02-03 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_plataforma", "0005_governanceauditlog_es_intervencion_soberana"),
    ]

    operations = [
        migrations.AddField(
            model_name="governanceauditlog",
            name="integrity_hash",
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="governanceauditlog",
            name="previous_hash",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
