# Generated by Django 5.2.6 on 2026-02-18 00:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_plataforma", "0007_workflowdefinition_workflowinstance_stepexecution"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentPerformance",
            fields=[
                (
                    "agent_id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("total_votes", models.IntegerField(default=0)),
                (
                    "votes_in_consensus",
                    models.IntegerField(
                        default=0,
                        help_text="Veces que votó con la decisión final exitosa.",
                    ),
                ),
                ("avg_confidence", models.FloatField(default=0.0)),
                ("current_weight_multiplier", models.FloatField(default=1.0)),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="DecisionHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("intention", models.CharField(db_index=True, max_length=255)),
                ("input_params", models.JSONField()),
                ("risk_score", models.FloatField()),
                ("consensus_score", models.FloatField()),
                ("final_status", models.CharField(db_index=True, max_length=50)),
                ("execution_time_ms", models.IntegerField(blank=True, null=True)),
                ("was_compensated", models.BooleanField(default=False)),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "embedding",
                    models.BinaryField(
                        blank=True,
                        help_text="Representación vectorial de la decisión.",
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AdaptiveProposal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("WEIGHT_ADJUST", "Ajuste de Pesos PCA"),
                            ("WORKFLOW_OPT", "Optimización de Workflow"),
                            ("RISK_THRESHOLD", "Ajuste de Umbral de Riesgo"),
                        ],
                        max_length=50,
                    ),
                ),
                ("proposal_data", models.JSONField()),
                ("reasoning", models.TextField()),
                ("is_applied", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
