# Generated by Django 5.2.6 on 2026-02-18 01:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_plataforma", "0008_agentperformance_decisionhistory_adaptiveproposal"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentInteraction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("correlation_id", models.UUIDField(db_index=True)),
                ("sender_id", models.CharField(max_length=100)),
                ("interaction_type", models.CharField(max_length=50)),
                ("payload", models.JSONField()),
                ("intelligence", models.JSONField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
