# Generated by Django 5.2.12 on 2026-03-15 13:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("prestadores", "0001_full_reset"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Proveedor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                ("identificacion", models.CharField(blank=True, max_length=20)),
                ("telefono", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("direccion", models.TextField(blank=True)),
                (
                    "perfil",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proveedores",
                        to="prestadores.providerprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FacturaCompra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=50)),
                ("issue_date", models.DateField()),
                ("fecha_vencimiento", models.DateField(blank=True, null=True)),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=18),
                ),
                (
                    "impuestos",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=18),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=18),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("BORRADOR", "Borrador"),
                            ("POR_PAGAR", "Por Pagar"),
                            ("PAGADA", "Pagada"),
                            ("VENCIDA", "Vencida"),
                            ("ANULADA", "Anulada"),
                        ],
                        default="POR_PAGAR",
                        max_length=20,
                    ),
                ),
                ("notas", models.TextField(blank=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "creado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "perfil",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="facturas_compra",
                        to="prestadores.providerprofile",
                    ),
                ),
                (
                    "proveedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="facturas",
                        to="compras.proveedor",
                    ),
                ),
            ],
            options={
                "ordering": ["-issue_date"],
                "unique_together": {("perfil", "proveedor", "number")},
            },
        ),
    ]
