# Generated by Django 5.2.6 on 2026-01-22 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("compras", "0001_initial"),
        ("prestadores", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="facturacompra",
            name="perfil",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="facturas_compra",
                to="prestadores.providerprofile",
            ),
        ),
        migrations.AddField(
            model_name="proveedor",
            name="perfil",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="proveedores",
                to="prestadores.providerprofile",
            ),
        ),
        migrations.AddField(
            model_name="facturacompra",
            name="proveedor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="facturas",
                to="compras.proveedor",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="facturacompra",
            unique_together={("perfil", "proveedor", "number")},
        ),
    ]
