# Generated by Django 5.2.12 on 2026-03-15 12:35

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import djmoney.models.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalogs", "0001_full_reset"),
        ("domain_business", "0001_full_reset"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoriaPrestador",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("nombre", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(max_length=100, unique=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="IncidenteLaboral",
            fields=[
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("ACCIDENTE", "Accidente de Trabajo"),
                            ("INCIDENTE", "Incidente (Casi accidente)"),
                            ("ENFERMEDAD", "Enfermedad Laboral"),
                        ],
                        max_length=20,
                    ),
                ),
                ("fecha_hora", models.DateTimeField()),
                ("lugar", models.CharField(max_length=255)),
                ("descripcion_hechos", models.TextField()),
                ("personas_afectadas", models.JSONField(default=list)),
                (
                    "gravedad",
                    models.CharField(
                        choices=[
                            ("LEVE", "Leve"),
                            ("GRAVE", "Grave"),
                            ("MORTAL", "Mortal"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "estado_investigacion",
                    models.CharField(default="PENDIENTE", max_length=50),
                ),
                (
                    "evidencia_archivistica_ref_id",
                    models.UUIDField(blank=True, null=True),
                ),
            ],
            options={
                "verbose_name": "Incidente Laboral",
                "verbose_name_plural": "Incidentes Laborales",
            },
        ),
        migrations.CreateModel(
            name="InspeccionSST",
            fields=[
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tipo", models.CharField(max_length=100)),
                ("fecha", models.DateField()),
                ("inspector_id", models.UUIDField()),
                ("centro_trabajo", models.CharField(max_length=255)),
                (
                    "porcentaje_hallazgos_cerrados",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InventoryItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "nombre_item",
                    models.CharField(max_length=255, verbose_name="Nombre del Ítem"),
                ),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("CONSUMABLE", "Consumible"),
                            ("ASSET", "Activo Fijo"),
                            ("RETAIL", "Producto de Venta"),
                        ],
                        default="CONSUMABLE",
                        max_length=20,
                        verbose_name="Tipo de Ítem",
                    ),
                ),
                (
                    "stock_actual",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="Stock Actual",
                    ),
                ),
                (
                    "stock_minimo",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="Stock Mínimo",
                    ),
                ),
                (
                    "stock_maximo",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="Stock Máximo",
                    ),
                ),
                (
                    "unidad",
                    models.CharField(
                        help_text="Ej: unidades, kg, litros",
                        max_length=50,
                        verbose_name="Unidad de Medida",
                    ),
                ),
                (
                    "punto_reorden",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="Punto de Reorden",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ítem de Inventario",
                "verbose_name_plural": "Ítems de Inventario",
                "ordering": ["nombre_item"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="KitchenStation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "nombre",
                    models.CharField(
                        max_length=100, verbose_name="Nombre de la Estación"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MatrizRiesgo",
            fields=[
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("proceso_operativo_ref_id", models.UUIDField(blank=True, null=True)),
                ("peligro_descripcion", models.CharField(max_length=255)),
                ("clasificacion", models.CharField(max_length=100)),
                ("efectos_posibles", models.TextField()),
                ("probabilidad", models.IntegerField(help_text="1 a 4")),
                ("consecuencia", models.IntegerField(help_text="1 a 4")),
                ("nivel_riesgo", models.IntegerField(editable=False)),
                ("aceptabilidad", models.CharField(max_length=50)),
                ("criticidad", models.CharField(default="MEDIA", max_length=20)),
                ("fecha_identificacion", models.DateField(auto_now_add=True)),
                ("ultima_revision", models.DateTimeField(auto_now=True)),
                ("version", models.IntegerField(default=1)),
                ("es_vigente", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Matriz de Riesgo",
                "verbose_name_plural": "Matrices de Riesgo",
            },
        ),
        migrations.CreateModel(
            name="PlanAnualSST",
            fields=[
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("año", models.IntegerField()),
                ("nombre", models.CharField(max_length=255)),
                ("objetivo", models.TextField()),
                (
                    "porcentaje_cumplimiento",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("estado", models.CharField(default="BORRADOR", max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="PoliticaCancelacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("perfil_ref_id", models.UUIDField()),
                ("nombre", models.CharField(max_length=100)),
                ("descripcion", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="ProviderProfile",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("domain_business.providerprofile",),
        ),
        migrations.CreateModel(
            name="HallazgoInspeccion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descripcion", models.TextField()),
                (
                    "criticidad",
                    models.CharField(
                        choices=[
                            ("ALTA", "Alta"),
                            ("MEDIA", "Media"),
                            ("BAJA", "Baja"),
                        ],
                        max_length=20,
                    ),
                ),
                ("plan_accion", models.TextField()),
                ("fecha_limite", models.DateField()),
                ("cerrado", models.BooleanField(default=False)),
                ("fecha_cierre", models.DateField(blank=True, null=True)),
                (
                    "inspeccion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hallazgos",
                        to="prestadores.inspeccionsst",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AsignacionRecurso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("orden_operativa_ref_id", models.UUIDField()),
                (
                    "cantidad_asignada",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "cantidad_consumida_real",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("fecha_asignacion", models.DateTimeField(auto_now_add=True)),
                ("completado", models.BooleanField(default=False)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asignaciones",
                        to="prestadores.inventoryitem",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InvestigacionIncidente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("causas_basicas", models.TextField()),
                ("causas_inmediatas", models.TextField()),
                ("plan_accion", models.TextField()),
                ("responsable_seguimiento_id", models.UUIDField()),
                ("fecha_cierre", models.DateField(blank=True, null=True)),
                (
                    "incidente",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="investigacion",
                        to="prestadores.incidentelaboral",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ControlRiesgo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "jerarquia",
                    models.CharField(
                        choices=[
                            ("ELIMINACION", "Eliminación"),
                            ("SUSTITUCION", "Sustitución"),
                            ("INGENIERIA", "Controles de Ingeniería"),
                            ("ADMINISTRATIVO", "Controles Administrativos"),
                            ("EPP", "Equipos de Protección Personal"),
                        ],
                        max_length=50,
                    ),
                ),
                ("descripcion_control", models.TextField()),
                ("implementado", models.BooleanField(default=False)),
                ("fecha_implementacion", models.DateField(blank=True, null=True)),
                (
                    "matriz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="controles",
                        to="prestadores.matrizriesgo",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ActividadPlanSST",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                ("fecha_programada", models.DateField()),
                ("fecha_ejecutada", models.DateField(blank=True, null=True)),
                ("responsable_id", models.UUIDField(blank=True, null=True)),
                ("completada", models.BooleanField(default=False)),
                ("evidencia_id", models.UUIDField(blank=True, null=True)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actividades",
                        to="prestadores.plananualsst",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "id_publico",
                    models.UUIDField(editable=False, null=True, unique=True),
                ),
                ("nombre", models.CharField(max_length=200, verbose_name="Nombre")),
                (
                    "descripcion",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("PRODUCTO", "Producto"), ("SERVICIO", "Servicio")],
                        default="PRODUCTO",
                        max_length=10,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "es_inventariable",
                    models.BooleanField(
                        default=False,
                        help_text="Marcar si este producto gestiona stock.",
                        verbose_name="Es Inventariable",
                    ),
                ),
                (
                    "stock",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="La cantidad actual de este producto en inventario.",
                        verbose_name="Stock Actual",
                    ),
                ),
                (
                    "base_price_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[
                            ("XUA", "ADB Unit of Account"),
                            ("AFN", "Afghan Afghani"),
                            ("AFA", "Afghan Afghani (1927–2002)"),
                            ("ALL", "Albanian Lek"),
                            ("ALK", "Albanian Lek (1946–1965)"),
                            ("DZD", "Algerian Dinar"),
                            ("ADP", "Andorran Peseta"),
                            ("AOA", "Angolan Kwanza"),
                            ("AOK", "Angolan Kwanza (1977–1991)"),
                            ("AON", "Angolan New Kwanza (1990–2000)"),
                            ("AOR", "Angolan Readjusted Kwanza (1995–1999)"),
                            ("ARA", "Argentine Austral"),
                            ("ARS", "Argentine Peso"),
                            ("ARM", "Argentine Peso (1881–1970)"),
                            ("ARP", "Argentine Peso (1983–1985)"),
                            ("ARL", "Argentine Peso Ley (1970–1983)"),
                            ("AMD", "Armenian Dram"),
                            ("AWG", "Aruban Florin"),
                            ("AUD", "Australian Dollar"),
                            ("ATS", "Austrian Schilling"),
                            ("AZN", "Azerbaijani Manat"),
                            ("AZM", "Azerbaijani Manat (1993–2006)"),
                            ("BSD", "Bahamian Dollar"),
                            ("BHD", "Bahraini Dinar"),
                            ("BDT", "Bangladeshi Taka"),
                            ("BBD", "Barbadian Dollar"),
                            ("BYN", "Belarusian Ruble"),
                            ("BYB", "Belarusian Ruble (1994–1999)"),
                            ("BYR", "Belarusian Ruble (2000–2016)"),
                            ("BEF", "Belgian Franc"),
                            ("BEC", "Belgian Franc (convertible)"),
                            ("BEL", "Belgian Franc (financial)"),
                            ("BZD", "Belize Dollar"),
                            ("BMD", "Bermudan Dollar"),
                            ("BTN", "Bhutanese Ngultrum"),
                            ("BOB", "Bolivian Boliviano"),
                            ("BOL", "Bolivian Boliviano (1863–1963)"),
                            ("BOV", "Bolivian Mvdol"),
                            ("BOP", "Bolivian Peso"),
                            ("VED", "Bolívar Soberano"),
                            ("BAM", "Bosnia-Herzegovina Convertible Mark"),
                            ("BAD", "Bosnia-Herzegovina Dinar (1992–1994)"),
                            ("BAN", "Bosnia-Herzegovina New Dinar (1994–1997)"),
                            ("BWP", "Botswanan Pula"),
                            ("BRC", "Brazilian Cruzado (1986–1989)"),
                            ("BRZ", "Brazilian Cruzeiro (1942–1967)"),
                            ("BRE", "Brazilian Cruzeiro (1990–1993)"),
                            ("BRR", "Brazilian Cruzeiro (1993–1994)"),
                            ("BRN", "Brazilian New Cruzado (1989–1990)"),
                            ("BRB", "Brazilian New Cruzeiro (1967–1986)"),
                            ("BRL", "Brazilian Real"),
                            ("GBP", "British Pound"),
                            ("BND", "Brunei Dollar"),
                            ("BGL", "Bulgarian Hard Lev"),
                            ("BGN", "Bulgarian Lev"),
                            ("BGO", "Bulgarian Lev (1879–1952)"),
                            ("BGM", "Bulgarian Socialist Lev"),
                            ("BUK", "Burmese Kyat"),
                            ("BIF", "Burundian Franc"),
                            ("XPF", "CFP Franc"),
                            ("KHR", "Cambodian Riel"),
                            ("CAD", "Canadian Dollar"),
                            ("CVE", "Cape Verdean Escudo"),
                            ("KYD", "Cayman Islands Dollar"),
                            ("XAF", "Central African CFA Franc"),
                            ("CLE", "Chilean Escudo"),
                            ("CLP", "Chilean Peso"),
                            ("CLF", "Chilean Unit of Account (UF)"),
                            ("CNX", "Chinese People’s Bank Dollar"),
                            ("CNY", "Chinese Yuan"),
                            ("CNH", "Chinese Yuan (offshore)"),
                            ("COP", "Colombian Peso"),
                            ("COU", "Colombian Real Value Unit"),
                            ("KMF", "Comorian Franc"),
                            ("CDF", "Congolese Franc"),
                            ("CRC", "Costa Rican Colón"),
                            ("HRD", "Croatian Dinar"),
                            ("HRK", "Croatian Kuna"),
                            ("CUC", "Cuban Convertible Peso"),
                            ("CUP", "Cuban Peso"),
                            ("CYP", "Cypriot Pound"),
                            ("CZK", "Czech Koruna"),
                            ("CSK", "Czechoslovak Hard Koruna"),
                            ("DKK", "Danish Krone"),
                            ("DJF", "Djiboutian Franc"),
                            ("DOP", "Dominican Peso"),
                            ("NLG", "Dutch Guilder"),
                            ("XCD", "East Caribbean Dollar"),
                            ("DDM", "East German Mark"),
                            ("ECS", "Ecuadorian Sucre"),
                            ("ECV", "Ecuadorian Unit of Constant Value"),
                            ("EGP", "Egyptian Pound"),
                            ("GQE", "Equatorial Guinean Ekwele"),
                            ("ERN", "Eritrean Nakfa"),
                            ("EEK", "Estonian Kroon"),
                            ("ETB", "Ethiopian Birr"),
                            ("EUR", "Euro"),
                            ("XBA", "European Composite Unit"),
                            ("XEU", "European Currency Unit"),
                            ("XBB", "European Monetary Unit"),
                            ("XBC", "European Unit of Account (XBC)"),
                            ("XBD", "European Unit of Account (XBD)"),
                            ("FKP", "Falkland Islands Pound"),
                            ("FJD", "Fijian Dollar"),
                            ("FIM", "Finnish Markka"),
                            ("FRF", "French Franc"),
                            ("XFO", "French Gold Franc"),
                            ("XFU", "French UIC-Franc"),
                            ("GMD", "Gambian Dalasi"),
                            ("GEK", "Georgian Kupon Larit"),
                            ("GEL", "Georgian Lari"),
                            ("DEM", "German Mark"),
                            ("GHS", "Ghanaian Cedi"),
                            ("GHC", "Ghanaian Cedi (1979–2007)"),
                            ("GIP", "Gibraltar Pound"),
                            ("XAU", "Gold"),
                            ("GRD", "Greek Drachma"),
                            ("GTQ", "Guatemalan Quetzal"),
                            ("GWP", "Guinea-Bissau Peso"),
                            ("GNF", "Guinean Franc"),
                            ("GNS", "Guinean Syli"),
                            ("GYD", "Guyanaese Dollar"),
                            ("HTG", "Haitian Gourde"),
                            ("HNL", "Honduran Lempira"),
                            ("HKD", "Hong Kong Dollar"),
                            ("HUF", "Hungarian Forint"),
                            ("IMP", "IMP"),
                            ("ISK", "Icelandic Króna"),
                            ("ISJ", "Icelandic Króna (1918–1981)"),
                            ("INR", "Indian Rupee"),
                            ("IDR", "Indonesian Rupiah"),
                            ("IRR", "Iranian Rial"),
                            ("IQD", "Iraqi Dinar"),
                            ("IEP", "Irish Pound"),
                            ("ILS", "Israeli New Shekel"),
                            ("ILP", "Israeli Pound"),
                            ("ILR", "Israeli Shekel (1980–1985)"),
                            ("ITL", "Italian Lira"),
                            ("JMD", "Jamaican Dollar"),
                            ("JPY", "Japanese Yen"),
                            ("JOD", "Jordanian Dinar"),
                            ("KZT", "Kazakhstani Tenge"),
                            ("KES", "Kenyan Shilling"),
                            ("KWD", "Kuwaiti Dinar"),
                            ("KGS", "Kyrgystani Som"),
                            ("LAK", "Laotian Kip"),
                            ("LVL", "Latvian Lats"),
                            ("LVR", "Latvian Ruble"),
                            ("LBP", "Lebanese Pound"),
                            ("LSL", "Lesotho Loti"),
                            ("LRD", "Liberian Dollar"),
                            ("LYD", "Libyan Dinar"),
                            ("LTL", "Lithuanian Litas"),
                            ("LTT", "Lithuanian Talonas"),
                            ("LUL", "Luxembourg Financial Franc"),
                            ("LUC", "Luxembourgian Convertible Franc"),
                            ("LUF", "Luxembourgian Franc"),
                            ("MOP", "Macanese Pataca"),
                            ("MKD", "Macedonian Denar"),
                            ("MKN", "Macedonian Denar (1992–1993)"),
                            ("MGA", "Malagasy Ariary"),
                            ("MGF", "Malagasy Franc"),
                            ("MWK", "Malawian Kwacha"),
                            ("MYR", "Malaysian Ringgit"),
                            ("MVR", "Maldivian Rufiyaa"),
                            ("MVP", "Maldivian Rupee (1947–1981)"),
                            ("MLF", "Malian Franc"),
                            ("MTL", "Maltese Lira"),
                            ("MTP", "Maltese Pound"),
                            ("MRU", "Mauritanian Ouguiya"),
                            ("MRO", "Mauritanian Ouguiya (1973–2017)"),
                            ("MUR", "Mauritian Rupee"),
                            ("MXV", "Mexican Investment Unit"),
                            ("MXN", "Mexican Peso"),
                            ("MXP", "Mexican Silver Peso (1861–1992)"),
                            ("MDC", "Moldovan Cupon"),
                            ("MDL", "Moldovan Leu"),
                            ("MCF", "Monegasque Franc"),
                            ("MNT", "Mongolian Tugrik"),
                            ("MAD", "Moroccan Dirham"),
                            ("MAF", "Moroccan Franc"),
                            ("MZE", "Mozambican Escudo"),
                            ("MZN", "Mozambican Metical"),
                            ("MZM", "Mozambican Metical (1980–2006)"),
                            ("MMK", "Myanmar Kyat"),
                            ("NAD", "Namibian Dollar"),
                            ("NPR", "Nepalese Rupee"),
                            ("ANG", "Netherlands Antillean Guilder"),
                            ("TWD", "New Taiwan Dollar"),
                            ("NZD", "New Zealand Dollar"),
                            ("NIO", "Nicaraguan Córdoba"),
                            ("NIC", "Nicaraguan Córdoba (1988–1991)"),
                            ("NGN", "Nigerian Naira"),
                            ("KPW", "North Korean Won"),
                            ("NOK", "Norwegian Krone"),
                            ("OMR", "Omani Rial"),
                            ("PKR", "Pakistani Rupee"),
                            ("XPD", "Palladium"),
                            ("PAB", "Panamanian Balboa"),
                            ("PGK", "Papua New Guinean Kina"),
                            ("PYG", "Paraguayan Guarani"),
                            ("PEI", "Peruvian Inti"),
                            ("PEN", "Peruvian Sol"),
                            ("PES", "Peruvian Sol (1863–1965)"),
                            ("PHP", "Philippine Peso"),
                            ("XPT", "Platinum"),
                            ("PLN", "Polish Zloty"),
                            ("PLZ", "Polish Zloty (1950–1995)"),
                            ("PTE", "Portuguese Escudo"),
                            ("GWE", "Portuguese Guinea Escudo"),
                            ("QAR", "Qatari Riyal"),
                            ("XRE", "RINET Funds"),
                            ("RHD", "Rhodesian Dollar"),
                            ("RON", "Romanian Leu"),
                            ("ROL", "Romanian Leu (1952–2006)"),
                            ("RUB", "Russian Ruble"),
                            ("RUR", "Russian Ruble (1991–1998)"),
                            ("RWF", "Rwandan Franc"),
                            ("SVC", "Salvadoran Colón"),
                            ("WST", "Samoan Tala"),
                            ("SAR", "Saudi Riyal"),
                            ("RSD", "Serbian Dinar"),
                            ("CSD", "Serbian Dinar (2002–2006)"),
                            ("SCR", "Seychellois Rupee"),
                            ("SLE", "Sierra Leonean Leone"),
                            ("SLL", "Sierra Leonean Leone (1964—2022)"),
                            ("XAG", "Silver"),
                            ("SGD", "Singapore Dollar"),
                            ("SKK", "Slovak Koruna"),
                            ("SIT", "Slovenian Tolar"),
                            ("SBD", "Solomon Islands Dollar"),
                            ("SOS", "Somali Shilling"),
                            ("ZAR", "South African Rand"),
                            ("ZAL", "South African Rand (financial)"),
                            ("KRH", "South Korean Hwan (1953–1962)"),
                            ("KRW", "South Korean Won"),
                            ("KRO", "South Korean Won (1945–1953)"),
                            ("SSP", "South Sudanese Pound"),
                            ("SUR", "Soviet Rouble"),
                            ("ESP", "Spanish Peseta"),
                            ("ESA", "Spanish Peseta (A account)"),
                            ("ESB", "Spanish Peseta (convertible account)"),
                            ("XDR", "Special Drawing Rights"),
                            ("LKR", "Sri Lankan Rupee"),
                            ("SHP", "St. Helena Pound"),
                            ("XSU", "Sucre"),
                            ("SDD", "Sudanese Dinar (1992–2007)"),
                            ("SDG", "Sudanese Pound"),
                            ("SDP", "Sudanese Pound (1957–1998)"),
                            ("SRD", "Surinamese Dollar"),
                            ("SRG", "Surinamese Guilder"),
                            ("SZL", "Swazi Lilangeni"),
                            ("SEK", "Swedish Krona"),
                            ("CHF", "Swiss Franc"),
                            ("SYP", "Syrian Pound"),
                            ("STN", "São Tomé & Príncipe Dobra"),
                            ("STD", "São Tomé & Príncipe Dobra (1977–2017)"),
                            ("TVD", "TVD"),
                            ("TJR", "Tajikistani Ruble"),
                            ("TJS", "Tajikistani Somoni"),
                            ("TZS", "Tanzanian Shilling"),
                            ("XTS", "Testing Currency Code"),
                            ("THB", "Thai Baht"),
                            ("TPE", "Timorese Escudo"),
                            ("TOP", "Tongan Paʻanga"),
                            ("TTD", "Trinidad & Tobago Dollar"),
                            ("TND", "Tunisian Dinar"),
                            ("TRY", "Turkish Lira"),
                            ("TRL", "Turkish Lira (1922–2005)"),
                            ("TMT", "Turkmenistani Manat"),
                            ("TMM", "Turkmenistani Manat (1993–2009)"),
                            ("USD", "US Dollar"),
                            ("USN", "US Dollar (Next day)"),
                            ("USS", "US Dollar (Same day)"),
                            ("UGX", "Ugandan Shilling"),
                            ("UGS", "Ugandan Shilling (1966–1987)"),
                            ("UAH", "Ukrainian Hryvnia"),
                            ("UAK", "Ukrainian Karbovanets"),
                            ("AED", "United Arab Emirates Dirham"),
                            ("UYW", "Uruguayan Nominal Wage Index Unit"),
                            ("UYU", "Uruguayan Peso"),
                            ("UYP", "Uruguayan Peso (1975–1993)"),
                            ("UYI", "Uruguayan Peso (Indexed Units)"),
                            ("UZS", "Uzbekistani Som"),
                            ("VUV", "Vanuatu Vatu"),
                            ("VES", "Venezuelan Bolívar"),
                            ("VEB", "Venezuelan Bolívar (1871–2008)"),
                            ("VEF", "Venezuelan Bolívar (2008–2018)"),
                            ("VND", "Vietnamese Dong"),
                            ("VNN", "Vietnamese Dong (1978–1985)"),
                            ("CHE", "WIR Euro"),
                            ("CHW", "WIR Franc"),
                            ("XOF", "West African CFA Franc"),
                            ("YDD", "Yemeni Dinar"),
                            ("YER", "Yemeni Rial"),
                            ("YUN", "Yugoslavian Convertible Dinar (1990–1992)"),
                            ("YUD", "Yugoslavian Hard Dinar (1966–1990)"),
                            ("YUM", "Yugoslavian New Dinar (1994–2002)"),
                            ("YUR", "Yugoslavian Reformed Dinar (1992–1993)"),
                            ("ZWN", "ZWN"),
                            ("ZRN", "Zairean New Zaire (1993–1998)"),
                            ("ZRZ", "Zairean Zaire (1971–1993)"),
                            ("ZMW", "Zambian Kwacha"),
                            ("ZMK", "Zambian Kwacha (1968–2012)"),
                            ("ZWD", "Zimbabwean Dollar (1980–2008)"),
                            ("ZWR", "Zimbabwean Dollar (2008)"),
                            ("ZWL", "Zimbabwean Dollar (2009–2024)"),
                        ],
                        default="COP",
                        editable=False,
                        max_length=3,
                    ),
                ),
                (
                    "base_price",
                    djmoney.models.fields.MoneyField(
                        decimal_places=2,
                        default_currency="COP",
                        max_digits=19,
                        verbose_name="Precio Base",
                    ),
                ),
                (
                    "is_packageable",
                    models.BooleanField(
                        default=False,
                        help_text="¿Puede este servicio/producto ser parte de un paquete?",
                        verbose_name="Es Empaquetable",
                    ),
                ),
                (
                    "cancellation_policy",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="prestadores.politicacancelacion",
                    ),
                ),
                (
                    "operational_tags",
                    models.ManyToManyField(
                        blank=True, to="prestadores.categoriaprestador"
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_items",
                        to="prestadores.providerprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Producto/Servicio",
                "verbose_name_plural": "Productos/Servicios",
            },
        ),
        migrations.CreateModel(
            name="MenuItemDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "assigned_station",
                    models.ForeignKey(
                        blank=True,
                        help_text="Estación de cocina responsable de preparar este plato.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="prestadores.kitchenstation",
                    ),
                ),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="menu_item_details",
                        to="prestadores.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RoomType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "capacidad",
                    models.PositiveSmallIntegerField(
                        verbose_name="Capacidad de Personas"
                    ),
                ),
                (
                    "amenities",
                    models.ManyToManyField(blank=True, to="catalogs.amenity"),
                ),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="room_type_details",
                        to="prestadores.product",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_items",
                        to="prestadores.providerprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TourDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tour_details",
                        to="prestadores.product",
                    ),
                ),
                (
                    "required_skills",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Competencias requeridas para que un guía pueda realizar este tour.",
                        to="catalogs.skill",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "nombre",
                    models.CharField(
                        max_length=150, verbose_name="Nombre Identificativo"
                    ),
                ),
                (
                    "placa",
                    models.CharField(max_length=10, unique=True, verbose_name="Placa"),
                ),
                (
                    "modelo_ano",
                    models.PositiveIntegerField(verbose_name="Modelo (Año)"),
                ),
                ("tipo_vehiculo", models.CharField(max_length=50, verbose_name="Tipo")),
                (
                    "capacidad",
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name="Capacidad de Pasajeros"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AVAILABLE", "Disponible"),
                            ("IN_SERVICE", "En Servicio"),
                            ("MAINTENANCE", "En Mantenimiento"),
                            ("INACTIVE", "Inactivo"),
                        ],
                        default="AVAILABLE",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "insurance_expiry_date",
                    models.DateField(verbose_name="Vencimiento de Póliza"),
                ),
                (
                    "tech_inspection_expiry_date",
                    models.DateField(verbose_name="Vencimiento Revisión T-M"),
                ),
                (
                    "catalog_reference",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="catalogs.vehicle",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_items",
                        to="prestadores.providerprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SaludOcupacional",
            fields=[
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("empleado_id", models.UUIDField()),
                ("tipo_examen", models.CharField(max_length=100)),
                ("fecha_examen", models.DateField()),
                ("resultado_concepto", models.CharField(max_length=100)),
                ("recomendaciones", models.TextField(blank=True)),
                ("proximo_examen", models.DateField(blank=True, null=True)),
                (
                    "provider",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_items",
                        to="prestadores.providerprofile",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="plananualsst",
            name="provider",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_items",
                to="prestadores.providerprofile",
            ),
        ),
        migrations.CreateModel(
            name="MovimientoInventario",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "tipo_movimiento",
                    models.CharField(
                        choices=[
                            ("ENTRADA", "Entrada"),
                            ("SALIDA", "Salida"),
                            ("AJUSTE", "Ajuste"),
                            ("VENTA", "Venta"),
                            ("COMPRA", "Compra"),
                        ],
                        max_length=20,
                    ),
                ),
                ("cantidad", models.DecimalField(decimal_places=2, max_digits=10)),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                (
                    "referencia",
                    models.CharField(
                        blank=True,
                        help_text="Referencia a Venta ID o Factura ID",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movimientos",
                        to="prestadores.inventoryitem",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_items",
                        to="prestadores.providerprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="matrizriesgo",
            name="provider",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_items",
                to="prestadores.providerprofile",
            ),
        ),
        migrations.AddField(
            model_name="kitchenstation",
            name="provider",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_items",
                to="prestadores.providerprofile",
            ),
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="provider",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_items",
                to="prestadores.providerprofile",
            ),
        ),
        migrations.AddField(
            model_name="inspeccionsst",
            name="provider",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_items",
                to="prestadores.providerprofile",
            ),
        ),
        migrations.CreateModel(
            name="IndicadorSST",
            fields=[
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                ("tipo", models.CharField(max_length=100)),
                ("valor", models.DecimalField(decimal_places=2, max_digits=10)),
                ("meta", models.DecimalField(decimal_places=2, max_digits=10)),
                ("periodo", models.CharField(max_length=50)),
                ("fecha_calculo", models.DateTimeField(auto_now_add=True)),
                (
                    "provider",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_items",
                        to="prestadores.providerprofile",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="incidentelaboral",
            name="provider",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_items",
                to="prestadores.providerprofile",
            ),
        ),
        migrations.CreateModel(
            name="Costo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "concepto",
                    models.CharField(max_length=255, verbose_name="Concepto del Costo"),
                ),
                (
                    "monto",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Monto"
                    ),
                ),
                ("fecha", models.DateField(verbose_name="Fecha del Costo")),
                (
                    "es_recurrente",
                    models.BooleanField(default=False, verbose_name="¿Es Recurrente?"),
                ),
                (
                    "tipo_costo",
                    models.CharField(
                        choices=[
                            ("FIJO", "Fijo"),
                            ("VARIABLE", "Variable"),
                            ("INSUMOS", "Insumos / Materia Prima"),
                            ("PERSONAL", "Mano de Obra"),
                            ("TALLER", "Gastos de Taller/Cocina"),
                        ],
                        default="VARIABLE",
                        max_length=50,
                        verbose_name="Tipo de Costo",
                    ),
                ),
                (
                    "orden_operativa_ref_id",
                    models.UUIDField(
                        blank=True,
                        help_text="Vínculo con la orden que generó el gasto.",
                        null=True,
                    ),
                ),
                (
                    "insumo_ref_id",
                    models.UUIDField(
                        blank=True,
                        help_text="Vínculo con el ítem de inventario si aplica.",
                        null=True,
                    ),
                ),
                (
                    "personal_ref_id",
                    models.UUIDField(
                        blank=True,
                        help_text="Vínculo con el colaborador si es mano de obra.",
                        null=True,
                    ),
                ),
                (
                    "perfil",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="costos",
                        to="prestadores.providerprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Costo Operativo",
                "verbose_name_plural": "Costos Operativos",
                "ordering": ["-fecha"],
            },
        ),
        migrations.CreateModel(
            name="CapacitacionSST",
            fields=[
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tema", models.CharField(max_length=255)),
                ("fecha", models.DateField()),
                ("intensidad_horaria", models.IntegerField()),
                ("asistentes_count", models.IntegerField()),
                (
                    "evidencia_asistencia_ref_id",
                    models.UUIDField(blank=True, null=True),
                ),
                ("programada", models.BooleanField(default=False)),
                ("realizada", models.BooleanField(default=False)),
                (
                    "provider",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_items",
                        to="prestadores.providerprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AlertaSST",
            fields=[
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("titulo", models.CharField(max_length=255)),
                ("mensaje", models.TextField()),
                ("criticidad", models.CharField(max_length=20)),
                ("leida", models.BooleanField(default=False)),
                ("fecha_generacion", models.DateTimeField(auto_now_add=True)),
                (
                    "provider",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_items",
                        to="prestadores.providerprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Valoracion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "puntuacion",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                ("comentario", models.TextField()),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("respuesta_del_prestador", models.TextField(blank=True, null=True)),
                ("fecha_respuesta", models.DateTimeField(blank=True, null=True)),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="valoraciones",
                        to="prestadores.product",
                    ),
                ),
                (
                    "turista",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="valoraciones_emitidas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "perfil_prestador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="valoraciones_recibidas",
                        to="prestadores.providerprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha_creacion"],
                "unique_together": {("producto", "turista")},
            },
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "numero_habitacion",
                    models.CharField(
                        max_length=10, verbose_name="Número de Habitación"
                    ),
                ),
                (
                    "housekeeping_status",
                    models.CharField(
                        choices=[
                            ("CLEAN", "Limpia"),
                            ("DIRTY", "Sucia"),
                            ("IN_PROGRESS", "En Limpieza"),
                            ("INSPECTION", "Para Inspección"),
                            ("OUT_OF_ORDER", "Fuera de Servicio"),
                        ],
                        default="CLEAN",
                        max_length=20,
                        verbose_name="Estado de Limpieza",
                    ),
                ),
                (
                    "room_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rooms",
                        to="prestadores.roomtype",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_items",
                        to="prestadores.providerprofile",
                    ),
                ),
            ],
            options={
                "unique_together": {("provider", "numero_habitacion")},
            },
        ),
        migrations.CreateModel(
            name="RestaurantTable",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "table_number",
                    models.CharField(max_length=10, verbose_name="Número de Mesa"),
                ),
                (
                    "capacity",
                    models.PositiveSmallIntegerField(verbose_name="Capacidad"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("FREE", "Libre"),
                            ("OCCUPIED", "Ocupada"),
                            ("RESERVED", "Reservada"),
                            ("DIRTY", "Sucia"),
                        ],
                        default="FREE",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                ("pos_x", models.FloatField(default=0)),
                ("pos_y", models.FloatField(default=0)),
                (
                    "provider",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_items",
                        to="prestadores.providerprofile",
                    ),
                ),
            ],
            options={
                "unique_together": {("provider", "table_number")},
            },
        ),
        migrations.CreateModel(
            name="Horario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dia_semana",
                    models.IntegerField(
                        choices=[
                            (0, "Lunes"),
                            (1, "Martes"),
                            (2, "Miércoles"),
                            (3, "Jueves"),
                            (4, "Viernes"),
                            (5, "Sábado"),
                            (6, "Domingo"),
                        ]
                    ),
                ),
                ("hora_apertura", models.TimeField()),
                ("hora_cierre", models.TimeField()),
                (
                    "perfil",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="horarios",
                        to="prestadores.providerprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["dia_semana", "hora_apertura"],
                "unique_together": {("perfil", "dia_semana")},
            },
        ),
        migrations.CreateModel(
            name="ExcepcionHorario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField()),
                ("esta_abierto", models.BooleanField(default=False)),
                ("hora_apertura", models.TimeField(blank=True, null=True)),
                ("hora_cierre", models.TimeField(blank=True, null=True)),
                (
                    "descripcion",
                    models.CharField(
                        help_text="Ej: Feriado Nacional, Evento Privado", max_length=255
                    ),
                ),
                (
                    "perfil",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="excepciones_horario",
                        to="prestadores.providerprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["fecha"],
                "unique_together": {("perfil", "fecha")},
            },
        ),
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "id_publico",
                    models.UUIDField(editable=False, null=True, unique=True),
                ),
                ("nombre", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("telefono", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "perfil",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clientes",
                        to="prestadores.providerprofile",
                    ),
                ),
            ],
            options={
                "unique_together": {("perfil", "email")},
            },
        ),
    ]
