# Generated by Django 5.2.6 on 2025-12-12 22:17

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import djmoney.models.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("api", "0001_initial"),
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Menu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("descripcion", models.TextField(blank=True, null=True)),
                ("activo", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="TipoAlojamiento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, unique=True)),
                ("descripcion", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="TipoVehiculo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, unique=True)),
                ("descripcion", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Alojamiento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("descripcion", models.TextField()),
                ("direccion", models.CharField(max_length=255)),
                (
                    "perfil",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alojamiento",
                        to="api.providerprofile",
                    ),
                ),
                (
                    "tipo",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="prestadores.tipoalojamiento",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Amenity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "nombre",
                    models.CharField(
                        max_length=100, verbose_name="Nombre de la Amenidad"
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_items",
                        to="api.providerprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("telefono", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "perfil",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clientes",
                        to="api.providerprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CompaniaTransporte",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("descripcion", models.TextField()),
                (
                    "perfil",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compania_transporte",
                        to="api.providerprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Costo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "concepto",
                    models.CharField(max_length=255, verbose_name="Concepto del Costo"),
                ),
                (
                    "monto",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Monto"
                    ),
                ),
                ("fecha", models.DateField(verbose_name="Fecha del Costo")),
                (
                    "es_recurrente",
                    models.BooleanField(default=False, verbose_name="¿Es Recurrente?"),
                ),
                (
                    "tipo_costo",
                    models.CharField(
                        choices=[("FIJO", "Fijo"), ("VARIABLE", "Variable")],
                        default="VARIABLE",
                        max_length=50,
                        verbose_name="Tipo de Costo",
                    ),
                ),
                (
                    "perfil",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="costos",
                        to="api.providerprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Costo Operativo",
                "verbose_name_plural": "Costos Operativos",
                "ordering": ["-fecha"],
            },
        ),
        migrations.CreateModel(
            name="InventoryItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "nombre_item",
                    models.CharField(max_length=255, verbose_name="Nombre del Ítem"),
                ),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("CONSUMABLE", "Consumible"),
                            ("ASSET", "Activo Fijo"),
                            ("RETAIL", "Producto de Venta"),
                        ],
                        default="CONSUMABLE",
                        max_length=20,
                        verbose_name="Tipo de Ítem",
                    ),
                ),
                (
                    "cantidad",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="Cantidad Disponible",
                    ),
                ),
                (
                    "unidad",
                    models.CharField(
                        help_text="Ej: unidades, kg, litros",
                        max_length=50,
                        verbose_name="Unidad de Medida",
                    ),
                ),
                (
                    "punto_reorden",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="Punto de Reorden",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_items",
                        to="api.providerprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ítem de Inventario",
                "verbose_name_plural": "Ítems de Inventario",
                "ordering": ["nombre_item"],
            },
        ),
        migrations.CreateModel(
            name="KitchenStation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "nombre",
                    models.CharField(
                        max_length=100, verbose_name="Nombre de la Estación"
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_items",
                        to="api.providerprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CategoriaPlato",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                (
                    "orden",
                    models.PositiveIntegerField(
                        default=0, help_text="Orden de aparición en el menú"
                    ),
                ),
                (
                    "menu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categorias",
                        to="prestadores.menu",
                    ),
                ),
            ],
            options={
                "ordering": ["orden", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="OperadorTuristico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("descripcion", models.TextField()),
                ("licencia_turismo", models.CharField(blank=True, max_length=100)),
                (
                    "perfil",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operador_turistico",
                        to="api.providerprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrganizadorEvento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("descripcion", models.TextField()),
                (
                    "perfil",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organizador_eventos",
                        to="api.providerprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PoliticaCancelacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        help_text="Ej: Estricta, Flexible, No reembolsable",
                        max_length=100,
                    ),
                ),
                ("descripcion", models.TextField()),
                (
                    "perfil",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="politicas_cancelacion",
                        to="api.providerprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("nombre", models.CharField(max_length=200, verbose_name="Nombre")),
                (
                    "descripcion",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                (
                    "nature",
                    models.CharField(
                        choices=[
                            ("SERVICE", "Servicio (Reservable)"),
                            ("GOOD", "Bien Físico (Comprable)"),
                            ("PACKAGE", "Paquete (Compuesto)"),
                        ],
                        max_length=10,
                        verbose_name="Naturaleza",
                    ),
                ),
                (
                    "base_price_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[
                            ("XUA", "ADB Unit of Account"),
                            ("AFN", "Afghan Afghani"),
                            ("AFA", "Afghan Afghani (1927–2002)"),
                            ("ALL", "Albanian Lek"),
                            ("ALK", "Albanian Lek (1946–1965)"),
                            ("DZD", "Algerian Dinar"),
                            ("ADP", "Andorran Peseta"),
                            ("AOA", "Angolan Kwanza"),
                            ("AOK", "Angolan Kwanza (1977–1991)"),
                            ("AON", "Angolan New Kwanza (1990–2000)"),
                            ("AOR", "Angolan Readjusted Kwanza (1995–1999)"),
                            ("ARA", "Argentine Austral"),
                            ("ARS", "Argentine Peso"),
                            ("ARM", "Argentine Peso (1881–1970)"),
                            ("ARP", "Argentine Peso (1983–1985)"),
                            ("ARL", "Argentine Peso Ley (1970–1983)"),
                            ("AMD", "Armenian Dram"),
                            ("AWG", "Aruban Florin"),
                            ("AUD", "Australian Dollar"),
                            ("ATS", "Austrian Schilling"),
                            ("AZN", "Azerbaijani Manat"),
                            ("AZM", "Azerbaijani Manat (1993–2006)"),
                            ("BSD", "Bahamian Dollar"),
                            ("BHD", "Bahraini Dinar"),
                            ("BDT", "Bangladeshi Taka"),
                            ("BBD", "Barbadian Dollar"),
                            ("BYN", "Belarusian Ruble"),
                            ("BYB", "Belarusian Ruble (1994–1999)"),
                            ("BYR", "Belarusian Ruble (2000–2016)"),
                            ("BEF", "Belgian Franc"),
                            ("BEC", "Belgian Franc (convertible)"),
                            ("BEL", "Belgian Franc (financial)"),
                            ("BZD", "Belize Dollar"),
                            ("BMD", "Bermudan Dollar"),
                            ("BTN", "Bhutanese Ngultrum"),
                            ("BOB", "Bolivian Boliviano"),
                            ("BOL", "Bolivian Boliviano (1863–1963)"),
                            ("BOV", "Bolivian Mvdol"),
                            ("BOP", "Bolivian Peso"),
                            ("VED", "Bolívar Soberano"),
                            ("BAM", "Bosnia-Herzegovina Convertible Mark"),
                            ("BAD", "Bosnia-Herzegovina Dinar (1992–1994)"),
                            ("BAN", "Bosnia-Herzegovina New Dinar (1994–1997)"),
                            ("BWP", "Botswanan Pula"),
                            ("BRC", "Brazilian Cruzado (1986–1989)"),
                            ("BRZ", "Brazilian Cruzeiro (1942–1967)"),
                            ("BRE", "Brazilian Cruzeiro (1990–1993)"),
                            ("BRR", "Brazilian Cruzeiro (1993–1994)"),
                            ("BRN", "Brazilian New Cruzado (1989–1990)"),
                            ("BRB", "Brazilian New Cruzeiro (1967–1986)"),
                            ("BRL", "Brazilian Real"),
                            ("GBP", "British Pound"),
                            ("BND", "Brunei Dollar"),
                            ("BGL", "Bulgarian Hard Lev"),
                            ("BGN", "Bulgarian Lev"),
                            ("BGO", "Bulgarian Lev (1879–1952)"),
                            ("BGM", "Bulgarian Socialist Lev"),
                            ("BUK", "Burmese Kyat"),
                            ("BIF", "Burundian Franc"),
                            ("XPF", "CFP Franc"),
                            ("KHR", "Cambodian Riel"),
                            ("CAD", "Canadian Dollar"),
                            ("CVE", "Cape Verdean Escudo"),
                            ("KYD", "Cayman Islands Dollar"),
                            ("XAF", "Central African CFA Franc"),
                            ("CLE", "Chilean Escudo"),
                            ("CLP", "Chilean Peso"),
                            ("CLF", "Chilean Unit of Account (UF)"),
                            ("CNX", "Chinese People’s Bank Dollar"),
                            ("CNY", "Chinese Yuan"),
                            ("CNH", "Chinese Yuan (offshore)"),
                            ("COP", "Colombian Peso"),
                            ("COU", "Colombian Real Value Unit"),
                            ("KMF", "Comorian Franc"),
                            ("CDF", "Congolese Franc"),
                            ("CRC", "Costa Rican Colón"),
                            ("HRD", "Croatian Dinar"),
                            ("HRK", "Croatian Kuna"),
                            ("CUC", "Cuban Convertible Peso"),
                            ("CUP", "Cuban Peso"),
                            ("CYP", "Cypriot Pound"),
                            ("CZK", "Czech Koruna"),
                            ("CSK", "Czechoslovak Hard Koruna"),
                            ("DKK", "Danish Krone"),
                            ("DJF", "Djiboutian Franc"),
                            ("DOP", "Dominican Peso"),
                            ("NLG", "Dutch Guilder"),
                            ("XCD", "East Caribbean Dollar"),
                            ("DDM", "East German Mark"),
                            ("ECS", "Ecuadorian Sucre"),
                            ("ECV", "Ecuadorian Unit of Constant Value"),
                            ("EGP", "Egyptian Pound"),
                            ("GQE", "Equatorial Guinean Ekwele"),
                            ("ERN", "Eritrean Nakfa"),
                            ("EEK", "Estonian Kroon"),
                            ("ETB", "Ethiopian Birr"),
                            ("EUR", "Euro"),
                            ("XBA", "European Composite Unit"),
                            ("XEU", "European Currency Unit"),
                            ("XBB", "European Monetary Unit"),
                            ("XBC", "European Unit of Account (XBC)"),
                            ("XBD", "European Unit of Account (XBD)"),
                            ("FKP", "Falkland Islands Pound"),
                            ("FJD", "Fijian Dollar"),
                            ("FIM", "Finnish Markka"),
                            ("FRF", "French Franc"),
                            ("XFO", "French Gold Franc"),
                            ("XFU", "French UIC-Franc"),
                            ("GMD", "Gambian Dalasi"),
                            ("GEK", "Georgian Kupon Larit"),
                            ("GEL", "Georgian Lari"),
                            ("DEM", "German Mark"),
                            ("GHS", "Ghanaian Cedi"),
                            ("GHC", "Ghanaian Cedi (1979–2007)"),
                            ("GIP", "Gibraltar Pound"),
                            ("XAU", "Gold"),
                            ("GRD", "Greek Drachma"),
                            ("GTQ", "Guatemalan Quetzal"),
                            ("GWP", "Guinea-Bissau Peso"),
                            ("GNF", "Guinean Franc"),
                            ("GNS", "Guinean Syli"),
                            ("GYD", "Guyanaese Dollar"),
                            ("HTG", "Haitian Gourde"),
                            ("HNL", "Honduran Lempira"),
                            ("HKD", "Hong Kong Dollar"),
                            ("HUF", "Hungarian Forint"),
                            ("IMP", "IMP"),
                            ("ISK", "Icelandic Króna"),
                            ("ISJ", "Icelandic Króna (1918–1981)"),
                            ("INR", "Indian Rupee"),
                            ("IDR", "Indonesian Rupiah"),
                            ("IRR", "Iranian Rial"),
                            ("IQD", "Iraqi Dinar"),
                            ("IEP", "Irish Pound"),
                            ("ILS", "Israeli New Shekel"),
                            ("ILP", "Israeli Pound"),
                            ("ILR", "Israeli Shekel (1980–1985)"),
                            ("ITL", "Italian Lira"),
                            ("JMD", "Jamaican Dollar"),
                            ("JPY", "Japanese Yen"),
                            ("JOD", "Jordanian Dinar"),
                            ("KZT", "Kazakhstani Tenge"),
                            ("KES", "Kenyan Shilling"),
                            ("KWD", "Kuwaiti Dinar"),
                            ("KGS", "Kyrgystani Som"),
                            ("LAK", "Laotian Kip"),
                            ("LVL", "Latvian Lats"),
                            ("LVR", "Latvian Ruble"),
                            ("LBP", "Lebanese Pound"),
                            ("LSL", "Lesotho Loti"),
                            ("LRD", "Liberian Dollar"),
                            ("LYD", "Libyan Dinar"),
                            ("LTL", "Lithuanian Litas"),
                            ("LTT", "Lithuanian Talonas"),
                            ("LUL", "Luxembourg Financial Franc"),
                            ("LUC", "Luxembourgian Convertible Franc"),
                            ("LUF", "Luxembourgian Franc"),
                            ("MOP", "Macanese Pataca"),
                            ("MKD", "Macedonian Denar"),
                            ("MKN", "Macedonian Denar (1992–1993)"),
                            ("MGA", "Malagasy Ariary"),
                            ("MGF", "Malagasy Franc"),
                            ("MWK", "Malawian Kwacha"),
                            ("MYR", "Malaysian Ringgit"),
                            ("MVR", "Maldivian Rufiyaa"),
                            ("MVP", "Maldivian Rupee (1947–1981)"),
                            ("MLF", "Malian Franc"),
                            ("MTL", "Maltese Lira"),
                            ("MTP", "Maltese Pound"),
                            ("MRU", "Mauritanian Ouguiya"),
                            ("MRO", "Mauritanian Ouguiya (1973–2017)"),
                            ("MUR", "Mauritian Rupee"),
                            ("MXV", "Mexican Investment Unit"),
                            ("MXN", "Mexican Peso"),
                            ("MXP", "Mexican Silver Peso (1861–1992)"),
                            ("MDC", "Moldovan Cupon"),
                            ("MDL", "Moldovan Leu"),
                            ("MCF", "Monegasque Franc"),
                            ("MNT", "Mongolian Tugrik"),
                            ("MAD", "Moroccan Dirham"),
                            ("MAF", "Moroccan Franc"),
                            ("MZE", "Mozambican Escudo"),
                            ("MZN", "Mozambican Metical"),
                            ("MZM", "Mozambican Metical (1980–2006)"),
                            ("MMK", "Myanmar Kyat"),
                            ("NAD", "Namibian Dollar"),
                            ("NPR", "Nepalese Rupee"),
                            ("ANG", "Netherlands Antillean Guilder"),
                            ("TWD", "New Taiwan Dollar"),
                            ("NZD", "New Zealand Dollar"),
                            ("NIO", "Nicaraguan Córdoba"),
                            ("NIC", "Nicaraguan Córdoba (1988–1991)"),
                            ("NGN", "Nigerian Naira"),
                            ("KPW", "North Korean Won"),
                            ("NOK", "Norwegian Krone"),
                            ("OMR", "Omani Rial"),
                            ("PKR", "Pakistani Rupee"),
                            ("XPD", "Palladium"),
                            ("PAB", "Panamanian Balboa"),
                            ("PGK", "Papua New Guinean Kina"),
                            ("PYG", "Paraguayan Guarani"),
                            ("PEI", "Peruvian Inti"),
                            ("PEN", "Peruvian Sol"),
                            ("PES", "Peruvian Sol (1863–1965)"),
                            ("PHP", "Philippine Peso"),
                            ("XPT", "Platinum"),
                            ("PLN", "Polish Zloty"),
                            ("PLZ", "Polish Zloty (1950–1995)"),
                            ("PTE", "Portuguese Escudo"),
                            ("GWE", "Portuguese Guinea Escudo"),
                            ("QAR", "Qatari Riyal"),
                            ("XRE", "RINET Funds"),
                            ("RHD", "Rhodesian Dollar"),
                            ("RON", "Romanian Leu"),
                            ("ROL", "Romanian Leu (1952–2006)"),
                            ("RUB", "Russian Ruble"),
                            ("RUR", "Russian Ruble (1991–1998)"),
                            ("RWF", "Rwandan Franc"),
                            ("SVC", "Salvadoran Colón"),
                            ("WST", "Samoan Tala"),
                            ("SAR", "Saudi Riyal"),
                            ("RSD", "Serbian Dinar"),
                            ("CSD", "Serbian Dinar (2002–2006)"),
                            ("SCR", "Seychellois Rupee"),
                            ("SLE", "Sierra Leonean Leone"),
                            ("SLL", "Sierra Leonean Leone (1964—2022)"),
                            ("XAG", "Silver"),
                            ("SGD", "Singapore Dollar"),
                            ("SKK", "Slovak Koruna"),
                            ("SIT", "Slovenian Tolar"),
                            ("SBD", "Solomon Islands Dollar"),
                            ("SOS", "Somali Shilling"),
                            ("ZAR", "South African Rand"),
                            ("ZAL", "South African Rand (financial)"),
                            ("KRH", "South Korean Hwan (1953–1962)"),
                            ("KRW", "South Korean Won"),
                            ("KRO", "South Korean Won (1945–1953)"),
                            ("SSP", "South Sudanese Pound"),
                            ("SUR", "Soviet Rouble"),
                            ("ESP", "Spanish Peseta"),
                            ("ESA", "Spanish Peseta (A account)"),
                            ("ESB", "Spanish Peseta (convertible account)"),
                            ("XDR", "Special Drawing Rights"),
                            ("LKR", "Sri Lankan Rupee"),
                            ("SHP", "St. Helena Pound"),
                            ("XSU", "Sucre"),
                            ("SDD", "Sudanese Dinar (1992–2007)"),
                            ("SDG", "Sudanese Pound"),
                            ("SDP", "Sudanese Pound (1957–1998)"),
                            ("SRD", "Surinamese Dollar"),
                            ("SRG", "Surinamese Guilder"),
                            ("SZL", "Swazi Lilangeni"),
                            ("SEK", "Swedish Krona"),
                            ("CHF", "Swiss Franc"),
                            ("SYP", "Syrian Pound"),
                            ("STN", "São Tomé & Príncipe Dobra"),
                            ("STD", "São Tomé & Príncipe Dobra (1977–2017)"),
                            ("TVD", "TVD"),
                            ("TJR", "Tajikistani Ruble"),
                            ("TJS", "Tajikistani Somoni"),
                            ("TZS", "Tanzanian Shilling"),
                            ("XTS", "Testing Currency Code"),
                            ("THB", "Thai Baht"),
                            ("TPE", "Timorese Escudo"),
                            ("TOP", "Tongan Paʻanga"),
                            ("TTD", "Trinidad & Tobago Dollar"),
                            ("TND", "Tunisian Dinar"),
                            ("TRY", "Turkish Lira"),
                            ("TRL", "Turkish Lira (1922–2005)"),
                            ("TMT", "Turkmenistani Manat"),
                            ("TMM", "Turkmenistani Manat (1993–2009)"),
                            ("USD", "US Dollar"),
                            ("USN", "US Dollar (Next day)"),
                            ("USS", "US Dollar (Same day)"),
                            ("UGX", "Ugandan Shilling"),
                            ("UGS", "Ugandan Shilling (1966–1987)"),
                            ("UAH", "Ukrainian Hryvnia"),
                            ("UAK", "Ukrainian Karbovanets"),
                            ("AED", "United Arab Emirates Dirham"),
                            ("UYW", "Uruguayan Nominal Wage Index Unit"),
                            ("UYU", "Uruguayan Peso"),
                            ("UYP", "Uruguayan Peso (1975–1993)"),
                            ("UYI", "Uruguayan Peso (Indexed Units)"),
                            ("UZS", "Uzbekistani Som"),
                            ("VUV", "Vanuatu Vatu"),
                            ("VES", "Venezuelan Bolívar"),
                            ("VEB", "Venezuelan Bolívar (1871–2008)"),
                            ("VEF", "Venezuelan Bolívar (2008–2018)"),
                            ("VND", "Vietnamese Dong"),
                            ("VNN", "Vietnamese Dong (1978–1985)"),
                            ("CHE", "WIR Euro"),
                            ("CHW", "WIR Franc"),
                            ("XOF", "West African CFA Franc"),
                            ("YDD", "Yemeni Dinar"),
                            ("YER", "Yemeni Rial"),
                            ("YUN", "Yugoslavian Convertible Dinar (1990–1992)"),
                            ("YUD", "Yugoslavian Hard Dinar (1966–1990)"),
                            ("YUM", "Yugoslavian New Dinar (1994–2002)"),
                            ("YUR", "Yugoslavian Reformed Dinar (1992–1993)"),
                            ("ZWN", "ZWN"),
                            ("ZRN", "Zairean New Zaire (1993–1998)"),
                            ("ZRZ", "Zairean Zaire (1971–1993)"),
                            ("ZMW", "Zambian Kwacha"),
                            ("ZMK", "Zambian Kwacha (1968–2012)"),
                            ("ZWD", "Zimbabwean Dollar (1980–2008)"),
                            ("ZWR", "Zimbabwean Dollar (2008)"),
                            ("ZWL", "Zimbabwean Dollar (2009–2024)"),
                        ],
                        default="COP",
                        editable=False,
                        max_length=3,
                    ),
                ),
                (
                    "base_price",
                    djmoney.models.fields.MoneyField(
                        decimal_places=2,
                        default_currency="COP",
                        max_digits=19,
                        verbose_name="Precio Base",
                    ),
                ),
                (
                    "stock",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Capacidad por evento, o unidades de un bien.",
                        verbose_name="Stock/Capacidad",
                    ),
                ),
                (
                    "is_packageable",
                    models.BooleanField(
                        default=False,
                        help_text="¿Puede este servicio ser parte de un paquete de agencia?",
                        verbose_name="Es Empaquetable",
                    ),
                ),
                (
                    "cancellation_policy",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="prestadores.politicacancelacion",
                    ),
                ),
                (
                    "operational_tags",
                    models.ManyToManyField(blank=True, to="api.categoriaprestador"),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_items",
                        to="api.providerprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Producto/Servicio",
                "verbose_name_plural": "Productos/Servicios",
            },
        ),
        migrations.CreateModel(
            name="Plato",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("disponible", models.BooleanField(default=True)),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="platos",
                        to="prestadores.categoriaplato",
                    ),
                ),
                (
                    "producto",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plato",
                        to="prestadores.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PaqueteTuristico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("duracion_dias", models.PositiveIntegerField()),
                (
                    "incluye",
                    models.TextField(
                        blank=True,
                        help_text="Breve descripción de lo que incluye el paquete (ej: Alojamiento, Transporte).",
                        null=True,
                    ),
                ),
                (
                    "operador",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paquetes",
                        to="prestadores.operadorturistico",
                    ),
                ),
                (
                    "producto",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paquete_turistico",
                        to="prestadores.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MenuItemDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "assigned_station",
                    models.ForeignKey(
                        blank=True,
                        help_text="Estación de cocina responsable de preparar este plato.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="prestadores.kitchenstation",
                    ),
                ),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="menu_item_details",
                        to="prestadores.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Habitacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("capacidad_maxima", models.PositiveIntegerField()),
                (
                    "alojamiento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="habitaciones",
                        to="prestadores.alojamiento",
                    ),
                ),
                (
                    "producto",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="habitacion",
                        to="prestadores.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Evento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_inicio", models.DateTimeField()),
                ("fecha_fin", models.DateTimeField()),
                ("ubicacion", models.CharField(max_length=255)),
                ("capacidad", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "organizador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="eventos",
                        to="prestadores.organizadorevento",
                    ),
                ),
                (
                    "producto",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evento",
                        to="prestadores.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Promocion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("descripcion", models.TextField(blank=True)),
                ("fecha_inicio", models.DateField()),
                ("fecha_fin", models.DateField()),
                (
                    "tipo_descuento",
                    models.CharField(
                        choices=[("porcentaje", "Porcentaje"), ("fijo", "Monto Fijo")],
                        max_length=10,
                    ),
                ),
                (
                    "valor_descuento",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Valor del descuento (ej: 10 para 10% o 5000 para $5000 fijos)",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("activa", models.BooleanField(default=True)),
                (
                    "perfil",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promociones",
                        to="api.providerprofile",
                    ),
                ),
                (
                    "productos_aplicables",
                    models.ManyToManyField(
                        related_name="promociones", to="prestadores.product"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Reserva",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                ("fecha_inicio", models.DateTimeField()),
                ("fecha_fin", models.DateTimeField()),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente"),
                            ("CONFIRMADA", "Confirmada"),
                            ("CANCELADA", "Cancelada"),
                            ("COMPLETADA", "Completada"),
                        ],
                        default="PENDIENTE",
                        max_length=20,
                    ),
                ),
                ("notas", models.TextField(blank=True)),
                ("precio_total", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "deposito_pagado",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("modificado_en", models.DateTimeField(auto_now=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reservas",
                        to="prestadores.cliente",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "perfil",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservas",
                        to="api.providerprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReservaServicioAdicional",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad", models.PositiveIntegerField(default=1)),
                (
                    "precio_unitario",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Precio en el momento de la reserva",
                        max_digits=10,
                    ),
                ),
                (
                    "reserva",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="servicios_adicionales",
                        to="prestadores.reserva",
                    ),
                ),
                (
                    "servicio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="prestadores.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Restaurante",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("descripcion", models.TextField()),
                ("ofrece_delivery", models.BooleanField(default=False)),
                (
                    "perfil",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="restaurante",
                        to="api.providerprofile",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="menu",
            name="restaurante",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="menus",
                to="prestadores.restaurante",
            ),
        ),
        migrations.CreateModel(
            name="RoomType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "capacidad",
                    models.PositiveSmallIntegerField(
                        verbose_name="Capacidad de Personas"
                    ),
                ),
                (
                    "amenities",
                    models.ManyToManyField(blank=True, to="prestadores.amenity"),
                ),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="room_type_details",
                        to="prestadores.product",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_items",
                        to="api.providerprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Ruta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("origen", models.CharField(max_length=150)),
                ("destino", models.CharField(max_length=150)),
                ("distancia_km", models.FloatField(blank=True, null=True)),
                (
                    "compania",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rutas",
                        to="prestadores.companiatransporte",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SitioTuristico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=150)),
                ("descripcion_corta", models.CharField(max_length=255)),
                ("descripcion_larga", models.TextField()),
                (
                    "tipo_sitio",
                    models.CharField(
                        choices=[
                            ("parque_tematico", "Parque Temático"),
                            ("reserva_natural", "Reserva Natural"),
                            ("museo", "Museo"),
                            ("centro_cultural", "Centro Cultural"),
                            ("mirador", "Mirador"),
                            ("finca_agroturistica", "Finca Agroturística"),
                            ("otro", "Otro"),
                        ],
                        default="otro",
                        max_length=30,
                    ),
                ),
                ("ubicacion_latitud", models.FloatField(blank=True, null=True)),
                ("ubicacion_longitud", models.FloatField(blank=True, null=True)),
                (
                    "direccion_texto",
                    models.CharField(
                        blank=True,
                        help_text="Dirección o indicaciones de cómo llegar.",
                        max_length=255,
                    ),
                ),
                ("horario_apertura", models.TimeField(blank=True, null=True)),
                ("horario_cierre", models.TimeField(blank=True, null=True)),
                (
                    "dias_operacion",
                    models.CharField(
                        blank=True,
                        help_text="Ej: Lunes a Viernes, Fines de semana",
                        max_length=100,
                    ),
                ),
                (
                    "precio_entrada_adulto",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "precio_entrada_nino",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "activo",
                    models.BooleanField(
                        default=True,
                        help_text="Indica si el sitio está abierto al público.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "perfil",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sitios_turisticos",
                        to="api.providerprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ActividadEnSitio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("descripcion", models.TextField()),
                (
                    "duracion_estimada_minutos",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "precio_adicional",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Costo adicional a la entrada del sitio.",
                        max_digits=10,
                    ),
                ),
                ("requiere_reserva", models.BooleanField(default=False)),
                (
                    "sitio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actividades",
                        to="prestadores.sitioturistico",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "nombre",
                    models.CharField(
                        max_length=150, verbose_name="Nombre de la Competencia"
                    ),
                ),
                (
                    "skill_type",
                    models.CharField(
                        choices=[
                            ("SPECIALIZATION", "Especialización"),
                            ("CERTIFICATION", "Certificación"),
                            ("LANGUAGE", "Idioma"),
                        ],
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_items",
                        to="api.providerprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tarifa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("fecha_inicio", models.DateField()),
                ("fecha_fin", models.DateField()),
                (
                    "precio_adicional",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Valor a sumar (o restar si es negativo) al precio base de la habitación.",
                        max_digits=10,
                    ),
                ),
                (
                    "habitacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tarifas",
                        to="prestadores.habitacion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TourDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tour_details",
                        to="prestadores.product",
                    ),
                ),
                (
                    "required_skills",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Competencias requeridas para que un guía pueda realizar este tour.",
                        to="prestadores.skill",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "nombre",
                    models.CharField(
                        max_length=150, verbose_name="Nombre Identificativo"
                    ),
                ),
                (
                    "placa",
                    models.CharField(max_length=10, unique=True, verbose_name="Placa"),
                ),
                (
                    "modelo_ano",
                    models.PositiveIntegerField(verbose_name="Modelo (Año)"),
                ),
                ("tipo_vehiculo", models.CharField(max_length=50, verbose_name="Tipo")),
                (
                    "capacidad",
                    models.PositiveSmallIntegerField(
                        verbose_name="Capacidad de Pasajeros"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AVAILABLE", "Disponible"),
                            ("IN_SERVICE", "En Servicio"),
                            ("MAINTENANCE", "En Mantenimiento"),
                            ("INACTIVE", "Inactivo"),
                        ],
                        default="AVAILABLE",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "insurance_expiry_date",
                    models.DateField(verbose_name="Vencimiento de Póliza"),
                ),
                (
                    "tech_inspection_expiry_date",
                    models.DateField(verbose_name="Vencimiento Revisión T-M"),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_items",
                        to="api.providerprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Vehiculo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("placa", models.CharField(max_length=20, unique=True)),
                ("capacidad_pasajeros", models.PositiveIntegerField()),
                (
                    "compania",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vehiculos",
                        to="prestadores.companiatransporte",
                    ),
                ),
                (
                    "producto",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vehiculo",
                        to="prestadores.product",
                    ),
                ),
                (
                    "tipo",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="prestadores.tipovehiculo",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HorarioRuta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hora_salida", models.TimeField()),
                ("hora_llegada_estimada", models.TimeField()),
                (
                    "dias_operacion",
                    models.CharField(
                        help_text="Ej: 'L-V', 'S,D', 'L,M,X'", max_length=50
                    ),
                ),
                (
                    "ruta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="horarios",
                        to="prestadores.ruta",
                    ),
                ),
                (
                    "vehiculo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="horarios_asignados",
                        to="prestadores.vehiculo",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VehiculoDeAlquiler",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        help_text="Ej: Toyota Corolla 2023", max_length=100
                    ),
                ),
                ("placa", models.CharField(max_length=10, unique=True)),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("economico", "Económico"),
                            ("compacto", "Compacto"),
                            ("intermedio", "Intermedio"),
                            ("suv", "SUV"),
                            ("lujo", "Lujo"),
                            ("van", "Van/Minivan"),
                            ("moto", "Motocicleta"),
                        ],
                        default="compacto",
                        max_length=20,
                    ),
                ),
                (
                    "transmision",
                    models.CharField(
                        choices=[("automatica", "Automática"), ("manual", "Manual")],
                        default="automatica",
                        max_length=10,
                    ),
                ),
                ("numero_pasajeros", models.PositiveIntegerField(default=5)),
                (
                    "precio_por_dia",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("disponible", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "perfil",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vehiculos_de_alquiler",
                        to="api.providerprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Alquiler",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_cliente_temporal", models.CharField(max_length=150)),
                ("email_cliente", models.EmailField(max_length=254)),
                ("fecha_recogida", models.DateTimeField()),
                ("fecha_devolucion", models.DateTimeField()),
                (
                    "costo_total_calculado",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("reservado", "Reservado"),
                            ("activo", "Activo"),
                            ("finalizado", "Finalizado"),
                            ("cancelado", "Cancelado"),
                        ],
                        default="reservado",
                        max_length=15,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "vehiculo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="alquileres",
                        to="prestadores.vehiculodealquiler",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ZonaDelivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        help_text="Ej: 'Centro', 'Zona Norte'", max_length=100
                    ),
                ),
                ("costo_envio", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "tiempo_estimado_minutos",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "restaurante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="zonas_delivery",
                        to="prestadores.restaurante",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExcepcionHorario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField()),
                ("esta_abierto", models.BooleanField(default=False)),
                ("hora_apertura", models.TimeField(blank=True, null=True)),
                ("hora_cierre", models.TimeField(blank=True, null=True)),
                (
                    "descripcion",
                    models.CharField(
                        help_text="Ej: Feriado Nacional, Evento Privado", max_length=255
                    ),
                ),
                (
                    "perfil",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="excepciones_horario",
                        to="api.providerprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["fecha"],
                "unique_together": {("perfil", "fecha")},
            },
        ),
        migrations.CreateModel(
            name="Horario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dia_semana",
                    models.IntegerField(
                        choices=[
                            (0, "Lunes"),
                            (1, "Martes"),
                            (2, "Miércoles"),
                            (3, "Jueves"),
                            (4, "Viernes"),
                            (5, "Sábado"),
                            (6, "Domingo"),
                        ]
                    ),
                ),
                ("hora_apertura", models.TimeField()),
                ("hora_cierre", models.TimeField()),
                (
                    "perfil",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="horarios",
                        to="api.providerprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["dia_semana", "hora_apertura"],
                "unique_together": {("perfil", "dia_semana")},
            },
        ),
        migrations.CreateModel(
            name="ItinerarioDia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dia", models.PositiveIntegerField()),
                (
                    "titulo",
                    models.CharField(
                        help_text="Ej: 'Día 1: Llegada a la ciudad'", max_length=200
                    ),
                ),
                ("descripcion", models.TextField()),
                (
                    "paquete",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itinerario",
                        to="prestadores.paqueteturistico",
                    ),
                ),
            ],
            options={
                "ordering": ["dia"],
                "unique_together": {("paquete", "dia")},
            },
        ),
        migrations.CreateModel(
            name="RestaurantTable",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "table_number",
                    models.CharField(max_length=10, verbose_name="Número de Mesa"),
                ),
                (
                    "capacity",
                    models.PositiveSmallIntegerField(verbose_name="Capacidad"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("FREE", "Libre"),
                            ("OCCUPIED", "Ocupada"),
                            ("RESERVED", "Reservada"),
                            ("DIRTY", "Sucia"),
                        ],
                        default="FREE",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                ("pos_x", models.FloatField(default=0)),
                ("pos_y", models.FloatField(default=0)),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_items",
                        to="api.providerprofile",
                    ),
                ),
            ],
            options={
                "unique_together": {("provider", "table_number")},
            },
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "numero_habitacion",
                    models.CharField(
                        max_length=10, verbose_name="Número de Habitación"
                    ),
                ),
                (
                    "housekeeping_status",
                    models.CharField(
                        choices=[
                            ("CLEAN", "Limpia"),
                            ("DIRTY", "Sucia"),
                            ("IN_PROGRESS", "En Limpieza"),
                            ("INSPECTION", "Para Inspección"),
                            ("OUT_OF_ORDER", "Fuera de Servicio"),
                        ],
                        default="CLEAN",
                        max_length=20,
                        verbose_name="Estado de Limpieza",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_items",
                        to="api.providerprofile",
                    ),
                ),
                (
                    "room_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rooms",
                        to="prestadores.roomtype",
                    ),
                ),
            ],
            options={
                "unique_together": {("provider", "numero_habitacion")},
            },
        ),
        migrations.CreateModel(
            name="Valoracion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "puntuacion",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                ("comentario", models.TextField()),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("respuesta_del_prestador", models.TextField(blank=True, null=True)),
                ("fecha_respuesta", models.DateTimeField(blank=True, null=True)),
                (
                    "perfil_prestador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="valoraciones_recibidas",
                        to="api.providerprofile",
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="valoraciones",
                        to="prestadores.product",
                    ),
                ),
                (
                    "turista",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="valoraciones_emitidas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha_creacion"],
                "unique_together": {("producto", "turista")},
            },
        ),
    ]
