# Generated by Django 5.2.6 on 2026-01-08 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prestadores", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MigrationProbe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
