# Generated by Django 5.2.6 on 2026-02-08 04:10

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prestadores", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProcesoOperativo",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("nombre", models.CharField(max_length=255)),
                ("descripcion", models.TextField(blank=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PLANIFICADO", "Planificado"),
                            ("EN_EJECUCION", "En Ejecución"),
                            ("COMPLETADO", "Completado"),
                            ("FALLIDO", "Fallido"),
                            ("SUSPENDIDO", "Suspendido"),
                        ],
                        default="PLANIFICADO",
                        max_length=20,
                    ),
                ),
                ("inicio_real", models.DateTimeField(blank=True, null=True)),
                ("fin_real", models.DateTimeField(blank=True, null=True)),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_items",
                        to="prestadores.providerprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TareaOperativa",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("nombre", models.CharField(max_length=255)),
                ("responsable_id", models.UUIDField(blank=True, null=True)),
                ("estado", models.CharField(default="PENDIENTE", max_length=20)),
                ("fecha_limite", models.DateTimeField()),
                (
                    "proceso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tareas",
                        to="prestadores.procesooperativo",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_items",
                        to="prestadores.providerprofile",
                    ),
                ),
            ],
        ),
    ]
