# Generated by Django 5.2.6 on 2026-01-04 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
        ("prestadores", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cliente",
            name="email",
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterUniqueTogether(
            name="cliente",
            unique_together={("perfil", "email")},
        ),
    ]
