# Generated by Django 5.2.6 on 2026-01-04 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prestadores", "0002_alter_cliente_email_alter_cliente_unique_together"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="nature",
        ),
        migrations.RemoveField(
            model_name="product",
            name="stock",
        ),
        migrations.AddField(
            model_name="product",
            name="es_inventariable",
            field=models.BooleanField(
                default=False,
                help_text="Marcar si este producto gestiona stock.",
                verbose_name="Es Inventariable",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="tipo",
            field=models.CharField(
                choices=[("PRODUCTO", "Producto"), ("SERVICIO", "Servicio")],
                default="PRODUCTO",
                max_length=10,
                verbose_name="Tipo",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="is_packageable",
            field=models.BooleanField(
                default=False,
                help_text="¿Puede este servicio/producto ser parte de un paquete?",
                verbose_name="Es Empaquetable",
            ),
        ),
    ]
