# Generated by Django 5.2.6 on 2026-01-09 09:47

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prestadores", "0002_migrationprobe"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoriaPrestador",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("nombre", models.CharField(max_length=100, unique=True)),
                (
                    "slug",
                    models.SlugField(
                        help_text="Versión del nombre amigable para URLs",
                        max_length=100,
                        unique=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Categoría de Prestador",
                "verbose_name_plural": "Categorías de Prestadores",
            },
        ),
        migrations.CreateModel(
            name="ProviderProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("company_id", models.UUIDField(blank=True, null=True)),
                (
                    "nombre_comercial",
                    models.CharField(max_length=255, verbose_name="Nombre Comercial"),
                ),
                (
                    "provider_type",
                    models.CharField(
                        choices=[
                            ("RESTAURANT", "Restaurante"),
                            ("HOTEL", "Hotel"),
                            ("AGENCY", "Agencia de Viajes"),
                            ("GUIDE", "Guía Turístico"),
                            ("TRANSPORT", "Transportadora Turística"),
                            ("BAR_DISCO", "Bar o Discoteca"),
                            ("ARTISAN", "Artesano"),
                        ],
                        default="HOTEL",
                        max_length=20,
                    ),
                ),
                ("telefono_principal", models.CharField(blank=True, max_length=50)),
                ("email_comercial", models.EmailField(blank=True, max_length=255)),
                ("direccion", models.CharField(blank=True, max_length=255)),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False, help_text="Verificado por el Super Admin"
                    ),
                ),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="perfil_prestador",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.DeleteModel(
            name="MigrationProbe",
        ),
        migrations.AddField(
            model_name="cliente",
            name="id_publico",
            field=models.UUIDField(editable=False, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="product",
            name="id_publico",
            field=models.UUIDField(editable=False, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="reserva",
            name="id_publico",
            field=models.UUIDField(editable=False, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="operational_tags",
            field=models.ManyToManyField(
                blank=True, to="prestadores.categoriaprestador"
            ),
        ),
        migrations.AlterField(
            model_name="alojamiento",
            name="perfil",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alojamiento",
                to="prestadores.providerprofile",
            ),
        ),
        migrations.AlterField(
            model_name="amenity",
            name="provider",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_items",
                to="prestadores.providerprofile",
            ),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="perfil",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="clientes",
                to="prestadores.providerprofile",
            ),
        ),
        migrations.AlterField(
            model_name="companiatransporte",
            name="perfil",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="compania_transporte",
                to="prestadores.providerprofile",
            ),
        ),
        migrations.AlterField(
            model_name="costo",
            name="perfil",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="costos",
                to="prestadores.providerprofile",
            ),
        ),
        migrations.AlterField(
            model_name="excepcionhorario",
            name="perfil",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="excepciones_horario",
                to="prestadores.providerprofile",
            ),
        ),
        migrations.AlterField(
            model_name="horario",
            name="perfil",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="horarios",
                to="prestadores.providerprofile",
            ),
        ),
        migrations.AlterField(
            model_name="inventoryitem",
            name="provider",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_items",
                to="prestadores.providerprofile",
            ),
        ),
        migrations.AlterField(
            model_name="kitchenstation",
            name="provider",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_items",
                to="prestadores.providerprofile",
            ),
        ),
        migrations.AlterField(
            model_name="operadorturistico",
            name="perfil",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="operador_turistico",
                to="prestadores.providerprofile",
            ),
        ),
        migrations.AlterField(
            model_name="organizadorevento",
            name="perfil",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="organizador_eventos",
                to="prestadores.providerprofile",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="provider",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_items",
                to="prestadores.providerprofile",
            ),
        ),
        migrations.AlterField(
            model_name="promocion",
            name="perfil",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="promociones",
                to="prestadores.providerprofile",
            ),
        ),
        migrations.AlterField(
            model_name="restaurante",
            name="perfil",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="restaurante",
                to="prestadores.providerprofile",
            ),
        ),
        migrations.AlterField(
            model_name="restauranttable",
            name="provider",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_items",
                to="prestadores.providerprofile",
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="provider",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_items",
                to="prestadores.providerprofile",
            ),
        ),
        migrations.AlterField(
            model_name="roomtype",
            name="provider",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_items",
                to="prestadores.providerprofile",
            ),
        ),
        migrations.AlterField(
            model_name="sitioturistico",
            name="perfil",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sitios_turisticos",
                to="prestadores.providerprofile",
            ),
        ),
        migrations.AlterField(
            model_name="skill",
            name="provider",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_items",
                to="prestadores.providerprofile",
            ),
        ),
        migrations.AlterField(
            model_name="valoracion",
            name="perfil_prestador",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="valoraciones_recibidas",
                to="prestadores.providerprofile",
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="provider",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_items",
                to="prestadores.providerprofile",
            ),
        ),
        migrations.AlterField(
            model_name="vehiculodealquiler",
            name="perfil",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vehiculos_de_alquiler",
                to="prestadores.providerprofile",
            ),
        ),
    ]
