# Generated by Django 5.2.6 on 2026-02-08 16:24

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prestadores", "0002_procesooperativo_tareaoperativa"),
    ]

    operations = [
        migrations.CreateModel(
            name="CapacitacionSST",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("tema", models.CharField(max_length=255)),
                ("fecha", models.DateField()),
                ("intensidad_horaria", models.IntegerField()),
                ("asistentes_count", models.IntegerField()),
                (
                    "evidencia_asistencia_ref_id",
                    models.UUIDField(blank=True, null=True),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_items",
                        to="prestadores.providerprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IncidenteLaboral",
            fields=[
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("ACCIDENTE", "Accidente de Trabajo"),
                            ("INCIDENTE", "Incidente (Casi accidente)"),
                            ("ENFERMEDAD", "Enfermedad Laboral"),
                        ],
                        max_length=20,
                    ),
                ),
                ("fecha_hora", models.DateTimeField()),
                ("lugar", models.CharField(max_length=255)),
                ("descripcion_hechos", models.TextField()),
                ("personas_afectadas", models.JSONField(default=list)),
                (
                    "gravedad",
                    models.CharField(
                        choices=[
                            ("LEVE", "Leve"),
                            ("GRAVE", "Grave"),
                            ("MORTAL", "Mortal"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "estado_investigacion",
                    models.CharField(default="PENDIENTE", max_length=50),
                ),
                (
                    "evidencia_archivistica_ref_id",
                    models.UUIDField(blank=True, null=True),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_items",
                        to="prestadores.providerprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Incidente Laboral",
                "verbose_name_plural": "Incidentes Laborales",
            },
        ),
        migrations.CreateModel(
            name="InvestigacionIncidente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("causas_basicas", models.TextField()),
                ("causas_inmediatas", models.TextField()),
                ("plan_accion", models.TextField()),
                ("responsable_seguimiento_id", models.UUIDField()),
                ("fecha_cierre", models.DateField(blank=True, null=True)),
                (
                    "incidente",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="investigacion",
                        to="prestadores.incidentelaboral",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MatrizRiesgo",
            fields=[
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("proceso_operativo_ref_id", models.UUIDField(blank=True, null=True)),
                ("peligro_descripcion", models.CharField(max_length=255)),
                ("clasificacion", models.CharField(max_length=100)),
                ("efectos_posibles", models.TextField()),
                ("probabilidad", models.IntegerField(help_text="1 a 4")),
                ("consecuencia", models.IntegerField(help_text="1 a 4")),
                ("nivel_riesgo", models.IntegerField(editable=False)),
                ("aceptabilidad", models.CharField(max_length=50)),
                ("fecha_identificacion", models.DateField(auto_now_add=True)),
                ("ultima_revision", models.DateTimeField(auto_now=True)),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_items",
                        to="prestadores.providerprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Matriz de Riesgo",
                "verbose_name_plural": "Matrices de Riesgo",
            },
        ),
        migrations.CreateModel(
            name="ControlRiesgo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "jerarquia",
                    models.CharField(
                        choices=[
                            ("ELIMINACION", "Eliminación"),
                            ("SUSTITUCION", "Sustitución"),
                            ("INGENIERIA", "Controles de Ingeniería"),
                            ("ADMINISTRATIVO", "Controles Administrativos"),
                            ("EPP", "Equipos de Protección Personal"),
                        ],
                        max_length=50,
                    ),
                ),
                ("descripcion_control", models.TextField()),
                ("implementado", models.BooleanField(default=False)),
                ("fecha_implementacion", models.DateField(blank=True, null=True)),
                (
                    "matriz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="controles",
                        to="prestadores.matrizriesgo",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SaludOcupacional",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("empleado_id", models.UUIDField()),
                ("tipo_examen", models.CharField(max_length=100)),
                ("fecha_examen", models.DateField()),
                ("resultado_concepto", models.CharField(max_length=100)),
                ("recomendaciones", models.TextField(blank=True)),
                ("proximo_examen", models.DateField(blank=True, null=True)),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_items",
                        to="prestadores.providerprofile",
                    ),
                ),
            ],
        ),
    ]
