# Generated by Django 5.2.6 on 2025-11-01 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_plantillaverificacion_categoria_prestador"),
        ("comercial", "0003_alter_cliente_perfil"),
        ("inventario", "0003_alter_producto_perfil"),
        (
            "prestadores",
            "0002_currency_bankaccount_cashtransaction_chartofaccount_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bankaccount",
            name="perfil",
        ),
        migrations.RemoveField(
            model_name="cashtransaction",
            name="bank_account",
        ),
        migrations.RemoveField(
            model_name="cashtransaction",
            name="perfil",
        ),
        migrations.RemoveField(
            model_name="perfil",
            name="categoria",
        ),
        migrations.AlterUniqueTogether(
            name="chartofaccount",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="chartofaccount",
            name="perfil",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="account",
        ),
        migrations.RemoveField(
            model_name="cliente",
            name="perfil",
        ),
        migrations.RemoveField(
            model_name="costcenter",
            name="perfil",
        ),
        migrations.RemoveField(
            model_name="costo",
            name="perfil",
        ),
        migrations.DeleteModel(
            name="Currency",
        ),
        migrations.RemoveField(
            model_name="inventario",
            name="perfil",
        ),
        migrations.RemoveField(
            model_name="journalentry",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="journalentry",
            name="perfil",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="journal_entry",
        ),
        migrations.RemoveField(
            model_name="perfil",
            name="usuario",
        ),
        migrations.RemoveField(
            model_name="productoservicio",
            name="perfil",
        ),
        migrations.DeleteModel(
            name="BankAccount",
        ),
        migrations.DeleteModel(
            name="CashTransaction",
        ),
        migrations.DeleteModel(
            name="CategoriaPrestador",
        ),
        migrations.DeleteModel(
            name="ChartOfAccount",
        ),
        migrations.DeleteModel(
            name="Cliente",
        ),
        migrations.DeleteModel(
            name="CostCenter",
        ),
        migrations.DeleteModel(
            name="Costo",
        ),
        migrations.DeleteModel(
            name="Inventario",
        ),
        migrations.DeleteModel(
            name="JournalEntry",
        ),
        migrations.DeleteModel(
            name="Transaction",
        ),
        migrations.DeleteModel(
            name="Perfil",
        ),
        migrations.DeleteModel(
            name="ProductoServicio",
        ),
    ]
