# Generated by Django 5.2.6 on 2025-12-05 23:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prestadores", "0002_cancellationpolicy_kitchenstation_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Almacen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("ubicacion", models.CharField(blank=True, max_length=255)),
                (
                    "perfil",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="almacenes",
                        to="prestadores.providerprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CategoriaProducto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("descripcion", models.TextField(blank=True)),
                (
                    "perfil",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categorias_producto",
                        to="prestadores.providerprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CuentaBancaria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("banco", models.CharField(max_length=100)),
                ("numero_cuenta", models.CharField(max_length=50)),
                (
                    "tipo_cuenta",
                    models.CharField(
                        choices=[("AHORROS", "Ahorros"), ("CORRIENTE", "Corriente")],
                        max_length=20,
                    ),
                ),
                (
                    "saldo_actual",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=18),
                ),
                ("titular", models.CharField(max_length=255)),
                (
                    "perfil",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cuentas_bancarias",
                        to="prestadores.providerprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Producto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                ("sku", models.CharField(max_length=100, unique=True)),
                ("descripcion", models.TextField(blank=True)),
                (
                    "costo",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=18),
                ),
                (
                    "precio_venta",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=18),
                ),
                (
                    "stock_actual",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=18),
                ),
                (
                    "stock_minimo",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=18),
                ),
                (
                    "categoria",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="productos",
                        to="prestadores.categoriaproducto",
                    ),
                ),
                (
                    "perfil",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="productos",
                        to="prestadores.providerprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MovimientoInventario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_movimiento",
                    models.CharField(
                        choices=[
                            ("ENTRADA", "Entrada"),
                            ("SALIDA", "Salida"),
                            ("AJUSTE_POSITIVO", "Ajuste Positivo"),
                            ("AJUSTE_NEGATIVO", "Ajuste Negativo"),
                        ],
                        max_length=20,
                    ),
                ),
                ("cantidad", models.DecimalField(decimal_places=2, max_digits=18)),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                ("descripcion", models.TextField(blank=True)),
                (
                    "almacen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movimientos",
                        to="prestadores.almacen",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movimientos",
                        to="prestadores.producto",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TransaccionBancaria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField()),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("INGRESO", "Ingreso"),
                            ("EGRESO", "Egreso"),
                            ("TRANSFERENCIA", "Transferencia"),
                        ],
                        max_length=20,
                    ),
                ),
                ("monto", models.DecimalField(decimal_places=2, max_digits=18)),
                ("descripcion", models.CharField(max_length=255)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "creado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "cuenta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transacciones",
                        to="prestadores.cuentabancaria",
                    ),
                ),
            ],
        ),
    ]
