# Generated by Django 5.2.6 on 2026-01-04 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prestadores", "0003_remove_product_nature_remove_product_stock_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="stock",
            field=models.PositiveIntegerField(
                default=0,
                help_text="La cantidad actual de este producto en inventario.",
                verbose_name="Stock Actual",
            ),
        ),
    ]
