# Generated by Django 5.2.6 on 2025-12-05 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "prestadores",
            "0003_almacen_categoriaproducto_cuentabancaria_producto_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaccionbancaria",
            name="cuenta",
        ),
        migrations.RemoveField(
            model_name="transaccionbancaria",
            name="creado_por",
        ),
        migrations.DeleteModel(
            name="CuentaBancaria",
        ),
        migrations.DeleteModel(
            name="TransaccionBancaria",
        ),
    ]
