# Generated by Django 5.2.6 on 2026-02-15 01:14

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prestadores", "0003_capacitacionsst_incidentelaboral_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="alojamiento",
            name="perfil",
        ),
        migrations.RemoveField(
            model_name="alojamiento",
            name="tipo",
        ),
        migrations.RemoveField(
            model_name="habitacion",
            name="alojamiento",
        ),
        migrations.RemoveField(
            model_name="alquiler",
            name="vehiculo",
        ),
        migrations.RemoveField(
            model_name="categoriaplato",
            name="menu",
        ),
        migrations.RemoveField(
            model_name="plato",
            name="categoria",
        ),
        migrations.RemoveField(
            model_name="companiatransporte",
            name="perfil",
        ),
        migrations.RemoveField(
            model_name="ruta",
            name="compania",
        ),
        migrations.RemoveField(
            model_name="vehiculo",
            name="compania",
        ),
        migrations.RemoveField(
            model_name="habitacion",
            name="producto",
        ),
        migrations.RemoveField(
            model_name="tarifa",
            name="habitacion",
        ),
        migrations.RemoveField(
            model_name="horarioruta",
            name="ruta",
        ),
        migrations.RemoveField(
            model_name="horarioruta",
            name="vehiculo",
        ),
        migrations.AlterUniqueTogether(
            name="itinerariodia",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="itinerariodia",
            name="paquete",
        ),
        migrations.RemoveField(
            model_name="menu",
            name="restaurante",
        ),
        migrations.RemoveField(
            model_name="operadorturistico",
            name="perfil",
        ),
        migrations.RemoveField(
            model_name="paqueteturistico",
            name="operador",
        ),
        migrations.RemoveField(
            model_name="paqueteturistico",
            name="producto",
        ),
        migrations.RemoveField(
            model_name="plato",
            name="producto",
        ),
        migrations.RemoveField(
            model_name="procesooperativo",
            name="provider",
        ),
        migrations.RemoveField(
            model_name="tareaoperativa",
            name="proceso",
        ),
        migrations.RemoveField(
            model_name="restaurante",
            name="perfil",
        ),
        migrations.RemoveField(
            model_name="zonadelivery",
            name="restaurante",
        ),
        migrations.RemoveField(
            model_name="sitioturistico",
            name="perfil",
        ),
        migrations.RemoveField(
            model_name="tareaoperativa",
            name="provider",
        ),
        migrations.RemoveField(
            model_name="vehiculo",
            name="tipo",
        ),
        migrations.RemoveField(
            model_name="vehiculo",
            name="producto",
        ),
        migrations.RemoveField(
            model_name="vehiculodealquiler",
            name="perfil",
        ),
        migrations.AlterModelOptions(
            name="amenity",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="kitchenstation",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="restauranttable",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="room",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="roomtype",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="vehicle",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RemoveField(
            model_name="restauranttable",
            name="pos_x",
        ),
        migrations.RemoveField(
            model_name="restauranttable",
            name="pos_y",
        ),
        migrations.RemoveField(
            model_name="vehicle",
            name="nombre",
        ),
        migrations.RemoveField(
            model_name="vehicle",
            name="tech_inspection_expiry_date",
        ),
        migrations.RemoveField(
            model_name="vehicle",
            name="tipo_vehiculo",
        ),
        migrations.AddField(
            model_name="costo",
            name="insumo_ref_id",
            field=models.UUIDField(
                blank=True,
                help_text="Vínculo con el ítem de inventario si aplica.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="costo",
            name="orden_operativa_ref_id",
            field=models.UUIDField(
                blank=True,
                help_text="Vínculo con la orden que generó el gasto.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="costo",
            name="personal_ref_id",
            field=models.UUIDField(
                blank=True,
                help_text="Vínculo con el colaborador si es mano de obra.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="menuitemdetail",
            name="allergens",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="menuitemdetail",
            name="is_vegetarian",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="room",
            name="status",
            field=models.CharField(
                choices=[
                    ("AVAILABLE", "Disponible"),
                    ("OCCUPIED", "Ocupada"),
                    ("RESERVED", "Reservada"),
                    ("MAINTENANCE", "Mantenimiento"),
                ],
                default="AVAILABLE",
                max_length=20,
                verbose_name="Estado de Ocupación",
            ),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="product",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vehicle_details",
                to="prestadores.product",
            ),
        ),
        migrations.AlterField(
            model_name="menuitemdetail",
            name="assigned_station",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="prestadores.kitchenstation",
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="capacidad",
            field=models.PositiveSmallIntegerField(
                default=1, verbose_name="Capacidad de Pasajeros"
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="insurance_expiry_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Vencimiento de Póliza"
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="modelo_ano",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Modelo (Año)"
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="placa",
            field=models.CharField(
                blank=True, max_length=10, null=True, unique=True, verbose_name="Placa"
            ),
        ),
        migrations.CreateModel(
            name="AsignacionRecurso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("orden_operativa_ref_id", models.UUIDField()),
                (
                    "cantidad_asignada",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "cantidad_consumida_real",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("fecha_asignacion", models.DateTimeField(auto_now_add=True)),
                ("completado", models.BooleanField(default=False)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asignaciones",
                        to="prestadores.inventoryitem",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TransportRoute",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("nombre", models.CharField(max_length=200)),
                ("origen", models.CharField(max_length=150)),
                ("destino", models.CharField(max_length=150)),
                ("distancia_km", models.FloatField(blank=True, null=True)),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_items",
                        to="prestadores.providerprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.DeleteModel(
            name="ActividadEnSitio",
        ),
        migrations.DeleteModel(
            name="TipoAlojamiento",
        ),
        migrations.DeleteModel(
            name="Alojamiento",
        ),
        migrations.DeleteModel(
            name="Alquiler",
        ),
        migrations.DeleteModel(
            name="CategoriaPlato",
        ),
        migrations.DeleteModel(
            name="CompaniaTransporte",
        ),
        migrations.DeleteModel(
            name="Habitacion",
        ),
        migrations.DeleteModel(
            name="Tarifa",
        ),
        migrations.DeleteModel(
            name="Ruta",
        ),
        migrations.DeleteModel(
            name="HorarioRuta",
        ),
        migrations.DeleteModel(
            name="ItinerarioDia",
        ),
        migrations.DeleteModel(
            name="Menu",
        ),
        migrations.DeleteModel(
            name="OperadorTuristico",
        ),
        migrations.DeleteModel(
            name="PaqueteTuristico",
        ),
        migrations.DeleteModel(
            name="Plato",
        ),
        migrations.DeleteModel(
            name="ProcesoOperativo",
        ),
        migrations.DeleteModel(
            name="Restaurante",
        ),
        migrations.DeleteModel(
            name="ZonaDelivery",
        ),
        migrations.DeleteModel(
            name="SitioTuristico",
        ),
        migrations.DeleteModel(
            name="TareaOperativa",
        ),
        migrations.DeleteModel(
            name="TipoVehiculo",
        ),
        migrations.DeleteModel(
            name="Vehiculo",
        ),
        migrations.DeleteModel(
            name="VehiculoDeAlquiler",
        ),
    ]
