# Generated by Django 5.2.11 on 2026-02-15 18:04

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "prestadores",
            "0004_remove_alojamiento_perfil_remove_alojamiento_tipo_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="capacitacionsst",
            name="programada",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="capacitacionsst",
            name="realizada",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="matrizriesgo",
            name="criticidad",
            field=models.CharField(default="MEDIA", max_length=20),
        ),
        migrations.AddField(
            model_name="matrizriesgo",
            name="es_vigente",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="matrizriesgo",
            name="version",
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name="AlertaSST",
            fields=[
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("titulo", models.CharField(max_length=255)),
                ("mensaje", models.TextField()),
                ("criticidad", models.CharField(max_length=20)),
                ("leida", models.BooleanField(default=False)),
                ("fecha_generacion", models.DateTimeField(auto_now_add=True)),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_items",
                        to="prestadores.providerprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IndicadorSST",
            fields=[
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                ("tipo", models.CharField(max_length=100)),
                ("valor", models.DecimalField(decimal_places=2, max_digits=10)),
                ("meta", models.DecimalField(decimal_places=2, max_digits=10)),
                ("periodo", models.CharField(max_length=50)),
                ("fecha_calculo", models.DateTimeField(auto_now_add=True)),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_items",
                        to="prestadores.providerprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InspeccionSST",
            fields=[
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tipo", models.CharField(max_length=100)),
                ("fecha", models.DateField()),
                ("inspector_id", models.UUIDField()),
                ("centro_trabajo", models.CharField(max_length=255)),
                (
                    "porcentaje_hallazgos_cerrados",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_items",
                        to="prestadores.providerprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HallazgoInspeccion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descripcion", models.TextField()),
                (
                    "criticidad",
                    models.CharField(
                        choices=[
                            ("ALTA", "Alta"),
                            ("MEDIA", "Media"),
                            ("BAJA", "Baja"),
                        ],
                        max_length=20,
                    ),
                ),
                ("plan_accion", models.TextField()),
                ("fecha_limite", models.DateField()),
                ("cerrado", models.BooleanField(default=False)),
                ("fecha_cierre", models.DateField(blank=True, null=True)),
                (
                    "inspeccion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hallazgos",
                        to="prestadores.inspeccionsst",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PlanAnualSST",
            fields=[
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("año", models.IntegerField()),
                ("nombre", models.CharField(max_length=255)),
                ("objetivo", models.TextField()),
                (
                    "porcentaje_cumplimiento",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("estado", models.CharField(default="BORRADOR", max_length=20)),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_items",
                        to="prestadores.providerprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ActividadPlanSST",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                ("fecha_programada", models.DateField()),
                ("fecha_ejecutada", models.DateField(blank=True, null=True)),
                ("responsable_id", models.UUIDField(blank=True, null=True)),
                ("completada", models.BooleanField(default=False)),
                ("evidencia_id", models.UUIDField(blank=True, null=True)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actividades",
                        to="prestadores.plananualsst",
                    ),
                ),
            ],
        ),
    ]
