# Generated by Django 5.2.6 on 2025-12-09 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("prestadores", "0004_remove_transaccionbancaria_cuenta_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movimientoinventario",
            name="almacen",
        ),
        migrations.RemoveField(
            model_name="categoriaproducto",
            name="perfil",
        ),
        migrations.RemoveField(
            model_name="producto",
            name="categoria",
        ),
        migrations.RemoveField(
            model_name="movimientoinventario",
            name="producto",
        ),
        migrations.RemoveField(
            model_name="movimientoinventario",
            name="usuario",
        ),
        migrations.RemoveField(
            model_name="producto",
            name="perfil",
        ),
        migrations.DeleteModel(
            name="Almacen",
        ),
        migrations.DeleteModel(
            name="CategoriaProducto",
        ),
        migrations.DeleteModel(
            name="MovimientoInventario",
        ),
        migrations.DeleteModel(
            name="Producto",
        ),
    ]
