# Generated by Django 5.2.6 on 2026-02-16 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "prestadores",
            "0005_capacitacionsst_programada_capacitacionsst_realizada_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="costo",
            name="tipo_costo",
            field=models.CharField(
                choices=[
                    ("FIJO", "Fijo"),
                    ("VARIABLE", "Variable"),
                    ("INSUMOS", "Insumos / Materia Prima"),
                    ("PERSONAL", "Mano de Obra"),
                    ("TALLER", "Gastos de Taller/Cocina"),
                ],
                default="VARIABLE",
                max_length=50,
                verbose_name="Tipo de Costo",
            ),
        ),
    ]
