# Generated by Django 5.2.6 on 2025-12-10 16:16

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("prestadores", "0005_remove_movimientoinventario_almacen_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Menu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("descripcion", models.TextField(blank=True, null=True)),
                ("activo", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="TipoAlojamiento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, unique=True)),
                ("descripcion", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="TipoVehiculo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, unique=True)),
                ("descripcion", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="paqueteturistico",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="paqueteturistico",
            name="descripcion",
        ),
        migrations.RemoveField(
            model_name="paqueteturistico",
            name="estado",
        ),
        migrations.RemoveField(
            model_name="paqueteturistico",
            name="nombre",
        ),
        migrations.RemoveField(
            model_name="paqueteturistico",
            name="perfil",
        ),
        migrations.RemoveField(
            model_name="paqueteturistico",
            name="precio_por_persona",
        ),
        migrations.RemoveField(
            model_name="paqueteturistico",
            name="servicios_incluidos",
        ),
        migrations.RemoveField(
            model_name="paqueteturistico",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="paqueteturistico",
            name="incluye",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Breve descripción de lo que incluye el paquete (ej: Alojamiento, Transporte).",
            ),
        ),
        migrations.AddField(
            model_name="paqueteturistico",
            name="producto",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="paquete_turistico",
                to="prestadores.product",
            ),
        ),
        migrations.AlterField(
            model_name="paqueteturistico",
            name="duracion_dias",
            field=models.PositiveIntegerField(),
        ),
        migrations.CreateModel(
            name="Alojamiento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("descripcion", models.TextField()),
                ("direccion", models.CharField(max_length=255)),
                (
                    "perfil",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alojamiento",
                        to="prestadores.providerprofile",
                    ),
                ),
                (
                    "tipo",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="prestadores.tipoalojamiento",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CompaniaTransporte",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("descripcion", models.TextField()),
                (
                    "perfil",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compania_transporte",
                        to="prestadores.providerprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Habitacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("capacidad_maxima", models.PositiveIntegerField()),
                (
                    "alojamiento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="habitaciones",
                        to="prestadores.alojamiento",
                    ),
                ),
                (
                    "producto",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="habitacion",
                        to="prestadores.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CategoriaPlato",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                (
                    "orden",
                    models.PositiveIntegerField(
                        default=0, help_text="Orden de aparición en el menú"
                    ),
                ),
                (
                    "menu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categorias",
                        to="prestadores.menu",
                    ),
                ),
            ],
            options={
                "ordering": ["orden", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="OperadorTuristico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("descripcion", models.TextField()),
                ("licencia_turismo", models.CharField(blank=True, max_length=100)),
                (
                    "perfil",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operador_turistico",
                        to="prestadores.providerprofile",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="paqueteturistico",
            name="operador",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="paquetes",
                to="prestadores.operadorturistico",
            ),
        ),
        migrations.CreateModel(
            name="OrganizadorEvento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("descripcion", models.TextField()),
                (
                    "perfil",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organizador_eventos",
                        to="prestadores.providerprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Evento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_inicio", models.DateTimeField()),
                ("fecha_fin", models.DateTimeField()),
                ("ubicacion", models.CharField(max_length=255)),
                ("capacidad", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "producto",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evento",
                        to="prestadores.product",
                    ),
                ),
                (
                    "organizador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="eventos",
                        to="prestadores.organizadorevento",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Plato",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("disponible", models.BooleanField(default=True)),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="platos",
                        to="prestadores.categoriaplato",
                    ),
                ),
                (
                    "producto",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plato",
                        to="prestadores.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PoliticaCancelacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        help_text="Ej: Estricta, Flexible, No reembolsable",
                        max_length=100,
                    ),
                ),
                ("descripcion", models.TextField()),
                (
                    "perfil",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="politicas_cancelacion",
                        to="prestadores.providerprofile",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="product",
            name="cancellation_policy",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="prestadores.politicacancelacion",
            ),
        ),
        migrations.CreateModel(
            name="Promocion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("descripcion", models.TextField(blank=True)),
                ("fecha_inicio", models.DateField()),
                ("fecha_fin", models.DateField()),
                (
                    "tipo_descuento",
                    models.CharField(
                        choices=[("porcentaje", "Porcentaje"), ("fijo", "Monto Fijo")],
                        max_length=10,
                    ),
                ),
                (
                    "valor_descuento",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Valor del descuento (ej: 10 para 10% o 5000 para $5000 fijos)",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("activa", models.BooleanField(default=True)),
                (
                    "perfil",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promociones",
                        to="prestadores.providerprofile",
                    ),
                ),
                (
                    "productos_aplicables",
                    models.ManyToManyField(
                        related_name="promociones", to="prestadores.product"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Reserva",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                ("fecha_inicio", models.DateTimeField()),
                ("fecha_fin", models.DateTimeField()),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente"),
                            ("CONFIRMADA", "Confirmada"),
                            ("CANCELADA", "Cancelada"),
                            ("COMPLETADA", "Completada"),
                        ],
                        default="PENDIENTE",
                        max_length=20,
                    ),
                ),
                ("notas", models.TextField(blank=True)),
                ("precio_total", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "deposito_pagado",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("modificado_en", models.DateTimeField(auto_now=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reservas",
                        to="prestadores.cliente",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "perfil",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservas",
                        to="prestadores.providerprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Restaurante",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("descripcion", models.TextField()),
                ("ofrece_delivery", models.BooleanField(default=False)),
                (
                    "perfil",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="restaurante",
                        to="prestadores.providerprofile",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="menu",
            name="restaurante",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="menus",
                to="prestadores.restaurante",
            ),
        ),
        migrations.CreateModel(
            name="Ruta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("origen", models.CharField(max_length=150)),
                ("destino", models.CharField(max_length=150)),
                ("distancia_km", models.FloatField(blank=True, null=True)),
                (
                    "compania",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rutas",
                        to="prestadores.companiatransporte",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tarifa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("fecha_inicio", models.DateField()),
                ("fecha_fin", models.DateField()),
                (
                    "precio_adicional",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Valor a sumar (o restar si es negativo) al precio base de la habitación.",
                        max_digits=10,
                    ),
                ),
                (
                    "habitacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tarifas",
                        to="prestadores.habitacion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Valoracion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "puntuacion",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                ("comentario", models.TextField()),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("respuesta_del_prestador", models.TextField(blank=True, null=True)),
                ("fecha_respuesta", models.DateTimeField(blank=True, null=True)),
                (
                    "perfil_prestador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="valoraciones_recibidas",
                        to="prestadores.providerprofile",
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="valoraciones",
                        to="prestadores.product",
                    ),
                ),
                (
                    "turista",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="valoraciones_emitidas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha_creacion"],
                "unique_together": {("producto", "turista")},
            },
        ),
        migrations.CreateModel(
            name="Vehiculo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("placa", models.CharField(max_length=20, unique=True)),
                ("capacidad_pasajeros", models.PositiveIntegerField()),
                (
                    "compania",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vehiculos",
                        to="prestadores.companiatransporte",
                    ),
                ),
                (
                    "producto",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vehiculo",
                        to="prestadores.product",
                    ),
                ),
                (
                    "tipo",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="prestadores.tipovehiculo",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HorarioRuta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hora_salida", models.TimeField()),
                ("hora_llegada_estimada", models.TimeField()),
                (
                    "dias_operacion",
                    models.CharField(
                        help_text="Ej: 'L-V', 'S,D', 'L,M,X'", max_length=50
                    ),
                ),
                (
                    "ruta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="horarios",
                        to="prestadores.ruta",
                    ),
                ),
                (
                    "vehiculo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="horarios_asignados",
                        to="prestadores.vehiculo",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ZonaDelivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        help_text="Ej: 'Centro', 'Zona Norte'", max_length=100
                    ),
                ),
                ("costo_envio", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "tiempo_estimado_minutos",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "restaurante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="zonas_delivery",
                        to="prestadores.restaurante",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExcepcionHorario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField()),
                ("esta_abierto", models.BooleanField(default=False)),
                ("hora_apertura", models.TimeField(blank=True, null=True)),
                ("hora_cierre", models.TimeField(blank=True, null=True)),
                (
                    "descripcion",
                    models.CharField(
                        help_text="Ej: Feriado Nacional, Evento Privado", max_length=255
                    ),
                ),
                (
                    "perfil",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="excepciones_horario",
                        to="prestadores.providerprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["fecha"],
                "unique_together": {("perfil", "fecha")},
            },
        ),
        migrations.CreateModel(
            name="Horario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dia_semana",
                    models.IntegerField(
                        choices=[
                            (0, "Lunes"),
                            (1, "Martes"),
                            (2, "Miércoles"),
                            (3, "Jueves"),
                            (4, "Viernes"),
                            (5, "Sábado"),
                            (6, "Domingo"),
                        ]
                    ),
                ),
                ("hora_apertura", models.TimeField()),
                ("hora_cierre", models.TimeField()),
                (
                    "perfil",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="horarios",
                        to="prestadores.providerprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["dia_semana", "hora_apertura"],
                "unique_together": {("perfil", "dia_semana")},
            },
        ),
        migrations.CreateModel(
            name="ItinerarioDia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dia", models.PositiveIntegerField()),
                (
                    "titulo",
                    models.CharField(
                        help_text="Ej: 'Día 1: Llegada a la ciudad'", max_length=200
                    ),
                ),
                ("descripcion", models.TextField()),
                (
                    "paquete",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itinerario",
                        to="prestadores.paqueteturistico",
                    ),
                ),
            ],
            options={
                "ordering": ["dia"],
                "unique_together": {("paquete", "dia")},
            },
        ),
        migrations.DeleteModel(
            name="CancellationPolicy",
        ),
    ]
