# Generated by Django 5.2.6 on 2026-02-16 14:09

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "prestadores",
            "0007_liquorinventory_nightclubprofile_nightconsumption_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="skill",
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="GrupoTuristico",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("nombre", models.CharField(blank=True, max_length=100)),
                ("numero_turistas", models.PositiveIntegerField()),
                ("contacto_principal", models.CharField(max_length=255)),
                ("observaciones", models.TextField(blank=True)),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_items",
                        to="prestadores.providerprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="GuiaTuristico",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("identificacion", models.CharField(max_length=50, unique=True)),
                (
                    "nivel",
                    models.CharField(
                        choices=[
                            ("JUNIOR", "Junior"),
                            ("SENIOR", "Senior"),
                            ("ESPECIALIZADO", "Especializado"),
                        ],
                        default="JUNIOR",
                        max_length=20,
                    ),
                ),
                (
                    "idiomas",
                    models.JSONField(
                        default=list, help_text="Lista de idiomas que habla el guía"
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("ACTIVO", "Activo"),
                            ("SUSPENDIDO", "Suspendido"),
                            ("VENCIDO_DOCUMENTAL", "Vencido por Documentación"),
                        ],
                        default="ACTIVO",
                        max_length=20,
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_items",
                        to="prestadores.providerprofile",
                    ),
                ),
                ("skills", models.ManyToManyField(blank=True, to="prestadores.skill")),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="perfil_guia",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Guía Turístico",
                "verbose_name_plural": "Guías Turísticos",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CertificacionGuia",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("tipo_certificacion", models.CharField(max_length=100)),
                ("entidad_emisora", models.CharField(max_length=150)),
                ("fecha_emision", models.DateField()),
                ("fecha_vencimiento", models.DateField()),
                ("documento_adjunto_ref_id", models.UUIDField(blank=True, null=True)),
                (
                    "estado_validacion",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente"),
                            ("VALIDADO", "Validado"),
                            ("RECHAZADO", "Rechazado"),
                            ("VENCIDO", "Vencido"),
                        ],
                        default="PENDIENTE",
                        max_length=20,
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_items",
                        to="prestadores.providerprofile",
                    ),
                ),
                (
                    "guia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificaciones",
                        to="prestadores.guiaturistico",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="LiquidacionGuia",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("periodo_inicio", models.DateField()),
                ("periodo_fin", models.DateField()),
                ("monto_total", models.DecimalField(decimal_places=2, max_digits=12)),
                ("fecha_liquidacion", models.DateTimeField(auto_now_add=True)),
                ("asiento_contable_ref_id", models.UUIDField(blank=True, null=True)),
                (
                    "guia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="liquidaciones",
                        to="prestadores.guiaturistico",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_items",
                        to="prestadores.providerprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="LocalRutaTuristica",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("nombre", models.CharField(max_length=255)),
                ("descripcion", models.TextField()),
                ("ruta_global_ref_id", models.UUIDField(blank=True, null=True)),
                (
                    "duracion_estimada_horas",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_items",
                        to="prestadores.providerprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Itinerario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("orden", models.PositiveIntegerField()),
                ("actividad", models.CharField(max_length=255)),
                ("descripcion", models.TextField(blank=True)),
                ("tiempo_estimado_minutos", models.PositiveIntegerField()),
                (
                    "ruta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itinerarios",
                        to="prestadores.localrutaturistica",
                    ),
                ),
            ],
            options={
                "ordering": ["orden"],
            },
        ),
        migrations.CreateModel(
            name="ServicioGuiado",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("fecha", models.DateField()),
                ("hora_inicio", models.TimeField()),
                (
                    "precio_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "comision_guia",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PROGRAMADO", "Programado"),
                            ("CONFIRMADO", "Confirmado"),
                            ("EN_CURSO", "En Curso"),
                            ("FINALIZADO", "Finalizado"),
                            ("CANCELADO", "Cancelado"),
                            ("LIQUIDADO", "Liquidado"),
                        ],
                        default="PROGRAMADO",
                        max_length=20,
                    ),
                ),
                ("operacion_comercial_ref_id", models.UUIDField(blank=True, null=True)),
                (
                    "governance_intention_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "grupo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="prestadores.grupoturistico",
                    ),
                ),
                (
                    "guia_asignado",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="servicios",
                        to="prestadores.guiaturistico",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_items",
                        to="prestadores.providerprofile",
                    ),
                ),
                (
                    "ruta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="prestadores.localrutaturistica",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="IncidenciaServicio",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("descripcion", models.TextField()),
                (
                    "gravedad",
                    models.CharField(
                        choices=[
                            ("BAJA", "Baja"),
                            ("MEDIA", "Media"),
                            ("ALTA", "Alta"),
                            ("CRITICA", "Crítica"),
                        ],
                        default="BAJA",
                        max_length=20,
                    ),
                ),
                ("resuelto", models.BooleanField(default=False)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_items",
                        to="prestadores.providerprofile",
                    ),
                ),
                (
                    "staff_reporta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "servicio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incidencias",
                        to="prestadores.servicioguiado",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
    ]
