# Generated by Django 5.2.6 on 2026-02-16 15:43

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prestadores", "0009_rename_capacidad_vehicle_capacidad_maxima_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgencyBooking",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("cliente_ref_id", models.UUIDField()),
                ("fecha_inicio", models.DateField()),
                ("numero_personas", models.PositiveIntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pendiente"),
                            ("CONFIRMED", "Confirmada"),
                            ("CANCELLED", "Cancelada"),
                            ("COMPLETED", "Completada"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "total_facturado",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("asiento_contable_id", models.UUIDField(blank=True, null=True)),
                ("factura_ref_id", models.UUIDField(blank=True, null=True)),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_items",
                        to="prestadores.providerprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AgencyLiquidation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "monto_total_ingresado",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "total_costo_proveedores",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "utilidad_agencia",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("fecha_liquidacion", models.DateTimeField(auto_now_add=True)),
                ("procesado", models.BooleanField(default=False)),
                (
                    "booking",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="liquidation",
                        to="prestadores.agencybooking",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_items",
                        to="prestadores.providerprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProviderCommission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("monto_base", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "monto_comision",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("pagado", models.BooleanField(default=False)),
                (
                    "liquidation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="provider_commissions",
                        to="prestadores.agencyliquidation",
                    ),
                ),
                (
                    "proveedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="prestadores.providerprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TravelPackage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "nombre",
                    models.CharField(max_length=200, verbose_name="Nombre del Paquete"),
                ),
                ("descripcion", models.TextField(verbose_name="Descripción")),
                (
                    "precio_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "margen_agencia",
                    models.DecimalField(
                        decimal_places=2,
                        default=10.0,
                        help_text="Porcentaje de ganancia",
                        max_digits=5,
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("BORRADOR", "Borrador"),
                            ("PUBLICADO", "Publicado"),
                            ("RESERVADO", "Reservado"),
                            ("CONFIRMADO", "Confirmado"),
                            ("EN_EJECUCION", "En Ejecución"),
                            ("FINALIZADO", "Finalizado"),
                            ("LIQUIDADO", "Liquidado"),
                        ],
                        default="BORRADOR",
                        max_length=20,
                    ),
                ),
                ("duracion_dias", models.PositiveIntegerField(default=1)),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_items",
                        to="prestadores.providerprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PackageIncident",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("descripcion", models.TextField()),
                ("nivel_gravedad", models.CharField(default="LOW", max_length=20)),
                ("resuelta", models.BooleanField(default=False)),
                (
                    "booking",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="prestadores.agencybooking",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_items",
                        to="prestadores.providerprofile",
                    ),
                ),
                (
                    "package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="prestadores.travelpackage",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PackageComponent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_servicio",
                    models.CharField(
                        choices=[
                            ("HOTEL", "Alojamiento"),
                            ("TRANSPORTE", "Transporte"),
                            ("GUIA", "Guía Turístico"),
                            ("EVENTO", "Evento/Actividad"),
                            ("ARTESANO", "Artesanía/Taller"),
                            ("OTROS", "Otros"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "referencia_id",
                    models.UUIDField(
                        help_text="ID del servicio específico en su módulo original"
                    ),
                ),
                (
                    "precio_proveedor",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "comision_proveedor",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("confirmado", models.BooleanField(default=False)),
                (
                    "proveedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="components_as_provider",
                        to="prestadores.providerprofile",
                    ),
                ),
                (
                    "package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="components",
                        to="prestadores.travelpackage",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="agencybooking",
            name="package",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="prestadores.travelpackage",
            ),
        ),
    ]
