# Generated by Django 5.2.6 on 2026-02-16 16:36

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "prestadores",
            "0010_agencybooking_agencyliquidation_providercommission_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ArtisanProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tecnica_usada",
                    models.CharField(
                        help_text="Ej: Torneado, Tejido manual", max_length=200
                    ),
                ),
                (
                    "tiempo_estimado_produccion",
                    models.DurationField(blank=True, null=True),
                ),
                ("es_por_encargo", models.BooleanField(default=False)),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="artisan_details",
                        to="prestadores.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RawMaterial",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("nombre", models.CharField(max_length=200)),
                (
                    "unidad_medida",
                    models.CharField(help_text="Ej: Kg, Gramos, Metros", max_length=50),
                ),
                (
                    "stock_actual",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "costo_por_unidad",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_items",
                        to="prestadores.providerprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="WorkshopOrder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("cliente_ref_id", models.UUIDField()),
                ("especificaciones", models.TextField(blank=True)),
                ("fecha_entrega_prometida", models.DateField()),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("DISENO", "En Diseño"),
                            ("MATERIALES", "Preparación de Materiales"),
                            ("PRODUCCION", "En Producción"),
                            ("ACABADO", "En Acabado"),
                            ("TERMINADO", "Terminado"),
                            ("ENTREGADO", "Entregado"),
                        ],
                        default="DISENO",
                        max_length=30,
                    ),
                ),
                ("total_precio", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "anticipo_pagado",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "artisan_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="prestadores.artisanproduct",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_items",
                        to="prestadores.providerprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProductionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("etapa", models.CharField(max_length=100)),
                ("descripcion", models.TextField(blank=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("evidencia_ref_id", models.UUIDField(blank=True, null=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="production_logs",
                        to="prestadores.workshoporder",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MaterialConsumption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cantidad_usada",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "costo_aplicado",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="prestadores.rawmaterial",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consumptions",
                        to="prestadores.workshoporder",
                    ),
                ),
            ],
        ),
    ]
