# Generated by Django 6.0 on 2025-12-16 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "infrastructure",
            "0002_aiinteraction_asset_campaign_customer_funnel_and_more",
        ),
        ("infrastructure", "0003_aiinteraction_asynctask_contentasset_and_more"),
    ]

    operations = []
