# Generated by Django 5.2.6 on 2025-10-16 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_delete_detalleshotel"),
    ]

    operations = [
        migrations.AddField(
            model_name="resena",
            name="respuesta_prestador",
            field=models.TextField(
                blank=True, help_text="Respuesta del prestador a la reseña.", null=True
            ),
        ),
    ]
