# Generated by Django 5.0.6 on 2024-07-25 15:00

from django.db import migrations

def create_initial_menu_items(apps, schema_editor):
    """
    Crea los elementos iniciales del menú para el sitio.
    """
    MenuItem = apps.get_model('api', 'MenuItem')
    db_alias = schema_editor.connection.alias

    # Limpiar items existentes para evitar duplicados en ejecuciones repetidas
    MenuItem.objects.using(db_alias).all().delete()

    menu_structure = [
        {'nombre': 'Inicio', 'url': '/', 'orden': 0},
        {
            'nombre': 'Descubre',
            'url': '#',
            'orden': 1,
            'children': [
                {'nombre': 'Atractivos Turísticos', 'url': '/descubre/atractivos', 'orden': 0},
                {'nombre': 'Rutas Turísticas', 'url': '/descubre/rutas', 'orden': 1},
                {'nombre': 'Guías Turísticos', 'url': '/guias', 'orden': 2},
                {'nombre': '¿Cómo llegar?', 'url': '/descubre/como-llegar', 'orden': 3},
            ]
        },
        {
            'nombre': 'Institucional',
            'url': '#',
            'orden': 2,
            'children': [
                {'nombre': 'Secretaría de Turismo', 'url': '/institucional/secretaria-turismo', 'orden': 0},
                {'nombre': 'Dirección de Turismo', 'url': '/institucional/direccion-turismo', 'orden': 1},
                {'nombre': 'Consejo Consultivo', 'url': '/institucional/consejo-turismo', 'orden': 2},
            ]
        },
        {'nombre': 'Publicaciones', 'url': '/publicaciones', 'orden': 3},
        {'nombre': 'Mi Viaje', 'url': '/mi-viaje', 'orden': 4},
        {'nombre': 'Empleo', 'url': '/empleo', 'orden': 5},
    ]

    for item_data in menu_structure:
        children_data = item_data.pop('children', None)
        parent_item, created = MenuItem.objects.using(db_alias).get_or_create(
            nombre=item_data['nombre'],
            defaults=item_data
        )

        if created:
            print(f"Creado menú principal: {parent_item.nombre}")

        if children_data:
            for child_data in children_data:
                child_item, child_created = MenuItem.objects.using(db_alias).get_or_create(
                    nombre=child_data['nombre'],
                    parent=parent_item,
                    defaults=child_data
                )
                if child_created:
                    print(f"  - Creado submenú: {child_data['nombre']}")

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_customuser_ai_provider_and_more'),
    ]

    operations = [
        migrations.RunPython(create_initial_menu_items),
    ]