# Generated by Django 5.2.6 on 2025-10-13 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_seed_initial_data"),
    ]

    operations = [
        migrations.CreateModel(
            name="Producto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("descripcion", models.TextField(blank=True, null=True)),
                ("precio", models.DecimalField(decimal_places=2, max_digits=10)),
                ("activo", models.BooleanField(default=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "prestador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="productos",
                        to="api.prestadorservicio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Producto",
                "verbose_name_plural": "Productos",
                "ordering": ["-fecha_creacion"],
            },
        ),
        migrations.CreateModel(
            name="RegistroCliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pais_origen", models.CharField(max_length=100)),
                ("cantidad", models.PositiveIntegerField(default=1)),
                ("fecha_registro", models.DateField()),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                (
                    "prestador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registros_clientes",
                        to="api.prestadorservicio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro de Cliente",
                "verbose_name_plural": "Registros de Clientes",
                "ordering": ["-fecha_registro"],
            },
        ),
    ]
