# Generated by Django 5.2.6 on 2025-10-13 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0014_vacante"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Super Administrador"),
                    ("ADMIN_DEPARTAMENTAL", "Admin Entidad Departamental"),
                    ("ADMIN_MUNICIPAL", "Admin Entidad Municipal"),
                    ("FUNCIONARIO_DIRECTIVO", "Funcionario Directivo"),
                    ("FUNCIONARIO_PROFESIONAL", "Funcionario Profesional"),
                    ("PRESTADOR", "Prestador de Servicio"),
                    ("ARTESANO", "Artesano"),
                    ("CONSEJO_CONSULTIVO_TURISMO", "Consejo Consultivo de Turismo"),
                    ("TURISTA", "Turista"),
                ],
                max_length=50,
                verbose_name="Rol",
            ),
        ),
    ]
