# Generated by Django 5.2.6 on 2025-10-14 00:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0015_alter_customuser_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Entity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(unique=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("municipal", "Municipal"),
                            ("departamental", "Departamental"),
                            ("nacional", "Nacional"),
                        ],
                        max_length=20,
                    ),
                ),
                ("logo", models.URLField(blank=True, null=True)),
                ("primary_color", models.CharField(default="#0070f3", max_length=7)),
                ("settings", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Super Administrador"),
                    ("ADMIN_ENTIDAD", "Admin de Entidad"),
                    ("ADMIN_DEPARTAMENTAL", "Admin Entidad Departamental"),
                    ("ADMIN_MUNICIPAL", "Admin Entidad Municipal"),
                    ("FUNCIONARIO_DIRECTIVO", "Funcionario Directivo"),
                    ("FUNCIONARIO_PROFESIONAL", "Funcionario Profesional"),
                    ("PRESTADOR", "Prestador de Servicio"),
                    ("ARTESANO", "Artesano"),
                    ("CONSEJO_CONSULTIVO_TURISMO", "Consejo Consultivo de Turismo"),
                    ("TURISTA", "Turista"),
                ],
                max_length=50,
                verbose_name="Rol",
            ),
        ),
        migrations.CreateModel(
            name="Municipality",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.department"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.department",
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.entity",
                    ),
                ),
                (
                    "municipality",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.municipality",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
