# Generated by Django 5.2.6 on 2025-10-14 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_department_entity_alter_customuser_role_municipality_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artesano',
            name='entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='artesanos', to='api.entity'),
        ),
        migrations.AddField(
            model_name='atractivoturistico',
            name='entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='atractivos', to='api.entity'),
        ),
        migrations.AddField(
            model_name='prestadorservicio',
            name='entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prestadores', to='api.entity'),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='publicaciones', to='api.entity'),
        ),
    ]
