# Generated by Django 5.2.6 on 2025-10-14 15:07

import api.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0017_artesano_entity_atractivoturistico_entity_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TipoDocumentoVerificacion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        help_text="Ej: RNT, Cámara de Comercio, etc.",
                        max_length=255,
                        unique=True,
                        verbose_name="Nombre del Documento",
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(
                        blank=True,
                        help_text="Explicación breve del documento.",
                        verbose_name="Descripción",
                    ),
                ),
                (
                    "requerido",
                    models.BooleanField(
                        default=True,
                        help_text="Indica si es obligatorio para la verificación del prestador.",
                        verbose_name="Requerido",
                    ),
                ),
                (
                    "activo",
                    models.BooleanField(
                        default=True,
                        help_text="Permite activar/desactivar tipos de documentos sin tocar el código.",
                        verbose_name="Activo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tipo de Documento de Verificación",
                "verbose_name_plural": "Tipos de Documentos de Verificación",
            },
        ),
        migrations.CreateModel(
            name="DocumentoVerificacion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "archivo",
                    models.FileField(
                        upload_to=api.models.documento_verificacion_path,
                        verbose_name="Archivo",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente de Verificación"),
                            ("APROBADO", "Aprobado"),
                            ("RECHAZADO", "Rechazado"),
                        ],
                        db_index=True,
                        default="PENDIENTE",
                        max_length=20,
                        verbose_name="Estado de Verificación",
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(
                        blank=True, verbose_name="Observaciones del Verificador"
                    ),
                ),
                (
                    "fecha_verificacion",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de Verificación"
                    ),
                ),
                ("fecha_subida", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "prestador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documentos_verificacion",
                        to="api.prestadorservicio",
                    ),
                ),
                (
                    "verificado_por",
                    models.ForeignKey(
                        blank=True,
                        help_text="El administrador (de entidad o súper) que realizó la verificación.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documentos_verificados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tipo_documento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="documentos",
                        to="api.tipodocumentoverificacion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Documento de Verificación",
                "verbose_name_plural": "Documentos de Verificación",
                "ordering": ["-fecha_subida"],
            },
        ),
        migrations.DeleteModel(
            name="DocumentoLegalizacion",
        ),
    ]
