# Generated by Django 5.2.12 on 2026-03-15 13:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PredictiveScenario",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "probability",
                    models.FloatField(
                        help_text="Probabilidad de ocurrencia calculada (0-1)."
                    ),
                ),
                ("estimated_impact", models.CharField(max_length=100)),
                ("affected_nodes", models.JSONField(default=list)),
                ("attack_vector", models.CharField(max_length=100)),
                ("is_active_threat", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-probability"],
            },
        ),
        migrations.CreateModel(
            name="ThreatNode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "node_type",
                    models.CharField(
                        choices=[
                            ("ENDPOINT", "Endpoint de API"),
                            ("ROLE", "Rol de Usuario"),
                            ("AGENT", "Agente IA"),
                            ("UI_COMPONENT", "Componente de Interfaz"),
                            ("EXTERNAL_SERVICE", "Servicio Externo"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "risk_score",
                    models.FloatField(
                        default=0.0,
                        help_text="Puntuación de vulnerabilidad actual (0-1).",
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("is_critical", models.BooleanField(default=False)),
                ("last_observation", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="PDEGovernanceConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "prediction_threshold",
                    models.FloatField(
                        default=0.7,
                        help_text="Umbral de probabilidad para proponer endurecimiento.",
                    ),
                ),
                (
                    "is_autonomous_hardening_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Si es True, la IA aplica medidas L1 sin esperar aprobación.",
                    ),
                ),
                ("start_hour", models.IntegerField(default=0)),
                ("end_hour", models.IntegerField(default=23)),
                ("last_update", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PreventiveHardening",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("action_name", models.CharField(max_length=255)),
                ("explanation", models.TextField()),
                ("estimated_cost_operative", models.FloatField(default=0.0)),
                ("is_applied", models.BooleanField(default=False)),
                ("applied_at", models.DateTimeField(blank=True, null=True)),
                (
                    "expiry_at",
                    models.DateTimeField(help_text="Cuándo revertir automáticamente."),
                ),
                ("config_override", models.JSONField(default=dict)),
                (
                    "scenario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hardening_actions",
                        to="defense_predictive.predictivescenario",
                    ),
                ),
                (
                    "target_node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="defense_predictive.threatnode",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ThreatEdge",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "edge_type",
                    models.CharField(
                        help_text="Ej: DEPENDS_ON, HAS_ACCESS, AUTH_REQUIRED",
                        max_length=100,
                    ),
                ),
                ("exposure_level", models.FloatField(default=0.1)),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_edges",
                        to="defense_predictive.threatnode",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_edges",
                        to="defense_predictive.threatnode",
                    ),
                ),
            ],
            options={
                "unique_together": {("source", "target", "edge_type")},
            },
        ),
    ]
