# Generated by Django 5.2.6 on 2026-02-05 07:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("defense_predictive", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PDEGovernanceConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "prediction_threshold",
                    models.FloatField(
                        default=0.7,
                        help_text="Umbral de probabilidad para proponer endurecimiento.",
                    ),
                ),
                (
                    "is_autonomous_hardening_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Si es True, la IA aplica medidas L1 sin esperar aprobación.",
                    ),
                ),
                ("start_hour", models.IntegerField(default=0)),
                ("end_hour", models.IntegerField(default=23)),
                ("last_update", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
