# Generated by Django 5.2.6 on 2025-10-19 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_resena_respuesta_prestador"),
        ("prestadores", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=150)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("telefono", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "notas",
                    models.TextField(
                        blank=True,
                        help_text="Notas internas sobre el cliente.",
                        null=True,
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                (
                    "prestador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clientes_crm",
                        to="api.prestadorservicio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cliente (CRM)",
                "verbose_name_plural": "Clientes (CRM)",
                "db_table": "empresa_cliente",
                "ordering": ["nombre"],
                "unique_together": {("prestador", "email")},
            },
        ),
    ]
