# Generated by Django 5.2.6 on 2025-10-15 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Producto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("descripcion", models.TextField(blank=True, null=True)),
                ("precio", models.DecimalField(decimal_places=2, max_digits=10)),
                ("activo", models.BooleanField(default=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "prestador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="productos",
                        to="api.prestadorservicio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Producto",
                "verbose_name_plural": "Productos",
                "ordering": ["-fecha_creacion"],
            },
        ),
        migrations.CreateModel(
            name="RegistroCliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pais_origen", models.CharField(max_length=100)),
                ("cantidad", models.PositiveIntegerField(default=1)),
                ("fecha_registro", models.DateField()),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                (
                    "prestador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registros_clientes",
                        to="api.prestadorservicio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro de Cliente",
                "verbose_name_plural": "Registros de Clientes",
                "ordering": ["-fecha_registro"],
            },
        ),
        migrations.CreateModel(
            name="Vacante",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "titulo",
                    models.CharField(
                        max_length=200, verbose_name="Título de la Vacante"
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(verbose_name="Descripción del Puesto"),
                ),
                (
                    "tipo_contrato",
                    models.CharField(
                        choices=[
                            ("TIEMPO_COMPLETO", "Tiempo Completo"),
                            ("MEDIO_TIEMPO", "Medio Tiempo"),
                            ("POR_HORAS", "Por Horas"),
                            ("TEMPORAL", "Temporal"),
                            ("PRACTICAS", "Prácticas / Pasantía"),
                        ],
                        max_length=50,
                        verbose_name="Tipo de Contrato",
                    ),
                ),
                (
                    "ubicacion",
                    models.CharField(
                        help_text="Ej: 'Puerto Gaitán, Meta' o 'Remoto'",
                        max_length=255,
                        verbose_name="Ubicación",
                    ),
                ),
                (
                    "salario",
                    models.CharField(
                        blank=True,
                        help_text="Ej: '$2.000.000 - $2.500.000 COP' o 'A convenir'",
                        max_length=150,
                        null=True,
                        verbose_name="Salario o Rango Salarial",
                    ),
                ),
                ("fecha_publicacion", models.DateTimeField(auto_now_add=True)),
                (
                    "fecha_vencimiento",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de Vencimiento"
                    ),
                ),
                (
                    "activa",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Vacante Activa"
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vacantes",
                        to="api.prestadorservicio",
                        verbose_name="Empresa Ofertante",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vacante de Empleo",
                "verbose_name_plural": "Vacantes de Empleo",
                "ordering": ["-fecha_publicacion"],
            },
        ),
    ]
