# Generated by Django 5.2.6 on 2025-10-15 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_delete_detalleshotel"),
        ("empresa", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Costo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "concepto",
                    models.CharField(max_length=255, verbose_name="Concepto del Costo"),
                ),
                (
                    "monto",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Monto"
                    ),
                ),
                ("fecha", models.DateField(verbose_name="Fecha del Costo")),
                (
                    "es_recurrente",
                    models.BooleanField(default=False, verbose_name="¿Es Recurrente?"),
                ),
                (
                    "tipo_costo",
                    models.CharField(
                        choices=[("FIJO", "Fijo"), ("VARIABLE", "Variable")],
                        default="VARIABLE",
                        max_length=50,
                        verbose_name="Tipo de Costo",
                    ),
                ),
                (
                    "prestador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="costos",
                        to="api.prestadorservicio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Costo Operativo",
                "verbose_name_plural": "Costos Operativos",
                "ordering": ["-fecha"],
            },
        ),
        migrations.CreateModel(
            name="Inventario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre_item",
                    models.CharField(max_length=255, verbose_name="Nombre del Ítem"),
                ),
                (
                    "descripcion",
                    models.TextField(blank=True, null=True, verbose_name="Descripción"),
                ),
                (
                    "cantidad",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Cantidad Disponible"
                    ),
                ),
                (
                    "unidad",
                    models.CharField(
                        help_text="Ej: unidades, kg, litros",
                        max_length=50,
                        verbose_name="Unidad de Medida",
                    ),
                ),
                (
                    "punto_reorden",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Cantidad mínima antes de necesitar reabastecimiento",
                        verbose_name="Punto de Reorden",
                    ),
                ),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "prestador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventarios",
                        to="api.prestadorservicio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ítem de Inventario",
                "verbose_name_plural": "Ítems de Inventario",
                "ordering": ["nombre_item"],
            },
        ),
        migrations.CreateModel(
            name="Recurso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(max_length=200, verbose_name="Nombre del Recurso"),
                ),
                (
                    "tipo_recurso",
                    models.CharField(
                        choices=[
                            ("HUMANO", "Humano"),
                            ("LOGISTICO", "Logístico"),
                            ("TECNOLOGICO", "Tecnológico"),
                        ],
                        max_length=50,
                        verbose_name="Tipo de Recurso",
                    ),
                ),
                ("disponible", models.BooleanField(default=True)),
                (
                    "prestador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recursos",
                        to="api.prestadorservicio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Recurso",
                "verbose_name_plural": "Recursos",
            },
        ),
        migrations.CreateModel(
            name="ReglaPrecio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre_regla",
                    models.CharField(max_length=200, verbose_name="Nombre de la Regla"),
                ),
                (
                    "tipo_ajuste",
                    models.CharField(
                        choices=[
                            ("PORCENTAJE", "Porcentaje"),
                            ("MONTO_FIJO", "Monto Fijo"),
                        ],
                        max_length=50,
                        verbose_name="Tipo de Ajuste",
                    ),
                ),
                (
                    "valor_ajuste",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Valor del Ajuste"
                    ),
                ),
                ("fecha_inicio", models.DateField(verbose_name="Fecha de Inicio")),
                ("fecha_fin", models.DateField(verbose_name="Fecha de Fin")),
                ("activa", models.BooleanField(default=True)),
                (
                    "prestador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reglas_precio",
                        to="api.prestadorservicio",
                    ),
                ),
                (
                    "producto_asociado",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reglas_precio",
                        to="empresa.producto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Regla de Precio",
                "verbose_name_plural": "Reglas de Precios",
            },
        ),
    ]
