# Generated by Django 5.2.6 on 2025-10-16 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("empresa", "0003_cliente"),
    ]

    operations = [
        migrations.DeleteModel(
            name="RegistroCliente",
        ),
    ]
