# Generated by Django 5.2.6 on 2025-10-19 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("empresa", "0004_delete_registrocliente"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reglaprecio",
            name="producto_asociado",
        ),
        migrations.RemoveField(
            model_name="reglaprecio",
            name="prestador",
        ),
        migrations.DeleteModel(
            name="Producto",
        ),
        migrations.DeleteModel(
            name="ReglaPrecio",
        ),
    ]
