# Generated by Django 5.2.6 on 2025-10-19 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("empresa", "0005_remove_reglaprecio_producto_asociado_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="cliente",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="cliente",
            name="prestador",
        ),
    ]
