# Generated by Django 5.2.6 on 2025-10-19 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("empresa", "0006_alter_cliente_unique_together_and_more"),
        ("turismo", "0002_alter_reserva_cliente"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Cliente",
        ),
    ]
