# Generated by Django 5.2.12 on 2026-03-15 13:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AutonomousAction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "domain",
                    models.CharField(
                        choices=[
                            ("COMERCIAL", "Comercial"),
                            ("CONTABLE", "Contable"),
                            ("FINANCIERO", "Financiero"),
                            ("OPERATIVO", "Operativo"),
                            ("ARCHIVISTICO", "Archivístico"),
                            ("GOBERNANZA", "Gobernanza"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "autonomy_level",
                    models.IntegerField(
                        choices=[
                            (0, "Manual"),
                            (1, "Asistida"),
                            (2, "Autónoma Condicionada"),
                            (3, "Autónoma Soberana (BLOQUEADO)"),
                        ],
                        default=0,
                    ),
                ),
                ("max_daily_executions", models.IntegerField(default=5)),
                (
                    "max_financial_impact",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "policy_reference",
                    models.CharField(
                        help_text="Referencia a la política legal/técnica",
                        max_length=255,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PerformanceMetric",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "domain",
                    models.CharField(
                        choices=[
                            ("COMERCIAL", "Comercial"),
                            ("CONTABLE", "Contable"),
                            ("FINANCIERO", "Financiero"),
                            ("OPERATIVO", "Operativo"),
                            ("ARCHIVISTICO", "Archivístico"),
                            ("GOBERNANZA", "Gobernanza"),
                        ],
                        max_length=50,
                    ),
                ),
                ("metric_name", models.CharField(max_length=100)),
                ("value", models.FloatField()),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="AutonomousExecutionLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "explanation",
                    models.TextField(
                        help_text="Explicación en lenguaje humano de por qué se ejecutó."
                    ),
                ),
                (
                    "data_points",
                    models.JSONField(help_text="Datos que justificaron la decisión."),
                ),
                ("policy_applied", models.TextField()),
                ("result_status", models.CharField(max_length=50)),
                ("impact_measured", models.JSONField(blank=True, null=True)),
                ("was_interrupted", models.BooleanField(default=False)),
                (
                    "action",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="executions",
                        to="ecosystem_optimization.autonomousaction",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="AutonomyControl",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "control_type",
                    models.CharField(
                        choices=[
                            ("TECHNICAL", "Técnico"),
                            ("LEGAL", "Legal/Normativo"),
                            ("OPERATIVE", "Operativo"),
                        ],
                        default="TECHNICAL",
                        max_length=20,
                    ),
                ),
                (
                    "domain",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("COMERCIAL", "Comercial"),
                            ("CONTABLE", "Contable"),
                            ("FINANCIERO", "Financiero"),
                            ("OPERATIVO", "Operativo"),
                            ("ARCHIVISTICO", "Archivístico"),
                            ("GOBERNANZA", "Gobernanza"),
                        ],
                        help_text="Nulo para control Global",
                        max_length=50,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Si es Falso, actúa como Kill Switch activado.",
                    ),
                ),
                ("last_update", models.DateTimeField(auto_now=True)),
                ("reason", models.TextField(blank=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OptimizationProposal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "domain",
                    models.CharField(
                        choices=[
                            ("COMERCIAL", "Comercial"),
                            ("CONTABLE", "Contable"),
                            ("FINANCIERO", "Financiero"),
                            ("OPERATIVO", "Operativo"),
                            ("ARCHIVISTICO", "Archivístico"),
                            ("GOBERNANZA", "Gobernanza"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PROPOSED", "Propuesta"),
                            ("APPROVED", "Aprobada"),
                            ("REJECTED", "Rechazada"),
                            ("EXECUTED", "Ejecutada"),
                            ("REVERTED", "Revertida"),
                        ],
                        default="PROPOSED",
                        max_length=20,
                    ),
                ),
                (
                    "hallazgo",
                    models.TextField(
                        help_text="Patrón detectado que justifica la optimización."
                    ),
                ),
                (
                    "propuesta_ajuste",
                    models.TextField(
                        help_text="Descripción técnica del ajuste sugerido."
                    ),
                ),
                (
                    "parametros_cambio",
                    models.JSONField(
                        help_text="Valores técnicos a modificar (ej: {'threshold': 0.85})."
                    ),
                ),
                ("impacto_esperado", models.TextField()),
                (
                    "config_previa",
                    models.JSONField(
                        help_text="Snapshot de la configuración antes del cambio."
                    ),
                ),
                ("justificacion_admin", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "decidida_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Propuesta de Optimización",
                "verbose_name_plural": "Propuestas de Optimización",
            },
        ),
        migrations.CreateModel(
            name="OptimizationAuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("accion", models.CharField(max_length=50)),
                ("detalles", models.JSONField(default=dict)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "proposal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs",
                        to="ecosystem_optimization.optimizationproposal",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
    ]
