# Generated by Django 5.2.10 on 2026-01-29 23:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OptimizationProposal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "domain",
                    models.CharField(
                        choices=[
                            ("COMERCIAL", "Comercial"),
                            ("CONTABLE", "Contable"),
                            ("FINANCIERO", "Financiero"),
                            ("OPERATIVO", "Operativo"),
                            ("ARCHIVISTICO", "Archivístico"),
                            ("GOBERNANZA", "Gobernanza"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PROPOSED", "Propuesta"),
                            ("APPROVED", "Aprobada"),
                            ("REJECTED", "Rechazada"),
                            ("EXECUTED", "Ejecutada"),
                            ("REVERTED", "Revertida"),
                        ],
                        default="PROPOSED",
                        max_length=20,
                    ),
                ),
                (
                    "hallazgo",
                    models.TextField(
                        help_text="Patrón detectado que justifica la optimización."
                    ),
                ),
                (
                    "propuesta_ajuste",
                    models.TextField(
                        help_text="Descripción técnica del ajuste sugerido."
                    ),
                ),
                (
                    "parametros_cambio",
                    models.JSONField(
                        help_text="Valores técnicos a modificar (ej: {'threshold': 0.85})."
                    ),
                ),
                ("impacto_esperado", models.TextField()),
                (
                    "config_previa",
                    models.JSONField(
                        help_text="Snapshot de la configuración antes del cambio."
                    ),
                ),
                ("justificacion_admin", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "decidida_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Propuesta de Optimización",
                "verbose_name_plural": "Propuestas de Optimización",
            },
        ),
        migrations.CreateModel(
            name="OptimizationAuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("accion", models.CharField(max_length=50)),
                ("detalles", models.JSONField(default=dict)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "proposal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs",
                        to="ecosystem_optimization.optimizationproposal",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="PerformanceMetric",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "domain",
                    models.CharField(
                        choices=[
                            ("COMERCIAL", "Comercial"),
                            ("CONTABLE", "Contable"),
                            ("FINANCIERO", "Financiero"),
                            ("OPERATIVO", "Operativo"),
                            ("ARCHIVISTICO", "Archivístico"),
                            ("GOBERNANZA", "Gobernanza"),
                        ],
                        max_length=50,
                    ),
                ),
                ("metric_name", models.CharField(max_length=100)),
                ("value", models.FloatField()),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["domain", "metric_name"],
                        name="ecosystem_o_domain_b62745_idx",
                    )
                ],
            },
        ),
    ]
