# Generated by Django 5.2.6 on 2026-02-03 03:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecosystem_optimization", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AutonomousAction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "domain",
                    models.CharField(
                        choices=[
                            ("COMERCIAL", "Comercial"),
                            ("CONTABLE", "Contable"),
                            ("FINANCIERO", "Financiero"),
                            ("OPERATIVO", "Operativo"),
                            ("ARCHIVISTICO", "Archivístico"),
                            ("GOBERNANZA", "Gobernanza"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "autonomy_level",
                    models.IntegerField(
                        choices=[
                            (0, "Manual"),
                            (1, "Asistida"),
                            (2, "Autónoma Condicionada"),
                            (3, "Autónoma Soberana (BLOQUEADO)"),
                        ],
                        default=0,
                    ),
                ),
                ("max_daily_executions", models.IntegerField(default=5)),
                (
                    "max_financial_impact",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "policy_reference",
                    models.CharField(
                        help_text="Referencia a la política legal/técnica",
                        max_length=255,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AutonomousExecutionLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "explanation",
                    models.TextField(
                        help_text="Explicación en lenguaje humano de por qué se ejecutó."
                    ),
                ),
                (
                    "data_points",
                    models.JSONField(help_text="Datos que justificaron la decisión."),
                ),
                ("policy_applied", models.TextField()),
                ("result_status", models.CharField(max_length=50)),
                ("impact_measured", models.JSONField(blank=True, null=True)),
                ("was_interrupted", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="AutonomyControl",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "domain",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("COMERCIAL", "Comercial"),
                            ("CONTABLE", "Contable"),
                            ("FINANCIERO", "Financiero"),
                            ("OPERATIVO", "Operativo"),
                            ("ARCHIVISTICO", "Archivístico"),
                            ("GOBERNANZA", "Gobernanza"),
                        ],
                        help_text="Nulo para control Global",
                        max_length=50,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Si es Falso, actúa como Kill Switch activado.",
                    ),
                ),
                ("last_update", models.DateTimeField(auto_now=True)),
                ("reason", models.TextField(blank=True)),
            ],
        ),
        migrations.RemoveIndex(
            model_name="performancemetric",
            name="ecosystem_o_domain_b62745_idx",
        ),
        migrations.AddField(
            model_name="autonomousexecutionlog",
            name="action",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="executions",
                to="ecosystem_optimization.autonomousaction",
            ),
        ),
        migrations.AddField(
            model_name="autonomycontrol",
            name="updated_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
