# Generated by Django 5.2.6 on 2026-02-03 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "ecosystem_optimization",
            "0002_autonomousaction_autonomousexecutionlog_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="autonomycontrol",
            name="control_type",
            field=models.CharField(
                choices=[
                    ("TECHNICAL", "Técnico"),
                    ("LEGAL", "Legal/Normativo"),
                    ("OPERATIVE", "Operativo"),
                ],
                default="TECHNICAL",
                max_length=20,
            ),
        ),
    ]
