apiVersion: v1
kind: Service
metadata:
  name: sarita-backend-svc
spec:
  selector:
    app: sarita
    tier: backend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: sarita-frontend-svc
spec:
  selector:
    app: sarita
    tier: frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: LoadBalancer
