# Generated by Django 5.2.6 on 2026-01-22 19:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("companies", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("username", models.CharField(max_length=150)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("USER_LOGIN_SUCCESS", "Inicio de sesión exitoso"),
                            (
                                "USER_LOGIN_FAILED",
                                "Intento de inicio de sesión fallido",
                            ),
                            ("DOCUMENT_CREATED", "Creó concepto de documento"),
                            ("VERSION_UPLOADED", "Subió nueva versión"),
                            ("VERSION_DOWNLOADED", "Descargó versión"),
                            ("VERSION_DELETED", "Eliminó versión"),
                            ("VERSION_VERIFIED", "Verificó integridad de versión"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("details", models.JSONField(default=dict)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="companies.company",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Log Entry",
                "verbose_name_plural": "Audit Log",
                "ordering": ["-timestamp"],
            },
        ),
    ]
