# Generated by Django 5.2.12 on 2026-03-15 13:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("companies", "0001_full_reset"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PublicSystemAudit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("domain", models.CharField(max_length=50)),
                ("function_name", models.CharField(max_length=100)),
                ("impact_summary", models.TextField()),
                ("compliance_score", models.FloatField(default=1.0)),
                ("is_human_reviewed", models.BooleanField(default=False)),
                (
                    "technical_trace_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("username", models.CharField(max_length=150)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("USER_LOGIN_SUCCESS", "Inicio de sesión exitoso"),
                            (
                                "USER_LOGIN_FAILED",
                                "Intento de inicio de sesión fallido",
                            ),
                            ("DOCUMENT_CREATED", "Creó concepto de documento"),
                            ("VERSION_UPLOADED", "Subió nueva versión"),
                            ("VERSION_DOWNLOADED", "Descargó versión"),
                            ("VERSION_DELETED", "Eliminó versión"),
                            ("VERSION_VERIFIED", "Verificó integridad de versión"),
                            ("SALE_CREATED", "Operación comercial iniciada"),
                            ("SALE_CONFIRMED", "Operación comercial confirmada"),
                            ("INVOICE_GENERATED", "Factura de venta generada"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("details", models.JSONField(default=dict)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="companies.company",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Log Entry",
                "verbose_name_plural": "Audit Log",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="ForensicSecurityLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("source_ip", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "threat_level",
                    models.CharField(
                        choices=[
                            ("LOW", "Baja"),
                            ("MEDIUM", "Media"),
                            ("HIGH", "Alta"),
                            ("CRITICAL", "Crítica (Amenaza Activa)"),
                        ],
                        default="LOW",
                        max_length=20,
                    ),
                ),
                ("attack_vector", models.CharField(max_length=100)),
                ("payload_captured", models.JSONField()),
                ("headers_captured", models.JSONField()),
                ("action_taken", models.CharField(max_length=255)),
                (
                    "previous_hash",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "integrity_hash",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="FraudEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_type", models.CharField(max_length=100)),
                ("score", models.IntegerField()),
                ("ip_address", models.GenericIPAddressField()),
                ("metadata", models.JSONField(default=dict)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="SystemAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=255)),
                ("entity", models.CharField(max_length=100)),
                ("entity_id", models.CharField(max_length=255)),
                ("ip_address", models.GenericIPAddressField()),
                ("old_values", models.JSONField(blank=True, null=True)),
                ("new_values", models.JSONField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
    ]
