# Generated by Django 5.2.6 on 2026-02-04 23:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ForensicSecurityLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("source_ip", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "threat_level",
                    models.CharField(
                        choices=[
                            ("LOW", "Baja"),
                            ("MEDIUM", "Media"),
                            ("HIGH", "Alta"),
                            ("CRITICAL", "Crítica (Amenaza Activa)"),
                        ],
                        default="LOW",
                        max_length=20,
                    ),
                ),
                (
                    "attack_vector",
                    models.CharField(
                        help_text="Ej: XSS_ATTEMPT, BRUTE_FORCE, GOVERNANCE_BYPASS",
                        max_length=100,
                    ),
                ),
                (
                    "payload_captured",
                    models.JSONField(
                        help_text="Cuerpo de la petición o parámetros sospechosos."
                    ),
                ),
                (
                    "headers_captured",
                    models.JSONField(
                        help_text="Headers HTTP de la petición maliciosa."
                    ),
                ),
                (
                    "action_taken",
                    models.CharField(
                        help_text="Ej: SESSION_QUARANTINE, TOKEN_INVALIDATED",
                        max_length=255,
                    ),
                ),
                (
                    "previous_hash",
                    models.CharField(
                        blank=True,
                        help_text="Hash de la entrada anterior para asegurar la integridad de la cadena.",
                        max_length=64,
                        null=True,
                    ),
                ),
                (
                    "integrity_hash",
                    models.CharField(
                        blank=True,
                        help_text="Hash SHA-256 para prevenir alteración forense.",
                        max_length=64,
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Forensic Security Log",
                "verbose_name_plural": "Forensic Security Logs",
                "ordering": ["-timestamp"],
            },
        ),
    ]
