# Generated by Django 5.2.6 on 2026-02-05 23:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0002_forensicsecuritylog"),
    ]

    operations = [
        migrations.CreateModel(
            name="PublicSystemAudit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "domain",
                    models.CharField(
                        help_text="Ej: Hacienda, Planeación, Salud", max_length=50
                    ),
                ),
                (
                    "function_name",
                    models.CharField(
                        help_text="Nombre de la función pública asistida",
                        max_length=100,
                    ),
                ),
                (
                    "impact_summary",
                    models.TextField(
                        help_text="Descripción del impacto social o administrativo"
                    ),
                ),
                (
                    "compliance_score",
                    models.FloatField(
                        default=1.0,
                        help_text="Índice de cumplimiento normativo (0.0 a 1.0)",
                    ),
                ),
                ("is_human_reviewed", models.BooleanField(default=False)),
                (
                    "technical_trace_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
            options={
                "verbose_name": "Public System Audit Entry",
                "verbose_name_plural": "Public System Audit",
                "ordering": ["-timestamp"],
            },
        ),
    ]
