# Generated by Django 5.2.6 on 2026-02-08 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0003_publicsystemaudit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("USER_LOGIN_SUCCESS", "Inicio de sesión exitoso"),
                    ("USER_LOGIN_FAILED", "Intento de inicio de sesión fallido"),
                    ("DOCUMENT_CREATED", "Creó concepto de documento"),
                    ("VERSION_UPLOADED", "Subió nueva versión"),
                    ("VERSION_DOWNLOADED", "Descargó versión"),
                    ("VERSION_DELETED", "Eliminó versión"),
                    ("VERSION_VERIFIED", "Verificó integridad de versión"),
                    ("SALE_CREATED", "Operación comercial iniciada"),
                    ("SALE_CONFIRMED", "Operación comercial confirmada"),
                    ("INVOICE_GENERATED", "Factura de venta generada"),
                ],
                db_index=True,
                max_length=50,
            ),
        ),
    ]
