# Generated by Django 5.2.6 on 2025-11-01 19:24

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("api", "0002_plantillaverificacion_categoria_prestador"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoriaPrestador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=100,
                        unique=True,
                        verbose_name="Nombre de la Categoría",
                    ),
                ),
                (
                    "nombre_es",
                    models.CharField(
                        max_length=100,
                        null=True,
                        unique=True,
                        verbose_name="Nombre de la Categoría",
                    ),
                ),
                (
                    "nombre_en",
                    models.CharField(
                        max_length=100,
                        null=True,
                        unique=True,
                        verbose_name="Nombre de la Categoría",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="Slug auto-generado para URLs amigables.",
                        max_length=120,
                        unique=True,
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
            ],
            options={
                "verbose_name": "Categoría de Prestador",
                "verbose_name_plural": "Categorías de Prestadores",
            },
        ),
        migrations.CreateModel(
            name="Perfil",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre_comercial",
                    models.CharField(max_length=255, verbose_name="Nombre Comercial"),
                ),
                (
                    "nit",
                    models.CharField(max_length=20, unique=True, verbose_name="NIT"),
                ),
                (
                    "razon_social",
                    models.CharField(max_length=255, verbose_name="Razón Social"),
                ),
                (
                    "direccion",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Dirección"
                    ),
                ),
                (
                    "puntuacion_calidad",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=3
                    ),
                ),
                (
                    "puntuacion_servicio",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=3
                    ),
                ),
                (
                    "puntuacion_precio",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=3
                    ),
                ),
                (
                    "puntuacion_total",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        editable=False,
                        max_digits=3,
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "categoria",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="perfiles",
                        to="mi_negocio.categoriaprestador",
                        verbose_name="Categoría del Prestador",
                    ),
                ),
                (
                    "departamento",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.department",
                        verbose_name="Departamento",
                    ),
                ),
                (
                    "municipio",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.municipality",
                        verbose_name="Municipio",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="perfil_prestador",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario Asociado",
                    ),
                ),
            ],
            options={
                "verbose_name": "Perfil de Prestador",
                "verbose_name_plural": "Perfiles de Prestadores",
                "ordering": ["nombre_comercial"],
            },
        ),
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(max_length=255, verbose_name="Nombre completo"),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Correo Electrónico",
                    ),
                ),
                (
                    "telefono",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Teléfono"
                    ),
                ),
                (
                    "perfil",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clientes_crm",
                        to="mi_negocio.perfil",
                        verbose_name="Perfil del Prestador",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cliente (CRM)",
                "verbose_name_plural": "Clientes (CRM)",
                "ordering": ["nombre"],
                "unique_together": {("perfil", "email")},
            },
        ),
    ]
