# Generated by Django 6.0.3 on 2026-03-23 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("prestadores", "0001_full_reset"),
    ]

    operations = [
        migrations.CreateModel(
            name="SitioTuristico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=150)),
                ("descripcion_corta", models.CharField(max_length=255)),
                ("descripcion_larga", models.TextField()),
                (
                    "tipo_sitio",
                    models.CharField(
                        choices=[
                            ("parque_tematico", "Parque Temático"),
                            ("reserva_natural", "Reserva Natural"),
                            ("museo", "Museo"),
                            ("centro_cultural", "Centro Cultural"),
                            ("mirador", "Mirador"),
                            ("finca_agroturistica", "Finca Agroturística"),
                            ("otro", "Otro"),
                        ],
                        default="otro",
                        max_length=30,
                    ),
                ),
                ("ubicacion_latitud", models.FloatField(blank=True, null=True)),
                ("ubicacion_longitud", models.FloatField(blank=True, null=True)),
                (
                    "direccion_texto",
                    models.CharField(
                        blank=True,
                        help_text="Dirección o indicaciones de cómo llegar.",
                        max_length=255,
                    ),
                ),
                ("horario_apertura", models.TimeField(blank=True, null=True)),
                ("horario_cierre", models.TimeField(blank=True, null=True)),
                (
                    "dias_operacion",
                    models.CharField(
                        blank=True,
                        help_text="Ej: Lunes a Viernes, Fines de semana",
                        max_length=100,
                    ),
                ),
                (
                    "precio_entrada_adulto",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "precio_entrada_nino",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "activo",
                    models.BooleanField(
                        default=True,
                        help_text="Indica si el sitio está abierto al público.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "perfil",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sitios_turisticos",
                        to="prestadores.providerprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ActividadEnSitio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("descripcion", models.TextField()),
                (
                    "duracion_estimada_minutos",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "precio_adicional",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Costo adicional a la entrada del sitio.",
                        max_digits=10,
                    ),
                ),
                ("requiere_reserva", models.BooleanField(default=False)),
                (
                    "sitio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actividades",
                        to="sitios_turisticos.sitioturistico",
                    ),
                ),
            ],
        ),
    ]
