# Generated by Django 5.2.6 on 2025-10-23 14:38

import apps.prestadores.mi_negocio.gestion_operativa.modulos_genericos.rat
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoriaPrestador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, unique=True)),
                (
                    "slug",
                    models.SlugField(
                        help_text="Versión del nombre amigable para URLs",
                        max_length=100,
                        unique=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Categoría de Prestador",
                "verbose_name_plural": "Categorías de Prestadores",
            },
        ),
        migrations.CreateModel(
            name="CategoriaProductoArtesanal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, unique=True)),
                ("descripcion", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Checklist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="FormularioDinamico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="CampoFormulario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("etiqueta", models.CharField(max_length=100)),
                ("tipo_campo", models.CharField(max_length=50)),
                (
                    "formulario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="campos",
                        to="prestadores.formulariodinamico",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ItemChecklist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("texto", models.CharField(max_length=255)),
                (
                    "checklist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="prestadores.checklist",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Perfil",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre_comercial",
                    models.CharField(max_length=255, verbose_name="Nombre Comercial"),
                ),
                ("telefono_principal", models.CharField(blank=True, max_length=50)),
                ("email_comercial", models.EmailField(blank=True, max_length=255)),
                ("direccion", models.CharField(blank=True, max_length=255)),
                (
                    "latitud",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                (
                    "longitud",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                ("descripcion_corta", models.TextField(blank=True)),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="logos_prestadores/"
                    ),
                ),
                ("sitio_web", models.URLField(blank=True, max_length=255)),
                (
                    "redes_sociales",
                    models.JSONField(blank=True, default=dict, null=True),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("Pendiente", "Pendiente de Revisión"),
                            ("Activo", "Activo y Visible"),
                            ("Rechazado", "Rechazado"),
                            ("Inactivo", "Inactivo por el Usuario"),
                        ],
                        default="Pendiente",
                        max_length=20,
                    ),
                ),
                (
                    "puntuacion_verificacion",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Puntaje acumulado de verificaciones de cumplimiento.",
                    ),
                ),
                (
                    "puntuacion_capacitacion",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Puntaje acumulado por asistencia a capacitaciones.",
                    ),
                ),
                (
                    "puntuacion_reseñas",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Puntaje acumulado por reseñas de turistas.",
                    ),
                ),
                (
                    "puntuacion_formularios",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Puntaje por completar formularios de caracterización.",
                    ),
                ),
                (
                    "puntuacion_total",
                    models.PositiveIntegerField(
                        db_index=True,
                        default=0,
                        help_text="Puntaje total para posicionamiento. Se calcula automáticamente.",
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "categoria",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="prestadores.categoriaprestador",
                    ),
                ),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="perfil_prestador",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Perfil de Prestador",
                "verbose_name_plural": "Perfiles de Prestadores",
            },
        ),
        migrations.CreateModel(
            name="Pedido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_cliente", models.CharField(max_length=255)),
                ("direccion_envio", models.TextField()),
                ("fecha_pedido", models.DateTimeField(auto_now_add=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente de Pago"),
                            ("pagado", "Pagado"),
                            ("en_preparacion", "En Preparación"),
                            ("enviado", "Enviado"),
                            ("entregado", "Entregado"),
                            ("cancelado", "Cancelado"),
                        ],
                        default="pendiente",
                        max_length=20,
                    ),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "perfil",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pedidos",
                        to="prestadores.perfil",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Mesa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero",
                    models.CharField(
                        help_text="Número o nombre de la mesa (ej. 'Mesa 5', 'Ventanal')",
                        max_length=10,
                    ),
                ),
                ("capacidad", models.PositiveIntegerField()),
                (
                    "ubicacion",
                    models.CharField(
                        choices=[
                            ("salon", "Salón Principal"),
                            ("terraza", "Terraza / Exterior"),
                            ("barra", "Barra"),
                            ("privado", "Salón Privado"),
                        ],
                        default="salon",
                        max_length=50,
                    ),
                ),
                ("disponible", models.BooleanField(default=True)),
                (
                    "perfil",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mesas",
                        to="prestadores.perfil",
                    ),
                ),
            ],
            options={
                "unique_together": {("perfil", "numero")},
            },
        ),
        migrations.CreateModel(
            name="Inventario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_item", models.CharField(max_length=255)),
                ("cantidad", models.PositiveIntegerField()),
                (
                    "perfil",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventario",
                        to="prestadores.perfil",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Habitacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                (
                    "perfil",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="habitaciones",
                        to="prestadores.perfil",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Equipamiento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=150)),
                ("descripcion", models.TextField(blank=True, null=True)),
                ("cantidad_total", models.PositiveIntegerField()),
                ("cantidad_disponible", models.PositiveIntegerField()),
                (
                    "foto",
                    models.ImageField(
                        blank=True, null=True, upload_to="equipamiento_guias/"
                    ),
                ),
                (
                    "perfil",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="equipamientos",
                        to="prestadores.perfil",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Costo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descripcion", models.CharField(max_length=255)),
                ("monto", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "perfil",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="costos",
                        to="prestadores.perfil",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ConfiguracionPrestador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("recibir_notificaciones", models.BooleanField(default=True)),
                (
                    "perfil",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="configuracion",
                        to="prestadores.perfil",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Conductor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=150)),
                ("apellido", models.CharField(max_length=150)),
                ("cedula", models.CharField(max_length=20, unique=True)),
                ("telefono", models.CharField(max_length=20)),
                (
                    "foto",
                    models.ImageField(blank=True, null=True, upload_to="conductores/"),
                ),
                (
                    "licencia_conduccion",
                    models.CharField(help_text="Número de la licencia", max_length=50),
                ),
                ("vencimiento_licencia", models.DateField()),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        help_text="Opcional: vincular a una cuenta de usuario del sistema.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "perfil",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conductores",
                        to="prestadores.perfil",
                    ),
                ),
            ],
            options={
                "verbose_name": "Conductor",
                "verbose_name_plural": "Conductores",
                "ordering": ["apellido", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("telefono", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "perfil",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clientes",
                        to="prestadores.perfil",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CategoriaMenu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("descripcion", models.TextField(blank=True, null=True)),
                (
                    "perfil",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="menu_categorias",
                        to="prestadores.perfil",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductoArtesanal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                ("descripcion", models.TextField()),
                ("precio", models.DecimalField(decimal_places=2, max_digits=10)),
                ("stock", models.PositiveIntegerField(default=0)),
                (
                    "foto",
                    models.ImageField(
                        blank=True, null=True, upload_to="productos_artesanales/"
                    ),
                ),
                (
                    "materiales",
                    models.CharField(
                        blank=True,
                        help_text="Materiales principales (ej. 'Lana de oveja, tintes naturales')",
                        max_length=255,
                    ),
                ),
                (
                    "tecnica",
                    models.CharField(
                        blank=True,
                        help_text="Técnica de elaboración (ej. 'Tejido en telar vertical')",
                        max_length=255,
                    ),
                ),
                (
                    "categoria",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="prestadores.categoriaproductoartesanal",
                    ),
                ),
                (
                    "perfil",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="productos_artesanales",
                        to="prestadores.perfil",
                    ),
                ),
            ],
            options={
                "verbose_name": "Producto Artesanal",
                "verbose_name_plural": "Productos Artesanales",
            },
        ),
        migrations.CreateModel(
            name="DetallePedido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad", models.PositiveIntegerField()),
                (
                    "precio_unitario",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Precio al momento de la compra",
                        max_digits=10,
                    ),
                ),
                ("subtotal", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "pedido",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detalles",
                        to="prestadores.pedido",
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="prestadores.productoartesanal",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductoMenu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                ("descripcion", models.TextField()),
                ("precio", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "foto",
                    models.ImageField(
                        blank=True, null=True, upload_to="productos_menu/"
                    ),
                ),
                ("disponible", models.BooleanField(default=True)),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="productos",
                        to="prestadores.categoriamenu",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductoServicio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=255, verbose_name="Nombre del Producto/Servicio"
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(blank=True, null=True, verbose_name="Descripción"),
                ),
                (
                    "precio",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=12,
                        verbose_name="Precio",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("PRODUCTO", "Producto"), ("SERVICIO", "Servicio")],
                        default="PRODUCTO",
                        max_length=50,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "cantidad_disponible",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Para servicios, usualmente es 1 o se deja en blanco.",
                        verbose_name="Cantidad Disponible",
                    ),
                ),
                (
                    "unidad_medida",
                    models.CharField(
                        blank=True,
                        help_text="Ej: unidades, kg, horas, etc.",
                        max_length=50,
                        verbose_name="Unidad de Medida",
                    ),
                ),
                (
                    "activo",
                    models.BooleanField(
                        default=True,
                        help_text="Indica si el producto/servicio está disponible para la venta.",
                        verbose_name="Activo",
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "perfil",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="productos_servicios",
                        to="prestadores.perfil",
                    ),
                ),
            ],
            options={
                "verbose_name": "Producto o Servicio",
                "verbose_name_plural": "Productos y Servicios",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Puntuacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("puntuacion", models.IntegerField()),
                (
                    "perfil",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="puntuaciones",
                        to="prestadores.perfil",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RegistroActividadTuristica",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre_documento",
                    models.CharField(
                        max_length=255, verbose_name="Nombre del Documento o Registro"
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                (
                    "archivo",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=apps.prestadores.mi_negocio.gestion_operativa.modulos_genericos.rat.rat_directory_path,
                        verbose_name="Archivo Adjunto",
                    ),
                ),
                (
                    "fecha_presentacion",
                    models.DateField(verbose_name="Fecha de Presentación"),
                ),
                (
                    "entidad_reguladora",
                    models.CharField(
                        blank=True,
                        help_text="Ej: Ministerio de Turismo, DIAN, etc.",
                        max_length=255,
                        verbose_name="Entidad Reguladora",
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                (
                    "perfil",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registros_rat",
                        to="prestadores.perfil",
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro de Actividad Turística (RAT)",
                "verbose_name_plural": "Registros de Actividad Turística (RAT)",
                "ordering": ["-fecha_presentacion"],
            },
        ),
        migrations.CreateModel(
            name="Reporte",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_reporte", models.CharField(max_length=255)),
                ("datos", models.JSONField()),
                (
                    "perfil",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reportes",
                        to="prestadores.perfil",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Reserva",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_reserva", models.DateTimeField(auto_now_add=True)),
                ("nombre_cliente", models.CharField(max_length=255)),
                (
                    "perfil",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservas",
                        to="prestadores.perfil",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReservaMesa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_cliente", models.CharField(max_length=255)),
                (
                    "telefono_cliente",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("fecha_hora", models.DateTimeField()),
                ("numero_personas", models.PositiveIntegerField()),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("confirmada", "Confirmada"),
                            ("cancelada", "Cancelada"),
                            ("completada", "Completada"),
                            ("no_show", "No Asistió"),
                        ],
                        default="confirmada",
                        max_length=20,
                    ),
                ),
                ("notas", models.TextField(blank=True, null=True)),
                (
                    "mesa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservas",
                        to="prestadores.mesa",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RespuestaFormulario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("valor", models.TextField()),
                (
                    "campo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="prestadores.campoformulario",
                    ),
                ),
                (
                    "perfil",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="respuestas",
                        to="prestadores.perfil",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Ruta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                ("descripcion_corta", models.CharField(max_length=300)),
                ("descripcion_larga", models.TextField()),
                (
                    "duracion_horas",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Duración estimada en horas.",
                        max_digits=5,
                    ),
                ),
                (
                    "distancia_km",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Distancia total en kilómetros.",
                        max_digits=6,
                    ),
                ),
                (
                    "dificultad",
                    models.CharField(
                        choices=[
                            ("facil", "Fácil"),
                            ("moderada", "Moderada"),
                            ("dificil", "Difícil"),
                            ("experto", "Experto"),
                        ],
                        default="moderada",
                        max_length=20,
                    ),
                ),
                (
                    "precio_persona",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("punto_encuentro", models.CharField(max_length=255)),
                (
                    "foto_principal",
                    models.ImageField(
                        blank=True, null=True, upload_to="rutas_turisticas/"
                    ),
                ),
                (
                    "perfil",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rutas_turisticas",
                        to="prestadores.perfil",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HitoRuta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        help_text="Nombre del hito o parada (ej. 'Cascada La Chorrera')",
                        max_length=200,
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(
                        help_text="Descripción de lo que se hará o verá en este hito."
                    ),
                ),
                (
                    "orden",
                    models.PositiveIntegerField(
                        help_text="Orden secuencial del hito en la ruta."
                    ),
                ),
                (
                    "latitud",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitud",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "ruta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hitos",
                        to="prestadores.ruta",
                    ),
                ),
            ],
            options={
                "ordering": ["orden"],
            },
        ),
        migrations.CreateModel(
            name="ServicioAdicionalHotel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                (
                    "perfil",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="servicios_adicionales_hotel",
                        to="prestadores.perfil",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TicketSoporte",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("asunto", models.CharField(max_length=255)),
                ("mensaje", models.TextField()),
                ("resuelto", models.BooleanField(default=False)),
                (
                    "perfil",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tickets_soporte",
                        to="prestadores.perfil",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Vehiculo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("placa", models.CharField(max_length=10, unique=True)),
                ("marca", models.CharField(max_length=100)),
                ("modelo", models.CharField(max_length=100)),
                ("año", models.PositiveIntegerField()),
                ("capacidad_pasajeros", models.PositiveIntegerField()),
                (
                    "tipo_vehiculo",
                    models.CharField(
                        choices=[
                            ("automovil", "Automóvil"),
                            ("camioneta", "Camioneta / SUV"),
                            ("van", "Van / Microbús"),
                            ("bus", "Autobús"),
                            ("chiva", "Chiva / Bus Escalera"),
                            ("otro", "Otro"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "foto",
                    models.ImageField(
                        blank=True, null=True, upload_to="vehiculos_transporte/"
                    ),
                ),
                (
                    "soat_vigente",
                    models.BooleanField(
                        default=True, help_text="¿El SOAT está vigente?"
                    ),
                ),
                (
                    "tecnomecanica_vigente",
                    models.BooleanField(
                        default=True,
                        help_text="¿La revisión tecnomecánica está vigente?",
                    ),
                ),
                (
                    "perfil",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vehiculos",
                        to="prestadores.perfil",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vehículo",
                "verbose_name_plural": "Vehículos",
                "ordering": ["marca", "modelo"],
            },
        ),
        migrations.CreateModel(
            name="PaqueteTuristico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                ("descripcion", models.TextField()),
                ("duracion_dias", models.PositiveIntegerField(default=1)),
                (
                    "precio_base",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Precio base del paquete por persona.",
                        max_digits=12,
                    ),
                ),
                (
                    "foto_principal",
                    models.ImageField(
                        blank=True, null=True, upload_to="paquetes_turisticos/"
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
                (
                    "habitaciones_incluidas",
                    models.ManyToManyField(blank=True, to="prestadores.habitacion"),
                ),
                (
                    "perfil",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paquetes_turisticos",
                        to="prestadores.perfil",
                    ),
                ),
                (
                    "comidas_incluidas",
                    models.ManyToManyField(blank=True, to="prestadores.productomenu"),
                ),
                (
                    "rutas_incluidas",
                    models.ManyToManyField(blank=True, to="prestadores.ruta"),
                ),
                (
                    "transporte_incluido",
                    models.ManyToManyField(blank=True, to="prestadores.vehiculo"),
                ),
            ],
            options={
                "verbose_name": "Paquete Turístico",
                "verbose_name_plural": "Paquetes Turísticos",
            },
        ),
        migrations.CreateModel(
            name="Verificacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("verificado", models.BooleanField(default=False)),
                (
                    "perfil",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verificaciones",
                        to="prestadores.perfil",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Itinerario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dia",
                    models.PositiveIntegerField(
                        help_text="Número del día dentro del paquete (ej. 1, 2, 3...)"
                    ),
                ),
                (
                    "titulo_actividad",
                    models.CharField(
                        help_text="Título principal para el día (ej. 'Llegada y City Tour')",
                        max_length=255,
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(
                        help_text="Descripción detallada de las actividades del día."
                    ),
                ),
                (
                    "paquete",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itinerarios",
                        to="prestadores.paqueteturistico",
                    ),
                ),
            ],
            options={
                "verbose_name": "Itinerario",
                "verbose_name_plural": "Itinerarios",
                "ordering": ["dia"],
                "unique_together": {("paquete", "dia")},
            },
        ),
    ]
