# Generated by Django 5.2.6 on 2025-10-19 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("api", "0003_resena_respuesta_prestador"),
    ]

    operations = [
        migrations.CreateModel(
            name="Producto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("descripcion", models.TextField(blank=True, null=True)),
                ("precio", models.DecimalField(decimal_places=2, max_digits=10)),
                ("activo", models.BooleanField(default=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "prestador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="productos",
                        to="api.prestadorservicio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Producto",
                "verbose_name_plural": "Productos",
                "db_table": "empresa_producto",
                "ordering": ["-fecha_creacion"],
            },
        ),
        migrations.CreateModel(
            name="ReglaPrecio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre_regla",
                    models.CharField(max_length=200, verbose_name="Nombre de la Regla"),
                ),
                (
                    "tipo_ajuste",
                    models.CharField(
                        choices=[
                            ("PORCENTAJE", "Porcentaje"),
                            ("MONTO_FIJO", "Monto Fijo"),
                        ],
                        max_length=50,
                        verbose_name="Tipo de Ajuste",
                    ),
                ),
                (
                    "valor_ajuste",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Valor del Ajuste"
                    ),
                ),
                ("fecha_inicio", models.DateField(verbose_name="Fecha de Inicio")),
                ("fecha_fin", models.DateField(verbose_name="Fecha de Fin")),
                ("activa", models.BooleanField(default=True)),
                (
                    "prestador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reglas_precio",
                        to="api.prestadorservicio",
                    ),
                ),
                (
                    "producto_asociado",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reglas_precio",
                        to="prestadores.producto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Regla de Precio",
                "verbose_name_plural": "Reglas de Precios",
                "db_table": "empresa_reglaprecio",
            },
        ),
    ]
