# Generated by Django 5.2.6 on 2025-10-25 14:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoriaPrestador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, unique=True)),
                (
                    "slug",
                    models.SlugField(
                        help_text="Versión del nombre amigable para URLs",
                        max_length=100,
                        unique=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Categoría de Prestador",
                "verbose_name_plural": "Categorías de Prestadores",
            },
        ),
        migrations.CreateModel(
            name="Perfil",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre_comercial",
                    models.CharField(max_length=255, verbose_name="Nombre Comercial"),
                ),
                ("telefono_principal", models.CharField(blank=True, max_length=50)),
                ("email_comercial", models.EmailField(blank=True, max_length=255)),
                ("direccion", models.CharField(blank=True, max_length=255)),
                (
                    "latitud",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                (
                    "longitud",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                ("descripcion_corta", models.TextField(blank=True)),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="logos_prestadores/"
                    ),
                ),
                ("sitio_web", models.URLField(blank=True, max_length=255)),
                (
                    "redes_sociales",
                    models.JSONField(blank=True, default=dict, null=True),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("Pendiente", "Pendiente de Revisión"),
                            ("Activo", "Activo y Visible"),
                            ("Rechazado", "Rechazado"),
                            ("Inactivo", "Inactivo por el Usuario"),
                        ],
                        default="Pendiente",
                        max_length=20,
                    ),
                ),
                (
                    "puntuacion_verificacion",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Puntaje acumulado de verificaciones de cumplimiento.",
                    ),
                ),
                (
                    "puntuacion_capacitacion",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Puntaje acumulado por asistencia a capacitaciones.",
                    ),
                ),
                (
                    "puntuacion_reseñas",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Puntaje acumulado por reseñas de turistas.",
                    ),
                ),
                (
                    "puntuacion_formularios",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Puntaje por completar formularios de caracterización.",
                    ),
                ),
                (
                    "puntuacion_total",
                    models.PositiveIntegerField(
                        db_index=True,
                        default=0,
                        help_text="Puntaje total para posicionamiento. Se calcula automáticamente.",
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "categoria",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="prestadores.categoriaprestador",
                    ),
                ),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="perfil_prestador",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Perfil de Prestador",
                "verbose_name_plural": "Perfiles de Prestadores",
            },
        ),
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("telefono", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "perfil",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clientes",
                        to="prestadores.perfil",
                    ),
                ),
            ],
        ),
    ]
