# Generated by Django 5.2.6 on 2025-10-21 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prestadores", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="perfil",
            name="puntuacion_capacitacion",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Puntaje acumulado por asistencia a capacitaciones.",
            ),
        ),
        migrations.AddField(
            model_name="perfil",
            name="puntuacion_formularios",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Puntaje por completar formularios de caracterización.",
            ),
        ),
        migrations.AddField(
            model_name="perfil",
            name="puntuacion_reseñas",
            field=models.PositiveIntegerField(
                default=0, help_text="Puntaje acumulado por reseñas de turistas."
            ),
        ),
        migrations.AddField(
            model_name="perfil",
            name="puntuacion_verificacion",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Puntaje acumulado de verificaciones de cumplimiento.",
            ),
        ),
        migrations.AlterField(
            model_name="perfil",
            name="puntuacion_total",
            field=models.PositiveIntegerField(
                db_index=True,
                default=0,
                help_text="Puntaje total para posicionamiento. Se calcula automáticamente.",
            ),
        ),
    ]
