# Generated by Django 5.2.6 on 2025-10-23 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prestadores", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="inventario",
            options={
                "ordering": ["nombre_item"],
                "verbose_name": "Ítem de Inventario",
                "verbose_name_plural": "Ítems de Inventario",
            },
        ),
        migrations.AddField(
            model_name="inventario",
            name="descripcion",
            field=models.TextField(blank=True, null=True, verbose_name="Descripción"),
        ),
        migrations.AddField(
            model_name="inventario",
            name="fecha_actualizacion",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="inventario",
            name="punto_reorden",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Cantidad mínima antes de necesitar reabastecimiento",
                verbose_name="Punto de Reorden",
            ),
        ),
        migrations.AddField(
            model_name="inventario",
            name="unidad",
            field=models.CharField(
                blank=True,
                help_text="Ej: unidades, kg, litros",
                max_length=50,
                null=True,
                verbose_name="Unidad de Medida",
            ),
        ),
        migrations.AlterField(
            model_name="inventario",
            name="cantidad",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Cantidad Disponible"
            ),
        ),
        migrations.AlterField(
            model_name="inventario",
            name="nombre_item",
            field=models.CharField(max_length=255, verbose_name="Nombre del Ítem"),
        ),
        migrations.AlterField(
            model_name="inventario",
            name="perfil",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inventario_items",
                to="prestadores.perfil",
            ),
        ),
    ]
