# Generated by Django 5.2.6 on 2025-10-26 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prestadores", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Costo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "concepto",
                    models.CharField(max_length=255, verbose_name="Concepto del Costo"),
                ),
                (
                    "monto",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Monto"
                    ),
                ),
                ("fecha", models.DateField(verbose_name="Fecha del Costo")),
                (
                    "es_recurrente",
                    models.BooleanField(default=False, verbose_name="¿Es Recurrente?"),
                ),
                (
                    "tipo_costo",
                    models.CharField(
                        choices=[("FIJO", "Fijo"), ("VARIABLE", "Variable")],
                        default="VARIABLE",
                        max_length=50,
                        verbose_name="Tipo de Costo",
                    ),
                ),
                (
                    "perfil",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="costos",
                        to="prestadores.perfil",
                    ),
                ),
            ],
            options={
                "verbose_name": "Costo Operativo",
                "verbose_name_plural": "Costos Operativos",
                "ordering": ["-fecha"],
            },
        ),
        migrations.CreateModel(
            name="Inventario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre_item",
                    models.CharField(max_length=255, verbose_name="Nombre del Ítem"),
                ),
                (
                    "descripcion",
                    models.TextField(blank=True, null=True, verbose_name="Descripción"),
                ),
                (
                    "cantidad",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Cantidad Disponible"
                    ),
                ),
                (
                    "unidad",
                    models.CharField(
                        help_text="Ej: unidades, kg, litros",
                        max_length=50,
                        verbose_name="Unidad de Medida",
                    ),
                ),
                (
                    "punto_reorden",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Cantidad mínima antes de necesitar reabastecimiento",
                        verbose_name="Punto de Reorden",
                    ),
                ),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "perfil",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventario",
                        to="prestadores.perfil",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ítem de Inventario",
                "verbose_name_plural": "Ítems de Inventario",
                "ordering": ["nombre_item"],
            },
        ),
        migrations.CreateModel(
            name="ProductoServicio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=255, verbose_name="Nombre del Producto/Servicio"
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(blank=True, null=True, verbose_name="Descripción"),
                ),
                (
                    "precio",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=12,
                        verbose_name="Precio",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("PRODUCTO", "Producto"), ("SERVICIO", "Servicio")],
                        default="PRODUCTO",
                        max_length=50,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "cantidad_disponible",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Para servicios, usualmente es 1 o se deja en blanco.",
                        verbose_name="Cantidad Disponible",
                    ),
                ),
                (
                    "unidad_medida",
                    models.CharField(
                        blank=True,
                        help_text="Ej: unidades, kg, horas, etc.",
                        max_length=50,
                        verbose_name="Unidad de Medida",
                    ),
                ),
                (
                    "activo",
                    models.BooleanField(
                        default=True,
                        help_text="Indica si el producto/servicio está disponible para la venta.",
                        verbose_name="Activo",
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "perfil",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="productos_servicios",
                        to="prestadores.perfil",
                    ),
                ),
            ],
            options={
                "verbose_name": "Producto o Servicio",
                "verbose_name_plural": "Productos y Servicios",
                "ordering": ["nombre"],
            },
        ),
    ]
