# Generated by Django 5.2.6 on 2025-10-23 14:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "prestadores",
            "0002_alter_inventario_options_inventario_descripcion_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="costo",
            options={
                "ordering": ["-fecha"],
                "verbose_name": "Costo Operativo",
                "verbose_name_plural": "Costos Operativos",
            },
        ),
        migrations.AlterModelOptions(
            name="reserva",
            options={
                "ordering": ["-fecha_hora_inicio"],
                "verbose_name": "Reserva / Cita",
                "verbose_name_plural": "Reservas y Citas",
            },
        ),
        migrations.AlterModelOptions(
            name="ticketsoporte",
            options={
                "ordering": ["-fecha_creacion"],
                "verbose_name": "Ticket de Soporte",
                "verbose_name_plural": "Tickets de Soporte",
            },
        ),
        migrations.RemoveField(
            model_name="costo",
            name="descripcion",
        ),
        migrations.RemoveField(
            model_name="reserva",
            name="fecha_reserva",
        ),
        migrations.RemoveField(
            model_name="reserva",
            name="nombre_cliente",
        ),
        migrations.RemoveField(
            model_name="ticketsoporte",
            name="resuelto",
        ),
        migrations.AddField(
            model_name="costo",
            name="concepto",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Concepto del Costo"
            ),
        ),
        migrations.AddField(
            model_name="costo",
            name="es_recurrente",
            field=models.BooleanField(default=False, verbose_name="¿Es Recurrente?"),
        ),
        migrations.AddField(
            model_name="costo",
            name="fecha",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fecha del Costo"
            ),
        ),
        migrations.AddField(
            model_name="costo",
            name="tipo_costo",
            field=models.CharField(
                choices=[("FIJO", "Fijo"), ("VARIABLE", "Variable")],
                default="VARIABLE",
                max_length=50,
                verbose_name="Tipo de Costo",
            ),
        ),
        migrations.AddField(
            model_name="reserva",
            name="cliente",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reservas",
                to="prestadores.cliente",
            ),
        ),
        migrations.AddField(
            model_name="reserva",
            name="estado",
            field=models.CharField(
                choices=[
                    ("PENDIENTE", "Pendiente"),
                    ("CONFIRMADA", "Confirmada"),
                    ("CANCELADA", "Cancelada"),
                    ("COMPLETADA", "Completada"),
                ],
                default="PENDIENTE",
                max_length=50,
                verbose_name="Estado de la Reserva",
            ),
        ),
        migrations.AddField(
            model_name="reserva",
            name="fecha_actualizacion",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="reserva",
            name="fecha_creacion",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="reserva",
            name="fecha_hora_fin",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Fecha y Hora de Fin"
            ),
        ),
        migrations.AddField(
            model_name="reserva",
            name="fecha_hora_inicio",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Fecha y Hora de Inicio"
            ),
        ),
        migrations.AddField(
            model_name="reserva",
            name="monto_total",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=12, verbose_name="Monto Total"
            ),
        ),
        migrations.AddField(
            model_name="reserva",
            name="notas",
            field=models.TextField(blank=True, verbose_name="Notas Adicionales"),
        ),
        migrations.AddField(
            model_name="reserva",
            name="producto_servicio",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="prestadores.productoservicio",
            ),
        ),
        migrations.AddField(
            model_name="ticketsoporte",
            name="estado",
            field=models.CharField(
                choices=[
                    ("ABIERTO", "Abierto"),
                    ("EN_PROGRESO", "En Progreso"),
                    ("CERRADO", "Cerrado"),
                ],
                default="ABIERTO",
                max_length=50,
                verbose_name="Estado del Ticket",
            ),
        ),
        migrations.AddField(
            model_name="ticketsoporte",
            name="fecha_actualizacion",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="ticketsoporte",
            name="fecha_creacion",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="costo",
            name="monto",
            field=models.DecimalField(
                decimal_places=2, max_digits=12, verbose_name="Monto"
            ),
        ),
        migrations.AlterField(
            model_name="costo",
            name="perfil",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="costos_operativos",
                to="prestadores.perfil",
            ),
        ),
        migrations.AlterField(
            model_name="reserva",
            name="perfil",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reservas_citas",
                to="prestadores.perfil",
            ),
        ),
        migrations.AlterField(
            model_name="ticketsoporte",
            name="asunto",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Asunto"
            ),
        ),
        migrations.AlterField(
            model_name="ticketsoporte",
            name="mensaje",
            field=models.TextField(blank=True, null=True, verbose_name="Mensaje"),
        ),
        migrations.AlterField(
            model_name="ticketsoporte",
            name="perfil",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tickets_soporte_nuevos",
                to="prestadores.perfil",
            ),
        ),
    ]
