# Generated by Django 5.2.6 on 2025-10-21 02:34

import apps.prestadores.mi_negocio.gestion_operativa.modulos_genericos.rat
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prestadores", "0002_perfil_puntuacion_capacitacion_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfiguracionPrestador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "recibir_notificaciones_email",
                    models.BooleanField(
                        default=True,
                        verbose_name="Recibir notificaciones por correo electrónico",
                    ),
                ),
                (
                    "recibir_notificaciones_push",
                    models.BooleanField(
                        default=True,
                        verbose_name="Recibir notificaciones push en la aplicación",
                    ),
                ),
                (
                    "tema_interfaz",
                    models.CharField(
                        choices=[
                            ("CLARO", "Claro"),
                            ("OSCURO", "Oscuro"),
                            ("SISTEMA", "Automático (Sistema)"),
                        ],
                        default="SISTEMA",
                        max_length=50,
                        verbose_name="Tema de la Interfaz",
                    ),
                ),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "perfil",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="configuracion",
                        to="prestadores.perfil",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuración de Prestador",
                "verbose_name_plural": "Configuraciones de Prestadores",
            },
        ),
        migrations.CreateModel(
            name="RegistroActividadTuristica",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre_documento",
                    models.CharField(
                        max_length=255, verbose_name="Nombre del Documento o Registro"
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                (
                    "archivo",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=apps.prestadores.mi_negocio.gestion_operativa.modulos_genericos.rat.rat_directory_path,
                        verbose_name="Archivo Adjunto",
                    ),
                ),
                (
                    "fecha_presentacion",
                    models.DateField(verbose_name="Fecha de Presentación"),
                ),
                (
                    "entidad_reguladora",
                    models.CharField(
                        blank=True,
                        help_text="Ej: Ministerio de Turismo, DIAN, etc.",
                        max_length=255,
                        verbose_name="Entidad Reguladora",
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                (
                    "perfil",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registros_rat",
                        to="prestadores.perfil",
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro de Actividad Turística (RAT)",
                "verbose_name_plural": "Registros de Actividad Turística (RAT)",
                "ordering": ["-fecha_presentacion"],
            },
        ),
        migrations.CreateModel(
            name="Reporte",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre_reporte",
                    models.CharField(max_length=255, verbose_name="Nombre del Reporte"),
                ),
                (
                    "tipo_reporte",
                    models.CharField(
                        choices=[
                            ("VENTAS", "Ventas"),
                            ("OCUPACION", "Ocupación"),
                            ("CLIENTES", "Clientes"),
                            ("PERSONALIZADO", "Personalizado"),
                        ],
                        default="PERSONALIZADO",
                        max_length=50,
                        verbose_name="Tipo de Reporte",
                    ),
                ),
                (
                    "fecha_inicio",
                    models.DateField(verbose_name="Fecha de Inicio del Reporte"),
                ),
                (
                    "fecha_fin",
                    models.DateField(verbose_name="Fecha de Fin del Reporte"),
                ),
                (
                    "datos",
                    models.JSONField(
                        help_text="Almacena los datos agregados del reporte en formato JSON.",
                        verbose_name="Datos del Reporte",
                    ),
                ),
                ("fecha_generacion", models.DateTimeField(auto_now_add=True)),
                (
                    "perfil",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reportes",
                        to="prestadores.perfil",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reporte / Estadística",
                "verbose_name_plural": "Reportes y Estadísticas",
                "ordering": ["-fecha_generacion"],
            },
        ),
        migrations.CreateModel(
            name="Reserva",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha_hora_inicio",
                    models.DateTimeField(verbose_name="Fecha y Hora de Inicio"),
                ),
                (
                    "fecha_hora_fin",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha y Hora de Fin"
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente"),
                            ("CONFIRMADA", "Confirmada"),
                            ("CANCELADA", "Cancelada"),
                            ("COMPLETADA", "Completada"),
                        ],
                        default="PENDIENTE",
                        max_length=50,
                        verbose_name="Estado de la Reserva",
                    ),
                ),
                (
                    "notas",
                    models.TextField(blank=True, verbose_name="Notas Adicionales"),
                ),
                (
                    "monto_total",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=12,
                        verbose_name="Monto Total",
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reservas",
                        to="prestadores.cliente",
                    ),
                ),
                (
                    "perfil",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservas",
                        to="prestadores.perfil",
                    ),
                ),
                (
                    "producto_servicio",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="prestadores.productoservicio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reserva / Cita",
                "verbose_name_plural": "Reservas y Citas",
                "ordering": ["-fecha_hora_inicio"],
            },
        ),
        migrations.CreateModel(
            name="TicketSoporte",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("asunto", models.CharField(max_length=255, verbose_name="Asunto")),
                ("mensaje", models.TextField(verbose_name="Mensaje")),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("ABIERTO", "Abierto"),
                            ("EN_PROGRESO", "En Progreso"),
                            ("CERRADO", "Cerrado"),
                        ],
                        default="ABIERTO",
                        max_length=50,
                        verbose_name="Estado del Ticket",
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "perfil",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tickets_soporte",
                        to="prestadores.perfil",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ticket de Soporte",
                "verbose_name_plural": "Tickets de Soporte",
                "ordering": ["-fecha_creacion"],
            },
        ),
    ]
