# Generated by Django 5.2.6 on 2025-10-29 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ActivoFijo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                ("fecha_adquisicion", models.DateField()),
                ("costo_inicial", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "valor_residual",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("vida_util_meses", models.PositiveIntegerField()),
                (
                    "depreciacion_acumulada",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "valor_en_libros",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RegistroDepreciacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField()),
                ("monto", models.DecimalField(decimal_places=2, max_digits=15)),
            ],
        ),
    ]
