# Generated by Django 5.2.6 on 2025-10-29 01:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("activos", "0001_initial"),
        ("prestadores", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="activofijo",
            name="perfil",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activos_fijos",
                to="prestadores.perfil",
            ),
        ),
        migrations.AddField(
            model_name="registrodepreciacion",
            name="activo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="registros_depreciacion",
                to="activos.activofijo",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="registrodepreciacion",
            unique_together={("activo", "fecha")},
        ),
    ]
