# Generated by Django 5.2.6 on 2026-02-06 01:16

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OperationalTreaty",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("TIT", "Tratado de Interoperabilidad Técnica"),
                            ("TNA", "Tratado de Neutralidad Algorítmica"),
                            ("TNID", "Tratado de No-Injerencia Digital"),
                            ("TSDS", "Tratado de Soberanía de Datos y Señales"),
                        ],
                        max_length=10,
                    ),
                ),
                ("version", models.CharField(default="1.0", max_length=20)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "guardrails_config",
                    models.JSONField(
                        help_text="Configuración de límites algorítmicos para este tratado."
                    ),
                ),
                (
                    "participating_nodes",
                    models.JSONField(
                        default=list,
                        help_text="Lista de IDs de nodos soberanos firmantes.",
                    ),
                ),
                ("signed_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("scope", models.TextField(help_text="Alcance institucional y geográfico del tratado.", default="")),
                ("permissions_granted", models.JSONField(default=dict, help_text="Capacidades técnicas habilitadas (ej: READ_ALERTS, PROPOSE_MITIGATION).")),
                ("data_boundaries", models.JSONField(default=dict, help_text="Límites duros de acceso a datos (ej: AGGREGATED_ONLY).")),
                ("signal_types_allowed", models.JSONField(default=list, help_text="Tipos de señales DSO permitidas.")),
                ("revocation_rules", models.JSONField(default=dict, help_text="Condiciones de auto-suspensión del tratado.")),
                ("audit_level", models.IntegerField(default=1, help_text="Nivel de auditoría (1: Local, 2: Cruzada, 3: Supranacional).")),
            ],
        ),
        migrations.CreateModel(
            name="SovereignKillSwitch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_triggered", models.BooleanField(default=False)),
                ("triggered_at", models.DateTimeField(blank=True, null=True)),
                ("reason", models.TextField()),
                ("block_level", models.IntegerField(default=3)),
                (
                    "treaty",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kill_switch",
                        to="operational_treaties.operationaltreaty",
                    ),
                ),
                (
                    "triggered_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TreatyComplianceAudit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("actor_node_id", models.CharField(max_length=100)),
                (
                    "action_type",
                    models.CharField(
                        help_text="Ej: SIGNAL_EMISSION, MITIGATION_PROPOSAL",
                        max_length=100,
                    ),
                ),
                ("payload_summary", models.JSONField()),
                ("is_compliant", models.BooleanField(default=True)),
                ("violation_details", models.TextField(blank=True, null=True)),
                (
                    "previous_hash",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "integrity_hash",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "treaty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audits",
                        to="operational_treaties.operationaltreaty",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
    ]
