# Generated by Django 5.2.6 on 2026-02-06 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operational_treaties", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="operationaltreaty",
            name="lifecycle_status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "Activo"),
                    ("OBSERVATION", "En Observación"),
                    ("ADJUSTMENT", "En Ajuste"),
                    ("SUSPENDED", "Suspendido"),
                    ("EXPIRED", "Expirado"),
                ],
                default="ACTIVE",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="operationaltreaty",
            name="performance_metrics",
            field=models.JSONField(
                default=dict, help_text="Métricas de efectividad del tratado."
            ),
        ),
        migrations.AddField(
            model_name="operationaltreaty",
            name="risk_indicators",
            field=models.JSONField(
                default=dict, help_text="Señales de riesgo asociadas a este tratado."
            ),
        ),
        migrations.AddField(
            model_name="operationaltreaty",
            name="trust_score",
            field=models.FloatField(
                default=1.0,
                help_text="Nivel de confianza actual en la contraparte (0.0 a 1.0).",
            ),
        ),
        migrations.AlterField(
            model_name="operationaltreaty",
            name="guardrails_config",
            field=models.JSONField(
                default=dict,
                help_text="Configuración de límites algorítmicos para este tratado.",
            ),
        ),
        migrations.AlterField(
            model_name="operationaltreaty",
            name="scope",
            field=models.TextField(
                help_text="Alcance institucional y geográfico del tratado."
            ),
        ),
    ]
