# Generated by Django 5.2.12 on 2026-03-15 13:07

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core_erp", "0001_initial_base"),
    ]

    operations = [
        migrations.CreateModel(
            name="CuentaBancaria",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("bank_name", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "account_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "account_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "balance",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=18),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("perfil_ref_id", models.UUIDField()),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_records",
                        to="core_erp.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cuenta Bancaria (Admin)",
            },
        ),
        migrations.CreateModel(
            name="OrdenPago",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("payment_date", models.DateField(default=django.utils.timezone.now)),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=18),
                ),
                ("concept", models.CharField(blank=True, max_length=255, null=True)),
                ("status", models.CharField(default="PENDING", max_length=20)),
                ("perfil_ref_id", models.UUIDField()),
                ("cuenta_bancaria_ref_id", models.UUIDField()),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_records",
                        to="core_erp.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Orden de Pago (Admin)",
            },
        ),
        migrations.CreateModel(
            name="TransaccionBancaria",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("payment_date", models.DateField(default=django.utils.timezone.now)),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=18),
                ),
                ("method", models.CharField(blank=True, max_length=50, null=True)),
                ("reference", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "bank_fees",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=18),
                ),
                (
                    "cuenta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admin_transacciones",
                        to="admin_financiera.cuentabancaria",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_records",
                        to="core_erp.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transacción Bancaria (Admin)",
            },
        ),
    ]
