# Generated by Django 5.2.6 on 2026-01-29 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CuentaBancaria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("perfil_ref_id", models.UUIDField()),
                ("banco", models.CharField(max_length=100)),
                ("numero_cuenta", models.CharField(max_length=50, unique=True)),
                ("tipo_cuenta", models.CharField(max_length=50)),
                (
                    "saldo_actual",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=18),
                ),
                ("activa", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Cuenta Bancaria (Admin)",
            },
        ),
        migrations.CreateModel(
            name="OrdenPago",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("perfil_ref_id", models.UUIDField()),
                ("cuenta_bancaria_ref_id", models.UUIDField()),
                ("fecha_pago", models.DateField()),
                ("monto", models.DecimalField(decimal_places=2, max_digits=18)),
                ("concepto", models.CharField(max_length=255)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente"),
                            ("PAGADA", "Pagada"),
                            ("CANCELADA", "Cancelada"),
                        ],
                        default="PENDIENTE",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "Orden de Pago (Admin)",
            },
        ),
        migrations.CreateModel(
            name="TransaccionBancaria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                ("monto", models.DecimalField(decimal_places=2, max_digits=18)),
                ("descripcion", models.CharField(max_length=255)),
                (
                    "cuenta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admin_transacciones",
                        to="admin_financiera.cuentabancaria",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transacción Bancaria (Admin)",
            },
        ),
    ]
