# Generated by Django 5.2.6 on 2026-01-29 12:00

import django.db.models.deletion
from django.db import migrations, models
import uuid

class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CuentaBancaria",
            fields=[
                ("id", models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("bank_name", models.CharField(max_length=100)),
                ("account_number", models.CharField(max_length=50)),
                ("account_type", models.CharField(max_length=50)),
                ("balance", models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ("is_active", models.BooleanField(default=True)),
                ("perfil_ref_id", models.UUIDField()),
            ],
            options={
                "verbose_name": "Cuenta Bancaria (Admin)",
            },
        ),
        migrations.CreateModel(
            name="OrdenPago",
            fields=[
                ("id", models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("payment_date", models.DateField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=18)),
                ("concept", models.CharField(max_length=255)),
                ("status", models.CharField(max_length=20)),
                ("perfil_ref_id", models.UUIDField()),
                ("cuenta_bancaria_ref_id", models.UUIDField()),
            ],
            options={
                "verbose_name": "Orden de Pago (Admin)",
            },
        ),
        migrations.CreateModel(
            name="TransaccionBancaria",
            fields=[
                ("id", models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("payment_date", models.DateField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=18)),
                ("method", models.CharField(max_length=50)),
                ("reference", models.CharField(blank=True, max_length=100)),
                ("bank_fees", models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                (
                    "cuenta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admin_transacciones",
                        to="admin_financiera.cuentabancaria",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transacción Bancaria (Admin)",
            },
        ),
    ]
