# Generated by Django 5.2.10 on 2026-01-29 20:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DecisionMatrix",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("LOW", "Bajo Riesgo"),
                            ("MEDIUM", "Medio Riesgo"),
                            ("HIGH", "Alto Riesgo"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "requires_approval",
                    models.BooleanField(
                        default=True,
                        help_text="Si es False, se permite ejecución autónoma bajo regla previa.",
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "verbose_name": "Matriz de Decisión",
                "verbose_name_plural": "Matrices de Decisión",
            },
        ),
        migrations.CreateModel(
            name="StrategyProposal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "domain",
                    models.CharField(
                        choices=[
                            ("FINANCIERO", "Financiero"),
                            ("OPERATIVO", "Operativo"),
                            ("COMERCIAL", "Comercial"),
                            ("NORMATIVO", "Normativo"),
                            ("SISTEMICO", "Sistémico"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pendiente de Revisión"),
                            ("APPROVED", "Aprobada"),
                            ("REJECTED", "Rechazada"),
                            ("POSTPONED", "Postergada"),
                            ("EXECUTED", "Ejecutada"),
                            ("FAILED", "Fallo en Ejecución"),
                        ],
                        default="PENDING",
                        max_length=50,
                    ),
                ),
                (
                    "contexto_detectado",
                    models.TextField(
                        help_text="Contexto histórico y patrones detectados."
                    ),
                ),
                (
                    "riesgo_actual",
                    models.TextField(help_text="Evaluación del riesgo si no se actúa."),
                ),
                (
                    "oportunidad_detectada",
                    models.TextField(help_text="Beneficio potencial de la acción."),
                ),
                (
                    "accion_sugerida",
                    models.JSONField(
                        help_text="Directiva técnica sugerida (Intención + Parámetros)."
                    ),
                ),
                (
                    "impacto_estimado",
                    models.TextField(help_text="Proyección de resultados."),
                ),
                (
                    "nivel_confianza",
                    models.FloatField(
                        default=0.0,
                        help_text="Probabilidad de éxito estimada por la IA (0-1).",
                    ),
                ),
                (
                    "nivel_urgencia",
                    models.CharField(
                        choices=[
                            ("LOW", "Baja"),
                            ("MEDIUM", "Media"),
                            ("HIGH", "Alta"),
                            ("CRITICAL", "Crítica"),
                        ],
                        default="LOW",
                        max_length=20,
                    ),
                ),
                (
                    "nivel_riesgo",
                    models.CharField(
                        choices=[
                            ("LOW", "Bajo Riesgo"),
                            ("MEDIUM", "Medio Riesgo"),
                            ("HIGH", "Alto Riesgo"),
                        ],
                        default="LOW",
                        max_length=20,
                    ),
                ),
                (
                    "agent_id",
                    models.CharField(
                        help_text="Identificador del agente que generó la propuesta.",
                        max_length=255,
                    ),
                ),
                ("justificacion_humana", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "decidida_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="decisiones_estrategicas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Propuesta Estratégica",
                "verbose_name_plural": "Propuestas Estratégicas",
                "ordering": ["-created_at"],
            },
        ),
    ]
