# Generated by Django 5.2.10 on 2026-01-29 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("decision_intelligence", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="strategyproposal",
            name="decision_level",
            field=models.IntegerField(
                choices=[
                    (1, "Automática (Riesgo Bajo, Reversible)"),
                    (2, "Supervisada (Riesgo Medio, Espera Confirmación)"),
                    (3, "Estratégica (Alto Impacto, Recomendación)"),
                ],
                default=3,
            ),
        ),
    ]
