# Generated by Django 5.2.6 on 2026-02-04 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("decision_intelligence", "0002_strategyproposal_decision_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="strategyproposal",
            name="agent_id_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
