from django.db import models
from django.utils.translation import gettext_lazy as _
from .provider_models import BaseModel, TourismProvider
from .divipola import Department, Municipality
from api.models import AtractivoTuristico

class TourismRoute(BaseModel):
    name = models.CharField(max_length=255)
    description = models.TextField()
    department = models.ForeignKey(Department, on_delete=models.CASCADE, related_name='routes')
    municipality = models.ForeignKey(Municipality, on_delete=models.CASCADE, related_name='routes', null=True, blank=True)

    # Associated items
    attractions = models.ManyToManyField(AtractivoTuristico, related_name='tourism_routes', blank=True)
    providers = models.ManyToManyField(TourismProvider, related_name='tourism_routes', blank=True)

    # Metadata
    route_type = models.CharField(max_length=50, help_text="e.g., Gastronómica, Naturaleza, Histórica")
    is_intelligent = models.BooleanField(default=False, help_text="Generated by AI engine")

    def __str__(self):
        return self.name
