# Generated by Django 5.2.6 on 2026-02-06 00:21

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StabilityAlert",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("LOW", "Baja (Detección)"),
                            ("MEDIUM", "Media (Tensión)"),
                            ("HIGH", "Alta (Inestabilidad)"),
                            ("CRITICAL", "Crítica (Riesgo de Colapso)"),
                        ],
                        max_length=20,
                    ),
                ),
                ("context_summary", models.TextField()),
                (
                    "detected_patterns",
                    models.JSONField(
                        help_text="Patrones detectados por los agentes Tenientes"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="SystemicRiskIndicator",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "domain",
                    models.CharField(
                        choices=[
                            ("ECONOMIC", "Económico"),
                            ("INSTITUTIONAL", "Institucional"),
                            ("SOCIAL", "Social"),
                            ("GOVERNANCE", "Gobernanza"),
                            ("ALGORITHMIC", "Algorítmico"),
                        ],
                        max_length=20,
                    ),
                ),
                ("current_value", models.FloatField()),
                ("baseline_value", models.FloatField()),
                ("threshold_critical", models.FloatField()),
                ("last_update", models.DateTimeField(auto_now=True)),
                ("source_metadata", models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name="MitigationScenario",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "proposed_actions",
                    models.JSONField(
                        help_text="Lista de acciones de alineación institucional"
                    ),
                ),
                ("estimated_impact", models.TextField()),
                ("is_validated_by_human", models.BooleanField(default=False)),
                ("is_applied", models.BooleanField(default=False)),
                (
                    "reasoning_chain",
                    models.JSONField(help_text="Cadena de decisión del agente"),
                ),
                (
                    "alert",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scenarios",
                        to="peace_net.stabilityalert",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="stabilityalert",
            name="indicators",
            field=models.ManyToManyField(
                related_name="alerts", to="peace_net.systemicriskindicator"
            ),
        ),
    ]
