# Generated by Django 5.2.12 on 2026-03-15 13:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core_erp", "0001_initial_base"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DecisionProposal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("origin_metric", models.CharField(max_length=100)),
                ("metric_value", models.DecimalField(decimal_places=4, max_digits=20)),
                (
                    "evaluated_risk",
                    models.FloatField(help_text="Calculated risk score 0.0 to 1.0"),
                ),
                (
                    "risk_category",
                    models.CharField(default="OPERATIONAL", max_length=50),
                ),
                (
                    "suggested_action",
                    models.JSONField(
                        help_text="Intent data: {'intention': '...', 'parameters': {...}}"
                    ),
                ),
                (
                    "governance_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Approval"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("EXECUTED", "Executed"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("executed", models.BooleanField(default=False)),
                ("execution_result", models.JSONField(blank=True, null=True)),
                ("autonomy_level_applied", models.IntegerField(default=1)),
                (
                    "agent_id",
                    models.CharField(default="EOS-CORE-ENGINE", max_length=100),
                ),
                (
                    "policy_reference",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("correlation_id", models.UUIDField(db_index=True, default=uuid.uuid4)),
                (
                    "integrity_hash",
                    models.CharField(
                        blank=True, db_index=True, max_length=64, null=True
                    ),
                ),
                (
                    "previous_hash",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_proposals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_records",
                        to="core_erp.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Decision Proposal",
                "verbose_name_plural": "Decision Proposals",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RiskSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "overall_score",
                    models.FloatField(help_text="Normalized risk 0.0 to 1.0"),
                ),
                (
                    "risk_factors",
                    models.JSONField(
                        help_text="Breakdown of contributors (liquidity, concentration, churn, etc.)"
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_records",
                        to="core_erp.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Risk Snapshot",
                "verbose_name_plural": "Risk Snapshots",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="StrategicRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "trigger_metric",
                    models.CharField(
                        help_text="Metric name from control_tower or operational_intelligence",
                        max_length=100,
                    ),
                ),
                (
                    "condition_expression",
                    models.CharField(
                        help_text="Logic expression e.g. 'metric < 1000'",
                        max_length=255,
                    ),
                ),
                (
                    "risk_weight",
                    models.FloatField(
                        default=1.0,
                        help_text="Impact of this rule on overall risk score",
                    ),
                ),
                (
                    "recommended_action",
                    models.CharField(
                        help_text="Intent name to be executed via GovernanceKernel",
                        max_length=255,
                    ),
                ),
                (
                    "autonomy_level",
                    models.IntegerField(
                        default=1,
                        help_text="0: Suggestion, 1: Human Approval, 2: Auto under Threshold, 3: Full Autonomy",
                    ),
                ),
                (
                    "impact_threshold",
                    models.DecimalField(
                        decimal_places=2,
                        default=1000.0,
                        help_text="Max financial impact for auto-execution",
                        max_digits=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_records",
                        to="core_erp.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Strategic Rule",
                "verbose_name_plural": "Strategic Rules",
            },
        ),
    ]
