 
# Generated by Django 5.2.6 on 2026-01-22 00:25
 

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SadiAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "comando_original",
                    models.TextField(
                        help_text="El comando de voz original en texto plano."
                    ),
                ),
                (
                    "accion_ejecutada",
                    models.JSONField(
                        blank=True,
                        help_text="La acción y parámetros interpretados por el LLM.",
                        null=True,
                    ),
                ),
                (
                    "resultado",
                    models.TextField(
                        help_text="El resultado de la ejecución del comando (éxito, error, etc.)."
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Fecha y hora en que se procesó el comando.",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sadi_commands",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro de Auditoría SADI",
                "verbose_name_plural": "Registros de Auditoría SADI",
                "ordering": ["-timestamp"],
            },
        ),
    ]
