# Generated by Django 5.2.6 on 2026-01-25 14:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sadi_agent", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentExecution",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "objective",
                    models.TextField(
                        help_text="The initial objective or prompt given to the agent.",
                        verbose_name="objective",
                    ),
                ),
                (
                    "plan",
                    models.JSONField(
                        blank=True,
                        help_text="The step-by-step plan generated by the planner LLM.",
                        null=True,
                        verbose_name="plan",
                    ),
                ),
                (
                    "execution_history",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="A list of executed steps, including thoughts, tools, params, and observations.",
                        verbose_name="execution history",
                    ),
                ),
                (
                    "logs",
                    models.TextField(
                        blank=True,
                        help_text="The full, raw log output from the agent's logger.",
                        verbose_name="logs",
                    ),
                ),
                (
                    "final_result",
                    models.TextField(
                        blank=True,
                        help_text="The final answer or result from the agent's execution.",
                        verbose_name="final result",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("RUNNING", "Running"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=10,
                        verbose_name="status",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_executions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "agent execution",
                "verbose_name_plural": "agent executions",
                "ordering": ["-created_at"],
            },
        ),
    ]
