# Generated by Django 5.2.6 on 2026-01-26 00:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sadi_agent", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Intent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre de la intención.", max_length=100
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Descripción de la intención."
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SemanticDomain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre del dominio.", max_length=100, unique=True
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Descripción del dominio."),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Example",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        help_text="Texto del comando de ejemplo.", unique=True
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        default="es",
                        help_text="Idioma del ejemplo (ej. 'es', 'en').",
                        max_length=10,
                    ),
                ),
                (
                    "intent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="examples",
                        to="sadi_agent.intent",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="intent",
            name="domain",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="intents",
                to="sadi_agent.semanticdomain",
            ),
        ),
        migrations.CreateModel(
            name="Entity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Nombre de la entidad.", max_length=100),
                ),
                (
                    "domain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entities",
                        to="sadi_agent.semanticdomain",
                    ),
                ),
            ],
            options={
                "unique_together": {("domain", "name")},
            },
        ),
        migrations.CreateModel(
            name="VoiceInteractionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp_start", models.DateTimeField(auto_now_add=True)),
                ("timestamp_end", models.DateTimeField(blank=True, null=True)),
                (
                    "audio_hash",
                    models.CharField(
                        blank=True,
                        help_text="SHA-256 hash del archivo de audio de entrada.",
                        max_length=64,
                    ),
                ),
                ("detected_language", models.CharField(blank=True, max_length=10)),
                ("transcribed_text", models.TextField(blank=True)),
                (
                    "normalized_text",
                    models.TextField(
                        blank=True,
                        help_text="Texto traducido al idioma base (español).",
                    ),
                ),
                ("extracted_entities", models.JSONField(blank=True, null=True)),
                ("permission_checked", models.BooleanField(default=False)),
                ("permission_granted", models.BooleanField(default=False)),
                (
                    "mission_id",
                    models.UUIDField(
                        blank=True,
                        help_text="ID de la misión de SARITA si fue creada.",
                        null=True,
                    ),
                ),
                ("final_status", models.CharField(default="PENDING", max_length=50)),
                ("text_response", models.TextField(blank=True)),
                (
                    "detected_intent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="sadi_agent.intent",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="voice_interactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro de Interacción por Voz",
                "verbose_name_plural": "Registros de Interacción por Voz",
                "ordering": ["-timestamp_start"],
            },
        ),
        migrations.CreateModel(
            name="VoicePermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("ADMIN", "Super Administrador"),
                            ("ADMIN_ENTIDAD", "Admin de Entidad"),
                            ("ADMIN_DEPARTAMENTAL", "Admin Entidad Departamental"),
                            ("ADMIN_MUNICIPAL", "Admin Entidad Municipal"),
                            ("FUNCIONARIO_DIRECTIVO", "Funcionario Directivo"),
                            ("FUNCIONARIO_PROFESIONAL", "Funcionario Profesional"),
                            ("PRESTADOR", "Prestador de Servicio"),
                            ("ARTESANO", "Artesano"),
                            (
                                "CONSEJO_CONSULTIVO_TURISMO",
                                "Consejo Consultivo de Turismo",
                            ),
                            ("TURISTA", "Turista"),
                        ],
                        help_text="Rol del usuario al que se aplica el permiso.",
                        max_length=50,
                    ),
                ),
                (
                    "domain",
                    models.CharField(
                        help_text="El dominio de la misión (ej. 'prestadores', 'gubernamental').",
                        max_length=100,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        help_text="La acción específica dentro del dominio (ej. 'crear', 'consultar').",
                        max_length=100,
                    ),
                ),
            ],
            options={
                "verbose_name": "Permiso de Voz",
                "verbose_name_plural": "Permisos de Voz",
                "unique_together": {("role", "domain", "action")},
            },
        ),
        migrations.DeleteModel(
            name="SadiAuditLog",
        ),
        migrations.AlterUniqueTogether(
            name="intent",
            unique_together={("domain", "name")},
        ),
    ]
