# Generated by Django 5.2.6 on 2026-01-28 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sadi_agent", "0002_agentexecution"),
        (
            "sadi_agent",
            "0002_intent_semanticdomain_example_intent_domain_entity_and_more",
        ),
    ]

    operations = []
