# Generated by Django 5.2.6 on 2026-02-08 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sadi_agent", "0003_merge_20260128_1419"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AgentExecution",
        ),
    ]
