# Generated by Django 6.0 on 2025-12-17 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("funnels", "0001_initial"),
        (
            "infrastructure",
            "0005_remove_campaign_tenant_remove_funnel_campaign_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="LandingPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                ("publicada", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="CadenaTurismo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                ("color_primario", models.CharField(max_length=7)),
                ("color_secundario", models.CharField(max_length=7)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cadenas",
                        to="infrastructure.tenant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                ("icon", models.CharField(blank=True, max_length=50)),
                (
                    "cadena",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categorias",
                        to="funnels.cadenaturismo",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="funnel",
            name="landing_page",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="funnels",
                to="funnels.landingpage",
            ),
        ),
        migrations.CreateModel(
            name="Subcategoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subcategorias",
                        to="funnels.categoria",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="landingpage",
            name="subcategoria",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="landing_pages",
                to="funnels.subcategoria",
            ),
        ),
    ]
