# Generated by Django 5.2.12 on 2026-03-15 13:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core_erp", "0001_initial_base"),
    ]

    operations = [
        migrations.CreateModel(
            name="ComplianceConstraint",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("jurisdiction", models.CharField(max_length=3)),
                ("rule_type", models.CharField(max_length=50)),
                ("parameters", models.JSONField()),
                ("is_blocking", models.BooleanField(default=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_records",
                        to="core_erp.tenant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TokenizedAsset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "asset_type",
                    models.CharField(
                        choices=[
                            ("EQUITY", "Equity Token"),
                            ("DEBT", "Debt Token"),
                            ("REVENUE_SHARE", "Revenue Share Token"),
                            ("ASSET_BACKED", "Asset-Backed Token"),
                            ("IP", "IP Token"),
                            ("INFRASTRUCTURE", "Infrastructure Token"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "classification",
                    models.CharField(
                        choices=[
                            ("SECURITY", "Security Token"),
                            ("UTILITY", "Utility Token"),
                            ("HYBRID", "Hybrid Instrument"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "underlying_asset_ref_id",
                    models.UUIDField(
                        blank=True,
                        help_text="Reference to physical/ledger asset",
                        null=True,
                    ),
                ),
                (
                    "valuation_model",
                    models.CharField(
                        help_text="Method used for valuation (e.g. DCF, NAV)",
                        max_length=100,
                    ),
                ),
                (
                    "jurisdiction",
                    models.CharField(help_text="ISO Country Code", max_length=3),
                ),
                ("total_supply", models.DecimalField(decimal_places=10, max_digits=30)),
                ("par_value", models.DecimalField(decimal_places=2, max_digits=20)),
                ("governance_rules", models.JSONField(blank=True, default=dict)),
                ("transfer_constraints", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_records",
                        to="core_erp.tenant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SmartGovernanceRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("trigger_event", models.CharField(max_length=100)),
                (
                    "logic_code",
                    models.TextField(
                        help_text="DSL or Python snippet for automated execution"
                    ),
                ),
                ("autonomy_level", models.IntegerField(default=1)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_records",
                        to="core_erp.tenant",
                    ),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rules",
                        to="tokenization.tokenizedasset",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProgrammableCapitalUnit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("unit_id", models.CharField(max_length=100, unique=True)),
                (
                    "ownership_percentage",
                    models.DecimalField(decimal_places=8, max_digits=10),
                ),
                ("current_holder_id", models.UUIDField(db_index=True)),
                (
                    "automated_distribution_rules",
                    models.JSONField(blank=True, default=dict),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_records",
                        to="core_erp.tenant",
                    ),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="units",
                        to="tokenization.tokenizedasset",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DigitalRegistry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("from_holder_id", models.UUIDField(blank=True, null=True)),
                ("to_holder_id", models.UUIDField()),
                ("quantity", models.DecimalField(decimal_places=10, max_digits=30)),
                ("transaction_hash", models.CharField(max_length=64, unique=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_records",
                        to="core_erp.tenant",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="tokenization.programmablecapitalunit",
                    ),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tokenization.tokenizedasset",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
    ]
