# Generated by Django 5.2.6 on 2025-10-28 04:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contabilidad", "0001_initial"),
        ("prestadores", "0002_costo_inventario_productoservicio"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BankAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bank_name", models.CharField(max_length=255)),
                ("account_number", models.CharField(max_length=50)),
                ("account_holder", models.CharField(max_length=255)),
                (
                    "account_type",
                    models.CharField(
                        choices=[("SAVINGS", "Ahorros"), ("CHECKING", "Corriente")],
                        max_length=10,
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "linked_account",
                    models.OneToOneField(
                        blank=True,
                        help_text="Cuenta contable asociada a esta cuenta bancaria (ej. '111005 Bancos')",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contabilidad.chartofaccount",
                    ),
                ),
                (
                    "perfil",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bank_accounts",
                        to="prestadores.perfil",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cuenta Bancaria",
                "verbose_name_plural": "Cuentas Bancarias",
                "unique_together": {("perfil", "account_number", "bank_name")},
            },
        ),
        migrations.CreateModel(
            name="CashTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("DEPOSIT", "Depósito"),
                            ("WITHDRAWAL", "Retiro"),
                            ("TRANSFER", "Transferencia"),
                        ],
                        max_length=10,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("date", models.DateField()),
                ("description", models.TextField()),
                ("reference", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "bank_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="financiera.bankaccount",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "journal_entry",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="originating_cash_transaction",
                        to="contabilidad.journalentry",
                    ),
                ),
                (
                    "perfil",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cash_transactions",
                        to="prestadores.perfil",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transacción de Caja",
                "verbose_name_plural": "Transacciones de Caja",
                "ordering": ["-date"],
            },
        ),
    ]
