# Generated by Django 5.2.12 on 2026-03-15 13:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core_erp", "0001_initial_base"),
    ]

    operations = [
        migrations.CreateModel(
            name="GlobalCapitalAllocator",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("entity_id", models.UUIDField()),
                ("country_code", models.CharField(max_length=3)),
                ("capital_cost", models.DecimalField(decimal_places=4, max_digits=5)),
                ("risk_score", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "allocation_limit",
                    models.DecimalField(decimal_places=2, max_digits=20),
                ),
                (
                    "current_allocation",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                ("last_rebalance", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_records",
                        to="core_erp.tenant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JurisdictionConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("country_code", models.CharField(max_length=3, unique=True)),
                ("currency_code", models.CharField(max_length=3)),
                ("autonomy_level", models.IntegerField(default=1)),
                (
                    "tax_pressure_index",
                    models.DecimalField(decimal_places=4, max_digits=5),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("regulatory_rules", models.JSONField(blank=True, default=dict)),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_records",
                        to="core_erp.tenant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MacroScenario",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("title", models.CharField(max_length=255)),
                ("scenario_type", models.CharField(max_length=50)),
                (
                    "impact_ebitda_pct",
                    models.DecimalField(decimal_places=4, max_digits=5),
                ),
                (
                    "impact_liquidity_pct",
                    models.DecimalField(decimal_places=4, max_digits=5),
                ),
                ("probability", models.DecimalField(decimal_places=4, max_digits=5)),
                ("is_active_sim", models.BooleanField(default=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_records",
                        to="core_erp.tenant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TaxStrategy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("name", models.CharField(max_length=255)),
                ("jurisdiction_a", models.CharField(max_length=3)),
                ("jurisdiction_b", models.CharField(max_length=3)),
                (
                    "transfer_pricing_markup",
                    models.DecimalField(decimal_places=4, max_digits=5),
                ),
                (
                    "withholding_tax_rate",
                    models.DecimalField(decimal_places=4, max_digits=5),
                ),
                ("is_beps_compliant", models.BooleanField(default=True)),
                ("last_review_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_records",
                        to="core_erp.tenant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TreasuryPosition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("currency", models.CharField(max_length=3)),
                ("total_balance", models.DecimalField(decimal_places=2, max_digits=20)),
                (
                    "hedged_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                ("exposure_pct", models.DecimalField(decimal_places=4, max_digits=5)),
                ("hedge_strategy", models.CharField(blank=True, max_length=100)),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_records",
                        to="core_erp.tenant",
                    ),
                ),
            ],
        ),
    ]
