# Generated by Django 5.2.12 on 2026-03-15 12:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("companies", "0001_full_reset"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IndicadorLogistico",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("provider_id", models.UUIDField()),
                ("nombre", models.CharField(max_length=255)),
                ("valor", models.DecimalField(decimal_places=2, max_digits=18)),
                ("periodo", models.CharField(max_length=20)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="DeliveryCompany",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery_profile",
                        to="companies.company",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DeliveryService",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tourist_id",
                    models.IntegerField(
                        blank=True,
                        help_text="ID del CustomUser (aislamiento DB)",
                        null=True,
                    ),
                ),
                (
                    "provider_id",
                    models.UUIDField(
                        blank=True, help_text="ID del ProviderProfile", null=True
                    ),
                ),
                ("origin_address", models.CharField(max_length=500)),
                ("destination_address", models.CharField(max_length=500)),
                ("prioridad", models.CharField(default="NORMAL", max_length=20)),
                (
                    "estimated_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "final_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=18, null=True
                    ),
                ),
                (
                    "comision_repartidor",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "value_declared",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente"),
                            ("EN_PREPARACION", "En Preparación"),
                            ("LISTO_DESPACHO", "Listo para Despacho"),
                            ("EN_RUTA", "En Ruta"),
                            ("ENTREGADO", "Entregado"),
                            ("FALLIDO", "Fallido"),
                            ("REPROGRAMADO", "Reprogramado"),
                            ("CANCELADO", "Cancelado"),
                        ],
                        default="PENDIENTE",
                        max_length=20,
                    ),
                ),
                (
                    "wallet_transaction",
                    models.UUIDField(
                        blank=True,
                        help_text="ID de la transacción en apps.wallet",
                        null=True,
                    ),
                ),
                (
                    "governance_intention_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "related_operational_order_id",
                    models.UUIDField(blank=True, null=True),
                ),
                ("rating", models.PositiveIntegerField(blank=True, null=True)),
                ("tourist_comment", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "delivery_company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="delivery.deliverycompany",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DeliveryLiquidation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "total_to_provider",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "total_to_driver",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "platform_fee",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                ("is_processed", models.BooleanField(default=False)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "delivery",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="liquidation",
                        to="delivery.deliveryservice",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DeliveryItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "weight_kg",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "delivery",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="delivery.deliveryservice",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DeliveryIncident",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("severity", models.CharField(default="MEDIUM", max_length=20)),
                ("description", models.TextField()),
                ("is_resolved", models.BooleanField(default=False)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "delivery",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incidents",
                        to="delivery.deliveryservice",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DeliveryEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("event_type", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="delivery.deliveryservice",
                    ),
                ),
            ],
            options={
                "ordering": ["timestamp"],
            },
        ),
        migrations.CreateModel(
            name="Driver",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("license_number", models.CharField(max_length=100)),
                ("is_available", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "delivery_company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="drivers",
                        to="delivery.deliverycompany",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="driver_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="deliveryservice",
            name="driver",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="delivery.driver",
            ),
        ),
        migrations.CreateModel(
            name="DeliveryPenalty",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=18)),
                ("reason", models.CharField(max_length=255)),
                ("applied", models.BooleanField(default=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "delivery",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="delivery.deliveryservice",
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="penalties",
                        to="delivery.driver",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EvidenciaEntrega",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "foto",
                    models.ImageField(
                        blank=True, null=True, upload_to="delivery/evidencias/"
                    ),
                ),
                ("firma_digital", models.TextField(blank=True)),
                ("observaciones", models.TextField(blank=True)),
                ("latitud", models.FloatField(blank=True, null=True)),
                ("longitud", models.FloatField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "delivery",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidencia",
                        to="delivery.deliveryservice",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Ruta",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                ("zona", models.CharField(max_length=100)),
                ("activa", models.BooleanField(default=True)),
                (
                    "geodata",
                    models.JSONField(
                        default=dict, help_text="Coordenadas de la ruta optimizada"
                    ),
                ),
                ("tiempo_estimado_mins", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "repartidor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rutas",
                        to="delivery.driver",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="deliveryservice",
            name="ruta",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pedidos",
                to="delivery.ruta",
            ),
        ),
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "plate",
                    models.CharField(blank=True, max_length=20, null=True, unique=True),
                ),
                (
                    "vehicle_type",
                    models.CharField(
                        choices=[
                            ("MOTO", "Motocicleta"),
                            ("MOTOCARRO", "Motocarro"),
                            ("AUTO", "Automóvil"),
                            ("VAN", "Camioneta / Van"),
                            ("BICICLETA", "Bicicleta"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "capacity_kg",
                    models.DecimalField(decimal_places=2, default=5.0, max_digits=10),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "current_driver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="current_vehicles",
                        to="delivery.driver",
                    ),
                ),
                (
                    "delivery_company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vehicles",
                        to="delivery.deliverycompany",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="deliveryservice",
            name="vehicle",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="delivery.vehicle",
            ),
        ),
    ]
