# Generated by Django 5.2.6 on 2026-02-08 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliveryservice",
            name="rating",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="deliveryservice",
            name="related_operational_order_id",
            field=models.UUIDField(
                blank=True,
                help_text="ID de la Reserva/Orden Operativa vinculada",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="deliveryservice",
            name="tourist_comment",
            field=models.TextField(blank=True),
        ),
    ]
