# Generated by Django 5.2.12 on 2026-03-15 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0001_full_reset"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="driver",
            name="user",
        ),
        migrations.AddField(
            model_name="driver",
            name="user_id",
            field=models.IntegerField(
                blank=True,
                help_text="ID del CustomUser (aislamiento DB)",
                null=True,
                unique=True,
            ),
        ),
    ]
