# Generated by Django 5.2.6 on 2026-02-15 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0002_deliveryservice_rating_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deliveryservice",
            name="estimated_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
    ]
