# Generated by Django 5.2.12 on 2026-03-15 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0002_remove_driver_user_driver_user_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="deliverycompany",
            name="company",
        ),
        migrations.AddField(
            model_name="deliverycompany",
            name="company_id",
            field=models.UUIDField(
                blank=True,
                help_text="ID de la Company (aislamiento DB)",
                null=True,
                unique=True,
            ),
        ),
    ]
