# Generated by Django 6.0.3 on 2026-03-26 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0003_remove_deliverycompany_company_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliveryservice",
            name="department_code",
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name="deliveryservice",
            name="municipality_code",
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name="deliveryservice",
            name="sub_classification",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
