# Generated by Django 5.2.11 on 2026-02-16 00:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0003_alter_deliveryservice_estimated_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="IndicadorLogistico",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("provider_id", models.UUIDField()),
                ("nombre", models.CharField(max_length=255)),
                ("valor", models.DecimalField(decimal_places=2, max_digits=18)),
                ("periodo", models.CharField(max_length=20)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name="deliveryservice",
            name="comision_repartidor",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name="deliveryservice",
            name="prioridad",
            field=models.CharField(default="NORMAL", max_length=20),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="capacity_kg",
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="deliveryservice",
            name="provider_id",
            field=models.UUIDField(
                blank=True,
                help_text="ID del ProviderProfile (Dueño del producto)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="deliveryservice",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDIENTE", "Pendiente"),
                    ("EN_PREPARACION", "En Preparación"),
                    ("LISTO_DESPACHO", "Listo para Despacho"),
                    ("EN_RUTA", "En Ruta"),
                    ("ENTREGADO", "Entregado"),
                    ("FALLIDO", "Fallido"),
                    ("REPROGRAMADO", "Reprogramado"),
                    ("CANCELADO", "Cancelado"),
                ],
                default="PENDIENTE",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="plate",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="vehicle_type",
            field=models.CharField(
                choices=[
                    ("MOTO", "Motocicleta"),
                    ("MOTOCARRO", "Motocarro"),
                    ("AUTO", "Automóvil"),
                    ("VAN", "Camioneta / Van"),
                    ("BICICLETA", "Bicicleta"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="EvidenciaEntrega",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "foto",
                    models.ImageField(
                        blank=True, null=True, upload_to="delivery/evidencias/"
                    ),
                ),
                ("firma_digital", models.TextField(blank=True)),
                ("observaciones", models.TextField(blank=True)),
                ("latitud", models.FloatField(blank=True, null=True)),
                ("longitud", models.FloatField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "delivery",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidencia",
                        to="delivery.deliveryservice",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Ruta",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                ("zona", models.CharField(max_length=100)),
                ("activa", models.BooleanField(default=True)),
                (
                    "geodata",
                    models.JSONField(
                        default=dict, help_text="Coordenadas de la ruta optimizada"
                    ),
                ),
                ("tiempo_estimado_mins", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "repartidor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rutas",
                        to="delivery.driver",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="deliveryservice",
            name="ruta",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pedidos",
                to="delivery.ruta",
            ),
        ),
    ]
