# Generated by Django 5.2.6 on 2026-02-17 19:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0004_indicadorlogistico_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliveryservice",
            name="value_declared",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name="deliveryservice",
            name="provider_id",
            field=models.UUIDField(
                blank=True, help_text="ID del ProviderProfile", null=True
            ),
        ),
        migrations.AlterField(
            model_name="deliveryservice",
            name="related_operational_order_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="DeliveryIncident",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("reason", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("resolved", models.BooleanField(default=False)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "delivery",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incidents",
                        to="delivery.deliveryservice",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DeliveryItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "weight_kg",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "delivery",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="delivery.deliveryservice",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DeliveryLiquidation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "amount_provider",
                    models.DecimalField(decimal_places=2, max_digits=18),
                ),
                (
                    "amount_delivery",
                    models.DecimalField(decimal_places=2, max_digits=18),
                ),
                (
                    "amount_platform",
                    models.DecimalField(decimal_places=2, max_digits=18),
                ),
                ("processed", models.BooleanField(default=False)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "delivery",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="liquidation",
                        to="delivery.deliveryservice",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DeliveryPenalty",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=18)),
                ("reason", models.CharField(max_length=255)),
                ("applied", models.BooleanField(default=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "delivery",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="delivery.deliveryservice",
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="penalties",
                        to="delivery.driver",
                    ),
                ),
            ],
        ),
    ]
