# Generated by Django 5.2.6 on 2026-02-17 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0005_deliveryservice_value_declared_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="deliveryincident",
            name="reason",
        ),
        migrations.RemoveField(
            model_name="deliveryincident",
            name="resolved",
        ),
        migrations.AddField(
            model_name="deliveryincident",
            name="is_resolved",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="deliveryincident",
            name="severity",
            field=models.CharField(default="MEDIUM", max_length=20),
        ),
    ]
