# Generated by Django 5.2.6 on 2026-02-17 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0006_remove_deliveryincident_reason_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="deliveryliquidation",
            name="amount_delivery",
        ),
        migrations.RemoveField(
            model_name="deliveryliquidation",
            name="amount_platform",
        ),
        migrations.RemoveField(
            model_name="deliveryliquidation",
            name="amount_provider",
        ),
        migrations.RemoveField(
            model_name="deliveryliquidation",
            name="processed",
        ),
        migrations.AddField(
            model_name="deliveryliquidation",
            name="is_processed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="deliveryliquidation",
            name="platform_fee",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name="deliveryliquidation",
            name="total_to_driver",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name="deliveryliquidation",
            name="total_to_provider",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
    ]
