# Generated by Django 5.2.10 on 2026-01-30 00:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FinancialEventRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("event_type", models.CharField(db_index=True, max_length=50)),
                ("session_id", models.CharField(db_index=True, max_length=100)),
                ("value", models.FloatField(default=0.0)),
                ("metadata", models.JSONField(default=dict)),
                ("timestamp", models.DateTimeField(db_index=True)),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="FinancialMetric",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("metric_name", models.CharField(max_length=20)),
                ("dimension", models.CharField(max_length=100)),
                ("value", models.FloatField()),
                ("calculated_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-calculated_at"],
            },
        ),
    ]
