# Generated by Django 5.2.11 on 2026-02-16 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0002_walletaccount_locked_balance_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="wallettransaction",
            name="idempotency_key",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="wallettransaction",
            name="signature",
            field=models.TextField(
                blank=True, help_text="Firma digital interna", null=True
            ),
        ),
        migrations.AlterField(
            model_name="walletaccount",
            name="owner_type",
            field=models.CharField(
                choices=[
                    ("TOURIST", "Turista"),
                    ("PROVIDER", "Prestador"),
                    ("DELIVERY", "Delivery"),
                    ("EMPLOYEE", "Empleado"),
                    ("CORPORATE", "Corporativo Interno"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="walletaccount",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "Activo"),
                    ("FROZEN", "Congelado"),
                    ("BLOCKED", "Bloqueado"),
                    ("AUDITED", "En Auditoría"),
                ],
                default="ACTIVE",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="wallettransaction",
            name="integrity_hash",
            field=models.CharField(
                blank=True,
                help_text="Hash SHA-256 encadenado",
                max_length=64,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="wallettransaction",
            name="type",
            field=models.CharField(
                choices=[
                    ("RECHARGE", "Recarga Manual"),
                    ("AUTO_RECHARGE", "Recarga Automática por Venta"),
                    ("DEPOSIT", "Depósito"),
                    ("PAYMENT", "Pago / Débito por Compra"),
                    ("TRANSFER", "Transferencia Interna"),
                    ("CASHBACK", "Cashback"),
                    ("COMMISSION", "Comisión"),
                    ("RETENTION", "Retención"),
                    ("REFUND", "Reembolso"),
                    ("REVERSAL", "Reversión"),
                    ("ADJUSTMENT", "Ajuste Administrativo"),
                    ("LIQUIDATION", "Liquidación"),
                    ("FREEZE", "Congelamiento"),
                ],
                max_length=20,
            ),
        ),
    ]
