# Generated by Django 5.2.6 on 2026-02-16 15:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0003_wallettransaction_idempotency_key_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wallettransaction",
            name="timestamp",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
