# Generated by Django 5.2.6 on 2026-02-17 20:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0004_alter_wallettransaction_timestamp"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WalletTransaccion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "referencia_operativa",
                    models.CharField(
                        help_text="Referencia al servicio (Booking ID, Order ID, etc.)",
                        max_length=255,
                    ),
                ),
                ("monto_total", models.DecimalField(decimal_places=2, max_digits=18)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente"),
                            ("PROCESANDO", "En Proceso"),
                            ("COMPLETADA", "Completada con Éxito"),
                            ("FALLIDA", "Fallida / Rechazada"),
                            ("REVERTIDA", "Revertida Totalmente"),
                        ],
                        default="PENDIENTE",
                        max_length=20,
                    ),
                ),
                (
                    "governance_intention_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Transacción de Monedero",
                "verbose_name_plural": "Transacciones de Monedero",
            },
        ),
        migrations.RemoveField(
            model_name="wallettransaction",
            name="from_wallet",
        ),
        migrations.RemoveField(
            model_name="wallettransaction",
            name="to_wallet",
        ),
        migrations.CreateModel(
            name="Wallet",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "owner_type",
                    models.CharField(
                        choices=[
                            ("AGENCIA", "Agencia de Viajes"),
                            ("HOTEL", "Hotel / Alojamiento"),
                            ("GUIA", "Guía Turístico"),
                            ("TRANSPORTE", "Transporte Turístico"),
                            ("ARTESANO", "Artesano / Productor"),
                            ("TURISTA", "Turista / Cliente Final"),
                            ("DELIVERY", "Servicio de Delivery"),
                            ("EMPLEADO", "Empleado / Nómina"),
                            ("CORPORATIVO", "Corporativo Interno Sarita"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "owner_id",
                    models.CharField(
                        help_text="ID del perfil de negocio o usuario", max_length=255
                    ),
                ),
                (
                    "saldo_disponible",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=18),
                ),
                (
                    "saldo_bloqueado",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=18),
                ),
                (
                    "saldo_en_proceso",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=18),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("ACTIVO", "Activo"),
                            ("SUSPENDIDO", "Suspendido"),
                            ("BLOQUEADO", "Bloqueado por Seguridad"),
                            ("AUDITORIA", "En Proceso de Auditoría"),
                        ],
                        default="ACTIVO",
                        max_length=20,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sarita_wallets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Monedero",
                "verbose_name_plural": "Monederos",
                "unique_together": {("owner_type", "owner_id")},
            },
        ),
        migrations.CreateModel(
            name="WalletAuditoria",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tipo_hallazgo", models.CharField(max_length=100)),
                ("descripcion", models.TextField()),
                (
                    "nivel_riesgo",
                    models.CharField(
                        choices=[
                            ("BAJO", "Bajo"),
                            ("MEDIO", "Medio"),
                            ("ALTO", "Alto"),
                            ("CRITICO", "Crítico"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "resultado_esperado",
                    models.DecimalField(decimal_places=2, max_digits=18),
                ),
                (
                    "resultado_real",
                    models.DecimalField(decimal_places=2, max_digits=18),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="wallet.wallet"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WalletLimiteOperativo",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "monto_maximo_transaccion",
                    models.DecimalField(decimal_places=2, max_digits=18),
                ),
                (
                    "monto_maximo_diario",
                    models.DecimalField(decimal_places=2, max_digits=18),
                ),
                ("requiere_aprobacion_soberana", models.BooleanField(default=False)),
                (
                    "wallet",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="limite",
                        to="wallet.wallet",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WalletLiquidacion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("monto", models.DecimalField(decimal_places=2, max_digits=18)),
                ("periodo_inicio", models.DateField()),
                ("periodo_fin", models.DateField()),
                (
                    "comprobante_pago",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="wallet.wallet"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WalletReversion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("motivo", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "autorizado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "transaccion_original",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reversiones",
                        to="wallet.wallettransaccion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WalletMovimiento",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("INGRESO", "Ingreso de Fondos"),
                            ("COMISION", "Comisión"),
                            ("LIQUIDACION", "Liquidación"),
                            ("REVERSION", "Reversión"),
                            ("RETENCION", "Retención Temporal"),
                            ("PAGO", "Pago por Servicio"),
                        ],
                        max_length=20,
                    ),
                ),
                ("monto", models.DecimalField(decimal_places=2, max_digits=18)),
                ("referencia_modelo", models.CharField(max_length=100)),
                ("referencia_id", models.CharField(max_length=255)),
                ("hash_integridad", models.CharField(editable=False, max_length=64)),
                ("creado_por_sistema", models.BooleanField(default=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movimientos",
                        to="wallet.wallet",
                    ),
                ),
                (
                    "transaccion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movimientos",
                        to="wallet.wallettransaccion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WalletComision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("monto", models.DecimalField(decimal_places=2, max_digits=18)),
                ("porcentaje", models.DecimalField(decimal_places=2, max_digits=5)),
                ("descripcion", models.CharField(max_length=255)),
                (
                    "receptor_wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="wallet.wallet"
                    ),
                ),
                (
                    "transaccion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comisiones",
                        to="wallet.wallettransaccion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WalletBloqueo",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("monto", models.DecimalField(decimal_places=2, max_digits=18)),
                ("motivo", models.CharField(max_length=255)),
                ("activo", models.BooleanField(default=True)),
                ("liberado_en", models.DateTimeField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bloqueos",
                        to="wallet.wallet",
                    ),
                ),
                (
                    "transaccion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wallet.wallettransaccion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WalletAlertaRiesgo",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("codigo_alerta", models.CharField(max_length=50)),
                ("descripcion", models.TextField()),
                ("atendida", models.BooleanField(default=False)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="wallet.wallet"
                    ),
                ),
                (
                    "transaccion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wallet.wallettransaccion",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="WalletAccount",
        ),
        migrations.DeleteModel(
            name="WalletTransaction",
        ),
    ]
