# Generated by Django 5.2.6 on 2026-01-09 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nomina", "0001_initial"),
        ("prestadores", "0003_categoriaprestador_providerprofile_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="empleado",
            name="perfil",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="empleados",
                to="prestadores.providerprofile",
            ),
        ),
        migrations.AlterField(
            model_name="planilla",
            name="perfil",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="planillas",
                to="prestadores.providerprofile",
            ),
        ),
    ]
