# Generated by Django 6.0.3 on 2026-03-23 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("prestadores", "0001_full_reset"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaqueteTuristico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("descripcion", models.TextField()),
                ("duracion_dias", models.PositiveIntegerField(default=1)),
                (
                    "precio_por_persona",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "servicios_incluidos",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Lista de IDs de productos/servicios genéricos incluidos.",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("borrador", "Borrador"),
                            ("publicado", "Publicado"),
                            ("archivado", "Archivado"),
                        ],
                        default="borrador",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "perfil",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paquetes_turisticos",
                        to="prestadores.providerprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReservaPaquete",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre_cliente_temporal",
                    models.CharField(
                        help_text="Nombre del cliente que hace la reserva",
                        max_length=150,
                    ),
                ),
                ("email_cliente", models.EmailField(max_length=254)),
                ("telefono_cliente", models.CharField(blank=True, max_length=20)),
                ("fecha_inicio", models.DateField()),
                ("numero_de_personas", models.PositiveIntegerField(default=1)),
                ("costo_total", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente de Confirmación"),
                            ("confirmada", "Confirmada"),
                            ("pagada", "Pagada"),
                            ("cancelada", "Cancelada"),
                            ("completada", "Completada"),
                        ],
                        default="pendiente",
                        max_length=15,
                    ),
                ),
                (
                    "notas_especiales",
                    models.TextField(
                        blank=True,
                        help_text="Requerimientos o notas especiales del cliente.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "paquete",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservas",
                        to="agencias_de_viajes.paqueteturistico",
                    ),
                ),
            ],
        ),
    ]
