# Generated by Django 5.2.6 on 2026-01-22 19:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre legal y completo de la empresa cliente.",
                        max_length=200,
                        unique=True,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Código corto y único usado en la codificación de documentos (ej. SNT, TRVW).",
                        max_length=10,
                        unique=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indica si la suscripción de la compañía está activa. Desmarcar para suspender el acceso.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Company (Tenant)",
                "verbose_name_plural": "Companies (Tenants)",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="CompanyEncryptionKey",
            fields=[
                (
                    "company",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="encryption_key",
                        serialize=False,
                        to="companies.company",
                    ),
                ),
                (
                    "key_salt",
                    models.CharField(
                        help_text="Sal criptográfica única generada para la derivación de claves.",
                        max_length=255,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
