# Generated by Django 5.2.6 on 2025-11-08 22:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyEncryptionKey",
            fields=[
                (
                    "company",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="encryption_key",
                        serialize=False,
                        to="companies.company",
                    ),
                ),
                (
                    "key_salt",
                    models.CharField(
                        help_text="Sal criptográfica única generada para la derivación de claves.",
                        max_length=255,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name="company",
            options={
                "ordering": ["name"],
                "verbose_name": "Company (Tenant)",
                "verbose_name_plural": "Companies (Tenants)",
            },
        ),
        migrations.AddField(
            model_name="company",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="company",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Indica si la suscripción de la compañía está activa. Desmarcar para suspender el acceso.",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="updated_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="company",
            name="code",
            field=models.CharField(
                help_text="Código corto y único usado en la codificación de documentos (ej. SNT, TRVW).",
                max_length=10,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="name",
            field=models.CharField(
                help_text="Nombre legal y completo de la empresa cliente.",
                max_length=200,
                unique=True,
            ),
        ),
    ]
