# Generated by Django 5.2.6 on 2025-11-09 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0002_companyencryptionkey_alter_company_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
