# Generated by Django 5.2.12 on 2026-03-15 13:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core_erp", "0001_initial_base"),
    ]

    operations = [
        migrations.CreateModel(
            name="CashOptimizationProposal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("source_entity_id", models.UUIDField()),
                ("target_entity_id", models.UUIDField()),
                (
                    "suggested_amount",
                    models.DecimalField(decimal_places=2, max_digits=20),
                ),
                ("currency", models.CharField(max_length=3)),
                ("reasoning", models.TextField()),
                ("priority", models.IntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("EXECUTED", "Executed"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_records",
                        to="core_erp.tenant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DecisionLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("decision_type", models.CharField(max_length=100)),
                ("input_payload", models.JSONField()),
                ("output_result", models.JSONField()),
                ("actor_id", models.CharField(max_length=100)),
                ("reasoning", models.TextField(blank=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_records",
                        to="core_erp.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="EnterpriseDecisionRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("trigger_metric", models.CharField(max_length=100)),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("LT", "<"),
                            ("GT", ">"),
                            ("LTE", "<="),
                            ("GTE", ">="),
                        ],
                        max_length=10,
                    ),
                ),
                ("threshold", models.DecimalField(decimal_places=2, max_digits=20)),
                ("recommended_action", models.CharField(max_length=255)),
                ("auto_execute", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_records",
                        to="core_erp.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Decision Rule",
            },
        ),
        migrations.CreateModel(
            name="EnterprisePolicy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("TENANT", "Tenant"),
                            ("ENTITY", "Legal Entity"),
                            ("HOLDING", "Holding"),
                            ("GLOBAL", "Global System"),
                        ],
                        default="TENANT",
                        max_length=50,
                    ),
                ),
                (
                    "metric_name",
                    models.CharField(
                        help_text="KPI name to monitor (e.g., EBITDA_MARGIN)",
                        max_length=100,
                    ),
                ),
                ("threshold", models.DecimalField(decimal_places=2, max_digits=20)),
                (
                    "operator",
                    models.CharField(
                        choices=[
                            ("GT", ">"),
                            ("LT", "<"),
                            ("EQ", "=="),
                            ("GTE", ">="),
                            ("LTE", "<="),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "action_on_breach",
                    models.CharField(
                        choices=[
                            ("ALERT", "Trigger Alert"),
                            ("BLOCK", "Block Operation"),
                            ("ESCALATE", "Escalate to CFO"),
                            ("ADJUST_BUDGET", "Adjust Budget"),
                            ("WORKFLOW", "Trigger Corrective Workflow"),
                            ("OPTIMIZE", "Self-Optimize Policy"),
                        ],
                        default="ALERT",
                        max_length=50,
                    ),
                ),
                ("action_params", models.JSONField(blank=True, default=dict)),
                (
                    "autonomy_level",
                    models.IntegerField(
                        default=0,
                        help_text="0: Alert, 1: Recommend, 2: Execute (Confirm), 3: Auto-Execute, 4: Adjust Rules, 5: Strategic Optimization",
                    ),
                ),
                (
                    "dynamic_threshold_model",
                    models.CharField(
                        blank=True,
                        help_text="ML model name for dynamic thresholds",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("escalation_matrix", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_records",
                        to="core_erp.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Enterprise Policy",
            },
        ),
        migrations.CreateModel(
            name="AutonomousActionRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("autonomy_level", models.IntegerField()),
                ("execution_payload", models.JSONField()),
                ("outcome_status", models.CharField(max_length=50)),
                ("correlation_id", models.UUIDField(db_index=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_records",
                        to="core_erp.tenant",
                    ),
                ),
                (
                    "policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="enterprise.enterprisepolicy",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EnterpriseWorkflow",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PLANNED", "Planned"),
                            ("RUNNING", "Running"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                            ("COMPENSATING", "Compensating"),
                        ],
                        default="PLANNED",
                        max_length=20,
                    ),
                ),
                ("context_data", models.JSONField(blank=True, default=dict)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_records",
                        to="core_erp.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Enterprise Workflow",
            },
        ),
        migrations.CreateModel(
            name="LearningLoopRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("engine_name", models.CharField(max_length=100)),
                ("input_trend_data", models.JSONField()),
                ("previous_rule_state", models.JSONField()),
                ("suggested_rule_state", models.JSONField()),
                (
                    "impact_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "confidence_level",
                    models.DecimalField(decimal_places=4, max_digits=5),
                ),
                ("is_applied", models.BooleanField(default=False)),
                ("applied_at", models.DateTimeField(blank=True, null=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_records",
                        to="core_erp.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Learning Loop Record",
            },
        ),
        migrations.CreateModel(
            name="PolicyEvaluationLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("metric_value", models.DecimalField(decimal_places=2, max_digits=20)),
                ("was_breached", models.BooleanField()),
                ("action_taken", models.CharField(blank=True, max_length=100)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="enterprise.enterprisepolicy",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_records",
                        to="core_erp.tenant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RiskExposure",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "risk_type",
                    models.CharField(
                        choices=[
                            ("FINANCIAL", "Financial Liquidity"),
                            ("FISCAL", "Fiscal Compliance"),
                            ("FX", "Currency Exposure"),
                            ("CONCENTRATION", "Revenue Concentration"),
                            ("COUNTRY", "Country Risk"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "exposure_value",
                    models.DecimalField(decimal_places=2, max_digits=20),
                ),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                        ],
                        max_length=20,
                    ),
                ),
                ("factors", models.JSONField(default=dict)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_records",
                        to="core_erp.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Risk Exposure",
            },
        ),
        migrations.CreateModel(
            name="RollingForecast",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("fiscal_year", models.IntegerField()),
                ("month", models.IntegerField()),
                (
                    "base_budget_revenue",
                    models.DecimalField(decimal_places=2, max_digits=20),
                ),
                (
                    "actual_revenue_mtd",
                    models.DecimalField(decimal_places=2, max_digits=20),
                ),
                (
                    "projected_variance",
                    models.DecimalField(decimal_places=2, max_digits=20),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_records",
                        to="core_erp.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rolling Forecast",
            },
        ),
        migrations.CreateModel(
            name="ScenarioSimulation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "revenue_growth_rate",
                    models.DecimalField(
                        decimal_places=4, help_text="e.g. 0.05 for 5%", max_digits=5
                    ),
                ),
                (
                    "fx_variation",
                    models.DecimalField(decimal_places=4, default=0, max_digits=5),
                ),
                (
                    "cost_inflation",
                    models.DecimalField(decimal_places=4, default=0, max_digits=5),
                ),
                (
                    "projected_ebitda",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                (
                    "projected_cash_position",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_records",
                        to="core_erp.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Scenario Simulation",
            },
        ),
        migrations.CreateModel(
            name="SelfHealingAudit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("issue_type", models.CharField(max_length=100)),
                ("target_id", models.UUIDField()),
                ("action_taken", models.CharField(max_length=255)),
                ("result", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_records",
                        to="core_erp.tenant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StrategicObjective",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("target_value", models.DecimalField(decimal_places=2, max_digits=20)),
                (
                    "current_value",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
                ),
                ("unit", models.CharField(max_length=20)),
                ("deadline", models.DateField()),
                ("priority", models.IntegerField(default=1)),
                ("is_achieved", models.BooleanField(default=False)),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_records",
                        to="core_erp.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Strategic Objective",
            },
        ),
        migrations.CreateModel(
            name="WorkflowStep",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("order", models.PositiveIntegerField()),
                ("name", models.CharField(max_length=255)),
                ("target_domain", models.CharField(max_length=100)),
                ("action_name", models.CharField(max_length=255)),
                ("params", models.JSONField(blank=True, default=dict)),
                ("status", models.CharField(default="PENDING", max_length=20)),
                ("error_log", models.TextField(blank=True, null=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_records",
                        to="core_erp.tenant",
                    ),
                ),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="enterprise.enterpriseworkflow",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="CorporateBudget",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("legal_entity_id", models.UUIDField(blank=True, null=True)),
                ("fiscal_year", models.IntegerField()),
                (
                    "revenue_target",
                    models.DecimalField(decimal_places=2, max_digits=20),
                ),
                ("expense_limit", models.DecimalField(decimal_places=2, max_digits=20)),
                ("ebitda_target", models.DecimalField(decimal_places=2, max_digits=20)),
                (
                    "actual_revenue",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
                ),
                (
                    "actual_expense",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("APPROVED", "Approved"),
                            ("LOCKED", "Locked"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_records",
                        to="core_erp.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Corporate Budget",
                "unique_together": {("tenant", "legal_entity_id", "fiscal_year")},
            },
        ),
    ]
