# Generated by Django 6.0.3 on 2026-03-23 21:30

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("gestion_comercial", "0001_full_reset"),
        ("prestadores", "0001_full_reset"),
    ]

    operations = [
        migrations.CreateModel(
            name="Factura",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("numero_factura", models.CharField(max_length=50, unique=True)),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                ("total", models.DecimalField(decimal_places=2, max_digits=18)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("BORRADOR", "Borrador"),
                            ("EMITIDA", "Emitida"),
                            ("ANULADA", "Anulada"),
                        ],
                        default="BORRADOR",
                        max_length=20,
                    ),
                ),
                ("cufe", models.CharField(blank=True, max_length=255, null=True)),
                ("qr_code_url", models.URLField(blank=True, null=True)),
                (
                    "provider",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_items",
                        to="prestadores.providerprofile",
                    ),
                ),
                (
                    "venta",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="factura",
                        to="gestion_comercial.venta",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
    ]
