# Generated by Django 5.2.6 on 2025-10-16 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("api", "0002_delete_detalleshotel"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("empresa", "0003_cliente"),
    ]

    operations = [
        migrations.CreateModel(
            name="Hotel",
            fields=[
                (
                    "prestador",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="hotel_profile",
                        serialize=False,
                        to="api.prestadorservicio",
                    ),
                ),
                (
                    "categoria_estrellas",
                    models.PositiveIntegerField(
                        default=3, help_text="Número de estrellas del hotel"
                    ),
                ),
                (
                    "reporte_ocupacion_nacional",
                    models.PositiveIntegerField(
                        default=0, help_text="Exclusivo para hoteles"
                    ),
                ),
                (
                    "reporte_ocupacion_internacional",
                    models.PositiveIntegerField(
                        default=0, help_text="Exclusivo para hoteles"
                    ),
                ),
            ],
            options={
                "verbose_name": "Perfil de Hotel",
                "verbose_name_plural": "Perfiles de Hotel",
            },
        ),
        migrations.CreateModel(
            name="Habitacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_o_numero", models.CharField(max_length=100)),
                (
                    "tipo_habitacion",
                    models.CharField(
                        choices=[
                            ("INDIVIDUAL", "Individual"),
                            ("DOBLE", "Doble"),
                            ("SUITE", "Suite"),
                            ("FAMILIAR", "Familiar"),
                        ],
                        max_length=50,
                    ),
                ),
                ("capacidad", models.PositiveIntegerField(default=1)),
                (
                    "precio_por_noche",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("disponible", models.BooleanField(default=True)),
                (
                    "hotel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="habitaciones",
                        to="turismo.hotel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Habitación",
                "verbose_name_plural": "Habitaciones",
            },
        ),
        migrations.CreateModel(
            name="Reserva",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveIntegerField(null=True)),
                ("fecha_inicio_reserva", models.DateTimeField()),
                ("fecha_fin_reserva", models.DateTimeField(blank=True, null=True)),
                ("numero_personas", models.PositiveIntegerField(default=1)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente"),
                            ("CONFIRMADA", "Confirmada"),
                            ("CANCELADA", "Cancelada"),
                            ("COMPLETADA", "Completada"),
                        ],
                        default="PENDIENTE",
                        max_length=20,
                    ),
                ),
                (
                    "monto_total",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                ("notas_reserva", models.TextField(blank=True, null=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        blank=True,
                        help_text="Cliente del CRM asociado a la reserva.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="empresa.cliente",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "prestador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservas",
                        to="api.prestadorservicio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reserva",
                "verbose_name_plural": "Reservas",
                "ordering": ["-fecha_inicio_reserva"],
            },
        ),
        migrations.CreateModel(
            name="Tarifa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        help_text="Ej: 'Tarifa Fin de Semana', 'Temporada Alta'",
                        max_length=150,
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                ("precio", models.DecimalField(decimal_places=2, max_digits=12)),
                ("fecha_inicio", models.DateField()),
                ("fecha_fin", models.DateField()),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "prestador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tarifas",
                        to="api.prestadorservicio",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Disponibilidad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                ("fecha", models.DateField()),
                ("cupos_totales", models.PositiveIntegerField(default=1)),
                ("cupos_ocupados", models.PositiveIntegerField(default=0)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "prestador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="disponibilidades",
                        to="api.prestadorservicio",
                    ),
                ),
            ],
            options={
                "unique_together": {("content_type", "object_id", "fecha")},
            },
        ),
    ]
