# Generated by Django 5.2.6 on 2025-10-15 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("api", "0002_delete_detalleshotel"),
    ]

    operations = [
        migrations.CreateModel(
            name="DetallesHotel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reporte_ocupacion_nacional",
                    models.PositiveIntegerField(
                        default=0, help_text="Exclusivo para hoteles"
                    ),
                ),
                (
                    "reporte_ocupacion_internacional",
                    models.PositiveIntegerField(
                        default=0, help_text="Exclusivo para hoteles"
                    ),
                ),
                (
                    "prestador",
                    models.OneToOneField(
                        limit_choices_to={"categoria__slug": "hoteles"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detalles_hotel",
                        to="api.prestadorservicio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Detalles de Hotel",
                "verbose_name_plural": "Detalles de Hoteles",
                "db_table": "api_detalleshotel",
            },
        ),
    ]
