# Generated by Django 5.2.6 on 2025-10-19 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prestadores", "0002_cliente"),
        ("turismo", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reserva",
            name="cliente",
            field=models.ForeignKey(
                blank=True,
                help_text="Cliente del CRM asociado a la reserva.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="prestadores.cliente",
            ),
        ),
    ]
