# Generated by Django 5.2.6 on 2025-10-15 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_delete_detalleshotel"),
        ("turismo", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Hotel",
            fields=[
                (
                    "prestador",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="hotel_profile",
                        serialize=False,
                        to="api.prestadorservicio",
                    ),
                ),
                (
                    "categoria_estrellas",
                    models.PositiveIntegerField(
                        default=3, help_text="Número de estrellas del hotel"
                    ),
                ),
                (
                    "reporte_ocupacion_nacional",
                    models.PositiveIntegerField(
                        default=0, help_text="Exclusivo para hoteles"
                    ),
                ),
                (
                    "reporte_ocupacion_internacional",
                    models.PositiveIntegerField(
                        default=0, help_text="Exclusivo para hoteles"
                    ),
                ),
            ],
            options={
                "verbose_name": "Perfil de Hotel",
                "verbose_name_plural": "Perfiles de Hotel",
            },
        ),
        migrations.CreateModel(
            name="Habitacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_o_numero", models.CharField(max_length=100)),
                (
                    "tipo_habitacion",
                    models.CharField(
                        choices=[
                            ("INDIVIDUAL", "Individual"),
                            ("DOBLE", "Doble"),
                            ("SUITE", "Suite"),
                            ("FAMILIAR", "Familiar"),
                        ],
                        max_length=50,
                    ),
                ),
                ("capacidad", models.PositiveIntegerField(default=1)),
                (
                    "precio_por_noche",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("disponible", models.BooleanField(default=True)),
                (
                    "hotel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="habitaciones",
                        to="turismo.hotel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Habitación",
                "verbose_name_plural": "Habitaciones",
            },
        ),
        migrations.DeleteModel(
            name="DetallesHotel",
        ),
    ]
