# Generated by Django 5.2.6 on 2025-10-15 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_delete_detalleshotel"),
        ("turismo", "0002_hotel_habitacion_delete_detalleshotel"),
    ]

    operations = [
        migrations.CreateModel(
            name="GuiaTuristico",
            fields=[
                (
                    "prestador",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="guia_profile",
                        serialize=False,
                        to="api.prestadorservicio",
                    ),
                ),
                (
                    "idiomas",
                    models.CharField(
                        help_text="Idiomas que domina, separados por coma",
                        max_length=200,
                    ),
                ),
                (
                    "especialidades",
                    models.TextField(
                        blank=True,
                        help_text="Áreas de especialización, ej: Ecoturismo, Historia, Aventura",
                    ),
                ),
                (
                    "rutas_asignadas",
                    models.ManyToManyField(
                        blank=True,
                        related_name="guias_asignados",
                        to="api.rutaturistica",
                    ),
                ),
            ],
            options={
                "verbose_name": "Perfil de Guía Turístico",
                "verbose_name_plural": "Perfiles de Guías Turísticos",
            },
        ),
        migrations.CreateModel(
            name="PaqueteTuristico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("descripcion", models.TextField()),
                (
                    "servicios_incluidos",
                    models.TextField(
                        help_text="Descripción de los servicios incluidos (ej. Alojamiento, Transporte, Guía)."
                    ),
                ),
                (
                    "precio_por_persona",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("duracion_dias", models.PositiveIntegerField(default=1)),
                (
                    "es_publico",
                    models.BooleanField(
                        default=False,
                        help_text="Marcar para que el paquete sea visible al público.",
                    ),
                ),
                (
                    "atractivos",
                    models.ManyToManyField(
                        blank=True, related_name="paquetes", to="api.atractivoturistico"
                    ),
                ),
                (
                    "prestador_agencia",
                    models.ForeignKey(
                        help_text="La agencia de viajes que crea y vende el paquete.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paquetes_ofrecidos",
                        to="api.prestadorservicio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Paquete Turístico",
                "verbose_name_plural": "Paquetes Turísticos",
            },
        ),
        migrations.CreateModel(
            name="VehiculoTuristico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("placa", models.CharField(max_length=10, unique=True)),
                ("marca", models.CharField(max_length=50)),
                ("modelo", models.CharField(max_length=50)),
                (
                    "tipo_vehiculo",
                    models.CharField(
                        choices=[
                            ("BUS", "Autobús"),
                            ("BUSETA", "Buseta"),
                            ("VAN", "Van de Turismo"),
                            ("AUTOMOVIL", "Automóvil Particular"),
                            ("CHIVA", "Chiva Turística"),
                            ("LANCHA", "Lancha Fluvial"),
                        ],
                        max_length=50,
                    ),
                ),
                ("capacidad", models.PositiveIntegerField()),
                (
                    "documentacion_al_dia",
                    models.BooleanField(
                        default=True,
                        help_text="Indica si el SOAT, tecnomecánica, y otros permisos están vigentes.",
                    ),
                ),
                (
                    "foto",
                    models.ImageField(blank=True, null=True, upload_to="vehiculos/"),
                ),
                (
                    "prestador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vehiculos",
                        to="api.prestadorservicio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vehículo Turístico",
                "verbose_name_plural": "Vehículos Turísticos",
            },
        ),
    ]
