# Generated by Django 5.2.6 on 2025-10-15 18:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_delete_detalleshotel"),
        ("turismo", "0002_hotel_habitacion_delete_detalleshotel"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Reserva",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre_cliente_externo",
                    models.CharField(
                        blank=True,
                        help_text="Nombre del cliente si no es un usuario registrado",
                        max_length=200,
                    ),
                ),
                ("fecha_inicio", models.DateTimeField()),
                ("fecha_fin", models.DateTimeField()),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente"),
                            ("CONFIRMADA", "Confirmada"),
                            ("CANCELADA", "Cancelada"),
                            ("COMPLETADA", "Completada"),
                        ],
                        default="PENDIENTE",
                        max_length=50,
                    ),
                ),
                ("notas", models.TextField(blank=True, null=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reservas_hechas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "prestador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservas",
                        to="api.prestadorservicio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reserva",
                "verbose_name_plural": "Reservas",
                "ordering": ["-fecha_inicio"],
            },
        ),
    ]
