# Generated by Django 5.2.6 on 2025-10-17 14:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_delete_detalleshotel"),
        ("turismo", "0002_hotel_habitacion_delete_detalleshotel"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GuiaTuristico",
            fields=[
                (
                    "prestador",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="perfil_guia",
                        serialize=False,
                        to="api.prestadorservicio",
                    ),
                ),
                (
                    "idiomas",
                    models.CharField(
                        help_text="Idiomas que domina, separados por coma",
                        max_length=255,
                    ),
                ),
                (
                    "especialidades",
                    models.CharField(
                        help_text="Áreas de especialidad, ej: Avistamiento de aves, Historia",
                        max_length=255,
                    ),
                ),
                ("experiencia_anos", models.PositiveIntegerField(default=1)),
            ],
            options={
                "verbose_name": "Perfil de Guía Turístico",
                "verbose_name_plural": "Perfiles de Guía Turístico",
            },
        ),
        migrations.CreateModel(
            name="PaqueteTuristico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("descripcion", models.TextField()),
                ("precio", models.DecimalField(decimal_places=2, max_digits=12)),
                ("fecha_inicio_validez", models.DateField()),
                ("fecha_fin_validez", models.DateField()),
                ("activo", models.BooleanField(default=True)),
                (
                    "prestador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paquetes_turisticos",
                        to="api.prestadorservicio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Paquete Turístico",
                "verbose_name_plural": "Paquetes Turísticos",
            },
        ),
        migrations.CreateModel(
            name="ReservaTuristica",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha_inicio_reserva",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("fecha_fin_reserva", models.DateTimeField()),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente"),
                            ("CONFIRMADA", "Confirmada"),
                            ("CANCELADA", "Cancelada"),
                            ("COMPLETADA", "Completada"),
                        ],
                        default="PENDIENTE",
                        max_length=20,
                    ),
                ),
                (
                    "monto_total",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                ("notas_adicionales", models.TextField(blank=True, null=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "prestador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservas_turismo",
                        to="api.prestadorservicio",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reservas_realizadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Reserva Turística",
                "verbose_name_plural": "Reservas Turísticas",
                "ordering": ["-fecha_inicio_reserva"],
            },
        ),
        migrations.CreateModel(
            name="VehiculoTuristico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("placa", models.CharField(max_length=10, unique=True)),
                ("marca", models.CharField(max_length=50)),
                ("modelo", models.CharField(max_length=50)),
                ("capacidad", models.PositiveIntegerField()),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("BUS", "Bus"),
                            ("BUSETA", "Buseta"),
                            ("VAN", "Van"),
                            ("AUTOMOVIL", "Automóvil"),
                            ("CAMPERO", "Campero"),
                            ("LANCHA", "Lancha"),
                        ],
                        max_length=20,
                    ),
                ),
                ("documentacion_al_dia", models.BooleanField(default=True)),
                (
                    "prestador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vehiculos",
                        to="api.prestadorservicio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vehículo Turístico",
                "verbose_name_plural": "Vehículos Turísticos",
            },
        ),
    ]
