# Generated by Django 5.2.6 on 2025-10-15 23:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_delete_detalleshotel"),
        ("empresa", "0003_cliente"),
        ("turismo", "0003_guiaturistico_paqueteturistico_vehiculoturistico"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reserva",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_reserva", models.DateTimeField()),
                ("numero_personas", models.PositiveIntegerField(default=1)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente"),
                            ("CONFIRMADA", "Confirmada"),
                            ("CANCELADA", "Cancelada"),
                            ("COMPLETADA", "Completada"),
                        ],
                        default="PENDIENTE",
                        max_length=20,
                    ),
                ),
                ("notas_reserva", models.TextField(blank=True, null=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        blank=True,
                        help_text="Cliente del CRM asociado a la reserva.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="empresa.cliente",
                    ),
                ),
                (
                    "prestador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservas",
                        to="api.prestadorservicio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reserva",
                "verbose_name_plural": "Reservas",
                "ordering": ["-fecha_reserva"],
            },
        ),
    ]
