# Generated by Django 5.2.6 on 2026-01-09 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contabilidad", "0001_initial"),
    ]

    operations = [
        # Paso 1: Eliminar la restricción de unicidad antigua.
        migrations.AlterUniqueTogether(
            name='chartofaccount',
            unique_together=set(),
        ),

        # Paso 2: Añadir los nuevos campos de referencia.
        migrations.AddField(
            model_name="chartofaccount",
            name="perfil_ref_id",
            field=models.UUIDField(db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="costcenter",
            name="perfil_ref_id",
            field=models.UUIDField(db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="perfil_ref_id",
            field=models.UUIDField(db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="origen_operativo_id",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="origen_tipo",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),

        # Paso 3: Eliminar los campos antiguos.
        migrations.RemoveField(
            model_name="chartofaccount",
            name="perfil",
        ),
        migrations.RemoveField(
            model_name="costcenter",
            name="perfil",
        ),
        migrations.RemoveField(
            model_name="journalentry",
            name="perfil",
        ),
        migrations.RemoveField(
            model_name="journalentry",
            name="content_type",
        ),
        migrations.RemoveField(
            model_name="journalentry",
            name="object_id",
        ),

        # Paso 4: Añadir la nueva restricción de unicidad.
        migrations.AlterUniqueTogether(
            name="chartofaccount",
            unique_together={("perfil_ref_id", "code")},
        ),
    ]
