# Generated by Django 5.2.6 on 2025-10-29 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("prestadores", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConceptoNomina",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=10, unique=True)),
                ("descripcion", models.CharField(max_length=255)),
                (
                    "tipo",
                    models.CharField(
                        choices=[("ingreso", "Ingreso"), ("deduccion", "Deducción")],
                        max_length=10,
                    ),
                ),
                ("es_fijo", models.BooleanField(default=True)),
                (
                    "valor",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Empleado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("apellido", models.CharField(max_length=100)),
                (
                    "tipo_documento",
                    models.CharField(
                        choices=[
                            ("CC", "Cédula de Ciudadanía"),
                            ("CE", "Cédula de Extranjería"),
                            ("PA", "Pasaporte"),
                        ],
                        max_length=2,
                    ),
                ),
                ("numero_documento", models.CharField(max_length=20, unique=True)),
                ("fecha_nacimiento", models.DateField()),
                ("fecha_contratacion", models.DateField()),
                ("salario_base", models.DecimalField(decimal_places=2, max_digits=12)),
                ("activo", models.BooleanField(default=True)),
                (
                    "perfil",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="empleados",
                        to="prestadores.perfil",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Nomina",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_inicio", models.DateField()),
                ("fecha_fin", models.DateField()),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("borrador", "Borrador"),
                            ("procesada", "Procesada"),
                            ("pagada", "Pagada"),
                        ],
                        default="borrador",
                        max_length=10,
                    ),
                ),
                (
                    "total_ingresos",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "total_deducciones",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "neto_a_pagar",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "perfil",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nominas",
                        to="prestadores.perfil",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DetalleNomina",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "valor_calculado",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "concepto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="nomina.conceptonomina",
                    ),
                ),
                (
                    "empleado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detalles_nomina",
                        to="nomina.empleado",
                    ),
                ),
                (
                    "nomina",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detalles",
                        to="nomina.nomina",
                    ),
                ),
            ],
            options={
                "unique_together": {("nomina", "empleado", "concepto")},
            },
        ),
    ]
