# Generated by Django 5.2.6 on 2025-10-29 01:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("prestadores", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConceptoNomina",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(max_length=10, unique=True, verbose_name="Código"),
                ),
                (
                    "descripcion",
                    models.CharField(max_length=255, verbose_name="Descripción"),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("ingreso", "Ingreso"), ("deduccion", "Deducción")],
                        max_length=10,
                        verbose_name="Tipo de Concepto",
                    ),
                ),
                (
                    "es_fijo",
                    models.BooleanField(
                        default=True,
                        help_text="Marcar si este concepto es un valor fijo o un porcentaje.",
                        verbose_name="¿Es un valor fijo?",
                    ),
                ),
                (
                    "valor",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Valor fijo o porcentaje (ej. 0.04 para 4%).",
                        max_digits=12,
                        null=True,
                        verbose_name="Valor/Porcentaje",
                    ),
                ),
            ],
            options={
                "verbose_name": "Concepto de Nómina",
                "verbose_name_plural": "Conceptos de Nómina",
            },
        ),
        migrations.CreateModel(
            name="Empleado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, verbose_name="Nombre")),
                ("apellido", models.CharField(max_length=100, verbose_name="Apellido")),
                (
                    "tipo_documento",
                    models.CharField(
                        choices=[
                            ("CC", "Cédula de Ciudadanía"),
                            ("CE", "Cédula de Extranjería"),
                            ("PA", "Pasaporte"),
                        ],
                        max_length=2,
                        verbose_name="Tipo de Documento",
                    ),
                ),
                (
                    "numero_documento",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Número de Documento"
                    ),
                ),
                (
                    "fecha_nacimiento",
                    models.DateField(verbose_name="Fecha de Nacimiento"),
                ),
                (
                    "fecha_contratacion",
                    models.DateField(verbose_name="Fecha de Contratación"),
                ),
                (
                    "salario_base",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Salario Base"
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "perfil",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="empleados",
                        to="prestadores.perfil",
                        verbose_name="Perfil del Prestador",
                    ),
                ),
            ],
            options={
                "verbose_name": "Empleado",
                "verbose_name_plural": "Empleados",
                "ordering": ["-activo", "nombre", "apellido"],
            },
        ),
        migrations.CreateModel(
            name="Nomina",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_inicio", models.DateField(verbose_name="Fecha de Inicio")),
                ("fecha_fin", models.DateField(verbose_name="Fecha de Fin")),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("borrador", "Borrador"),
                            ("procesada", "Procesada"),
                            ("pagada", "Pagada"),
                        ],
                        default="borrador",
                        max_length=10,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "total_ingresos",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Total Ingresos",
                    ),
                ),
                (
                    "total_deducciones",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Total Deducciones",
                    ),
                ),
                (
                    "neto_a_pagar",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Neto a Pagar",
                    ),
                ),
                (
                    "perfil",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nominas",
                        to="prestadores.perfil",
                        verbose_name="Perfil del Prestador",
                    ),
                ),
            ],
            options={
                "verbose_name": "Nómina",
                "verbose_name_plural": "Nóminas",
                "ordering": ["-fecha_inicio"],
            },
        ),
        migrations.CreateModel(
            name="DetalleNomina",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "valor_calculado",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Valor Calculado"
                    ),
                ),
                (
                    "concepto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="nomina.conceptonomina",
                        verbose_name="Concepto",
                    ),
                ),
                (
                    "empleado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detalles_nomina",
                        to="nomina.empleado",
                        verbose_name="Empleado",
                    ),
                ),
                (
                    "nomina",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detalles",
                        to="nomina.nomina",
                        verbose_name="Nómina",
                    ),
                ),
            ],
            options={
                "verbose_name": "Detalle de Nómina",
                "verbose_name_plural": "Detalles de Nómina",
                "unique_together": {("nomina", "empleado", "concepto")},
            },
        ),
    ]
