# Generated by Django 6.0.3 on 2026-03-25 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("turismo", "0002_department_municipality"),
    ]

    operations = [
        migrations.AddField(
            model_name="tourismprovider",
            name="puntuacion_capacitacion",
            field=models.PositiveIntegerField(
                default=0, help_text="Puntaje por asistencia a capacitaciones."
            ),
        ),
        migrations.AddField(
            model_name="tourismprovider",
            name="puntuacion_resenas",
            field=models.PositiveIntegerField(
                default=0, help_text="Puntaje por reseñas de turistas."
            ),
        ),
        migrations.AddField(
            model_name="tourismprovider",
            name="puntuacion_total",
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name="tourismprovider",
            name="puntuacion_verificacion",
            field=models.PositiveIntegerField(
                default=0, help_text="Puntaje por cumplimiento de requisitos legales."
            ),
        ),
    ]
