# Generated by Django 6.0.3 on 2026-03-26 00:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("turismo", "0003_tourismprovider_puntuacion_capacitacion_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tourismprovider",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="providers",
                to="turismo.department",
            ),
        ),
        migrations.AddField(
            model_name="tourismprovider",
            name="municipality",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="providers",
                to="turismo.municipality",
            ),
        ),
        migrations.AddField(
            model_name="tourismprovider",
            name="rnt_last_sync",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tourismprovider",
            name="rnt_number",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=50,
                null=True,
                verbose_name="Número RNT",
            ),
        ),
        migrations.AddField(
            model_name="tourismprovider",
            name="rnt_validated",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="tourismprovider",
            name="sub_classification",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="Subclasificación"
            ),
        ),
    ]
