# Generated by Django 5.2.12 on 2026-03-27 00:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_alter_customuser_role"),
        ("turismo", "0004_tourismprovider_department_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TourismRoute",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "route_type",
                    models.CharField(
                        help_text="e.g., Gastronómica, Naturaleza, Histórica",
                        max_length=50,
                    ),
                ),
                (
                    "is_intelligent",
                    models.BooleanField(
                        default=False, help_text="Generated by AI engine"
                    ),
                ),
                (
                    "attractions",
                    models.ManyToManyField(
                        blank=True,
                        related_name="tourism_routes",
                        to="api.atractivoturistico",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="routes",
                        to="turismo.department",
                    ),
                ),
                (
                    "municipality",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="routes",
                        to="turismo.municipality",
                    ),
                ),
                (
                    "providers",
                    models.ManyToManyField(
                        blank=True,
                        related_name="tourism_routes",
                        to="turismo.tourismprovider",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
    ]
