# Generated by Django 5.2.12 on 2026-03-27 21:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("turismo", "0005_tourismroute"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tourismprovider",
            name="provider_type",
            field=models.CharField(
                choices=[
                    (
                        "HOTEL",
                        "Establecimiento de Alojamiento (Hoteles, Hostales, Glamping, etc.)",
                    ),
                    ("TRAVEL_AGENCY", "Agencia de Viajes y Turismo"),
                    ("REPRESENTATION_OFFICE", "Oficina de Representación Turística"),
                    ("GUIDE", "Guía de Turismo"),
                    (
                        "PROFESSIONAL_OPERATOR",
                        "Operador Profesional de Congresos y Ferias",
                    ),
                    ("VEHICLE_RENTAL", "Arrendador de Vehículos para Turismo"),
                    (
                        "INDUSTRIAL_USER",
                        "Usuario Industrial de Servicios en Zona Franca",
                    ),
                    ("TIME_SHARE", "Promotora de Tiempo Compartido y Multipropiedad"),
                    ("VACATION_EXCHANGE", "Compañía de Intercambio Vacacional"),
                    ("SAVINGS_FOR_TRAVEL", "Empresa Captadora de Ahorro para Viajes"),
                    (
                        "PARK_CONCESSIONAIRE",
                        "Concesionario de Servicios Turísticos en Parques",
                    ),
                    ("TRANSPORT", "Empresa de Transporte Terrestre Automotor Especial"),
                    (
                        "THEME_PARK_OPERATOR",
                        "Operador de Parques Temáticos y Ecoturismo",
                    ),
                    (
                        "DIGITAL_PLATFORM",
                        "Plataforma Electrónica de Servicios Turísticos",
                    ),
                    ("RESTAURANT_BAR", "Restaurante o Bar (RNT Voluntario)"),
                    ("WEDDING_PLANNER", "Organizador de Bodas Destino"),
                    ("ARTISAN", "Artesano"),
                    ("ASSOCIATION", "Asociación Turística"),
                    ("DELIVERY", "Servicio de Delivery"),
                    ("EVENT_ORGANIZER", "Organizador de Eventos (General)"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="tourismprovider",
            name="sub_classification",
            field=models.CharField(
                blank=True,
                max_length=150,
                null=True,
                verbose_name="Subclasificación (Texto)",
            ),
        ),
        migrations.CreateModel(
            name="TourismSubClassification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("HOTEL", "Hoteles"),
                            ("RESTAURANT", "Restaurantes"),
                            ("BAR", "Bares"),
                            ("DISCO", "Discotecas"),
                            ("AGENCY", "Agencias de Viajes"),
                            ("GUIDE", "Guías de Turismo"),
                            ("TRANSPORT", "Empresas Transportadoras"),
                            ("ASSOCIATION", "Asociaciones Turísticas"),
                            ("ARTISAN", "Artesanos"),
                            ("DELIVERY", "Servicios de Delivery"),
                        ],
                        max_length=50,
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("slug", models.SlugField(max_length=150, unique=True)),
                ("icon", models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                "verbose_name": "Subclasificación Turística",
                "verbose_name_plural": "Subclasificaciones Turísticas",
                "unique_together": {("category", "name")},
            },
        ),
        migrations.AddField(
            model_name="tourismprovider",
            name="sub_classification_ref",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="providers",
                to="turismo.tourismsubclassification",
            ),
        ),
    ]
