# Generated by Django 5.2.12 on 2026-03-15 12:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Amenity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, verbose_name="Nombre")),
                (
                    "icon",
                    models.CharField(blank=True, max_length=50, verbose_name="Icono"),
                ),
                (
                    "category",
                    models.CharField(
                        default="GENERAL", max_length=50, verbose_name="Categoría"
                    ),
                ),
            ],
            options={
                "verbose_name": "Comodidad / Amenidad",
                "verbose_name_plural": "Comodidades y Amenidades",
            },
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "nombre",
                    models.CharField(
                        max_length=150, verbose_name="Nombre de la Competencia"
                    ),
                ),
                (
                    "skill_type",
                    models.CharField(
                        choices=[
                            ("SPECIALIZATION", "Especialización"),
                            ("CERTIFICATION", "Certificación"),
                            ("LANGUAGE", "Idioma"),
                        ],
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Habilidad / Competencia",
                "verbose_name_plural": "Habilidades y Competencias",
            },
        ),
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("model_name", models.CharField(max_length=100, verbose_name="Modelo")),
                (
                    "vehicle_type",
                    models.CharField(
                        choices=[
                            ("CAR", "Automóvil"),
                            ("VAN", "Van / Microbús"),
                            ("BUS", "Autobús"),
                            ("BOAT", "Lancha / Bote"),
                            ("BIKE", "Bicicleta"),
                            ("MOTORCYCLE", "Motocicleta"),
                        ],
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "capacity_max",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Capacidad Máxima"
                    ),
                ),
            ],
            options={
                "verbose_name": "Vehículo del Catálogo",
                "verbose_name_plural": "Vehículos del Catálogo",
            },
        ),
    ]
