# Generated by Django 5.2.6 on 2025-10-15 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("api", "0002_delete_detalleshotel"),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoriaMenu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                (
                    "prestador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categorias_menu",
                        to="api.prestadorservicio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Categoría de Menú",
                "verbose_name_plural": "Categorías de Menú",
            },
        ),
        migrations.CreateModel(
            name="Mesa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_mesa", models.CharField(max_length=50)),
                ("capacidad", models.PositiveIntegerField(default=4)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("DISPONIBLE", "Disponible"),
                            ("OCUPADA", "Ocupada"),
                            ("RESERVADA", "Reservada"),
                        ],
                        default="DISPONIBLE",
                        max_length=50,
                    ),
                ),
                (
                    "prestador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mesas",
                        to="api.prestadorservicio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mesa",
                "verbose_name_plural": "Mesas",
            },
        ),
        migrations.CreateModel(
            name="Pedido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("completado", models.BooleanField(default=False)),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "mesa",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pedidos",
                        to="restaurante.mesa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pedido",
                "verbose_name_plural": "Pedidos",
            },
        ),
        migrations.CreateModel(
            name="ItemPedido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad", models.PositiveIntegerField(default=1)),
                (
                    "precio_unitario",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "pedido",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="restaurante.pedido",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductoMenu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("descripcion", models.TextField(blank=True, null=True)),
                ("precio", models.DecimalField(decimal_places=2, max_digits=10)),
                ("disponible", models.BooleanField(default=True)),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="productos",
                        to="restaurante.categoriamenu",
                    ),
                ),
            ],
            options={
                "verbose_name": "Producto del Menú",
                "verbose_name_plural": "Productos del Menú",
            },
        ),
        migrations.AddField(
            model_name="pedido",
            name="productos",
            field=models.ManyToManyField(
                through="restaurante.ItemPedido", to="restaurante.productomenu"
            ),
        ),
        migrations.AddField(
            model_name="itempedido",
            name="producto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="restaurante.productomenu",
            ),
        ),
    ]
