# Generated by Django 5.2.12 on 2026-03-15 13:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MicroTarea",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("soldado_asignado", models.CharField(db_index=True, max_length=255)),
                ("descripcion", models.TextField()),
                ("parametros", models.JSONField(default=dict)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente"),
                            ("EN_PROGRESO", "En Progreso"),
                            ("COMPLETADA", "Completada"),
                            ("FALLIDA", "Fallida"),
                        ],
                        db_index=True,
                        default="PENDIENTE",
                        max_length=50,
                    ),
                ),
                ("timestamp_creacion", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Mision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "idempotency_key",
                    models.UUIDField(
                        blank=True,
                        help_text="Clave única para prevenir duplicados.",
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "directiva_original",
                    models.JSONField(
                        help_text="La directiva JSON original recibida por el orquestador."
                    ),
                ),
                (
                    "dominio",
                    models.CharField(
                        db_index=True,
                        help_text="Dominio de negocio objetivo (ej. 'prestadores').",
                        max_length=100,
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente"),
                            ("EN_PROGRESO", "En Progreso"),
                            ("COMPLETADA", "Completada"),
                            ("FALLIDA", "Fallida"),
                            ("COMPLETADA_PARCIALMENTE", "Completada Parcialmente"),
                        ],
                        db_index=True,
                        default="PENDIENTE",
                        max_length=50,
                    ),
                ),
                (
                    "resultado_final",
                    models.JSONField(
                        blank=True,
                        help_text="El informe final consolidado de la misión.",
                        null=True,
                    ),
                ),
                ("timestamp_inicio", models.DateTimeField(auto_now_add=True)),
                ("timestamp_fin", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="MissionHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("mission_id", models.UUIDField(unique=True)),
                ("mission_type", models.CharField(db_index=True, max_length=100)),
                ("strategy", models.CharField(max_length=100)),
                (
                    "tenientes",
                    models.JSONField(help_text="Lista de tenientes involucrados"),
                ),
                ("score", models.FloatField()),
                ("impact", models.FloatField()),
                ("cost", models.FloatField()),
                ("time", models.FloatField()),
                ("result", models.JSONField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Historial de Misión",
                "verbose_name_plural": "Historial de Misiones",
            },
        ),
        migrations.CreateModel(
            name="Prestador",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("activo", models.BooleanField(default=False)),
                ("timestamp_creacion", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="SoldadoOperationalStatus",
            fields=[
                (
                    "nombre_soldado",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("dominio", models.CharField(db_index=True, max_length=100)),
                ("estado", models.CharField(default="Mock", max_length=50)),
                ("fecha_certificacion", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="TenienteLearning",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("teniente_id", models.CharField(db_index=True, max_length=255)),
                ("tarea", models.TextField()),
                ("estrategia", models.CharField(max_length=100)),
                ("resultado", models.JSONField()),
                ("score", models.FloatField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Aprendizaje de Teniente",
                "verbose_name_plural": "Aprendizajes de Tenientes",
            },
        ),
        migrations.CreateModel(
            name="IdempotencyKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(db_index=True, max_length=255)),
                ("domain", models.CharField(db_index=True, max_length=100)),
                ("status", models.CharField(default="PENDING", max_length=20)),
                ("response_payload", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "unique_together": {("key", "domain")},
            },
        ),
        migrations.CreateModel(
            name="PlanTáctico",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "capitan_responsable",
                    models.CharField(
                        db_index=True,
                        help_text="Clase del Capitán que generó el plan.",
                        max_length=255,
                    ),
                ),
                (
                    "pasos_del_plan",
                    models.JSONField(help_text="Los pasos estructurados del plan."),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PLANIFICADO", "Planificado"),
                            ("EN_EJECUCION", "En Ejecución"),
                            ("COMPLETADO", "Completado"),
                            ("FALLIDO", "Fallido"),
                            ("COMPLETADO_PARCIALMENTE", "Completado Parcialmente"),
                        ],
                        db_index=True,
                        default="PLANIFICADO",
                        max_length=50,
                    ),
                ),
                ("timestamp_creacion", models.DateTimeField(auto_now_add=True)),
                (
                    "mision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="planes_tacticos",
                        to="sarita_agents.mision",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RegistroMicroTarea",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("exitoso", models.BooleanField(db_index=True)),
                ("resultado", models.JSONField(blank=True, null=True)),
                ("observaciones", models.TextField(blank=True)),
                (
                    "micro_tarea",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="sarita_agents.microtarea",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TareaDelegada",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "teniente_asignado",
                    models.CharField(
                        db_index=True,
                        help_text="Identificador del Teniente responsable.",
                        max_length=255,
                    ),
                ),
                ("descripcion_tarea", models.TextField()),
                ("parametros", models.JSONField(default=dict)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente"),
                            ("EN_COLA", "En Cola"),
                            ("EN_PROGRESO", "En Progreso"),
                            ("REINTENTANDO", "Reintentando"),
                            ("COMPLETADA", "Completada"),
                            ("FALLIDA", "Fallida"),
                        ],
                        db_index=True,
                        default="PENDIENTE",
                        max_length=50,
                    ),
                ),
                ("timestamp_creacion", models.DateTimeField(auto_now_add=True)),
                (
                    "plan_tactico",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tareas",
                        to="sarita_agents.plantáctico",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RegistroDeEjecucion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("exitoso", models.BooleanField()),
                (
                    "salida_log",
                    models.TextField(
                        blank=True,
                        help_text="Salida estándar o log de la ejecución.",
                        null=True,
                    ),
                ),
                (
                    "resultado",
                    models.JSONField(
                        blank=True,
                        help_text="El resultado estructurado de la ejecución.",
                        null=True,
                    ),
                ),
                (
                    "tarea_delegada",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs_ejecucion",
                        to="sarita_agents.tareadelegada",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="microtarea",
            name="tarea_padre",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="micro_tareas",
                to="sarita_agents.tareadelegada",
            ),
        ),
    ]
