# Generated by Django 5.2.6 on 2026-01-25 15:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Mision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "directiva_original",
                    models.JSONField(
                        help_text="La directiva JSON original recibida por el orquestador."
                    ),
                ),
                (
                    "dominio",
                    models.CharField(
                        help_text="Dominio de negocio objetivo (ej. 'prestadores').",
                        max_length=100,
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente"),
                            ("EN_PROGRESO", "En Progreso"),
                            ("COMPLETADA", "Completada"),
                            ("FALLIDA", "Fallida"),
                        ],
                        default="PENDIENTE",
                        max_length=50,
                    ),
                ),
                (
                    "resultado_final",
                    models.JSONField(
                        blank=True,
                        help_text="El informe final consolidado de la misión.",
                        null=True,
                    ),
                ),
                ("timestamp_inicio", models.DateTimeField(auto_now_add=True)),
                ("timestamp_fin", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="PlanTáctico",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "capitan_responsable",
                    models.CharField(
                        help_text="Clase del Capitán que generó el plan.",
                        max_length=255,
                    ),
                ),
                (
                    "pasos_del_plan",
                    models.JSONField(help_text="Los pasos estructurados del plan."),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PLANIFICADO", "Planificado"),
                            ("EN_EJECUCION", "En Ejecución"),
                            ("COMPLETADO", "Completado"),
                            ("FALLIDO", "Fallido"),
                        ],
                        default="PLANIFICADO",
                        max_length=50,
                    ),
                ),
                ("timestamp_creacion", models.DateTimeField(auto_now_add=True)),
                (
                    "mision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="planes_tacticos",
                        to="sarita_agents.mision",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TareaDelegada",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "teniente_asignado",
                    models.CharField(
                        help_text="Identificador del Teniente responsable.",
                        max_length=255,
                    ),
                ),
                ("descripcion_tarea", models.TextField()),
                ("parametros", models.JSONField(default=dict)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente"),
                            ("EN_PROGRESO", "En Progreso"),
                            ("COMPLETADA", "Completada"),
                            ("FALLIDA", "Fallida"),
                        ],
                        default="PENDIENTE",
                        max_length=50,
                    ),
                ),
                ("timestamp_creacion", models.DateTimeField(auto_now_add=True)),
                (
                    "plan_tactico",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tareas",
                        to="sarita_agents.plantáctico",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RegistroDeEjecucion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("exitoso", models.BooleanField()),
                (
                    "salida_log",
                    models.TextField(
                        blank=True,
                        help_text="Salida estándar o log de la ejecución.",
                        null=True,
                    ),
                ),
                (
                    "resultado",
                    models.JSONField(
                        blank=True,
                        help_text="El resultado estructurado de la ejecución.",
                        null=True,
                    ),
                ),
                (
                    "tarea_delegada",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs_ejecucion",
                        to="sarita_agents.tareadelegada",
                    ),
                ),
            ],
        ),
    ]
