# Generated by Django 5.2.6 on 2026-01-25 16:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sarita_agents", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Prestador",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("activo", models.BooleanField(default=False)),
                ("timestamp_creacion", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
