# Generated by Django 5.2.6 on 2026-01-25 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sarita_agents", "0002_prestador"),
    ]

    operations = [
        migrations.AddField(
            model_name="mision",
            name="idempotency_key",
            field=models.UUIDField(
                blank=True,
                help_text="Clave única para prevenir duplicados.",
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="mision",
            name="estado",
            field=models.CharField(
                choices=[
                    ("PENDIENTE", "Pendiente"),
                    ("EN_PROGRESO", "En Progreso"),
                    ("COMPLETADA", "Completada"),
                    ("FALLIDA", "Fallida"),
                    ("COMPLETADA_PARCIALMENTE", "Completada Parcialmente"),
                ],
                default="PENDIENTE",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="plantáctico",
            name="estado",
            field=models.CharField(
                choices=[
                    ("PLANIFICADO", "Planificado"),
                    ("EN_EJECUCION", "En Ejecución"),
                    ("COMPLETADO", "Completado"),
                    ("FALLIDO", "Fallido"),
                    ("COMPLETADO_PARCIALMENTE", "Completado Parcialmente"),
                ],
                default="PLANIFICADO",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="tareadelegada",
            name="estado",
            field=models.CharField(
                choices=[
                    ("PENDIENTE", "Pendiente"),
                    ("EN_COLA", "En Cola"),
                    ("EN_PROGRESO", "En Progreso"),
                    ("REINTENTANDO", "Reintentando"),
                    ("COMPLETADA", "Completada"),
                    ("FALLIDA", "Fallida"),
                ],
                default="PENDIENTE",
                max_length=50,
            ),
        ),
    ]
