# Generated by Django 5.2.11 on 2026-02-15 08:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sarita_agents", "0003_mision_idempotency_key_alter_mision_estado_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mision",
            name="dominio",
            field=models.CharField(
                db_index=True,
                help_text="Dominio de negocio objetivo (ej. 'prestadores').",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="mision",
            name="estado",
            field=models.CharField(
                choices=[
                    ("PENDIENTE", "Pendiente"),
                    ("EN_PROGRESO", "En Progreso"),
                    ("COMPLETADA", "Completada"),
                    ("FALLIDA", "Fallida"),
                    ("COMPLETADA_PARCIALMENTE", "Completada Parcialmente"),
                ],
                db_index=True,
                default="PENDIENTE",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="plantáctico",
            name="capitan_responsable",
            field=models.CharField(
                db_index=True,
                help_text="Clase del Capitán que generó el plan.",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="plantáctico",
            name="estado",
            field=models.CharField(
                choices=[
                    ("PLANIFICADO", "Planificado"),
                    ("EN_EJECUCION", "En Ejecución"),
                    ("COMPLETADO", "Completado"),
                    ("FALLIDO", "Fallido"),
                    ("COMPLETADO_PARCIALMENTE", "Completado Parcialmente"),
                ],
                db_index=True,
                default="PLANIFICADO",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="tareadelegada",
            name="estado",
            field=models.CharField(
                choices=[
                    ("PENDIENTE", "Pendiente"),
                    ("EN_COLA", "En Cola"),
                    ("EN_PROGRESO", "En Progreso"),
                    ("REINTENTANDO", "Reintentando"),
                    ("COMPLETADA", "Completada"),
                    ("FALLIDA", "Fallida"),
                ],
                db_index=True,
                default="PENDIENTE",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="tareadelegada",
            name="teniente_asignado",
            field=models.CharField(
                db_index=True,
                help_text="Identificador del Teniente responsable.",
                max_length=255,
            ),
        ),
        migrations.CreateModel(
            name="MicroTarea",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("soldado_asignado", models.CharField(db_index=True, max_length=255)),
                ("descripcion", models.TextField()),
                ("parametros", models.JSONField(default=dict)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente"),
                            ("EN_PROGRESO", "En Progreso"),
                            ("COMPLETADA", "Completada"),
                            ("FALLIDA", "Fallida"),
                        ],
                        db_index=True,
                        default="PENDIENTE",
                        max_length=50,
                    ),
                ),
                ("timestamp_creacion", models.DateTimeField(auto_now_add=True)),
                (
                    "tarea_padre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="micro_tareas",
                        to="sarita_agents.tareadelegada",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RegistroMicroTarea",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("exitoso", models.BooleanField(db_index=True)),
                ("resultado", models.JSONField(blank=True, null=True)),
                ("observaciones", models.TextField(blank=True)),
                (
                    "micro_tarea",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="sarita_agents.microtarea",
                    ),
                ),
            ],
        ),
    ]
