# Generated by Django 5.2.6 on 2026-01-08 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="CuentaBancaria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("perfil_ref_id", models.UUIDField()),
                ("banco", models.CharField(max_length=100)),
                ("numero_cuenta", models.CharField(max_length=50, unique=True)),
                ("tipo_cuenta", models.CharField(max_length=50)),
                (
                    "saldo_inicial",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=18),
                ),
                (
                    "saldo_actual",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=18),
                ),
                ("cuenta_contable_ref_id", models.UUIDField(null=True)),
                ("activa", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="OrdenPago",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("perfil_ref_id", models.UUIDField()),
                ("cuenta_bancaria_ref_id", models.UUIDField()),
                ("beneficiario_object_id", models.CharField(max_length=36, null=True)),
                ("fecha_pago", models.DateField()),
                ("monto", models.DecimalField(decimal_places=2, max_digits=18)),
                ("concepto", models.CharField(max_length=255)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente"),
                            ("PAGADA", "Pagada"),
                            ("CANCELADA", "Cancelada"),
                        ],
                        default="PENDIENTE",
                        max_length=20,
                    ),
                ),
                ("referencia_pago", models.CharField(blank=True, max_length=100)),
                (
                    "documento_archivistico_ref_id",
                    models.UUIDField(blank=True, null=True),
                ),
                (
                    "beneficiario_content_type",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
        ),
    ]
