# Generated by Django 6.0.3 on 2026-03-23 21:21

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("prestadores", "0001_full_reset"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganizadorEvento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("descripcion", models.TextField()),
                (
                    "perfil",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organizador_eventos",
                        to="prestadores.providerprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Evento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_inicio", models.DateTimeField()),
                ("fecha_fin", models.DateTimeField()),
                ("ubicacion", models.CharField(max_length=255)),
                ("capacidad", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "producto",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evento",
                        to="prestadores.product",
                    ),
                ),
                (
                    "organizador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="eventos",
                        to="eventos.organizadorevento",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Promocion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("descripcion", models.TextField(blank=True)),
                ("fecha_inicio", models.DateField()),
                ("fecha_fin", models.DateField()),
                (
                    "tipo_descuento",
                    models.CharField(
                        choices=[("porcentaje", "Porcentaje"), ("fijo", "Monto Fijo")],
                        max_length=10,
                    ),
                ),
                (
                    "valor_descuento",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Valor del descuento (ej: 10 para 10% o 5000 para $5000 fijos)",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("activa", models.BooleanField(default=True)),
                (
                    "perfil",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promociones",
                        to="prestadores.providerprofile",
                    ),
                ),
                (
                    "productos_aplicables",
                    models.ManyToManyField(
                        related_name="promociones", to="prestadores.product"
                    ),
                ),
            ],
        ),
    ]
