# Generated by Django 5.2.6 on 2026-01-08 19:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("api", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivoFijo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                ("descripcion", models.TextField(blank=True)),
                ("fecha_adquisicion", models.DateField()),
                (
                    "costo_adquisicion",
                    models.DecimalField(decimal_places=2, max_digits=18),
                ),
                (
                    "valor_residual",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=18),
                ),
                ("vida_util_meses", models.PositiveIntegerField()),
                (
                    "metodo_depreciacion",
                    models.CharField(
                        choices=[("LINEA_RECTA", "Línea Recta")],
                        default="LINEA_RECTA",
                        max_length=20,
                    ),
                ),
                (
                    "depreciacion_acumulada",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=18),
                ),
                (
                    "valor_en_libros",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=18),
                ),
                (
                    "perfil",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activos_fijos",
                        to="api.providerprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CalculoDepreciacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField()),
                ("monto", models.DecimalField(decimal_places=2, max_digits=18)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "activo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calculos_depreciacion",
                        to="activos_fijos.activofijo",
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CategoriaActivo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("descripcion", models.TextField(blank=True)),
                (
                    "perfil",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categorias_activos",
                        to="api.providerprofile",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="activofijo",
            name="categoria",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="activos",
                to="activos_fijos.categoriaactivo",
            ),
        ),
    ]
