# Generated by Django 5.2.6 on 2026-02-05 22:29

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AlgorithmicCertificate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "node_id",
                    models.CharField(
                        help_text="ID del Nodo Nacional emisor", max_length=100
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("GOVERNANCE", "Certificado de Gobernanza"),
                            ("AUDIT", "Certificado de Auditoría"),
                            ("NEUTRALITY", "Certificado de Neutralidad"),
                            ("SECURITY", "Certificado de Seguridad"),
                            ("HUMAN_RIGHTS", "Certificado de Derechos Humanos"),
                        ],
                        max_length=20,
                    ),
                ),
                ("issued_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("expires_at", models.DateTimeField()),
                ("evidence_summary", models.JSONField()),
                (
                    "signature",
                    models.TextField(
                        help_text="Firma SHA-256 del contenido del certificado"
                    ),
                ),
                ("is_revoked", models.BooleanField(default=False)),
                ("revocation_reason", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="TrustSignal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("origin_node", models.CharField(max_length=100)),
                (
                    "category",
                    models.CharField(
                        help_text="Ej: CIBERSEGURIDAD, ESTABILIDAD_ECONOMICA",
                        max_length=50,
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("STABLE", "Estable"),
                            ("WARNING", "Advertencia"),
                            ("CRITICAL", "Crítica"),
                        ],
                        max_length=20,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("description", models.TextField()),
                ("metadata", models.JSONField(default=dict)),
                ("verification_hash", models.CharField(max_length=64)),
            ],
        ),
    ]
