# Generated by Django 5.2.6 on 2026-01-29 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("admin_operativa", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Proveedor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("nit", models.CharField(blank=True, max_length=20)),
                (
                    "perfil",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admin_proveedores",
                        to="admin_operativa.providerprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FacturaCompra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.CharField(max_length=50)),
                ("fecha", models.DateField()),
                ("total", models.DecimalField(decimal_places=2, max_digits=18)),
                (
                    "perfil",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admin_facturas_compra",
                        to="admin_operativa.providerprofile",
                    ),
                ),
                (
                    "proveedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admin_facturas",
                        to="admin_compras.proveedor",
                    ),
                ),
            ],
        ),
    ]
