# Generated by Django 5.2.12 on 2026-03-15 13:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core_erp", "0001_initial_base"),
    ]

    operations = [
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "profile_id",
                    models.UUIDField(
                        blank=True,
                        help_text="Decoupled reference to Operational Profile",
                        null=True,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("tax_id", models.CharField(max_length=50, unique=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_records",
                        to="core_erp.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Supplier",
                "db_table": "admin_procurement_supplier",
            },
        ),
        migrations.CreateModel(
            name="PurchaseInvoice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("number", models.CharField(blank=True, max_length=50, null=True)),
                ("issue_date", models.DateField(blank=True, null=True)),
                ("due_date", models.DateField(blank=True, null=True)),
                ("status", models.CharField(default="DRAFT", max_length=30)),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=18),
                ),
                (
                    "tax_amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=18),
                ),
                ("currency", models.CharField(default="COP", max_length=3)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_records",
                        to="core_erp.tenant",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoices",
                        to="admin_procurement.supplier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Purchase Invoice",
                "db_table": "admin_procurement_invoice",
            },
        ),
    ]
