# Generated by Django 5.2.6 on 2026-01-22 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MediaAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        help_text="Un nombre descriptivo para el archivo.",
                        max_length=200,
                        verbose_name="Nombre",
                    ),
                ),
                (
                    "archivo",
                    models.FileField(
                        upload_to="web_funnel_media/", verbose_name="Archivo"
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        blank=True,
                        help_text="Ej: 'image/jpeg', 'video/mp4'",
                        max_length=50,
                        verbose_name="Tipo de archivo",
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Activo Multimedia",
                "verbose_name_plural": "Activos Multimedia",
            },
        ),
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=200, verbose_name="Título de la Sección"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="El orden de la sección dentro de la página.",
                        verbose_name="Orden",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Sección",
                "verbose_name_plural": "Secciones",
                "ordering": ["web_page", "order"],
            },
        ),
        migrations.CreateModel(
            name="WebPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="El título principal de la página.",
                        max_length=200,
                        verbose_name="Título",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="La URL amigable de la página (ej. 'pagina-de-ventas').",
                        max_length=200,
                        unique=True,
                        verbose_name="Slug",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=False,
                        help_text="Indica si la página es visible públicamente.",
                        verbose_name="Está Publicada",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Página Web",
                "verbose_name_plural": "Páginas Web",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="ContentBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("text", "Texto"),
                            ("image", "Imagen"),
                            ("video", "Video"),
                            ("button", "Botón"),
                        ],
                        default="text",
                        max_length=10,
                        verbose_name="Tipo de Contenido",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True,
                        help_text="Contenido de texto, URL de imagen/video, o texto del botón.",
                        verbose_name="Contenido",
                    ),
                ),
                (
                    "link",
                    models.URLField(
                        blank=True,
                        help_text="URL para imágenes, videos o botones.",
                        null=True,
                        verbose_name="Enlace",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="El orden del bloque dentro de la sección.",
                        verbose_name="Orden",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_blocks",
                        to="web_funnel.section",
                        verbose_name="Sección",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bloque de Contenido",
                "verbose_name_plural": "Bloques de Contenido",
                "ordering": ["section", "order"],
            },
        ),
        migrations.AddField(
            model_name="section",
            name="web_page",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sections",
                to="web_funnel.webpage",
                verbose_name="Página Web",
            ),
        ),
    ]
