# Generated by Django 5.2.6 on 2026-02-08 20:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("companies", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WalletAccount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "owner_type",
                    models.CharField(
                        choices=[
                            ("TOURIST", "Turista"),
                            ("PROVIDER", "Prestador"),
                            ("DELIVERY", "Delivery"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "owner_id",
                    models.CharField(
                        help_text="ID del usuario dueño del monedero", max_length=255
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=18),
                ),
                ("currency", models.CharField(default="COP", max_length=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Activo"),
                            ("FROZEN", "Congelado"),
                            ("AUDITED", "En Auditoría"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wallets",
                        to="companies.company",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wallets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Cuenta de Monedero",
                "verbose_name_plural": "Cuentas de Monedero",
                "unique_together": {("owner_type", "owner_id", "company")},
            },
        ),
        migrations.CreateModel(
            name="WalletTransaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=18)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("DEPOSIT", "Depósito"),
                            ("PAYMENT", "Pago"),
                            ("REFUND", "Reembolso"),
                            ("ADJUSTMENT", "Ajuste"),
                            ("LIQUIDATION", "Liquidación"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pendiente"),
                            ("APPROVED", "Aprobado"),
                            ("EXECUTED", "Ejecutado"),
                            ("REVERSED", "Revertido"),
                            ("FAILED", "Fallido"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "related_service_id",
                    models.UUIDField(
                        blank=True,
                        help_text="ID del servicio relacionado (Reserva, Pedido, etc.)",
                        null=True,
                    ),
                ),
                (
                    "governance_intention_id",
                    models.CharField(
                        blank=True,
                        help_text="ID de la intención de gobernanza que autorizó esto",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "integrity_hash",
                    models.CharField(
                        blank=True,
                        help_text="Hash encadenado para integridad forense",
                        max_length=64,
                        null=True,
                    ),
                ),
                (
                    "previous_hash",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "from_wallet",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions_out",
                        to="wallet.walletaccount",
                    ),
                ),
                (
                    "to_wallet",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions_in",
                        to="wallet.walletaccount",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transacción de Monedero",
                "verbose_name_plural": "Transacciones de Monedero",
                "ordering": ["-timestamp"],
            },
        ),
    ]
