# Generated by Django 5.2.6 on 2026-02-08 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="walletaccount",
            name="locked_balance",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Saldo comprometido en servicios activos",
                max_digits=18,
            ),
        ),
        migrations.AlterField(
            model_name="walletaccount",
            name="balance",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Saldo disponible para transacciones",
                max_digits=18,
            ),
        ),
    ]
