# Generated by Django 5.2.6 on 2025-11-02 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contabilidad", "0001_initial"),
        ("mi_negocio", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BankAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        help_text="Ej: Cuenta Corriente Bancolombia", max_length=255
                    ),
                ),
                ("numero_cuenta", models.CharField(max_length=50)),
                ("nombre_banco", models.CharField(max_length=150)),
                ("esta_activa", models.BooleanField(default=True)),
                (
                    "cuenta_contable_asociada",
                    models.OneToOneField(
                        help_text="Cuenta contable del PUC que representa este banco.",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="contabilidad.chartofaccount",
                    ),
                ),
                (
                    "perfil",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cuentas_bancarias",
                        to="mi_negocio.perfil",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cuenta Bancaria",
                "verbose_name_plural": "Cuentas Bancarias",
                "unique_together": {("perfil", "numero_cuenta", "nombre_banco")},
            },
        ),
        migrations.CreateModel(
            name="CashTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_transaccion", models.DateField(db_index=True)),
                ("descripcion", models.CharField(max_length=512)),
                ("monto", models.DecimalField(decimal_places=2, max_digits=18)),
                (
                    "tipo_transaccion",
                    models.CharField(
                        choices=[("INFLOW", "Ingreso"), ("OUTFLOW", "Egreso")],
                        max_length=10,
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "asiento_contable",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transaccion_caja",
                        to="contabilidad.journalentry",
                    ),
                ),
                (
                    "cuenta_bancaria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transacciones",
                        to="financiero.bankaccount",
                    ),
                ),
                (
                    "perfil",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transacciones_caja",
                        to="mi_negocio.perfil",
                    ),
                ),
            ],
            options={
                "verbose_name": "Movimiento de Tesorería",
                "verbose_name_plural": "Movimientos de Tesorería",
                "ordering": ["-fecha_transaccion", "-id"],
            },
        ),
    ]
