# Generated by Django 6.0 on 2025-12-16 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("infrastructure", "0004_merge_20251216_1147"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="campaign",
            name="tenant",
        ),
        migrations.RemoveField(
            model_name="funnel",
            name="campaign",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="tenant",
        ),
        migrations.RemoveField(
            model_name="funnel",
            name="tenant",
        ),
        migrations.RemoveField(
            model_name="funnelpage",
            name="funnel",
        ),
        migrations.DeleteModel(
            name="Asset",
        ),
        migrations.DeleteModel(
            name="Campaign",
        ),
        migrations.DeleteModel(
            name="Customer",
        ),
        migrations.DeleteModel(
            name="Funnel",
        ),
        migrations.DeleteModel(
            name="FunnelPage",
        ),
    ]
