# Generated by Django 5.2.6 on 2026-01-22 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="CalculoDepreciacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField()),
                ("monto", models.DecimalField(decimal_places=2, max_digits=18)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="CategoriaActivo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("owner_object_id", models.UUIDField(blank=True, null=True)),
                ("nombre", models.CharField(max_length=100)),
                ("descripcion", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="ActivoFijo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("owner_object_id", models.UUIDField(blank=True, null=True)),
                ("nombre", models.CharField(max_length=255)),
                ("descripcion", models.TextField(blank=True)),
                ("fecha_adquisicion", models.DateField()),
                (
                    "costo_adquisicion",
                    models.DecimalField(decimal_places=2, max_digits=18),
                ),
                (
                    "valor_residual",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=18),
                ),
                ("vida_util_meses", models.PositiveIntegerField()),
                (
                    "metodo_depreciacion",
                    models.CharField(
                        choices=[("LINEA_RECTA", "Línea Recta")],
                        default="LINEA_RECTA",
                        max_length=20,
                    ),
                ),
                (
                    "depreciacion_acumulada",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=18),
                ),
                (
                    "valor_en_libros",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=18),
                ),
                (
                    "owner_content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
        ),
    ]
