# Generated by Django 5.2.6 on 2026-01-22 19:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("activos_fijos", "0001_initial"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("prestadores", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="activofijo",
            name="perfil",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activos_fijos",
                to="prestadores.providerprofile",
            ),
        ),
        migrations.AddField(
            model_name="calculodepreciacion",
            name="activo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="calculos_depreciacion",
                to="activos_fijos.activofijo",
            ),
        ),
        migrations.AddField(
            model_name="calculodepreciacion",
            name="creado_por",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="categoriaactivo",
            name="owner_content_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="categoriaactivo",
            name="perfil",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categorias_activos",
                to="prestadores.providerprofile",
            ),
        ),
        migrations.AddField(
            model_name="activofijo",
            name="categoria",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="activos",
                to="activos_fijos.categoriaactivo",
            ),
        ),
    ]
