# Generated by Django 5.2.6 on 2026-01-20 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activos_fijos", "0002_alter_activofijo_perfil_alter_categoriaactivo_perfil"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("prestadores", "0003_categoriaprestador_providerprofile_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="activofijo",
            name="owner_content_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="activofijo",
            name="owner_object_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="categoriaactivo",
            name="owner_content_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="categoriaactivo",
            name="owner_object_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="activofijo",
            name="perfil",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activos_fijos",
                to="prestadores.providerprofile",
            ),
        ),
        migrations.AlterField(
            model_name="categoriaactivo",
            name="perfil",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categorias_activos",
                to="prestadores.providerprofile",
            ),
        ),
    ]
