# Generated by Django 5.2.12 on 2026-03-15 13:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core_erp", "0001_initial_base"),
    ]

    operations = [
        migrations.CreateModel(
            name="CapitalStructure",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "wacc",
                    models.DecimalField(decimal_places=4, default=0, max_digits=5),
                ),
                (
                    "debt_to_equity",
                    models.DecimalField(decimal_places=4, default=0, max_digits=10),
                ),
                (
                    "total_equity",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "total_debt",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "tokenized_equity",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "tokenized_debt",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "internal_credit_rating",
                    models.CharField(default="BBB", max_length=10),
                ),
                (
                    "target_leverage",
                    models.DecimalField(decimal_places=4, default=0.4, max_digits=5),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_records",
                        to="core_erp.tenant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DebtInstrument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "instrument_type",
                    models.CharField(
                        choices=[
                            ("BOND", "Corporate Bond"),
                            ("GREEN_BOND", "Green Bond"),
                            ("NOTE", "Structured Note"),
                            ("PRIVATE_DEBT", "Private Debt"),
                        ],
                        max_length=50,
                    ),
                ),
                ("isin_code", models.CharField(blank=True, max_length=12, null=True)),
                (
                    "principal_amount",
                    models.DecimalField(decimal_places=2, max_digits=20),
                ),
                ("coupon_rate", models.DecimalField(decimal_places=4, max_digits=5)),
                ("maturity_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ISSUED", "Issued"),
                            ("MATURED", "Matured"),
                            ("REDEEMED", "Redeemed"),
                        ],
                        default="ISSUED",
                        max_length=20,
                    ),
                ),
                ("covenants", models.JSONField(blank=True, default=dict)),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_records",
                        to="core_erp.tenant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EquityInstrument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("instrument_name", models.CharField(max_length=255)),
                ("total_shares", models.DecimalField(decimal_places=2, max_digits=20)),
                ("par_value", models.DecimalField(decimal_places=2, max_digits=20)),
                (
                    "market_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                (
                    "dividend_yield",
                    models.DecimalField(decimal_places=4, default=0, max_digits=5),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_records",
                        to="core_erp.tenant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MarketRating",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("agency_source", models.CharField(max_length=100)),
                ("rating_score", models.CharField(max_length=10)),
                (
                    "default_probability",
                    models.DecimalField(decimal_places=4, max_digits=5),
                ),
                ("market_spread_bps", models.IntegerField()),
                ("effective_date", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_records",
                        to="core_erp.tenant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StructuredDeal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("deal_name", models.CharField(max_length=255)),
                ("underlying_asset_type", models.CharField(max_length=100)),
                ("tranche_structure", models.JSONField()),
                ("spv_legal_name", models.CharField(max_length=255)),
                ("total_size", models.DecimalField(decimal_places=2, max_digits=20)),
                ("status", models.CharField(default="PROPOSAL", max_length=20)),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_records",
                        to="core_erp.tenant",
                    ),
                ),
            ],
        ),
    ]
