# Generated by Django 5.2.6 on 2026-01-22 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ConceptoNomina",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=10, unique=True)),
                ("descripcion", models.CharField(max_length=255)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("DEVENGADO", "Devengado"),
                            ("DEDUCCION", "Deducción"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Contrato",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_inicio", models.DateField()),
                ("fecha_fin", models.DateField(blank=True, null=True)),
                ("salario", models.DecimalField(decimal_places=2, max_digits=18)),
                ("cargo", models.CharField(max_length=100)),
                ("activo", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="DetalleLiquidacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("salario_base", models.DecimalField(decimal_places=2, max_digits=18)),
                ("dias_trabajados", models.IntegerField()),
                (
                    "valor_prima",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=18),
                ),
                (
                    "valor_cesantias",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=18),
                ),
                (
                    "valor_intereses_cesantias",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=18),
                ),
                (
                    "valor_vacaciones",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=18),
                ),
                (
                    "valor_aporte_ccf",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=18),
                ),
                (
                    "valor_aporte_icbf",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=18),
                ),
                (
                    "valor_aporte_sena",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=18),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Empleado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("apellido", models.CharField(max_length=100)),
                ("identificacion", models.CharField(max_length=20, unique=True)),
                ("fecha_nacimiento", models.DateField()),
                ("direccion", models.CharField(max_length=255)),
                ("telefono", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="NovedadNomina",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("valor", models.DecimalField(decimal_places=2, max_digits=18)),
                ("descripcion", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Planilla",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("periodo_inicio", models.DateField()),
                ("periodo_fin", models.DateField()),
                (
                    "total_devengado",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=18),
                ),
                (
                    "total_deduccion",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=18),
                ),
                (
                    "total_neto",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=18),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("BORRADOR", "Borrador"),
                            ("LIQUIDADA", "Liquidada"),
                            ("CONTABILIZADA", "Contabilizada"),
                            ("PAGADA", "Pagada"),
                        ],
                        default="BORRADOR",
                        max_length=20,
                    ),
                ),
            ],
        ),
    ]
