# Generated by Django 5.2.12 on 2026-03-15 13:07

import api.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("prestadores", "0001_full_reset"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConceptoNomina",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=10, unique=True)),
                ("descripcion", models.CharField(max_length=255)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("DEVENGADO", "Devengado"),
                            ("DEDUCCION", "Deducción"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Empleado",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("apellido", models.CharField(max_length=100)),
                ("identificacion", models.CharField(max_length=100, unique=True)),
                ("fecha_nacimiento", models.DateField()),
                ("direccion", api.fields.EncryptedTextField()),
                ("telefono", api.fields.EncryptedTextField()),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("framework_legal", models.CharField(default="CO", max_length=50)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("ACTIVO", "Activo"),
                            ("SUSPENDIDO", "Suspendido"),
                            ("RETIRADO", "Retirado"),
                        ],
                        default="ACTIVO",
                        max_length=20,
                    ),
                ),
                ("centro_costo", models.CharField(blank=True, max_length=100)),
                ("cargo", models.CharField(blank=True, max_length=100)),
                (
                    "perfil",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="empleados",
                        to="prestadores.providerprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Contrato",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("fecha_inicio", models.DateField()),
                ("fecha_fin", models.DateField(blank=True, null=True)),
                ("salario", models.DecimalField(decimal_places=2, max_digits=18)),
                ("cargo", models.CharField(max_length=100)),
                (
                    "tipo_contrato",
                    models.CharField(
                        choices=[
                            ("TERMINO_INDEFINIDO", "Término Indefinido"),
                            ("TERMINO_FIJO", "Término Fijo"),
                            ("OBRA_LABOR", "Obra o Labor"),
                            ("APRENDIZAJE", "Aprendizaje"),
                            ("PRESTACION_SERVICIOS", "Prestación de Servicios"),
                        ],
                        default="TERMINO_INDEFINIDO",
                        max_length=50,
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
                (
                    "evidencia_archivistica_ref_id",
                    models.UUIDField(blank=True, null=True),
                ),
                (
                    "empleado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contratos",
                        to="nomina.empleado",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Ausencia",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tipo", models.CharField(max_length=50)),
                ("fecha_inicio", models.DateTimeField()),
                ("fecha_fin", models.DateTimeField()),
                ("justificada", models.BooleanField(default=False)),
                (
                    "empleado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="nomina.empleado",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HistorialSalarial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_cambio", models.DateField()),
                (
                    "salario_anterior",
                    models.DecimalField(decimal_places=2, max_digits=18),
                ),
                ("salario_nuevo", models.DecimalField(decimal_places=2, max_digits=18)),
                ("motivo", models.CharField(blank=True, max_length=255)),
                (
                    "contrato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historial_salarial",
                        to="nomina.contrato",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IncapacidadLaboral",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("incidente_sst_ref_id", models.UUIDField(blank=True, null=True)),
                ("fecha_inicio", models.DateField()),
                ("fecha_fin", models.DateField()),
                ("tipo_incapacidad", models.CharField(max_length=100)),
                ("diagnostico", models.TextField()),
                ("estado", models.CharField(default="PENDIENTE", max_length=20)),
                ("evidencia_id", models.UUIDField(blank=True, null=True)),
                (
                    "empleado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="nomina.empleado",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IndicadorLaboral",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("valor", models.DecimalField(decimal_places=2, max_digits=18)),
                ("fecha_calculo", models.DateTimeField(auto_now_add=True)),
                ("periodo", models.CharField(max_length=20)),
                (
                    "perfil",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="prestadores.providerprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Planilla",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("periodo_inicio", models.DateField()),
                ("periodo_fin", models.DateField()),
                (
                    "total_devengado",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=18),
                ),
                (
                    "total_deduccion",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=18),
                ),
                (
                    "total_neto",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=18),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("BORRADOR", "Borrador"),
                            ("LIQUIDADA", "Liquidada"),
                            ("CONTABILIZADA", "Contabilizada"),
                            ("PAGADA", "Pagada"),
                        ],
                        default="BORRADOR",
                        max_length=20,
                    ),
                ),
                ("asiento_contable_ref_id", models.UUIDField(blank=True, null=True)),
                ("orden_pago_ref_id", models.UUIDField(blank=True, null=True)),
                (
                    "evidencia_archivistica_ref_id",
                    models.UUIDField(blank=True, null=True),
                ),
                (
                    "perfil",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="planillas",
                        to="prestadores.providerprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NovedadNomina",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_evento", models.DateField(blank=True, null=True)),
                ("valor", models.DecimalField(decimal_places=2, max_digits=18)),
                (
                    "cantidad",
                    models.DecimalField(
                        decimal_places=2,
                        default=1,
                        help_text="Horas, días, etc.",
                        max_digits=10,
                    ),
                ),
                ("descripcion", models.TextField(blank=True)),
                ("procesada", models.BooleanField(default=False)),
                (
                    "concepto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="nomina.conceptonomina",
                    ),
                ),
                (
                    "empleado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="nomina.empleado",
                    ),
                ),
                (
                    "planilla",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="novedades",
                        to="nomina.planilla",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DetalleLiquidacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("salario_base", models.DecimalField(decimal_places=2, max_digits=18)),
                ("dias_trabajados", models.IntegerField()),
                (
                    "basico",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "horas_extras",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "recargos",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "bonificaciones",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "comisiones",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "auxilio_transporte",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "salud_empleado",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "pension_empleado",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "embargos",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "otras_deducciones",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "total_devengado",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=18),
                ),
                (
                    "total_deduccion",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=18),
                ),
                (
                    "total_neto",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=18),
                ),
                (
                    "valor_prima",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=18),
                ),
                (
                    "valor_cesantias",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=18),
                ),
                (
                    "valor_intereses_cesantias",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=18),
                ),
                (
                    "valor_vacaciones",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=18),
                ),
                (
                    "valor_aporte_salud_patron",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=18),
                ),
                (
                    "valor_aporte_pension_patron",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=18),
                ),
                (
                    "valor_aporte_arl",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=18),
                ),
                (
                    "valor_aporte_ccf",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=18),
                ),
                (
                    "valor_aporte_icbf",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=18),
                ),
                (
                    "valor_aporte_sena",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=18),
                ),
                (
                    "empleado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="liquidaciones",
                        to="nomina.empleado",
                    ),
                ),
                (
                    "planilla",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detalles_liquidacion",
                        to="nomina.planilla",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProvisionNomina",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("periodo_mes", models.IntegerField()),
                ("periodo_anio", models.IntegerField()),
                ("tipo_prestacion", models.CharField(max_length=50)),
                ("monto_total", models.DecimalField(decimal_places=2, max_digits=18)),
                ("asiento_contable_ref_id", models.UUIDField(blank=True, null=True)),
                (
                    "perfil",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="prestadores.providerprofile",
                    ),
                ),
            ],
        ),
    ]
