# Generated by Django 5.2.6 on 2026-01-22 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("nomina", "0001_initial"),
        ("prestadores", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="empleado",
            name="perfil",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="empleados",
                to="prestadores.providerprofile",
            ),
        ),
        migrations.AddField(
            model_name="detalleliquidacion",
            name="empleado",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="liquidaciones",
                to="nomina.empleado",
            ),
        ),
        migrations.AddField(
            model_name="contrato",
            name="empleado",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contratos",
                to="nomina.empleado",
            ),
        ),
        migrations.AddField(
            model_name="novedadnomina",
            name="concepto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="nomina.conceptonomina"
            ),
        ),
        migrations.AddField(
            model_name="novedadnomina",
            name="empleado",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="nomina.empleado"
            ),
        ),
        migrations.AddField(
            model_name="planilla",
            name="perfil",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="planillas",
                to="prestadores.providerprofile",
            ),
        ),
        migrations.AddField(
            model_name="novedadnomina",
            name="planilla",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="novedades",
                to="nomina.planilla",
            ),
        ),
        migrations.AddField(
            model_name="detalleliquidacion",
            name="planilla",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="detalles_liquidacion",
                to="nomina.planilla",
            ),
        ),
    ]
