# Generated by Django 5.2.6 on 2026-02-08 16:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nomina", "0002_initial"),
        ("prestadores", "0003_capacitacionsst_incidentelaboral_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contrato",
            name="evidencia_archivistica_ref_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contrato",
            name="tipo_contrato",
            field=models.CharField(default="TERMINO_INDEFINIDO", max_length=50),
        ),
        migrations.AddField(
            model_name="empleado",
            name="framework_legal",
            field=models.CharField(default="CO", max_length=50),
        ),
        migrations.AddField(
            model_name="planilla",
            name="asiento_contable_ref_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="planilla",
            name="evidencia_archivistica_ref_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="planilla",
            name="orden_pago_ref_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="contrato",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="empleado",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="planilla",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.CreateModel(
            name="Ausencia",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tipo", models.CharField(max_length=50)),
                ("fecha_inicio", models.DateTimeField()),
                ("fecha_fin", models.DateTimeField()),
                ("justificada", models.BooleanField(default=False)),
                (
                    "empleado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="nomina.empleado",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IncapacidadLaboral",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("incidente_sst_ref_id", models.UUIDField(blank=True, null=True)),
                ("fecha_inicio", models.DateField()),
                ("fecha_fin", models.DateField()),
                ("tipo_incapacidad", models.CharField(max_length=100)),
                ("diagnostico", models.TextField()),
                ("estado", models.CharField(default="PENDIENTE", max_length=20)),
                (
                    "empleado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="nomina.empleado",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProvisionNomina",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("periodo_mes", models.IntegerField()),
                ("periodo_anio", models.IntegerField()),
                ("tipo_prestacion", models.CharField(max_length=50)),
                ("monto_total", models.DecimalField(decimal_places=2, max_digits=18)),
                ("asiento_contable_ref_id", models.UUIDField(blank=True, null=True)),
                (
                    "perfil",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="prestadores.providerprofile",
                    ),
                ),
            ],
        ),
    ]
