# Generated by Django 5.2.6 on 2026-02-15 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nomina", "0003_contrato_evidencia_archivistica_ref_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="detalleliquidacion",
            name="total_deduccion",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=18),
        ),
        migrations.AddField(
            model_name="detalleliquidacion",
            name="total_devengado",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=18),
        ),
        migrations.AddField(
            model_name="detalleliquidacion",
            name="total_neto",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=18),
        ),
    ]
