# Generated by Django 5.2.11 on 2026-02-15 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nomina", "0004_detalleliquidacion_total_deduccion_and_more"),
        (
            "prestadores",
            "0005_capacitacionsst_programada_capacitacionsst_realizada_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="detalleliquidacion",
            name="auxilio_transporte",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name="detalleliquidacion",
            name="basico",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name="detalleliquidacion",
            name="bonificaciones",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name="detalleliquidacion",
            name="comisiones",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name="detalleliquidacion",
            name="embargos",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name="detalleliquidacion",
            name="horas_extras",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name="detalleliquidacion",
            name="otras_deducciones",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name="detalleliquidacion",
            name="pension_empleado",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name="detalleliquidacion",
            name="recargos",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name="detalleliquidacion",
            name="salud_empleado",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name="detalleliquidacion",
            name="valor_aporte_arl",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=18),
        ),
        migrations.AddField(
            model_name="detalleliquidacion",
            name="valor_aporte_pension_patron",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=18),
        ),
        migrations.AddField(
            model_name="detalleliquidacion",
            name="valor_aporte_salud_patron",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=18),
        ),
        migrations.AddField(
            model_name="empleado",
            name="cargo",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="empleado",
            name="centro_costo",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="empleado",
            name="estado",
            field=models.CharField(
                choices=[
                    ("ACTIVO", "Activo"),
                    ("SUSPENDIDO", "Suspendido"),
                    ("RETIRADO", "Retirado"),
                ],
                default="ACTIVO",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="incapacidadlaboral",
            name="evidencia_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="novedadnomina",
            name="cantidad",
            field=models.DecimalField(
                decimal_places=2,
                default=1,
                help_text="Horas, días, etc.",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="novedadnomina",
            name="fecha_evento",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="novedadnomina",
            name="procesada",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="contrato",
            name="tipo_contrato",
            field=models.CharField(
                choices=[
                    ("TERMINO_INDEFINIDO", "Término Indefinido"),
                    ("TERMINO_FIJO", "Término Fijo"),
                    ("OBRA_LABOR", "Obra o Labor"),
                    ("APRENDIZAJE", "Aprendizaje"),
                    ("PRESTACION_SERVICIOS", "Prestación de Servicios"),
                ],
                default="TERMINO_INDEFINIDO",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="novedadnomina",
            name="planilla",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="novedades",
                to="nomina.planilla",
            ),
        ),
        migrations.CreateModel(
            name="HistorialSalarial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_cambio", models.DateField()),
                (
                    "salario_anterior",
                    models.DecimalField(decimal_places=2, max_digits=18),
                ),
                ("salario_nuevo", models.DecimalField(decimal_places=2, max_digits=18)),
                ("motivo", models.CharField(blank=True, max_length=255)),
                (
                    "contrato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historial_salarial",
                        to="nomina.contrato",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IndicadorLaboral",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("valor", models.DecimalField(decimal_places=2, max_digits=18)),
                ("fecha_calculo", models.DateTimeField(auto_now_add=True)),
                ("periodo", models.CharField(max_length=20)),
                (
                    "perfil",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="prestadores.providerprofile",
                    ),
                ),
            ],
        ),
    ]
