# Generated by Django 5.2.6 on 2026-02-06 04:14

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GovernanceMemory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        help_text="Ej: CRISIS_DIPLOMATICA, TENSION_ECONOMICA",
                        max_length=100,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "detected_patterns",
                    models.JSONField(
                        help_text="Indicadores técnicos que precedieron al evento."
                    ),
                ),
                (
                    "actions_taken",
                    models.JSONField(help_text="Acciones de gobernanza ejecutadas."),
                ),
                (
                    "effectiveness_score",
                    models.FloatField(
                        default=0.0,
                        help_text="Puntaje de 0 a 1 sobre la efectividad de la respuesta.",
                    ),
                ),
                ("lessons_learned", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Memoria de Gobernanza",
                "verbose_name_plural": "Memorias de Gobernanza",
            },
        ),
        migrations.CreateModel(
            name="SystemicState",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "current_level",
                    models.CharField(
                        choices=[
                            ("NORMAL", "Estado Normal (Operación Plena)"),
                            ("OBSERVATION", "Observación Reforzada"),
                            ("WARNING", "Alerta Preventiva"),
                            ("CONTAINMENT", "Contención (Restricción de Autonomía)"),
                            ("PARTIAL_DECOUPLING", "Desacoplamiento Parcial"),
                            (
                                "TOTAL_DECOUPLING",
                                "Desacoplamiento Total (Soberanía Pura)",
                            ),
                        ],
                        default="NORMAL",
                        max_length=50,
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "reason",
                    models.TextField(
                        help_text="Justificación institucional del cambio de estado."
                    ),
                ),
                (
                    "context_data",
                    models.JSONField(
                        default=dict, help_text="Señales que dispararon la transición."
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "authorized_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="state_authorizations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Estado Sistémico",
                "verbose_name_plural": "Estados Sistémicos",
                "ordering": ["-timestamp"],
            },
        ),
    ]
