# Generated by Django 5.2.6 on 2025-11-09 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion_archivistica", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentversion",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING_UPLOAD", "Pendiente de Subida"),
                    ("PENDING_CONFIRMATION", "Pendiente de Confirmación"),
                    ("IN_BATCH", "En Lote para Notarización"),
                    ("VERIFIED", "Verificado"),
                    ("COMPROMISED", "Comprometido"),
                ],
                default="PENDING_UPLOAD",
                max_length=20,
            ),
        ),
    ]
