# Generated by Django 5.2.6 on 2025-10-28 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("prestadores", "0002_costo_inventario_productoservicio"),
    ]

    operations = [
        migrations.CreateModel(
            name="Producto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                ("descripcion", models.TextField(blank=True)),
                (
                    "costo_promedio_ponderado",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "cantidad_en_stock",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "perfil",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="productos",
                        to="prestadores.perfil",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MovimientoInventario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("ENTRADA", "Entrada por Compra"),
                            ("SALIDA", "Salida por Venta"),
                            ("AJUSTE", "Ajuste Manual"),
                        ],
                        max_length=10,
                    ),
                ),
                ("fecha", models.DateField()),
                ("cantidad", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "costo_unitario",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                ("costo_total", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movimientos",
                        to="inventario.producto",
                    ),
                ),
            ],
        ),
    ]
