# Generated by Django 5.2.6 on 2025-10-29 22:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("prestadores", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Producto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                ("descripcion", models.TextField(blank=True)),
                (
                    "costo_promedio_ponderado",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "cantidad_en_stock",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "perfil",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="productos",
                        to="prestadores.perfil",
                    ),
                ),
            ],
        ),
    ]
