# Generated by Django 5.2.6 on 2025-10-30 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0001_initial"),
        ("prestadores", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="producto",
            name="cantidad_en_stock",
        ),
        migrations.RemoveField(
            model_name="producto",
            name="costo_promedio_ponderado",
        ),
        migrations.RemoveField(
            model_name="producto",
            name="descripcion",
        ),
        migrations.AlterField(
            model_name="producto",
            name="perfil",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="productos_inventario",
                to="prestadores.perfil",
            ),
        ),
    ]
