# Generated by Django 5.2.6 on 2025-11-01 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0002_remove_producto_cantidad_en_stock_and_more"),
        ("mi_negocio", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producto",
            name="perfil",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="productos_inventario",
                to="mi_negocio.perfil",
            ),
        ),
    ]
