# Generated by Django 5.2.12 on 2026-03-15 13:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core_erp", "0001_initial_base"),
    ]

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "profile_id",
                    models.UUIDField(
                        blank=True,
                        help_text="Decoupled reference to Operational Profile",
                        null=True,
                    ),
                ),
                ("first_name", models.CharField(max_length=150)),
                ("last_name", models.CharField(max_length=150)),
                (
                    "tax_id",
                    models.CharField(
                        help_text="SSN or National ID", max_length=50, unique=True
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("address", models.TextField(blank=True, null=True)),
                ("birth_date", models.DateField(blank=True, null=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_records",
                        to="core_erp.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Employee",
                "db_table": "admin_payroll_employee",
            },
        ),
        migrations.CreateModel(
            name="EmploymentContract",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("base_salary", models.DecimalField(decimal_places=2, max_digits=18)),
                ("position", models.CharField(blank=True, max_length=150, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contracts",
                        to="admin_payroll.employee",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_records",
                        to="core_erp.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Employment Contract",
                "db_table": "admin_payroll_contract",
            },
        ),
        migrations.CreateModel(
            name="PayrollConcept",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("code", models.CharField(max_length=20, null=True, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "type",
                    models.CharField(
                        choices=[("EARNING", "Earning"), ("DEDUCTION", "Deduction")],
                        default="EARNING",
                        max_length=20,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_records",
                        to="core_erp.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payroll Concept",
                "db_table": "admin_payroll_concept",
            },
        ),
        migrations.CreateModel(
            name="PayrollRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("profile_id", models.UUIDField(blank=True, null=True)),
                ("period_start", models.DateField(null=True)),
                ("period_end", models.DateField(null=True)),
                ("month", models.IntegerField()),
                ("year", models.IntegerField()),
                (
                    "total_earnings",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=18),
                ),
                (
                    "total_deductions",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=18),
                ),
                (
                    "net_total",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=18),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_records",
                        to="core_erp.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payroll Run",
                "db_table": "admin_payroll_run",
            },
        ),
        migrations.CreateModel(
            name="PayrollNews",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=18)),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "concept",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="admin_payroll.payrollconcept",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payroll_news",
                        to="admin_payroll.employee",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_records",
                        to="core_erp.tenant",
                    ),
                ),
                (
                    "payroll_run",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="news",
                        to="admin_payroll.payrollrun",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payroll News",
                "db_table": "admin_payroll_news",
            },
        ),
        migrations.CreateModel(
            name="PayrollDetail",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "total_earnings",
                    models.DecimalField(decimal_places=2, max_digits=18),
                ),
                (
                    "total_deductions",
                    models.DecimalField(decimal_places=2, max_digits=18),
                ),
                ("net_pay", models.DecimalField(decimal_places=2, max_digits=18)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="admin_payroll.employee",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_records",
                        to="core_erp.tenant",
                    ),
                ),
                (
                    "payroll_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="details",
                        to="admin_payroll.payrollrun",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payroll Detail",
                "db_table": "admin_payroll_detail",
            },
        ),
    ]
