# Generated by Django 5.2.12 on 2026-03-15 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("prestadores", "0001_full_reset"),
    ]

    operations = [
        migrations.CreateModel(
            name="PeriodoContable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("fecha_inicio", models.DateField()),
                ("fecha_fin", models.DateField()),
                (
                    "estado",
                    models.CharField(
                        choices=[("ABIERTO", "Abierto"), ("CERRADO", "Cerrado")],
                        default="ABIERTO",
                        max_length=20,
                    ),
                ),
                (
                    "perfil",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="periodos_contables",
                        to="prestadores.providerprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha_inicio"],
                "unique_together": {("perfil", "fecha_inicio", "fecha_fin")},
            },
        ),
    ]
