# Generated by Django 5.2.6 on 2026-01-22 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cierres", "0001_initial"),
        ("prestadores", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="periodocontable",
            name="perfil",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="periodos_contables",
                to="prestadores.providerprofile",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="periodocontable",
            unique_together={("perfil", "fecha_inicio", "fecha_fin")},
        ),
    ]
