# Generated by Django 6.0.3 on 2026-03-23 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("prestadores", "0001_full_reset"),
    ]

    operations = [
        migrations.CreateModel(
            name="OperadorTuristico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("descripcion", models.TextField()),
                ("licencia_turismo", models.CharField(blank=True, max_length=100)),
                (
                    "perfil",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operador_turistico",
                        to="prestadores.providerprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PaqueteTuristico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("duracion_dias", models.PositiveIntegerField()),
                (
                    "incluye",
                    models.TextField(
                        blank=True,
                        help_text="Breve descripción de lo que incluye el paquete (ej: Alojamiento, Transporte).",
                        null=True,
                    ),
                ),
                (
                    "operador",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paquetes",
                        to="operadores_turisticos.operadorturistico",
                    ),
                ),
                (
                    "producto",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paquete_turistico",
                        to="prestadores.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ItinerarioDia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dia", models.PositiveIntegerField()),
                (
                    "titulo",
                    models.CharField(
                        help_text="Ej: 'Día 1: Llegada a la ciudad'", max_length=200
                    ),
                ),
                ("descripcion", models.TextField()),
                (
                    "paquete",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itinerario",
                        to="operadores_turisticos.paqueteturistico",
                    ),
                ),
            ],
            options={
                "ordering": ["dia"],
                "unique_together": {("paquete", "dia")},
            },
        ),
    ]
