# Generated by Django 5.2.12 on 2026-03-15 13:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AddOn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=50, unique=True)),
                ("monthly_price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone", models.CharField(blank=True, max_length=50)),
                ("source", models.CharField(default="organic", max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("qualified", "Qualified"),
                            ("rejected", "Rejected"),
                            ("converted", "Converted"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                ("score", models.IntegerField(default=0)),
                (
                    "estimated_value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="UsageMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tenant_id", models.CharField(max_length=100)),
                ("metric_type", models.CharField(max_length=50)),
                ("quantity", models.DecimalField(decimal_places=4, max_digits=15)),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Opportunity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("prospecting", "Prospecting"),
                            ("won", "Won"),
                            ("lost", "Lost"),
                        ],
                        default="prospecting",
                        max_length=20,
                    ),
                ),
                (
                    "estimated_revenue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="opportunities",
                        to="comercial.lead",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=50)),
                ("version", models.IntegerField(default=1)),
                ("description", models.TextField(blank=True)),
                (
                    "billing_schema",
                    models.CharField(
                        choices=[
                            ("FLAT", "Precio Fijo"),
                            ("TIERED", "Por Tramos (Escalonado)"),
                            ("PER_UNIT", "Por Unidad de Uso"),
                        ],
                        default="FLAT",
                        max_length=20,
                    ),
                ),
                (
                    "monthly_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "yearly_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("storage_limit_gb", models.IntegerField(default=5)),
                ("user_limit", models.IntegerField(default=1)),
                ("transaction_limit", models.IntegerField(default=100)),
                (
                    "target_user_type",
                    models.CharField(
                        choices=[("GOVERNMENT", "Gobierno"), ("PROVIDER", "Prestador")],
                        default="PROVIDER",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Configuraciones extra del plan",
                    ),
                ),
            ],
            options={
                "unique_together": {("code", "version")},
            },
        ),
        migrations.CreateModel(
            name="PlanTier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("from_unit", models.IntegerField()),
                ("to_unit", models.IntegerField(blank=True, null=True)),
                (
                    "price_per_unit",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tiers",
                        to="comercial.plan",
                    ),
                ),
            ],
            options={
                "ordering": ["from_unit"],
            },
        ),
        migrations.CreateModel(
            name="PricingRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "extra_gb_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pricing_rules",
                        to="comercial.plan",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tenant_id", models.CharField(max_length=100, unique=True)),
                (
                    "perfil_ref_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("TRIAL", "Periodo de Prueba"),
                            ("ACTIVE", "Activa"),
                            ("PAST_DUE", "Mora (Pendiente)"),
                            ("SUSPENDED", "Suspendida"),
                            ("CANCELED", "Cancelada"),
                        ],
                        default="TRIAL",
                        max_length=20,
                    ),
                ),
                (
                    "billing_cycle",
                    models.CharField(
                        choices=[("MONTHLY", "Mensual"), ("YEARLY", "Anual")],
                        default="MONTHLY",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField(auto_now_add=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("next_billing_date", models.DateField(blank=True, null=True)),
                ("last_billing_date", models.DateField(blank=True, null=True)),
                ("cancel_at_period_end", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("health_score", models.FloatField(default=1.0)),
                ("last_activity", models.DateTimeField(blank=True, null=True)),
                (
                    "add_ons",
                    models.ManyToManyField(
                        blank=True, related_name="subscriptions", to="comercial.addon"
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="comercial.plan"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BillingCycle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cycle_start", models.DateField()),
                ("cycle_end", models.DateField()),
                (
                    "amount_calculated",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("status", models.CharField(default="pending", max_length=20)),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="billing_cycles",
                        to="comercial.subscription",
                    ),
                ),
            ],
        ),
    ]
