# Generated by Django 5.2.6 on 2025-10-28 10:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("prestadores", "0002_costo_inventario_productoservicio"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                ("identificacion", models.CharField(blank=True, max_length=50)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("telefono", models.CharField(blank=True, max_length=50)),
                ("direccion", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "perfil",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clientes_comerciales",
                        to="prestadores.perfil",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FacturaVenta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_emision", models.DateField()),
                ("fecha_vencimiento", models.DateField()),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "impuestos",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "pagado",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("BORRADOR", "Borrador"),
                            ("EMITIDA", "Emitida"),
                            ("PAGADA", "Pagada"),
                            ("VENCIDA", "Vencida"),
                            ("ANULADA", "Anulada"),
                        ],
                        default="BORRADOR",
                        max_length=10,
                    ),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="comercial.cliente",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "perfil",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="facturas_venta",
                        to="prestadores.perfil",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ItemFactura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descripcion", models.CharField(max_length=255)),
                ("cantidad", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "precio_unitario",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                ("total_item", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "factura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="comercial.facturaventa",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NotaCredito",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField()),
                ("motivo", models.TextField()),
                ("monto", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "factura_original",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="comercial.facturaventa",
                    ),
                ),
                (
                    "perfil",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notas_credito",
                        to="prestadores.perfil",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PagoRecibido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_pago", models.DateField()),
                ("monto", models.DecimalField(decimal_places=2, max_digits=15)),
                ("metodo_pago", models.CharField(max_length=50)),
                (
                    "factura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pagos",
                        to="comercial.facturaventa",
                    ),
                ),
                (
                    "perfil",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pagos_recibidos",
                        to="prestadores.perfil",
                    ),
                ),
            ],
        ),
    ]
