# Generated by Django 5.2.6 on 2025-10-29 01:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("comercial", "0001_initial"),
        ("contabilidad", "0001_initial"),
        ("inventario", "0001_initial"),
        ("prestadores", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="facturaventa",
            name="centro_costo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="contabilidad.costcenter",
            ),
        ),
        migrations.AddField(
            model_name="facturaventa",
            name="cliente",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="comercial.cliente"
            ),
        ),
        migrations.AddField(
            model_name="facturaventa",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="facturaventa",
            name="perfil",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="facturas_venta",
                to="prestadores.perfil",
            ),
        ),
        migrations.AddField(
            model_name="itemfactura",
            name="factura",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="comercial.facturaventa",
            ),
        ),
        migrations.AddField(
            model_name="itemfactura",
            name="producto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="inventario.producto"
            ),
        ),
        migrations.AddField(
            model_name="notacredito",
            name="factura_original",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="comercial.facturaventa"
            ),
        ),
        migrations.AddField(
            model_name="notacredito",
            name="perfil",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notas_credito",
                to="prestadores.perfil",
            ),
        ),
        migrations.AddField(
            model_name="pagorecibido",
            name="factura",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pagos",
                to="comercial.facturaventa",
            ),
        ),
        migrations.AddField(
            model_name="pagorecibido",
            name="perfil",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pagos_recibidos",
                to="prestadores.perfil",
            ),
        ),
    ]
