# Generated by Django 5.2.6 on 2025-10-28 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0001_initial"),
        ("contabilidad", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="facturaventa",
            name="centro_costo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="contabilidad.costcenter",
            ),
        ),
    ]
