# Generated by Django 5.2.6 on 2025-10-28 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("comercial", "0001_initial"),
        ("inventario", "0001_initial"),
        ("prestadores", "0002_costo_inventario_productoservicio"),
    ]

    operations = [
        migrations.AddField(
            model_name="itemfactura",
            name="producto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="inventario.producto"
            ),
        ),
        migrations.AddField(
            model_name="notacredito",
            name="factura_original",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="comercial.facturaventa"
            ),
        ),
        migrations.AddField(
            model_name="notacredito",
            name="perfil",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notas_credito",
                to="prestadores.perfil",
            ),
        ),
        migrations.AddField(
            model_name="pagorecibido",
            name="factura",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pagos",
                to="comercial.facturaventa",
            ),
        ),
        migrations.AddField(
            model_name="pagorecibido",
            name="perfil",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pagos_recibidos",
                to="prestadores.perfil",
            ),
        ),
    ]
