# Generated by Django 5.2.6 on 2025-11-01 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0002_facturaventa_itemfactura"),
        ("mi_negocio", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cliente",
            name="perfil",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="clientes_comerciales",
                to="mi_negocio.perfil",
                verbose_name="Perfil del Prestador",
            ),
        ),
    ]
