# Generated by Django 5.2.6 on 2025-11-02 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0003_alter_cliente_perfil"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="facturaventa",
            name="cliente",
        ),
        migrations.RemoveField(
            model_name="itemfactura",
            name="factura",
        ),
        migrations.RemoveField(
            model_name="itemfactura",
            name="producto",
        ),
        migrations.DeleteModel(
            name="Cliente",
        ),
        migrations.DeleteModel(
            name="FacturaVenta",
        ),
        migrations.DeleteModel(
            name="ItemFactura",
        ),
    ]
