# Generated by Django 6.0 on 2025-12-18 01:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("funnels", "0003_lead_leadevent_leadstate"),
        ("marketing", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sendlog",
            name="variant",
        ),
        migrations.RemoveField(
            model_name="campaignchannel",
            name="config_json",
        ),
        migrations.AddField(
            model_name="campaign",
            name="target_leads",
            field=models.ManyToManyField(
                blank=True, related_name="marketing_campaigns", to="funnels.lead"
            ),
        ),
        migrations.AddField(
            model_name="campaign",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="campaignchannel",
            name="open_rate",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="campaignchannel",
            name="sent_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Borrador"),
                    ("scheduled", "Programada"),
                    ("sending", "Enviando"),
                    ("sent", "Enviada"),
                    ("archived", "Archivada"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="campaignchannel",
            name="channel_type",
            field=models.CharField(
                choices=[
                    ("email", "Email"),
                    ("sms", "SMS"),
                    ("whatsapp", "WhatsApp"),
                    ("facebook", "Facebook"),
                    ("instagram", "Instagram"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="campaignchannel",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="MarketingContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        blank=True, help_text="Asunto para emails", max_length=255
                    ),
                ),
                (
                    "body_text",
                    models.TextField(
                        blank=True,
                        help_text="Contenido principal en texto plano o Markdown",
                    ),
                ),
                (
                    "body_html",
                    models.TextField(
                        blank=True, help_text="Contenido HTML para emails"
                    ),
                ),
                (
                    "campaign",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content",
                        to="marketing.campaign",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="MessageVariant",
        ),
        migrations.DeleteModel(
            name="SendLog",
        ),
    ]
