# Generated by Django 5.2.6 on 2026-01-06 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="InformacionEmpresa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("razon_social", models.CharField(max_length=255)),
                ("nit", models.CharField(max_length=20, unique=True)),
                (
                    "perfil",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="informacion_empresa",
                        to="api.providerprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tercero",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                ("nit_o_cedula", models.CharField(max_length=20, unique=True)),
                (
                    "perfil",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="terceros",
                        to="api.providerprofile",
                    ),
                ),
            ],
            options={
                "unique_together": {("perfil", "nit_o_cedula")},
            },
        ),
    ]
