# Generated by Django 5.2.6 on 2026-01-22 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="InformacionEmpresa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("razon_social", models.CharField(max_length=255)),
                ("nit", models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Tercero",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                ("nit_o_cedula", models.CharField(max_length=20, unique=True)),
            ],
        ),
    ]
