# Generated by Django 5.2.6 on 2026-01-22 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("empresa", "0001_initial"),
        ("prestadores", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="informacionempresa",
            name="perfil",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="informacion_empresa",
                to="prestadores.providerprofile",
            ),
        ),
        migrations.AddField(
            model_name="tercero",
            name="perfil",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="terceros",
                to="prestadores.providerprofile",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="tercero",
            unique_together={("perfil", "nit_o_cedula")},
        ),
    ]
