import uuid
from django.conf import settings
from django.db import models
from django.utils.translation import gettext_lazy as _

class SadiAuditLog(models.Model):
    """
    Registra cada comando de voz procesado por el Orquestador SADI.
    """
    usuario = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        related_name='sadi_commands'
    )
    comando_original = models.TextField(
        help_text="El comando de voz original en texto plano."
    )
    accion_ejecutada = models.JSONField(
        null=True,
        blank=True,
        help_text="La acción y parámetros interpretados por el LLM."
    )
    resultado = models.TextField(
        help_text="El resultado de la ejecución del comando (éxito, error, etc.)."
    )
    timestamp = models.DateTimeField(
        auto_now_add=True,
        help_text="Fecha y hora en que se procesó el comando."
    )

    def __str__(self):
        return f"Comando de {self.usuario} a las {self.timestamp.strftime('%Y-%m-%d %H:%M')}"

    class Meta:
        verbose_name = "Registro de Auditoría SADI"
        verbose_name_plural = "Registros de Auditoría SADI"
        ordering = ['-timestamp']


class AgentExecution(models.Model):
    """
    Stores the entire lifecycle of an agent's execution, from objective to final result.
    """
    class Status(models.TextChoices):
        PENDING = 'PENDING', _('Pending')
        RUNNING = 'RUNNING', _('Running')
        COMPLETED = 'COMPLETED', _('Completed')
        FAILED = 'FAILED', _('Failed')

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='agent_executions',
        verbose_name=_('user')
    )
    objective = models.TextField(
        verbose_name=_('objective'),
        help_text=_('The initial objective or prompt given to the agent.')
    )
    plan = models.JSONField(
        null=True,
        blank=True,
        verbose_name=_('plan'),
        help_text=_('The step-by-step plan generated by the planner LLM.')
    )
    execution_history = models.JSONField(
        default=list,
        blank=True,
        verbose_name=_('execution history'),
        help_text=_('A list of executed steps, including thoughts, tools, params, and observations.')
    )
    logs = models.TextField(
        blank=True,
        verbose_name=_('logs'),
        help_text=_('The full, raw log output from the agent\'s logger.')
    )
    final_result = models.TextField(
        blank=True,
        verbose_name=_('final result'),
        help_text=_('The final answer or result from the agent\'s execution.')
    )
    status = models.CharField(
        max_length=10,
        choices=Status.choices,
        default=Status.PENDING,
        verbose_name=_('status')
    )
    created_at = models.DateTimeField(auto_now_add=True, verbose_name=_('created at'))
    updated_at = models.DateTimeField(auto_now=True, verbose_name=_('updated at'))

    class Meta:
        verbose_name = _('agent execution')
        verbose_name_plural = _('agent executions')
        ordering = ['-created_at']

    def __str__(self):
        return f"Execution {self.id} for {self.user.email} ({self.status})"
