# Generated by Django 5.2.6 on 2026-01-06 14:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("api", "0001_initial"),
        ("gestion_financiera", "0001_initial"),
        ("prestadores", "0004_product_stock"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FacturaVenta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_factura", models.CharField(max_length=50)),
                ("fecha_emision", models.DateField()),
                ("fecha_vencimiento", models.DateField(blank=True, null=True)),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "impuestos",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_pagado",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("BORRADOR", "Borrador"),
                            ("EMITIDA", "Emitida"),
                            ("PAGADA", "Pagada"),
                            ("ANULADA", "Anulada"),
                        ],
                        default="BORRADOR",
                        max_length=20,
                    ),
                ),
                (
                    "estado_dian",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PENDIENTE_ENVIO", "Pendiente de Envío"),
                            ("ENVIADA", "Enviada"),
                            ("ACEPTADA", "Aceptada"),
                            ("RECHAZADA", "Rechazada con Errores"),
                            ("CONTINGENCIA", "Contingencia"),
                        ],
                        default="PENDIENTE_ENVIO",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "cufe",
                    models.CharField(
                        blank=True,
                        help_text="Código Único de Factura Electrónica",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "track_id_dian",
                    models.CharField(
                        blank=True,
                        help_text="ID de seguimiento de la DIAN",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "xml_dian",
                    models.TextField(
                        blank=True,
                        help_text="XML de la factura electrónica enviada a la DIAN",
                        null=True,
                    ),
                ),
                (
                    "pdf_dian",
                    models.FileField(
                        blank=True,
                        help_text="PDF de la representación gráfica de la factura",
                        null=True,
                        upload_to="facturas_electronicas/",
                    ),
                ),
                (
                    "dian_response_log",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Log de respuestas de la DIAN",
                        null=True,
                    ),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="facturas",
                        to="prestadores.cliente",
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="facturas_creadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "perfil",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="facturas_venta",
                        to="api.providerprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha_emision", "-numero_factura"],
            },
        ),
        migrations.CreateModel(
            name="ItemFactura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descripcion", models.CharField(max_length=255)),
                ("cantidad", models.PositiveIntegerField()),
                (
                    "precio_unitario",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("subtotal", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "impuestos",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "factura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="gestion_comercial.facturaventa",
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="prestadores.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OperacionComercial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_operacion",
                    models.CharField(
                        choices=[
                            ("VENTA", "Venta de Productos/Servicios"),
                            ("CONTRATO", "Contrato"),
                        ],
                        default="VENTA",
                        max_length=20,
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("BORRADOR", "Borrador"),
                            ("CONFIRMADA", "Confirmada"),
                            ("FACTURADA", "Facturada"),
                            ("ANULADA", "Anulada"),
                        ],
                        default="BORRADOR",
                        max_length=20,
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "impuestos",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_confirmacion", models.DateTimeField(blank=True, null=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="operaciones_comerciales",
                        to="prestadores.cliente",
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "perfil",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operaciones_comerciales",
                        to="api.providerprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ItemOperacionComercial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descripcion", models.CharField(max_length=255)),
                ("cantidad", models.PositiveIntegerField()),
                (
                    "precio_unitario",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("subtotal", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="prestadores.product",
                    ),
                ),
                (
                    "operacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="gestion_comercial.operacioncomercial",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="facturaventa",
            name="operacion",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="factura",
                to="gestion_comercial.operacioncomercial",
            ),
        ),
        migrations.CreateModel(
            name="ReciboCaja",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_pago", models.DateField()),
                ("monto", models.DecimalField(decimal_places=2, max_digits=12)),
                ("metodo_pago", models.CharField(max_length=50)),
                (
                    "cuenta_bancaria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="gestion_financiera.cuentabancaria",
                    ),
                ),
                (
                    "factura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recibos_caja",
                        to="gestion_comercial.facturaventa",
                    ),
                ),
                (
                    "perfil",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recibos_caja",
                        to="api.providerprofile",
                    ),
                ),
            ],
        ),
        migrations.AlterUniqueTogether(
            name="facturaventa",
            unique_together={("perfil", "numero_factura")},
        ),
    ]
