# Generated by Django 5.2.6 on 2025-12-23 23:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("api", "0001_initial"),
        ("gestion_financiera", "0001_initial"),
        ("inventario", "0001_initial"),
        ("prestadores", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FacturaVenta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_factura", models.CharField(max_length=50)),
                ("fecha_emision", models.DateField()),
                ("fecha_vencimiento", models.DateField(blank=True, null=True)),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=18),
                ),
                (
                    "impuestos",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=18),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=18),
                ),
                (
                    "total_pagado",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=18),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("BORRADOR", "Borrador"),
                            ("ENVIADA", "Enviada"),
                            ("PAGADA", "Pagada"),
                            ("VENCIDA", "Vencida"),
                            ("ANULADA", "Anulada"),
                        ],
                        default="BORRADOR",
                        max_length=20,
                    ),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="facturas",
                        to="prestadores.cliente",
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "perfil",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="facturas_venta",
                        to="api.providerprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ItemFactura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descripcion", models.CharField(max_length=255)),
                ("cantidad", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "precio_unitario",
                    models.DecimalField(decimal_places=2, max_digits=18),
                ),
                ("subtotal", models.DecimalField(decimal_places=2, max_digits=18)),
                (
                    "impuestos",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=18),
                ),
                (
                    "factura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="gestion_comercial.facturaventa",
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="inventario.producto",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReciboCaja",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_pago", models.DateField()),
                ("monto", models.DecimalField(decimal_places=2, max_digits=18)),
                (
                    "metodo_pago",
                    models.CharField(
                        choices=[
                            ("EFECTIVO", "Efectivo"),
                            ("TRANSFERENCIA", "Transferencia"),
                            ("TARJETA", "Tarjeta"),
                            ("OTRO", "Otro"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "cuenta_bancaria",
                    models.ForeignKey(
                        help_text="Cuenta donde se recibe el pago",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="gestion_financiera.cuentabancaria",
                    ),
                ),
                (
                    "factura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recibos",
                        to="gestion_comercial.facturaventa",
                    ),
                ),
                (
                    "perfil",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recibos_caja",
                        to="api.providerprofile",
                    ),
                ),
            ],
        ),
    ]
