# Generated by Django 5.2.6 on 2026-01-07 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("api", "0001_initial"),
        ("gestion_comercial", "0001_initial"),
        ("gestion_financiera", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="recibocaja",
            name="cuenta_bancaria",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="gestion_financiera.cuentabancaria",
            ),
        ),
        migrations.AddField(
            model_name="recibocaja",
            name="factura",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recibos_caja",
                to="gestion_comercial.facturaventa",
            ),
        ),
        migrations.AddField(
            model_name="recibocaja",
            name="perfil",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recibos_caja",
                to="api.providerprofile",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="facturaventa",
            unique_together={("perfil", "numero_factura")},
        ),
    ]
