# Generated by Django 5.2.6 on 2026-02-07 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion_comercial", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="operacioncomercial",
            name="estado",
            field=models.CharField(
                choices=[
                    ("BORRADOR", "Borrador"),
                    ("CONFIRMADA", "Confirmada"),
                    ("COMERCIAL_CONFIRMADA", "Comercial Confirmada"),
                    ("FACTURADA", "Facturada"),
                    ("ANULADA", "Anulada"),
                ],
                default="BORRADOR",
                max_length=20,
            ),
        ),
    ]
