# Generated by Django 6.0.3 on 2026-03-23 21:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("domain_business", "0001_full_reset"),
        ("gestion_comercial", "0001_full_reset"),
    ]

    operations = [
        migrations.CreateModel(
            name="FacturaElectronica",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("cufe", models.CharField(max_length=188, unique=True)),
                ("xml_content", models.TextField()),
                ("pdf_url", models.URLField(blank=True)),
                (
                    "estado_dian",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("aceptada", "Aceptada"),
                            ("rechazada", "Rechazada"),
                        ],
                        default="pendiente",
                        max_length=20,
                    ),
                ),
                ("codigo_respuesta_dian", models.CharField(max_length=20)),
                ("fecha_envio_dian", models.DateTimeField(blank=True, null=True)),
                ("fecha_respuesta_dian", models.DateTimeField(blank=True, null=True)),
                ("email_enviada", models.BooleanField(default=False)),
                ("prestador_email", models.EmailField(max_length=254)),
                ("tenant_id", models.CharField(max_length=36)),
                (
                    "operacion_comercial",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="factura_electronica",
                        to="domain_business.commercialoperation",
                    ),
                ),
            ],
        ),
    ]
