# Generated by Django 5.2.6 on 2025-12-11 15:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("gestion_comercial", "0001_initial"),
        ("gestion_financiera", "0001_initial"),
        ("inventario", "0001_initial"),
        ("prestadores", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="facturaventa",
            name="cliente",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="facturas",
                to="prestadores.cliente",
            ),
        ),
        migrations.AddField(
            model_name="facturaventa",
            name="creado_por",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="facturaventa",
            name="perfil",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="facturas_venta",
                to="prestadores.providerprofile",
            ),
        ),
        migrations.AddField(
            model_name="itemfactura",
            name="factura",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="gestion_comercial.facturaventa",
            ),
        ),
        migrations.AddField(
            model_name="itemfactura",
            name="producto",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="inventario.producto",
            ),
        ),
        migrations.AddField(
            model_name="recibocaja",
            name="cuenta_bancaria",
            field=models.ForeignKey(
                help_text="Cuenta donde se recibe el pago",
                on_delete=django.db.models.deletion.PROTECT,
                to="gestion_financiera.cuentabancaria",
            ),
        ),
        migrations.AddField(
            model_name="recibocaja",
            name="factura",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recibos",
                to="gestion_comercial.facturaventa",
            ),
        ),
        migrations.AddField(
            model_name="recibocaja",
            name="perfil",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recibos_caja",
                to="prestadores.providerprofile",
            ),
        ),
    ]
