# Generated by Django 5.2.6 on 2025-12-23 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion_comercial", "0001_initial"),
        ("prestadores", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itemfactura",
            name="producto",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="prestadores.product",
            ),
        ),
    ]
