# Generated by Django 5.2.6 on 2026-02-08 11:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion_comercial", "0002_alter_operacioncomercial_estado"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="facturaventa",
            name="creado_por",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="facturaventa",
            name="cufe",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="facturaventa",
            name="dian_response_log",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="facturaventa",
            name="estado",
            field=models.CharField(
                choices=[
                    ("EMITIDA", "Emitida"),
                    ("PAGADA", "Pagada"),
                    ("ANULADA", "Anulada"),
                ],
                default="EMITIDA",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="facturaventa",
            name="estado_dian",
            field=models.CharField(
                choices=[
                    ("PENDIENTE", "Pendiente"),
                    ("ACEPTADA", "Aceptada"),
                    ("RECHAZADA", "Rechazada"),
                ],
                default="PENDIENTE",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="facturaventa",
            name="impuestos",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="facturaventa",
            name="subtotal",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="facturaventa",
            name="total",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.CreateModel(
            name="ContratoComercial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("perfil_ref_id", models.UUIDField()),
                ("cliente_ref_id", models.UUIDField()),
                ("terminos_y_condiciones", models.TextField()),
                ("fecha_firma", models.DateTimeField(blank=True, null=True)),
                (
                    "hash_firma_digital",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("BORRADOR", "Borrador"),
                            ("FIRMADO", "Firmado"),
                            ("VIGENTE", "Vigente"),
                            ("FINALIZADO", "Finalizado"),
                            ("INCUMPLIDO", "Incumplido"),
                        ],
                        default="BORRADOR",
                        max_length=20,
                    ),
                ),
                (
                    "evidencia_archivistica_ref_id",
                    models.UUIDField(blank=True, null=True),
                ),
                (
                    "operacion",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contrato_formal",
                        to="gestion_comercial.operacioncomercial",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrdenOperativa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("perfil_ref_id", models.UUIDField()),
                ("descripcion_servicio", models.TextField()),
                ("fecha_programada", models.DateTimeField()),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente"),
                            ("EN_PROCESO", "En Proceso"),
                            ("COMPLETADA", "Completada"),
                            ("CANCELADA", "Cancelada"),
                        ],
                        default="PENDIENTE",
                        max_length=20,
                    ),
                ),
                ("responsable_ref_id", models.UUIDField(blank=True, null=True)),
                (
                    "contrato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ordenes_operativas",
                        to="gestion_comercial.contratocomercial",
                    ),
                ),
            ],
        ),
    ]
