# Generated by Django 5.2.6 on 2026-01-07 22:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion_archivistica", "0001_initial"),
        ("gestion_comercial", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="facturaventa",
            name="documento_archivistico",
            field=models.ForeignKey(
                blank=True,
                help_text="Vínculo al registro maestro en el Sistema de Gestión Archivística.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="factura_comercial",
                to="gestion_archivistica.document",
            ),
        ),
    ]
