# Generated by Django 5.2.6 on 2026-02-05 08:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AdversarialProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("source_ip", models.GenericIPAddressField(unique=True)),
                ("technical_level", models.CharField(default="UNKNOWN", max_length=50)),
                ("persistence_score", models.FloatField(default=0.0)),
                ("abandonment_threshold", models.FloatField(default=0.5)),
                ("first_seen", models.DateTimeField(auto_now_add=True)),
                ("last_activity", models.DateTimeField(auto_now=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("is_quarantined", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="DisuasionMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_dissuaded_attempts", models.IntegerField(default=0)),
                ("avg_abandonment_time_minutes", models.FloatField(default=0.0)),
                ("total_cognitive_cost_imposed", models.FloatField(default=0.0)),
                ("last_update", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Métrica de Disuasión",
                "verbose_name_plural": "Métricas de Disuasión",
            },
        ),
        migrations.CreateModel(
            name="GhostSurface",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "path",
                    models.CharField(
                        help_text="Ruta del endpoint fantasma", max_length=512
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "deception_type",
                    models.CharField(
                        choices=[
                            ("FAKE_API", "API Ficticia"),
                            ("HONEYPOT_LOGIN", "Login Trampa"),
                            ("SIMULATED_DB_EXPORT", "Exportación DB Simulada"),
                            ("GHOST_ADMIN_PANEL", "Panel Admin Fantasma"),
                        ],
                        max_length=100,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="DeceptionInteractionLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("request_data", models.JSONField()),
                ("response_simulated", models.JSONField()),
                (
                    "cost_cognitive_imposed",
                    models.FloatField(
                        default=1.0,
                        help_text="Estimación del tiempo/esfuerzo desperdiciado por el atacante.",
                    ),
                ),
                (
                    "adversary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interactions",
                        to="defense_deception.adversarialprofile",
                    ),
                ),
                (
                    "surface",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="defense_deception.ghostsurface",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
    ]
