# Generated by Django 5.2.6 on 2026-01-22 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Almacen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("ubicacion", models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="MovimientoInventario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_movimiento",
                    models.CharField(
                        choices=[
                            ("ENTRADA", "Entrada"),
                            ("SALIDA", "Salida"),
                            ("AJUSTE_POSITIVO", "Ajuste Positivo"),
                            ("AJUSTE_NEGATIVO", "Ajuste Negativo"),
                        ],
                        max_length=20,
                    ),
                ),
                ("cantidad", models.DecimalField(decimal_places=2, max_digits=18)),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                ("descripcion", models.TextField(blank=True)),
            ],
        ),
    ]
