# Generated by Django 5.2.6 on 2026-01-04 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0001_initial"),
        ("prestadores", "0003_remove_product_nature_remove_product_stock_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="producto",
            name="categoria",
        ),
        migrations.RemoveField(
            model_name="producto",
            name="perfil",
        ),
        migrations.AlterField(
            model_name="movimientoinventario",
            name="producto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="movimientos_inventario",
                to="prestadores.product",
            ),
        ),
        migrations.DeleteModel(
            name="CategoriaProducto",
        ),
        migrations.DeleteModel(
            name="Producto",
        ),
    ]
