# Generated by Django 5.2.6 on 2025-10-29 01:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("compras", "0001_initial"),
        ("contabilidad", "0001_initial"),
        ("inventario", "0001_initial"),
        ("prestadores", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="facturaproveedor",
            name="centro_costo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="contabilidad.costcenter",
            ),
        ),
        migrations.AddField(
            model_name="facturaproveedor",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="facturaproveedor",
            name="perfil",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="facturas_proveedor",
                to="prestadores.perfil",
            ),
        ),
        migrations.AddField(
            model_name="itemfacturaproveedor",
            name="factura",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="compras.facturaproveedor",
            ),
        ),
        migrations.AddField(
            model_name="itemfacturaproveedor",
            name="producto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="inventario.producto"
            ),
        ),
        migrations.AddField(
            model_name="pagorealizado",
            name="factura",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pagos",
                to="compras.facturaproveedor",
            ),
        ),
        migrations.AddField(
            model_name="pagorealizado",
            name="perfil",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pagos_realizados",
                to="prestadores.perfil",
            ),
        ),
        migrations.AddField(
            model_name="proveedor",
            name="perfil",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="proveedores",
                to="prestadores.perfil",
            ),
        ),
        migrations.AddField(
            model_name="facturaproveedor",
            name="proveedor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="compras.proveedor"
            ),
        ),
    ]
