# Generated by Django 5.2.6 on 2025-10-28 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("compras", "0001_initial"),
        ("inventario", "0001_initial"),
        ("prestadores", "0002_costo_inventario_productoservicio"),
    ]

    operations = [
        migrations.AddField(
            model_name="itemfacturaproveedor",
            name="producto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="inventario.producto"
            ),
        ),
        migrations.AddField(
            model_name="pagorealizado",
            name="factura",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pagos",
                to="compras.facturaproveedor",
            ),
        ),
        migrations.AddField(
            model_name="pagorealizado",
            name="perfil",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pagos_realizados",
                to="prestadores.perfil",
            ),
        ),
        migrations.AddField(
            model_name="proveedor",
            name="perfil",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="proveedores",
                to="prestadores.perfil",
            ),
        ),
        migrations.AddField(
            model_name="facturaproveedor",
            name="proveedor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="compras.proveedor"
            ),
        ),
    ]
