# Generated by Django 5.2.6 on 2025-10-28 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compras", "0002_facturaproveedor_centro_costo"),
        ("prestadores", "0002_costo_inventario_productoservicio"),
    ]

    operations = [
        migrations.CreateModel(
            name="PagoRealizado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_pago", models.DateField()),
                ("monto", models.DecimalField(decimal_places=2, max_digits=15)),
                ("metodo_pago", models.CharField(blank=True, max_length=50)),
                (
                    "factura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pagos",
                        to="compras.facturaproveedor",
                    ),
                ),
                (
                    "perfil",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pagos_realizados",
                        to="prestadores.perfil",
                    ),
                ),
            ],
        ),
    ]
